### ISSUE TITLE
Can't read elm 327 usb

### ISSUE THREAD

**Issue by tameratf** [cedricp/ddt4all#10]
The last version of master can't read elm 327 usb .
i use Windows 10 .

**Comment by cedricp** [comment]
Provide log file for analyse.Tested successfully on my car yesterday
Any error message in terminal ?

**Comment by tameratf** [comment]
![capture](https://user-images.githubusercontent.com/31937960/30521349-73922c1c-9bbe-11e7-921a-0a3a0909ba53.PNG)

**Comment by cedricp** [comment]
No port found, have you tried with another application ?
Try to disable antivirus too.

**Comment by tameratf** [comment]
i tried with another version of master and the port found .
![capture](https://user-images.githubusercontent.com/31937960/30523072-e530332a-9bda-11e7-8590-34f8162d5f8a.PNG)

**Comment by cedricp** [comment]
My bad, I merged a part of the winXP branch into master, reverted. Can you check ?

**Comment by tameratf** [comment]
I tried the last version and it is work .

**Comment by cedricp** [comment]
Great, so closing
