### ISSUE TITLE
AttributeError: 'QString' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by cipman** [cedricp/ddt4all#101]
Ubuntu 16.04, python2 or 3, qt4.
Start from terminal > Edition Mode > File > Zip database =>
    _Traceback (most recent call last):
      File "ddt4all.py", line 585, in zipdb
        if not filename.endswith(".zip"):
    AttributeError: 'QString' object has no attribute 'endswith'_

After fixing that with `endsWith` in place of `endswith`, I got:
    _File "ddt4all.py", line 588, in zipdb
        if not isWritable(str(os.path.dirname(filename))):
      File "/usr/lib/python2.7/posixpath.py", line 122, in dirname
        i = p.rfind('/') + 1
    AttributeError: 'QString' object has no attribute 'rfind'_

Now I reversed the 1st fix and placed the following lines before any other import statement:
`import sip`
`sip.setapi('QString', 2)`

Now it works, database zipped and saved.
Can't tell if there's any bad influence, apparently not but not fully tested.

**Comment by cedricp** [comment]
Fixed in last commit (related to qt5 support)

**Comment by cipman** [comment]
Right. My last update was just before the last commit.
With the 'Screen logger fix' (filename converted from tuple to string) it's working fine.
Thanks.

Issue closed.
