### ISSUE TITLE
KeyError 'LANG' Unix (MacOs)

### ISSUE THREAD

**Issue by Eksponat** [cedricp/ddt4all#1014]
Help please, i dont know how startup this software. 
<img width="567" alt="Screenshot 2024-01-23 at 11 40 11 PM" src="https://github.com/cedricp/ddt4all/assets/50989871/1d57f84e-a5b5-416a-a8b9-4d8838ca227b">

**Comment by AndyIreland** [comment]
haven't you got an old windows laptop you could try using instead?

**Comment by Eksponat** [comment]
unfortunately no

**Comment by AndyIreland** [comment]
https://github.com/cedricp/ddt4all/issues/122

**Comment by Eksponat** [comment]
Left code: my fix
Right code: original
If anyone has the same problem, here is the solution code:
        langlayout = widgets.QHBoxLayout()
        self.langcombo = widgets.QComboBox()
        langlabels = widgets.QLabel(_("Interface language (need save and close)"))
        langlayout.addWidget(langlabels)
        langlayout.addWidget(self.langcombo)

        if 'LANG' in os.environ:
            for s in options.lang_list:
                self.langcombo.addItem(s)
                if options.lang_list[s].split("_")[0] ==os.environ['LANG'].split("_")[0]:
                    self.langcombo.setCurrentText(s)
        else:
        # Handle the situation when "LANG" is not present in the environment
            print ("The 'LANG' variable is not set in the support environment.")

        layout.addLayout(langlayout)

<img width="1706" alt="Screenshot 2024-01-24 at 5 47 02 AM" src="https://github.com/cedricp/ddt4all/assets/50989871/193f3d4d-9627-459a-bb3e-dd4ecfdb27bc">

**Comment by Furtif** [comment]
Install requirements 🤦🏻‍♂️

**Comment by Eksponat** [comment]
I did everything that was required, including in #122, none of the suggestions corrected the situation.

**Comment by Furtif** [comment]
> I did everything that was required, including in #122, none of the suggestions corrected the situation.

correct situation is: 
``` 
if not os.environ["LANG"]:
  export "LANG" = "en-US" 
```

more or less this.

or try :  ... except: export "LANG" = "en-US"

**Comment by Furtif** [comment]
ex: 
```python
       # languages setting
        lgn = None
        try:
            os.environ['LANG'].split("_")[0]
        except:
            lgn = "en"
            
        langlayout = widgets.QHBoxLayout()
        self.langcombo = widgets.QComboBox()
        langlabels = widgets.QLabel(_("Interface language (need save and close)"))
        langlayout.addWidget(langlabels)
        langlayout.addWidget(self.langcombo)
        for s in options.lang_list:
            self.langcombo.addItem(s)
            if options.lang_list[s].split("_")[0] == lgn:
                self.langcombo.setCurrentText(s)
        # self.langcombo.setCurrentIndex(0)
        layout.addLayout(langlayout)
        #
```

this teoricaly set English by default is not exists

**Comment by Furtif** [comment]
or set environement var 

```
os.environ['LANG'] = "en_US"

```

**Comment by Furtif** [comment]
if ok close this issue. 
Thanks.

**Comment by Furtif** [comment]
pip3 install -r requirements.txt

**Comment by Le-Spirit** [comment]
^ merci / thank you Furtif, previous post updated and enhanced.

**Comment by tLupus1978** [comment]
great, thanks for this perfect explanation!
