### ISSUE TITLE
Can not open port

### ISSUE THREAD

**Issue by bokkoman** [cedricp/ddt4all#102]
I've been using ddt4all a lot lately to install android auto for people.
But at my latest try, i got an error that ddt4all can not open port, acces denied error 5.

I don't know why this is happening. I can't use my elm device anymore. Tried changing the port, but with no success.

It happened after i tried an ELM test. Someone asked if i could do that too see difference with his ELM.
Didn't think any of it, so i just did.
So 2 days after that, i tried to connect with a car, but that error came up. 

Does someone know why? Or could help me out?

**Comment by cedricp** [comment]
What is your OS (Win, Linux, Mac) ?

**Comment by bokkoman** [comment]
I'm on Windows 10.
 Is it maybe cause i did the ELM test with the elm adapter connected to my laptop but not to my car?

**Comment by pcboys** [comment]
If you elm only connected to PC, then it is no power support, so,  is not work.

**Comment by cedricp** [comment]
You indeed need power supply from the car to power on the ELM chip.

**Comment by bokkoman** [comment]
The ELM test without connected to car worked, it gave 100%. Now when i connect to car and laptop i get error 5.

**Comment by KarelSvo** [comment]
Is your problem also present with this installer version?
https://www.drive2.ru/b/498093336985338243/

**Comment by bokkoman** [comment]
I bought a new elm device, and with that one there is no problem. It's the exact same device.
So i guess something internally on the elm went wrong when doing the elm test without connecting to a car.

**Comment by nickischenker** [comment]
Same Issue

Using an [OBDLink SX](http://www.obdlink.com/sxusb/) on Win7/32
[gives me an error](https://picload.org/view/dcaiocdr/error_v14.jpg.html)
..,got with one of these Chinese ELM327 forks a similar result. This only happens with v1.4, v1.3 is ok.

**Comment by cedricp** [comment]
There's a file missing in the installer, get the latest source code and replace it in the installation directory, it should work...

**Comment by nickischenker** [comment]
thx, v1.4 is working. :D
