### ISSUE TITLE
Impossible de démarrer ddt4all

### ISSUE THREAD

**Issue by ulysserevient** [cedricp/ddt4all#1030]
J'ai installé ddt4all RC-1, mais je n'arrive pas à lancer l'application.
L'interface de sélection ODB s'ouvre, mais quand je sélectionne connecté ou édition, ddt4all se ferme.

**Comment by KarelSvo** [comment]
You forgot the screenshot.

**Comment by Furtif** [comment]
c'est quoi encore cette histoire ....

**Comment by ulysserevient** [comment]
Bonjour,
après réinstallation de mon OS, ça fonctionne. Je en sais pas pourquoi, mais c'est résolu.
Merci

**Comment by ulysserevient** [comment]
RESOLU

**Comment by Furtif** [comment]
lol
