### ISSUE TITLE
Modify Day light in Megane 3 RS phase 1

### ISSUE THREAD

**Issue by sergiomaga** [cedricp/ddt4all#104]
Hi,

In Megane 3 r.s phase 1 the daylight are turned off when the lights is turn on, but this issue no happen in all cars because I've seen in other car in other country that the luminosity are only reduced by 50%.

What parameter can control this? 

Thank you!

**Comment by mishu28nmv** [comment]
Nobody knows where are the parameters to change DRL intensity or something related?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/discussions
