### ISSUE TITLE
connect but not respond

### ISSUE THREAD

**Issue by mahdyonline** [cedricp/ddt4all#106]
i have 2 elm327 one BT one usb
with both connect to car but can not read any ecu
why?

**Comment by cedricp** [comment]
Check if your ELM is a real one (Chinese clones are not working). You can benchmark at startup.

**Comment by mahdyonline** [comment]
how can i check it for clone or orginal

**Comment by cedricp** [comment]
Click on ELM benchmark on the startup page, if it finishes with _Incompatible ARM core_, you have a bad one...

**Comment by mahdyonline** [comment]
can u give me screenshot
