### ISSUE TITLE
Ddt4all working / Pyren macro not working

### ISSUE THREAD

**Issue by Marcovaldo78** [cedricp/ddt4all#1065]
Hello
I have read all the discussions and threads about Pyren and ddt4all…I changed my rlink display and now I have "radio not configured" message… Pyren recognize my ecus but when I apply macro gaves error "service not supported in active session" . I use USB elm with a modified can2 cable and I also changed parameters (min_tout)
I tried on PC with USB and wifi elm, changed USB to 230400, changed latency time
Also tried on Android phone (qpyren3)...same errors
My elm works on ddt4all and on Pyren, only macro commands gaves me those type of errors
Anyone can help me?
Twingo III - multimedia ecu on can2

Thank you very much

**Comment by KarelSvo** [comment]
Log files

**Comment by Marcovaldo78** [comment]
[ecu_log.txt](https://github.com/cedricp/ddt4all/files/14847672/ecu_log.txt)
[elm_log.txt](https://github.com/cedricp/ddt4all/files/14847673/elm_log.txt)
Wifi elm logs
Also with USB elm I have "service not supported" errors

I tried elm.py and init.txt modification as in Pyren issue 25 https://gitlab.com/py_ren/pyren/-/issues/25

**Comment by KarelSvo** [comment]
You send 1081 StopDiagSession  instead 10C0 StartDiagSession.

**Comment by Marcovaldo78** [comment]
I don't know...it's the macro from Pyren bot

**Comment by Marcovaldo78** [comment]
[cmd_can_10_1161_259209939R.txt](https://github.com/cedricp/ddt4all/files/14857610/cmd_can_10_1161_259209939R.txt)
Renamed from .CMD to txt

**Comment by shrlnm** [comment]
@Marcovaldo78 Open macro in text editor and replace 1081 on 10C0 or 1003

**Comment by Marcovaldo78** [comment]
[ecu_log.txt](https://github.com/cedricp/ddt4all/files/14863175/ecu_log.txt)
[elm_log.txt](https://github.com/cedricp/ddt4all/files/14863176/elm_log.txt)
[cmd_can_10_1161_259209939R.txt](https://github.com/cedricp/ddt4all/files/14863216/cmd_can_10_1161_259209939R.txt)

**Comment by Marcovaldo78** [comment]
MFD can is on can2, I am using modified cable (ddt4all recognize can2 ecus), maybe the problem could be the CMD the bot sent isn't can2??

**Comment by shrlnm** [comment]
CAN2 is about wiring. More over you receiving answers from ECU. 
Have you tried 10C0 for session opening?

**Comment by Marcovaldo78** [comment]
Yes both ... everything is working under can2 except macro...

**Comment by Marcovaldo78** [comment]
[ecu_ddt.txt](https://github.com/cedricp/ddt4all/files/14875821/ecu_ddt.txt)
[elm_ddt.txt](https://github.com/cedricp/ddt4all/files/14875822/elm_ddt.txt)

**Comment by KarelSvo** [comment]
>(https://github.com/cedricp/ddt4all/files/14863216/cmd_can_10_1161_259209939R.txt)

10C0 not 1003

**Comment by Marcovaldo78** [comment]
Now with 10C0 ecu received commands in macro
But yet radio not configured...
[ecu_log.txt](https://github.com/cedricp/ddt4all/files/14876677/ecu_log.txt)
[elm_log.txt](https://github.com/cedricp/ddt4all/files/14876684/elm_log.txt)

**Comment by Marcovaldo78** [comment]
I noticed that vin isn't written, but on ddt4all I can see it's the same vin and crc present in other ecus

**Comment by shrlnm** [comment]
> But yet radio not configured..

Have you run the macro for 76?

**Comment by Marcovaldo78** [comment]
On 76 macro Is for Radio_dab unit right? Since I have changed only screen (MFD), do I need to send macro also for this ecu (radio dab)?  
Another question: on ACI I receive 3 data for 10 and 76 ecu, like 10: 28540xxxx, 28307xxxx, 25xxxxx.
When I send vin to pyren bot, which is the correct syntax? Like that : vin VF100000000000001 10:259201014R,2592xx014R,24xxxxxxxx ?
Thank you

**Comment by Marcovaldo78** [comment]
Great! After speaker test sound and pin request, radio is ALIVE! Now maps on SD isn't recognized...neither USB connection and voice control. Also, I can't fix hour and temperature.... Now I connect ddt4all and will see if I can turn on some function... 
Maybe for maps on SD I need Rlink explorer??
For now, thank you guys for all your support
