### ISSUE TITLE
Megane 4 DisplayMode change with ddt4all

### ISSUE THREAD

**Issue by killuadk** [cedricp/ddt4all#107]
Hey 

if somme one could help plz i did by mistake change the DisplayMode as showing in photo 
i can connect with DDT4ALL but i can't find that parameter 

![](https://user-images.githubusercontent.com/42695091/46357802-4f10bf80-c66e-11e8-8182-5496fec4d183.jpeg)

**Comment by zatropin** [comment]
![fb_img_1541965839152](https://user-images.githubusercontent.com/44977768/48362530-e842e500-e6b4-11e8-88a8-507e7be46da1.jpg)
![img_20181111_005920](https://user-images.githubusercontent.com/44977768/48362604-0dcfee80-e6b5-11e8-9e2b-af5375833a16.jpg) bu bölümü denedim işe yaramıyor

**Comment by zatropin** [comment]
İletişim kuralım WhatsApp 05345003932

**Comment by zatropin** [comment]
https://github.com/cedricp/ddt4all/issues/110 
check the solution URL available
