### ISSUE TITLE
Rlink black screen after virgin MID/HIGH button clicked in developer mode

### ISSUE THREAD

**Issue by letrasluis2** [cedricp/ddt4all#1073]
Hi,
I have my R-link2 8.7" black screen after virgin MID/HIGH button clicked in developer mode by mistake.

Settings seems to correct. I was expecting them to be "landscape" instead "portrait" and with "landscape settings in Engineering Settings.
I did not change any settings in ddt4all, this readings is after black screen.

I'm sorry if i missed any post in search regarding this subject.

![WhatsApp Image 2024-04-08 at 12 18 21 (1)](https://github.com/cedricp/ddt4all/assets/165518226/0d645eab-9cc6-4830-ae6a-f3e2962d198f)
![WhatsApp Image 2024-04-08 at 12 18 21](https://github.com/cedricp/ddt4all/assets/165518226/b4290433-cc5f-4c3d-b725-729611e07c0a)
Thank you

Renault Scenic 4
Renault Scenic IV
Rlink
R-link
Rlink2
R-link2

**Comment by KarelSvo** [comment]
In Pyren pressed the Macro button and opened the Rlink2 folder?

**Comment by letrasluis2** [comment]
> In Pyren pressed the Macro button and opened the Rlink2 folder?

yes

![WhatsApp Image 2024-04-09 at 10 45 55](https://github.com/cedricp/ddt4all/assets/165518226/ec02dcc8-f749-44e4-b841-944febd5074d)

**Comment by letrasluis2** [comment]
EDIT - resolved,thank you all involved
