### ISSUE TITLE
Stop lamp control

### ISSUE THREAD

**Issue by maxclio** [cedricp/ddt4all#108]
after changing something on light settings that i do not remember on my clio 4 2014, I recieve stop lamp check light on even though stop lamp works perfectly. Can anyone check with theirs and tell me which one has wrong setting ? 

![dtc](https://user-images.githubusercontent.com/44920145/48299908-0e198f80-e4e5-11e8-99c4-bc853a59222d.JPG)

![fail 1](https://user-images.githubusercontent.com/44920145/48299893-e62a2c00-e4e4-11e8-95bd-fda36cf78607.JPG)
![fail 2](https://user-images.githubusercontent.com/44920145/48299894-e6c2c280-e4e4-11e8-8728-0a7c6a00648e.JPG)
![fail 3](https://user-images.githubusercontent.com/44920145/48299895-e6c2c280-e4e4-11e8-9012-dc0010707d4f.JPG)

**Comment by maxclio** [comment]
> If you did not delete your log files, it's possible to recover original parameters.

Unfortunately I dont have log files. Is it somewhere stored ?

**Comment by cedricp** [comment]
in your installation directory there's a log directory with 2 files.

**Comment by shrlnm** [comment]
The default configuration depends on ecus and functions installed in your car. So the values from other clio 4 2014 may not be suitable for you.
If you have deleted log file, then the original configuration can be restored only by your vin

**Comment by shrlnm** [comment]
Give me your email

**Comment by cedricp** [comment]
@shrlnm can you CC me your answer, I'm interested too

**Comment by maxclio** [comment]
> Give me your email

Can you also send me the details about how to reset according to VIN?

**Comment by shrlnm** [comment]
Most simplest way to get your default configuration is to make ECU emulator, connect it to CLIP and do reprog autoconfiguration

**Comment by shrlnm** [comment]
164

**Comment by mnigten** [comment]
I am interested too . Nigten@gmail.com

And about CLIP . Can it be done with a Chinese version?

**Comment by shrlnm** [comment]
Actually any clip which may do a reprog. Emulator is a simple program and  ELM (usb is much better).

**Comment by shrlnm** [comment]
Configuration database on reprog disk is strongly encrypted and get the data from it is very hard. But with simple emulator built from ELM you may trick the clip and make it to send commands of the default configuration to your emulator which log them.

**Comment by cedricp** [comment]
Ok I see, smart way to get back parameters but need a CLIP hardware..

**Comment by ohayyam** [comment]
> 
> 
> Give me your email

I am interested too.   omern7100@gmail.com

Thanks &  Regards

**Comment by pcboys** [comment]
> Give me your email

I am interested too.  pcboys@163.com
Thanks  & Regards

**Comment by maxclio** [comment]
It's Nbx_light_Pack_Active. When I set it to 0, the warning got dissappeared :)
