### ISSUE TITLE
Instalelr (November 2018) - Instalelr script error

### ISSUE THREAD

**Issue by bovirus** [cedricp/ddt4all#109]
@cedricp

Please take care that in the latest installer (November 2018) I got a strange window info

Please check the screenshot

**Comment by cedricp** [comment]
I saw it, will check that ASAP

**Comment by bovirus** [comment]
The problem is in the this line of teh script

Source: "{app}\DDT4ALL.BAT"; DestDir: "{app}"; AfterInstall: "AfterMyProgInstall('{cm:AfterMyProgInstall}', ExpandConstant('{app}'))"; MinVersion: 0.0,5.0;

**Comment by bovirus** [comment]
Please check here about syntax of **AfterInstall**

http://www.jrsoftware.org/ishelp/index.php?topic=scriptinstall

Please check if it's available a procedure called **AfterMyProgInstall** in **[Code]** section and the relative source

**Comment by cedricp** [comment]
I'll check into that as soon as can. I'm actually too busy...
