### ISSUE TITLE
3.0.1 "Stable"

### ISSUE THREAD

**Issue by KarelSvo** [cedricp/ddt4all#1094]
Connect ddt4all 3.0.1 to a USB interface that is powered via USB. Example OBDlink SX or vgate Vlinker FS.
Select xJA and then press the Scan button.
Select xJAPh2 then press the Scan button.
Show please photos of both results in the terminal.
I want to see if my experiences are the same.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/discussions/1088#discussioncomment-9286930 duplicated
