### ISSUE TITLE
ELM 327 cable can't load data...

### ISSUE THREAD

**Issue by hoonythink** [cedricp/ddt4all#11]
last DDT4ALL version is perfect at OBDLINK SX cable.

but ELM327 cable have one problem.

"USA_Bosch_Gen5_V7.6_20150423T151842.xml " can't read all data.

other all xml file can read data.

i used this cable.
 
http://auto.freeship.co.kr/goods/content.asp?guid=3267408&NaPm=ct%3Dj7vu3i57%7Cci%3Dcheckout%7Ctr%3Dppc%7Ctrx%3D%7Chk%3D3a06a3f2cb5ec828947e6f4b820e17be440b04fa

check please.

thanks always.

![k-001](https://user-images.githubusercontent.com/31832805/30841020-61190102-a2b5-11e7-9902-691185a00dc8.jpg)
![k-002](https://user-images.githubusercontent.com/31832805/30841019-611892d0-a2b5-11e7-8287-a2910c1ea216.jpg)
![k-003](https://user-images.githubusercontent.com/31832805/30841021-611927d6-a2b5-11e7-8623-53dda2f4adc4.jpg)
![k-004](https://user-images.githubusercontent.com/31832805/30841022-6119b624-a2b5-11e7-8eaf-e2d68e63ef7e.jpg)
![k-005](https://user-images.githubusercontent.com/31832805/30841024-6134321a-a2b5-11e7-8016-cc1b8d696311.jpg)
![k-006](https://user-images.githubusercontent.com/31832805/30841023-61241e52-a2b5-11e7-99da-395cea9700e4.jpg)
![k-007](https://user-images.githubusercontent.com/31832805/30841025-613e0628-a2b5-11e7-9f42-3dd0c93ea2c0.jpg)
![k-008](https://user-images.githubusercontent.com/31832805/30841027-613ec2fc-a2b5-11e7-9e9d-31dcb270c3f7.jpg)
![k-009](https://user-images.githubusercontent.com/31832805/30841026-613e1460-a2b5-11e7-861f-0750640ab682.jpg)

**Comment by cedricp** [comment]
Have you tried to increase CAN timeout value to 1000 ms ? (in the status bar)
If it doesn't work, I'll need logs

**Comment by hoonythink** [comment]
it works.
thanks. ^^

**Comment by cedricp** [comment]
Great :+1:
