### ISSUE TITLE
ModuleNotFoundError: No module named 'serial'

### ISSUE THREAD

**Issue by MalekLahbib** [cedricp/ddt4all#1104]
![Screenshot from 2024-05-12 11-50-12](https://github.com/cedricp/ddt4all/assets/111009238/3f8d9020-0e53-42d3-b346-b75b9a801a77)

when trying to launch main.py on ubuntu

**Comment by MalekLahbib** [comment]
My bad. I didn't notice the "pyserial" module in the list

**Comment by Furtif** [comment]
Instal requirements

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/blob/master/ddt4all.sh#L13
