### ISSUE TITLE
Dacia DusterII 2018 - Stop&Start Problem

### ISSUE THREAD

**Issue by bkamber** [cedricp/ddt4all#111]
I've a stopstart problem in my car.  (rarely works stably and sometimes doesn't work)
I want to change or calibrate the Stopstart settings and don't want to take it to the service. :/

UCH/BCM SW13_1
-clutch pedal ?
-fal mmi -stopstart_type
-features act.logic -stopstart_type
(stopstart_type_cf = true/false) If it is
 true= button is active or false= button is passive
-gee -conf-stopstartinhibit
![bcm gee](https://user-images.githubusercontent.com/6732830/49329318-bc1cd480-f58d-11e8-8e47-b128285a4826.PNG)

**Comment by Furtif** [comment]
is same a #112
