### ISSUE TITLE
How to run ddt4all on MacOS Intel

### ISSUE THREAD

**Issue by R22354413** [cedricp/ddt4all#1112]
Hi, I am trying to open ddt4all on my macbook Pro Monterey Ver 12.6.5. I have downloaded the latest python3 and tried running the main.py via python 3 but am getting the current error

FileNotFoundError: [Errno 2] No such file or directory: 'ddt4all_data/config.json'

I have tried creating a dmg but that has failed as well. 

Does anyone have any solutions?

Am new to this so please be kind.

**Comment by Furtif** [comment]
> Hi, I am trying to open ddt4all on my macbook Pro Monterey Ver 12.6.5. I have downloaded the latest python3 and tried running the main.py via python 3 but am getting the current error
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'ddt4all_data/config.json'
> 
> I have tried creating a dmg but that has failed as well.
> 
> Does anyone have any solutions?
> 
> Am new to this so please be kind.

Yep dmg gen is issued, runs 
runs directly code:
```python3 -m pip3 install -r requirements.txt```
```python3 ./main.py```

**Comment by Furtif** [comment]
Works well in mac intel i have macOs also:

![Capture d’écran 2024-05-01 à 19 16 14](https://github.com/cedricp/ddt4all/assets/11375035/cbaa16ea-17dd-43ad-8ab0-fd1cc4b2dfe8)

**Comment by R22354413** [comment]
thank you for your help. Do i run it directly on Terminal? I am getting an error saying there is no such module pip3
/usr/local/bin/python3: No module named pip3

**Comment by Furtif** [comment]
> thank you for your help. Do i run it directly on Terminal? I am getting an error saying there is no such module pip3 /usr/local/bin/python3: No module named pip3

uses:
```python3 -m pip3install -r requirements.txt ```

**Comment by Furtif** [comment]
or uses the sh for create a venv :

In terminal in path clone repos type:
```sh ./ddt4all.sh```

**Comment by R22354413** [comment]
thank you very much . I've got it. 
![Uploading Screenshot 2024-05-26 at 18.39.32.png…]()

**Comment by Furtif** [comment]
worked ? close issue.
