### ISSUE TITLE
Not possible to connect

### ISSUE THREAD

**Issue by franeti** [cedricp/ddt4all#112]
![f92ecc64-8534-4c91-9707-ba3c8c28bfa5](https://user-images.githubusercontent.com/45541582/49344047-90bfe580-f672-11e8-8fe5-487b61386bd0.jpeg)
![4179abb4-b1c7-467e-8ce8-3b89e9599f3d](https://user-images.githubusercontent.com/45541582/49343577-5e12ee80-f66c-11e8-86ec-d13d9de22bf1.jpeg)
I have bought the obd wifi on amazon iLC OBD2 OBD II Inalámbrico Coche... https://www.amazon.es/dp/B01NAQ2878?ref=yo_pop_ma_swf

I connect my laptop with Windows 7 to the obd, no problem. 
I open ddt4all, i press in wifi button but in the white box there isnt a port to select to connect. 

I have ussed the test elm option. Some times it says port closed and other after a type of scan it says to update throught scantool.net...

Thanks for your support. 

Regards.

**Comment by KarelSvo** [comment]
Upload your folder to ddt4all/logs

**Comment by globsecure** [comment]
I can't run my iLC OBD2's wifi connection over Wifi, it keeps trying to connect forever. But it doesn't connect.

**Comment by Furtif** [comment]
not.... connect....... is a joke???
