### ISSUE TITLE
DDT4ALL

### ISSUE THREAD

**Issue by alitarasi** [cedricp/ddt4all#1122]
Hi everyone. Ive downloaded the latest version of DDT4ALL. But it did not inistall successfully and the end the error came on.

**Comment by Furtif** [comment]
Reinstal again

**Comment by AndyIreland** [comment]
if you can do what you want to do on this version then use it instead. Its basically an older version but seems more stable:
https://cloud.mail.ru/public/4mtR/2PLQ7JcmG

**Comment by Furtif** [comment]
uses old https://github.com/cedricp/ddt4all/releases/tag/V2.0 or other https://github.com/cedricp/ddt4all/releases
