### ISSUE TITLE
ddt4all.py

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#1136]
What happened to the DDT4ALL.py file and why is it not in the up to date file structure please?

https://github.com/cedricp/ddt4all/blob/master/ddt4all.py

![image](https://github.com/cedricp/ddt4all/assets/49172217/debaa2f3-f401-4c5c-9d9f-04fbaf4c4c82)

**Comment by Furtif** [comment]
uses https://github.com/cedricp/ddt4all/blob/master/main.py

ddt4all.py is now main.py
