### ISSUE TITLE
OBD Link MX Wifi Dongle: Python freeze but Benchmarktest is excellent running

### ISSUE THREAD

**Issue by pyromixer** [cedricp/ddt4all#117]
I own the OBD Link MX Wifi dongle. The ddt4all test runs very fast and without errors with this dongle.

![screenshot 2018-12-12 10 54 54](https://user-images.githubusercontent.com/20294328/49928865-61567780-fec1-11e8-8d55-5a605518b2b8.png)![img_0247](https://user-images.githubusercontent.com/20294328/49928773-310ed900-fec1-11e8-8d0a-66287ce6e030.jpeg)
![img_0248](https://user-images.githubusercontent.com/20294328/49928797-3c620480-fec1-11e8-852b-5194903fd430.jpeg)

When I connect the vehicle and select a controller and then select the screen freezes ddt4all. Python does not respond in the header.

The dongle works very well otherwise, very fast and error free with other complex OBD software.

Can anybody help please? THX

**Comment by cedricp** [comment]
Difficult to debug without the hardware...

**Comment by pyromixer** [comment]
I can send it to you for debugging if you want.

**Comment by cedricp** [comment]
I have a Wifi dongle at home, I'll try it again with it before.

**Comment by shrlnm** [comment]
Could you please share the elm_ddt log?

**Comment by shrlnm** [comment]
And if it has internal web-server then the screenshot with settings...

**Comment by pyromixer** [comment]
What do I have to do for this ddt log?

Here are some screenshots from the original app from the manufacturer of the MX Link Dongle. This are all factory settings. Maybe it's helpful for the first step.

![mxlinksettings](https://user-images.githubusercontent.com/20294328/49940734-b2299880-fee0-11e8-916c-7b6b49b1a9a8.jpg)

**Comment by shrlnm** [comment]
I need files from folder dd4all/logs. There are should be two files elm_ddt and ecu_ddt. elm_ddt is most interesting. Start ecus scanning and then share these files.
Also when you are connected to SSID of this device, open any web-browser and go to url   http://192.168.0.10
Setting from screenshot above is relevant to connection to OBD. I need wifi and tcp settings.

**Comment by pyromixer** [comment]
OK. I'll do this in the next hour!

**Comment by pyromixer** [comment]
I cannot open the URL 192.168.0.10 (no access)

But I have the files now. I'm tested it with an ELM Dongle from Carly too. With this I can work with ddt4all.

[mx_log_files.zip](https://github.com/cedricp/ddt4all/files/2677794/mx_log_files.zip)
[carly_log_files.zip](https://github.com/cedricp/ddt4all/files/2677796/carly_log_files.zip)

**Comment by shrlnm** [comment]
Could you please also share the screenshot of the second tab in web mode? It is interesting what parameters are tunable. This adapter has good quality but not as fast I want. His response time  around 50ms. You may get in ten times less response time with cheapest USB adapter for 5$

**Comment by pyromixer** [comment]
Hi.

Here are the screenshots from the MX Wifi configuration sites (both):
![website01](https://user-images.githubusercontent.com/20294328/50017282-ea59d580-ffcb-11e8-88a8-7d24465ce99c.png)
![website02](https://user-images.githubusercontent.com/20294328/50017285-ed54c600-ffcb-11e8-935d-d590be34bc0a.png)

Unfortunately not possible to extend the timeout :-(

Your second tip: press the buttons faster are works but not very comfortable. And after a change of parameter the same problem: Python freezes :-(

**Comment by pyromixer** [comment]
Here the answer from the US manufacturer:

The 5 second timeout is part of the Wi-Fi module firmware. There is no option to change or disable it.
You can try sending a command like ATRV that only reads data to keep it alive.

**Comment by shrlnm** [comment]
Very strange behaviour ((. It require to change to change the code

**Comment by pyromixer** [comment]
Ok. I put the dongle in a case and wait :-) It's not very important.

**Comment by shrlnm** [comment]
Wait while @cedricp approve my push request or get the patch for testing from my fork

**Comment by pyromixer** [comment]
I will checked it now

**Comment by cedricp** [comment]
Patch merged

**Comment by pyromixer** [comment]
It works better now. I can now select ECU without errors. But then the problems come back when I work in the ECU Window.
[elm_ddt_mxtest.zip](https://github.com/cedricp/ddt4all/files/2689024/elm_ddt_mxtest.zip)

**Comment by shrlnm** [comment]
And also you probably chosen wrong xml if 021003 returns NR

**Comment by cedricp** [comment]
I made some modifications to attempt reconnection automatically after a TCP timeout. Not tested on my side.

**Comment by pyromixer** [comment]
I will check it today.
Other Question: Why is the TDB Ecu (Tacho Unit) always red and not green?

**Comment by cedricp** [comment]
Green indicates the exact version of the XML file has been found
Red indicates you're working with a XML file that has a close version. You generally should avoid working in write mode with a red XML file.

**Comment by pyromixer** [comment]
Hmmm...
But how can I get the right XML file?

I just installed ddt4all.

**Comment by cedricp** [comment]
Try to get a newer version of the database...

**Comment by cedricp** [comment]
Maybe, but it would be strange, which XML file is it in the 2nd picture ? I'll look into that

**Comment by KarelSvo** [comment]
CLUSTER_x52_X67_X79_X92_v4.9_20180903T095957.xml
The most recent file for the scanned TdB.

**Comment by cedricp** [comment]
I think 0x34 == 52 is a coincidence after checking.

**Comment by pyromixer** [comment]
The red MX Wifi adapter works well now! Good work! Thank you!
If you are interested, here are the logfiles.

![screenshot 2018-12-20 13 24 51](https://user-images.githubusercontent.com/20294328/50313531-f4884200-04ab-11e9-8a7f-c43519217f5e.png)
[ddt_log_files_20_12_2018.zip](https://github.com/cedricp/ddt4all/files/2700725/ddt_log_files_20_12_2018.zip)
