### ISSUE TITLE
WRONG RESPONSE MULTILINE CFC0 and TIMEOUT

### ISSUE THREAD

**Issue by mvmlt** [cedricp/ddt4all#12]
Hello and thanks in advance for your help. My car is a MEGANE III 2014, last version of RLINK1.
I am using a Chinese USB ELM clone running 1.5 (tested with ELM identifier working with commands up The ECus Database is the last (08/2017).to 1.4) and a Windows 10 laptop. The pins are remapped (6-13/14-12). The CAN timeout value is set to 1000 ms. I have the last DDT4all version.

It seems that ELM does not work with DDT4all ... 

Attached files, elm.ddt, ecu.ddt, pictures ddt4all soft
Thank in advance.
[logs.zip](https://github.com/cedricp/ddt4all/files/1347305/logs.zip)
[ddt4allimg.pdf](https://github.com/cedricp/ddt4all/files/1347308/ddt4allimg.pdf)

**Comment by mvmlt** [comment]
[elm_ddt.zip](https://github.com/cedricp/ddt4all/files/1347060/elm_ddt.zip)

**Comment by cedricp** [comment]
No communication, check your ELM or connection.

**Comment by Turbox35** [comment]
Hello,
Exactly the same problem. How do you solve it? (tested 4 ELM)

**Comment by mvmlt** [comment]
Merci Cedric.
Strange ...

I check the cable and it is ok (ELM <=> CAR ...4-4; 5-5; 16-16; 6-13; 14-12) 

I test ELM with EasyODBII (without adapter cable) and it is ok
![image](https://user-images.githubusercontent.com/32278412/31100898-816638ba-a7cb-11e7-9c68-ef5ea9ceb9a9.png)

Je suis sec! No Idea

**Comment by cedricp** [comment]
Does it work on the vehicle bus ? Can you connect to the engine control module ?
Have you read the issue #6 ?

**Comment by Turbox35** [comment]
I succeed (meg 3 rs 2014 rlink1):
I had yellow button and "no data" in red"

elm compatible: 95/95
timeout 1000
canbus (bluetooth) 500k
If it can help. Good luck

**Comment by mvmlt** [comment]
Sorry Cedric, ut I do not understand your question !!
TurboX ...What is your elm ?
my elm compatible score : 76/95 ... Is it the reason of the problem ?

**Comment by cedricp** [comment]
As tu essayé de te connecter à l'ECU moteur sur le bus CAN standard ? Il faut aussi vérifier que l'elm ait bien le circuit intégré PIC original, sinon ça marche pas.

**Comment by Turbox35** [comment]
the working elm was a Chinese Bluetooth. I've tried with 3 other elm (1 had 75/96) but none was working. 
With the working elm,  the scan of ecu found 2 other ecu that means the connection was OK and after I manually go in nav ecu.

**Comment by mvmlt** [comment]
My elm do not have the original PIC. I will buy another.
Merci pour vos conseils Cedric et turboX.

**Comment by mvmlt** [comment]
Hello,
Bien vu Cedric  - Merci ! 
Le problème venait bien de l'ELM (version USB acheté sur Ebay)
Après remplacement (version BT sur Aliexp), tout est ok!

![unnamed](https://user-images.githubusercontent.com/32278412/31674317-cf5b5b8a-b361-11e7-846a-879a792d7110.jpg)
