### ISSUE TITLE
Unlock android app

### ISSUE THREAD

**Issue by pitarenal** [cedricp/ddt4all#1320]
Hello Cedeic,

Frist of all, thanks you for your excellent work.

I need to restore my renault audio system and I need to unlock the android app.

I have read I need to write you to ulock it. Can you help me?

Thank you so much

**Comment by AndyIreland** [comment]
android app no longer needs unlocking (not the latest version anyway)

**Comment by pitarenal** [comment]
Ok, maybe the problem is my ELM device. I will try with another one.

Thank you!

**Comment by mishu28nmv** [comment]
> Hello Cedeic,
> 
> Frist of all, thanks you for your excellent work.
> 
> I need to restore my renault audio system and I need to unlock the android app.
> 
> I have read I need to write you to ulock it. Can you help me?
> 
> Thank you so much

Hi,
is there an Android App for this wonderful software? Can I have a link please?

**Comment by manio** [comment]
> is there an Android App for this wonderful software? Can I have a link please?

https://github.com/cedricp/ecutweaker

**Comment by mishu28nmv** [comment]
Thank you for the link. I will surely try this too!!!
