### ISSUE TITLE
Last 2 versione not working wifi connection

### ISSUE THREAD

**Issue by alex-military** [cedricp/ddt4all#1330]
hello today I tested the connection with ddt4all I confirm that on the android app the connection on can2 does not work but apart from this I tried the last 2 versions and it is not possible to connect to my wifi odb adapter the message attempt to open pprta 192.168. 0.10:53000 @34600
or something similar appears on the terminal. I tried a very old version found on another site and it works fine. I hope you can fix it.

**Comment by Furtif** [comment]
works perfectly

**Comment by Furtif** [comment]
Set good port   35000
