### ISSUE TITLE
Kadjar 2016 Screen on its side.

### ISSUE THREAD

**Issue by ak1mb0** [cedricp/ddt4all#137]
I am attempting to rotate my r-link2 screen as it is stuck on its side currently. I have lost all audio also all my parking, camera features. I have used the screen orientation tab with hard resets in between and still nothing. 
Usually quite good with these things but not this time it would seem.
would love to figure this out and learn more rather than taking to the dealers but I fear it would be an easier option

**Comment by ak1mb0** [comment]
![img_20190126_205206](https://user-images.githubusercontent.com/47067204/51800611-86146d80-2229-11e9-9063-d2a02d0c1191.jpg)

**Comment by ak1mb0** [comment]
Screen issue solved. 
After updating my software version to 2.2.19.300 the problem still persisted. 
All screen values through ddt4all are correct.
I entered developer mode and tapped "MED" and R-link rebooted into the correct orientation.

HOWEVER, My system still has no audio and is missing all of my functions for parking, reverse camera, lane warning, auto park, ultra sound parking sensors, dash styles and welcome sounds/intro ect... ect....

Any advise?

**Comment by shrlnm** [comment]
Give me your e-mail

**Comment by ak1mb0** [comment]
Hi shrlnm my email is ak1mb0@outlook.com

**Comment by ak1mb0** [comment]
Audio issue solved, loud speaker wasn't activated.
From what I can tell most of my functions are back also after trial and error activating them.
Still missing blind spot I think.
Still missing all dash styles.
And all my car displays seem to show a talisman/espace not a KADJAR.
Tomorrow is a new day

**Comment by JAzevedo351** [comment]
I have the same problem, can help me :'[

**Comment by shrlnm** [comment]
Hi, what the problem with the sound?

**Comment by JAzevedo351** [comment]
The Acoustic parameters not set, and I don't no haw I can set them.

**Comment by shrlnm** [comment]
Give me your email

**Comment by JAzevedo351** [comment]
door.1170@gmail.com

**Comment by comaly** [comment]
I have the same problem with my Megane 4 HB EDC DCI 2017.
Can you help me?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
