### ISSUE TITLE
Activate Extended Grip in Kadjar

### ISSUE THREAD

**Issue by jorgos3** [cedricp/ddt4all#139]
I'b bought Extended Grip selector and there is a connector available under center console. When I connect it the orange light flashes in selector and then nothing. Is it possible to active the Extended Grip function so that the selector would work?

**Comment by gordon6** [comment]
Hi, when you find Audio>RadNav x.x and ABS-VDC-ESP>ESC_1540-HFE-XGZ-x.x then you can change 2 values.
1. RadNav > ECU config - Part II > HMI > Setting > extended grip > Present
2. ESC_1540-HFE-XGZ > Config > Function Config > EG(extended grip) > Activated
If you need to reset, just click the Hard Reset...
I drive Koleos2, so, I didn't try this configurations...  ^^;

**Comment by caccolina** [comment]
Thanks for the topic. Has anybody tried the solution suggested by Gordon6 on the Kadjar ? thanks

**Comment by bobcho** [comment]
> Thanks for the topic. Has anybody tried the solution suggested by Gordon6 on the Kadjar ? thanks

I'll be trying it - looking to purchase the switch

**Comment by maty307** [comment]
hello will someone give me a link where to buy the Egrip rotary knob

**Comment by bobcho** [comment]
I have one for sale, didn't get the chance to try it out.

**Comment by maty307** [comment]
and what would be the price?  you can put some photos here, I'm from the Czech Republic.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
