### ISSUE TITLE
ZOE STOP: ERROR PROG

### ISSUE THREAD

**Issue by cjmillsnun** [cedricp/ddt4all#145]
Hi, 

I was originally trying to put in the temperature on the instrument screen as well as the R-Link, however now when I start the car it comes up STOP: Error Prog.  It won't let me delete any DTCs either.

**Comment by pakoto** [comment]
Same problem if you try to enable motor temp into old version dacia clusters.
I only know a solution: reprogram with can clip (chinese or genuine).

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
