### ISSUE TITLE
Can you check the availability of the scanner?

### ISSUE THREAD

**Issue by ratbws** [cedricp/ddt4all#149]
There is a scanner for this link. The vehicle is koleos.
https://kobraproducts.net/products/kobra-wifi-obd2-scan-tool

After ddt4all connection, it will be in no response state.

elm327 identifier is normal.
![153710225](https://user-images.githubusercontent.com/47841996/53144423-8c56f900-35df-11e9-9ed6-f13aa87ddf7a.jpg)

**Comment by cedricp** [comment]
Have you tried the ELM benchmark in the startup screen of DDT4all ?

**Comment by KarelSvo** [comment]
The latest generation of Chinese firmware produces fake-elm-tests  ;-)
There are only a few remnants offers with stable 1.5 firmware.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
