### ISSUE TITLE
Error in elm.py

### ISSUE THREAD

**Issue by FredLeudon** [cedricp/ddt4all#15]
Dans la classe Port du fichier elm.py,

Il y a une erreur dans le constructeur pour les connexions par cocker (wifi), la variable connectionStatus n'est pas passée à vrai.

J'ai ajouté self.connectionStatus = True juste avant le except: (ligne 312)

`...`
`try:`
`     self.hdr.connect((self.ipaddr, self.tcpprt))`
`     self.hdr.setblocking(True)`
**`     self.connectionStatus = True`**
`expect:`
`...`

**Comment by cedricp** [comment]
Bien vu ! le WiFi fonctionne après ca ?

**Comment by FredLeudon** [comment]
Oui, ça marche. 

J’ai une zoé de 2013 sur laquelle je teste ton soft.

Lors du scan des ECUs, la première méthode fonctionne (j’en récupère 14, mais j’ai quelques erreurs de versions) par contre la méthode scan_new n’en trouve aucun.




Frédéric RICHARD

**Comment by cedricp** [comment]
Super, je vais appliquer ce fix alors. La methode scan_new est pour des ECU tres recents qui ont une methode d'identification differente, ce n'est pas anormal qu'il ne trouve rien...

**Comment by FredLeudon** [comment]
Compris, merci
