### ISSUE TITLE
Bad Response CRC0 Error

### ISSUE THREAD

**Issue by spikar85** [cedricp/ddt4all#150]
After receiving a CLC0 ELM Bad Response error - quickly read to find out that the Benchmark run when my cable is plugged in returns to 'FAIL' on all instances. 

I read here that it is most likely the ELM chip as it's a clone and not the right one. 

I purchased it on eBay (Australia). 

Assuming most of the other ones on eBay would be the same..... 
Can someone point me to the right direction as to where to buy the correct cable with the right chip for this to work and return no Errors on Benchmark. 

Many Thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
