### ISSUE TITLE
Missing ECU information - Megane IV 2019

### ISSUE THREAD

**Issue by stich86** [cedricp/ddt4all#151]
Hi all,

i'm using latest version of DDT4ALL, but doing a scan on my Megane IV (from 2019) i got some missing or not matched files. For example i've tried to activate Video\Photo on the run but they got back to "Restricted" after reset of R-Link. Also configuration of L/KM > KM/L doesn't seems to work.

![screenshot_4](https://user-images.githubusercontent.com/27808541/53285274-b8998380-375f-11e9-9fd2-507f87e493aa.jpg)

Any hints?

Thanks!

**Comment by stich86** [comment]
Regarding L/KM mod and restricted video I’ve solved. After a complete power off of machine they start to work. I think I need to wait ECU update to match my own (may be car is too new)

**Comment by KarelSvo** [comment]
> I think I need to wait ECU update to match my own (may be car is too new)

No, the autoident procedure would have to be adapted to the model of the CLIP software. There, only one to two out of four ident-parameters are compared.
Then there would be better scan results.

Some ecus require a software or hardware reset to save the new configuration.

**Comment by ohayyam** [comment]
@KarelSvo could you please inform us with more details.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
