### ISSUE TITLE
Which settings are possible

### ISSUE THREAD

**Issue by tanerdogan** [cedricp/ddt4all#152]
Hello,

I have Clio 4 - 2015 EDC Icon and also I'm software developer. I just found this project and search on internet some possible settings and discovered some paramters on Demo mode. (still waiting correct ODB2 cable) But I wonder is it possible to edit engine parameters, ECO mode calibration, injections timeouts etc.

My plan is setting for fuel saving, increasing HP etc. 

Also I know its not about project issue but I hope someone else share their experience.

PS. Sorry for my English is not good eought but I think i explain what I want.

Regards...

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
