### ISSUE TITLE
Activate the Unstable Trajectory Allert (UTA)

### ISSUE THREAD

**Issue by igno77** [cedricp/ddt4all#154]
Hi to all,
as a lot of people known this function is present only on Megane IV Sedane (called Gran Coupe in Italy) and Scenic IV but not on all other cars. This function is managed by the "Aide du parking" ecu and it's called UTA. For sure the ecu has the same reference for all (Megane, Scenic, Talisman and so on) but a calibration is missing for it. First step is activate the frame and after we will be able to setup the information in the dedicated page. Unfortunately if I try to activate the frame I receive a reset of the ecu without the possibility to activate the function. I see the reset due to a blinking of the BSW lights on side mirrors. Someone knows the right way to activate it? We will need only the Renault CanClip or ddt4all is enough? Thanks a lot

![screen1](https://user-images.githubusercontent.com/35034014/53494231-8a88ac00-3a9d-11e9-9bd0-f350ab1932f2.png)

![screen2](https://user-images.githubusercontent.com/35034014/53494238-8f4d6000-3a9d-11e9-96f8-0b507e86d4ae.png)

![screen3](https://user-images.githubusercontent.com/35034014/53494245-92485080-3a9d-11e9-8e9a-ef6ca14c8bea.png)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ...
