### ISSUE TITLE
DDT4all doesn't find ELM (Bluetooth)

### ISSUE THREAD

**Issue by nickout10** [cedricp/ddt4all#156]
Hi guys, first of all, great job, I`ve been reading all the topics here and it`s nice to see how people help each other.

So, here it goes my issue:

I recently bought a Y splitter cable (to swap cables easily) + ELM327 1.5V Bluetooth for enabling the Android Auto on my Fluence 2016 (RLink1). I've installed the ddt4all software and inserted the Renault database into the right place, everything seemed to be great. However, ddt4all cannot reach out to ELM Bluetooth, the dongle is paired and connected to my PC, but the software doesn't connect to it. I`ve tried COM3 and COM4 at different port speeds, no success :( 

I connected the dongle to my Samsung S6 and using an app the dongle connected to the ECU correctly I could see everything about the car.

Any clue what could be made? Do I have a bad Chinese ELM clone?

Thanks!

**Comment by KarelSvo** [comment]
If the Elm test also does not work, you need to fix your PC problem first.

**Comment by IZ7QEB** [comment]
Hi everyone. I resume this post without opening a new one. I have the same problem.
I tried to connect my ELM, but I can't connect via bluetooth.
I tried it with my smartphone and it works. I also tried using the same laptop I'm using, with another software and it works.

What possible solutions? Are there any settings to check?
I attach screenshot.

![4](https://user-images.githubusercontent.com/9398445/58053624-5aaaeb00-7b58-11e9-9c7c-e3897f432435.png)
![01](https://user-images.githubusercontent.com/9398445/58053676-84fca880-7b58-11e9-88bf-4ca5c72687b4.png)
![02](https://user-images.githubusercontent.com/9398445/58053628-5b438180-7b58-11e9-80bc-47dc3f7e5257.png)
![3](https://user-images.githubusercontent.com/9398445/58053629-5b438180-7b58-11e9-985a-4b5a84ffaeee.png)

THANK YOU.

**Comment by tk5ep** [comment]
Hi,
Same for me with a Bluetooth ELM.
Works with other SW . Detected port with this SW is PORT 1, but DDT4ALL only gives me port 3 et 4...
Any guess ?
Thanks

**Comment by Megane412** [comment]
Hi,

I also have a Bluetooth ELM. On OBD Auto doctor it reports ELM327 v1.5; Works fine with the software for seeing data. When I try Check ELM on pyren it all the commands return FAIL. In DDT4All I have the same problem. Tried all rate settings for connection, also moved between port 4 and 5 to no success.

I am using this adapter https://www.conrad.at/de/p/exza-obd-ii-interface-hhobd-mini-497288155-uneingeschraenkt-1650373.html

Please let me know

**Comment by lmikolaj** [comment]
Hi,

I have same problem when I try connect my ELM via bluetooth.
Connection via bluetooth with OBD Auto doctor android app works.

Below is picture with problems. The dongle is paired and connected to my PC, but the software doesn't connect to it. I`ve tried COM3 and COM4 at different port speeds, no success.
 
![image](https://user-images.githubusercontent.com/63409442/78904279-91ddff80-7a7c-11ea-8761-1969a2d4d88a.png)

Do you have some solution?

**Comment by CRACKISH** [comment]
I have same error.

windows 10

**Comment by Kingsmart75** [comment]
I also join, unfortunately after trying with USB and wifi, now even with bluetooth I can't get ddt4all to work, I've tried various versions and with two notebooks (one with w11 and the other with w10) but I always get the same result that's wrong ... with pyren and ecu-tweaker I read all the data ... before putting everything at the stake, could someone help me?
![Screenshot_2022-06-14-19-27-19-677_com applagapp elm327identifier](https://user-images.githubusercontent.com/106084607/173693183-0f803cbc-519e-42a8-b1fc-1dd01373b209.jpg)
![IMG_20220614_192145](https://user-images.githubusercontent.com/106084607/173693228-1cf7a81e-b895-4634-87b2-fe1742a3eb61.jpg)

**Comment by AndyIreland** [comment]
Com7 seems a bit high up - I normally get Com3 or Com4 - what is your device manager looking like in windows 10 or 11?

**Comment by Kingsmart75** [comment]
in both systems I have com6 and com7, in the device manager I set the port speed to 38400, I connect perfectly with pyren ...

**Comment by AndyIreland** [comment]
if it connects perfectly with PyREN why dont you use the DDT Mode in PyRen to make your changes?

**Comment by Kingsmart75** [comment]
unfortunately in emm-lighting configuration I see NO DATA with pyren !!!  in other sections I see the data but in that section nothing!  with ecu-tweaker I see the data in the section but I cannot edit ...

**Comment by KarelSvo** [comment]
Which vehicle is it and where are the log files and savedEcus.p file from Pyren?

**Comment by Kingsmart75** [comment]
in desperation I changed the disk and put the Windows 7 operating system ... even here nothing to do ... it is not possible to go on like this ... I have bad luck on me?  I would like to know where am I wrong?  I'm banging my head everywhere !!!
![IMG_20220616_095815](https://user-images.githubusercontent.com/106084607/174028574-a5293fb1-630c-4333-b3e4-3d5fc47d3976.jpg)
![IMG_20220616_095524](https://user-images.githubusercontent.com/106084607/174028583-377c00d3-328d-4aea-a7e8-d0a34fbf628e.jpg)

**Comment by Kingsmart75** [comment]
> Which vehicle is it and where are the log files and savedEcus.p file from Pyren?

I have a 2019 smart forfour aka twingo III
Pyren LOGS FOLDER
[ecu_log.txt](https://github.com/cedricp/ddt4all/files/8917359/ecu_log.txt)
[elm_log.txt](https://github.com/cedricp/ddt4all/files/8917360/elm_log.txt)
Pyren savedEcus.p
[savedEcus.p.zip](https://github.com/cedricp/ddt4all/files/8917379/savedEcus.p.zip)

**Comment by Kingsmart75** [comment]
I am in absolute desperation, now I took it as a personal challenge, is it possible that I am so stupid that I can't do two encodings?  if i buy a sx obdlink USB cable will i be able to make the DDT4ALL work?  at 100%?  enough with these elm327 chinoiserie, there is no way to do anything, at least unfortunately I can't, I would like to understand what the problem is, where am I wrong?  no one here can give me some tips?

https://amzn.eu/d/7X72MLx[USB obdlink sx Amazon](https://amzn.eu/d/7X72MLx) 
![IMG-20220616-WA0003](https://user-images.githubusercontent.com/106084607/174187590-a75a27c7-9c7b-4c21-bee2-57c2dc345a59.jpeg)

**Comment by AndyIreland** [comment]
its strange, I dunno what is going on with your bluetooth elm327 obd2 adaptor. Could the actual OBD2 socket on the car be faulty or blocked / locked / firewalled by smart fourfour thats what i am wondering? 

If you thought it could work I could remotely log onto your windows 10 (or 7 ) laptop through the internet and control your laptop remotely and see if anything or settings spring  to mind or stand out but doing it blindly like this is pretty difficult without me actually seeing myself what is going on with your laptop /dongle

**Comment by KarelSvo** [comment]
> unfortunately in emm-lighting configuration I see NO DATA with pyren !!! in other sections I see the data but in that section nothing! with ecu-tweaker I see the data in the section but I cannot edit ...

No EMM ECU found in clip mode.
You also scanned in ddt mode.
There an EMM Ecu replied, you didn't open the screen of the EMM.

`18:53:45.334;74D;10C0;50 C0 
18:53:45.475;74D;2180;61 80 36 35 37 33 52 08 34 31 34 38 38 32 38 52 C1 52 80 01 00 00 02 01 00 88 00 
18:53:45.600;74D;2181;61 81 57 4D 45 34 35 33 30 34 34 31 59 32 32 38 32 35 34 9C D0 00 00 00 00 00 00 `

**Comment by Kingsmart75** [comment]
> > purtroppo in configurazione emm-illuminazione non vedo DATI con pyren !!! in altre sezioni vedo i dati ma in quella sezione niente! con ecu-tweaker vedo i dati nella sezione ma non riesco a modificare...
> 
> Nessuna ECU EMM trovata in modalità clip. Hai anche scansionato in modalità ddt. Lì ha risposto una EMM Ecu, non hai aperto lo schermo della EMM.
> 
> `18:53:45.334;74D;10C0;50 C0
> 
> 18:53:45.475;74D;2180;61 80 36 35 37 33 52 08 34 31 34 38 38 32 38 52 C1 52 80 01 00 00 02 01 00 88 00
> 
> 18:53:45.600;74D;2181;61 81 57 4D 45 34 35 33 30 34 34 31 59 32 32 38 32 35 34 9C D0 00 00 00 00 00 00 `

sorry, so where am I wrong?  can you give me the right steps to take?

**Comment by Kingsmart75** [comment]
> è strano, non so cosa sta succedendo con il tuo adattatore bluetooth elm327 obd2. La presa OBD2 effettiva dell'auto potrebbe essere difettosa o bloccata / bloccata / protetta da firewall da smart fourfour, ecco cosa mi chiedo?
> 
> Se pensavi che potesse funzionare, potrei accedere in remoto al tuo laptop Windows 10 (o 7) tramite Internet e controllare il tuo laptop in remoto e vedere se qualcosa o le impostazioni ti vengono in mente o risalta, ma farlo alla cieca in questo modo è piuttosto difficile senza di me in realtà mi vedo cosa sta succedendo con il tuo laptop / dongle

the obd port blocked I don't think, ELM read the data also with other apps, do you think there is a block from the Smart center?  the PC is virgin, I took a new SSD and installed the operating system, I didn't put anything else, I installed DDT4ALL and PYREN.  am I wrong something about the steps of the software?

**Comment by Kingsmart75** [comment]
here I am again, I formatted the notebook and installed Windows 10, same thing, DDT4ALL does not work with the ELM Bluetooth, with pyren it goes but I cannot see the data of the ECU emm-lighting configuration.  @KarelSvo I'll put you the pyren logs with Scan clip mode.  at this point i am determined to complete the mission, can someone tell me what it takes to make ddt4all work?  1. notebook: operating system version?  2. cable that 100% works?  3. various and possible?  Thanks everyone for the support.

![IMG_20220617_093243](https://user-images.githubusercontent.com/106084607/174265639-662bfff1-d931-413c-b29c-65c30110ebe1.jpg)
![IMG_20220617_093256](https://user-images.githubusercontent.com/106084607/174265768-da938c91-0551-4ed4-a48e-2214093c01ac.jpg)
![IMG_20220617_093452](https://user-images.githubusercontent.com/106084607/174265780-4543eda8-5bd9-4ae7-bce9-bec9dce08f7c.jpg)
![IMG_20220617_093709](https://user-images.githubusercontent.com/106084607/174266044-2f9b51e8-221b-44b3-82dd-d598bdb00ca8.jpg)
![IMG_20220617_094151](https://user-images.githubusercontent.com/106084607/174266053-2605c077-86c9-402f-9590-299c732d0ea7.jpg)
![IMG_20220617_094348](https://user-images.githubusercontent.com/106084607/174266061-4db434d3-24f7-4eec-9a54-62b6e48d5a0e.jpg)
![IMG_20220617_094512](https://user-images.githubusercontent.com/106084607/174266067-65464216-cce4-4585-ba97-f74d0bd8415d.jpg)
![IMG_20220617_094554](https://user-images.githubusercontent.com/106084607/174266073-05c024a6-f8a8-4606-814f-db381c3fbde0.jpg)
![IMG_20220617_094644](https://user-images.githubusercontent.com/106084607/174266083-d6555181-6933-4622-980b-862290b3625c.jpg)
![IMG_20220617_094658](https://user-images.githubusercontent.com/106084607/174266094-f4990112-5803-4df2-92be-43540562979e.jpg)
![IMG_20220617_094755](https://user-images.githubusercontent.com/106084607/174266098-6067a00f-5fc8-4d3a-a3d2-0174e23589f7.jpg)
![IMG_20220617_094837](https://user-images.githubusercontent.com/106084607/174266114-56050099-d5bf-4066-a9fa-043978cdf669.jpg)

**Comment by IZ7QEB** [comment]
Ciao @Kingsmart75  .. Assicurati di avere una versione "originale" dell' ELM. A me è successo con una versione fake e non funzionava. Ne ho comprata una adatta su amazon e tutto ha funzionato. 
Successivamente, accertati che il tuo antivirus e il tuo firewall non ti blocchino l'applicazione e di conseguenza il dialogo tra dispositivo e applicazione. Mi è successo e dopo aver escluso dalle protezioni ha funzionato tutto.

**Comment by Kingsmart75** [comment]
just for information that with the OBDLINK SX usb cable everything works without problems, I trashed all the fake elms that did not go in any way.  it is better to spend a little more but in the end you save time and health for all the pisses you have had ... damn fake elm !!!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by afmovement** [comment]
elm
