### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by mitakbas** [cedricp/ddt4all#159]
I've entered the developer mode but accidentally I've touched the first top right option related to 'Screen display', I think it's switched to 'high'...
Now the screen is off (blank), the functions are working but the screen is blank.
I tried more than once to switch off the engine, restart the display unit, and even i tried to pull out the fuse, but nothing worked...
Please help me
 renault kadjar

**Comment by gobo-ws** [comment]
https://gitlab.com/py_ren/pyren/wikis/how%20to%20rlink2%20black%20screen

**Comment by midoucirine** [comment]
es que ça marche pour megane 4 aussi ? merci

**Comment by shrlnm** [comment]
> es que ça marche pour megane 4 aussi ? merci

yes

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
