### ISSUE TITLE
grand kangoo2016 connection problem

### ISSUE THREAD

**Issue by Fischmaster3000** [cedricp/ddt4all#160]
I got the ecu database from a russian site, stated as feb2019. I also got a OBDLink SX and a Y Cable where i took out all the cables an rewired 4-4 5-5(mass) 13-6(can2) 12-14(can2) and 16-16(12v).
obdlink sx is blinking green. when i search for ecus i only find about 5 6, airbag etc...is the media can on kangoo2016 on different connectors?

thanks for help :)

**Comment by KarelSvo** [comment]
Show a screenshot of the scan result.

**Comment by Fischmaster3000** [comment]
sorry had no time to get to the car. i really appreciate your help :)
when i scan it looks like this:
![Capture](https://user-images.githubusercontent.com/48324298/54358055-bc823c80-465f-11e9-952b-fc602bb1087e.PNG)

**Comment by Fischmaster3000** [comment]
you already got time to look into it?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
