### ISSUE TITLE
Scenic 3 StopStart

### ISSUE THREAD

**Issue by steelcityuk** [cedricp/ddt4all#164]
Using ddt4all I've been looking at the UPC -EMM module trying to figure out why stop/start has never functioned on my vehicle. It's had a new battery and Clip used to reset the counters. Looking at the status in Read & Write\Read StopAndStart the only 'incorrect' status I can find is DriverSeatStatus which I think says Driver_nappe_not_detected. Does this mean the vehicle thinks no-one is in the drivers seat?

I'm assuming that the status in the white boxes have to match the status in the yellow boxes?

Thanks.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
