### ISSUE TITLE
 2016 Kadjar Control Glass Closure

### ISSUE THREAD

**Issue by ehese** [cedricp/ddt4all#165]
In my 2016 Kadjar tool, the auto window closing option of the software did not change to true.
![20190317_181629_HDR](https://user-images.githubusercontent.com/48653916/54494810-5ad80180-48ef-11e9-95c2-64550714b5e0.jpg)

**Comment by ehese** [comment]
auto window closing true
but the windows do not close.
Why? Should I make more adjustments?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
