### ISSUE TITLE
need any version with english descriptions

### ISSUE THREAD

**Issue by Tahreer1972** [cedricp/ddt4all#166]
Hi 
its amazing program  thanks alot , i dont know french , is there any version with english descriptions for the different parameters. thanks

**Comment by Tahreer1972** [comment]
Anyone help a bother who struggles with French ?thanks

**Comment by shrlnm** [comment]
The language of parameter descriptions depends on the database content.

The pyren may translate those parameters in ddt database which are in clip database, but usually  clip contains only about 30% of parameters from ddt database.

**Comment by Tahreer1972** [comment]
> The language of parameter descriptions depends on the database content.
> 
> The pyren may translate those parameters in ddt database which are in clip database, but usually clip contains only about 30% of parameters from ddt database.

thank you  very helpful . download it and it works perfect..
