### ISSUE TITLE
R.S Monitor

### ISSUE THREAD

**Issue by Prospero1** [cedricp/ddt4all#167]
Main Question to people who dev dd4all - will be possible to activate R.S Monitor on Rlink2 in near future ? Or it's not only software problem?

**Comment by kenanyildiz55** [comment]
Bu konuyu bende merak ediyorum. R.S monitör.

**Comment by shrlnm** [comment]
R.S. Monitor is a separate application. It is absent in default LGU installation file and should be installed separately

**Comment by ustunkaya07** [comment]
Here is a video. This man installed Rs monitor to megane 4 1.5 dci but he doesnt share anything how he did it

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
