### ISSUE TITLE
Car Type Table

### ISSUE THREAD

**Issue by Sig2018** [cedricp/ddt4all#168]
HI,

Do you know the code for Koleos 2 in the ECU Vehicle type.
There is a table below but Koleos is not there.
BFB – Megane 
BFB-GT – Megane GT 
HZG – Kadjar
JFA – Scenic
JFC – Espace
KFB – Megane SW
KFB-GT – Megane SW GT
KFD – Talisman SW
LFD – Talisman Sedan
LFF - Megane Sedan
RFA – Grand Scenic

Thank you for your help.

**Comment by shrlnm** [comment]
XZG

**Comment by pcboys** [comment]
XZG  koleos II
XZJ   Koleos II CN

**Comment by Sig2018** [comment]
@pcboys @shrlnm 
I'm using the ECU from Koleos XZG but there is no option XZG on vehicle as you can see on Screen capture below.
![VEhic Type](https://user-images.githubusercontent.com/39195035/54602966-e2be2880-4a21-11e9-8d99-ef4244e297be.jpg)
![VEhic Type2](https://user-images.githubusercontent.com/39195035/54602970-e6ea4600-4a21-11e9-83cf-eeb88e32b17e.jpg)

**Comment by shrlnm** [comment]
HZG

**Comment by Sig2018** [comment]
Thank you! Any reference for that?

**Comment by shrlnm** [comment]
I have this value in my koleos. 
And your list above have a mistake. HZG is not Kadjar
![Screenshot 2019-03-19 at 16 25 36](https://user-images.githubusercontent.com/16278412/54609330-cd69ee00-4a63-11e9-8fbf-baf03a64dc49.png)

**Comment by shrlnm** [comment]
I may be wrong but first sign means the type of body
H - SUV
x - any type of body. (the koleos has no others)

so for Koleos XZG==HZG

**Comment by Sig2018** [comment]
Thanks a Lot. Is it your Koleos a New Koleos? Have you played with RLINK 2?
I did a customized upgrade and  I need to set some values to Camera Guidelines, maybe we can share some info.
And yes there are some forums saying Kadjar is  HFE.

**Comment by shrlnm** [comment]
First Koleos was H45
What version of firmware did you have before customized upgrade and what version do you have now?

**Comment by Sig2018** [comment]
I moved from 2.2.19 to 3.3.

**Comment by Sig2018** [comment]
Additionally I found few ECU for new Koleos.

**Comment by Sig2018** [comment]
I'm talking I find just few ECUs compatible with New Koleos. I will scan and send you the list. sermass16-f@yahoo.com

**Comment by Sig2018** [comment]
Sorry I found few ECUs in ddt4 database. I have the 2019 database.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
