### ISSUE TITLE
Possible to set IDLE RPM level?

### ISSUE THREAD

**Issue by githubberboy** [cedricp/ddt4all#169]
Does anyone know if it's possible to change the RPM at idle with a cold engine?

**Comment by shrlnm** [comment]
it depends on ECU

**Comment by AndyIreland** [comment]
this is an interesting question - I have ems 312X_RDC_xxx_RDE320_470_5E0_600_770_850_v1.0  ecu on Mk IV Clio 16v 1.2 and I wouldnt mind increasing the idle speed slightly when engine warm , I find it a little too low idling  - can this be done with DDT4ALL?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
