### ISSUE TITLE
Where to put the ecus?

### ISSUE THREAD

**Issue by octav90st** [cedricp/ddt4all#17]
Please tell me exactly where to put the ecus. I have installed the program and everytime I copy them it seems that the software starts with 0 loaded ecus.

root: c:\program files (x86)\ddt4all\DDT4ALL.BAT

**Comment by gordon6** [comment]
Dear,
You need to put at C:\ECUs or C:\Program files (x86)\DDT4All\ECUs.
Then the problem should prove...

**Comment by octav90st** [comment]
thanks!

C:\Program files (x86)\DDT4All\ECUs is the right path and now it works to select zip database and in the final it says: permission denied ecu,zip

annoying thing. still can't use this program...

**Comment by cedricp** [comment]
zipping database is not mandatory, you can work without this step. I'll try to fix the permission issue, though.

**Comment by cedricp** [comment]
I added a file dialog to ask where to put the final archive, that should be fine now
