### ISSUE TITLE
clear crash airbag

### ISSUE THREAD

**Issue by benea333** [cedricp/ddt4all#170]
I made the page for  airbag logan ph2 so I can delete it crash rsat4_acu_eng_v15 dis russian language
![viber image 2019-03-19 , 17 42 46](https://user-images.githubusercontent.com/36487628/54618427-0f029500-4a74-11e9-9795-4568966fc037.jpg)
![viber image 2019-03-19  48](https://user-images.githubusercontent.com/36487628/54618436-13c74900-4a74-11e9-9237-1881aba58f3d.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
