### ISSUE TITLE
android port - font problem

### ISSUE THREAD

**Issue by Andrengg** [cedricp/ddt4all#171]
lenovo vibe z2pro (k920), lineage os 14.1
https://ibb.co/kMPjJvV
https://ibb.co/6bRR3SR
https://ibb.co/d2nVXR1
https://ibb.co/QY3q9Fj
установлен увеличенный масштаб на телефоне (zoomed on the phone).

**Comment by cedricp** [comment]
Try with default Android fonts from Android general settings. It's quite difficult to make it work with custom fonts

**Comment by Andrengg** [comment]
Can I embed my own font in the program so that it works guaranteed?
