### ISSUE TITLE
Torque PID

### ISSUE THREAD

**Issue by Tahreer1972** [cedricp/ddt4all#173]
Hi  Is there a posibility to produce torque pid in ddt4all ?thanks

**Comment by cedricp** [comment]
You can calculate them from the _request_ page in _edit mode_

**Comment by Tahreer1972** [comment]
Hi , iam sorry i could not find the edit mode . and i have another question if you dont mind .
i need the first steps to how create my own ECU parameters screen. which files i need to start with.  i hope you have a short tutorial somewhere . thanks

**Comment by Tahreer1972** [comment]
hi  it seems to me that my ddt4all windows version has no request page nor data , buttons  or uiedit

**Comment by KarelSvo** [comment]
https://www.club-renault.ru/forum/topic/5528-diagnostika-svoimi-rukami/page/146/?tab=comments#comment-2145011

**Comment by Tahreer1972** [comment]
thanks   done !!!
