### ISSUE TITLE
R-link Evo, screen orientation. 

### ISSUE THREAD

**Issue by ghost** [cedricp/ddt4all#174]
Hi All,

I have a little project, trying to fit RLink system to my Laguna, I've got display from Renault Twingo. 
All works fine except, To fit it in laguna frame I need screen to be rotated 180deegrees.
I know there are RLink with different orientation. 

There is a forum where guys there found value in eeprom for orientation, but they can't calculate checksum for that to work properly. 

Maybe there is better option than rewriting eeprom?

I've noticed in ddt for MFD v4.3 ECU, there is option display orientation, options are 6 or 12 hour view. But nothing changes regardless the option. 

Any ideas?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
