### ISSUE TITLE
fonts problem 2

### ISSUE THREAD

**Issue by Andrengg** [cedricp/ddt4all#180]
this default font Android
<a href='http://imglink.ru/show-image.php?id=ad391fe046ab8881ebd1bcf1120e5a4d'> <img src='http://imglink.ru/thumbnails/09-04-19/41de49155594ea76360be284a530d078.jpg' alt='фотохостинг' border='0'> </a>

**Comment by pakoto** [comment]
Same here

![WhatsApp Image 2019-04-09 at 21 45 44 (2)](https://user-images.githubusercontent.com/24203270/55830334-f89aa700-5b10-11e9-85cd-86d1a4928774.jpeg)
![WhatsApp Image 2019-04-09 at 21 45 44 (1)](https://user-images.githubusercontent.com/24203270/55830348-ff291e80-5b10-11e9-9dc4-4081bb87818d.jpeg)
![WhatsApp Image 2019-04-09 at 21 45 44](https://user-images.githubusercontent.com/24203270/55830350-005a4b80-5b11-11e9-8680-58592479fb84.jpeg)

**Comment by cedricp** [comment]
Did you try with V1.4 ? I fixed some problems like this one recently

**Comment by cedricp** [comment]
Except the font issue, what are your thoughts about the application ?

**Comment by pakoto** [comment]
App works ok! Thanks again.
Full uninstall / install 1.4 again. dokker - edc17c42 - fap
big zoom

![WhatsApp Image 2019-04-09 at 22 26 23](https://user-images.githubusercontent.com/24203270/55832794-9cd31c80-5b16-11e9-8f4e-d3476c9800d4.jpeg)

**Comment by Andrengg** [comment]
this v1.4 ...

**Comment by cedricp** [comment]
I added a font scale override in screen settings (gear icon) in **V1.5**. You can scale up/down.

**Comment by pakoto** [comment]
Works ok. Thanks!

**Comment by pakoto** [comment]
![Screenshot_2019-04-10-11-26-29](https://user-images.githubusercontent.com/24203270/55868422-ba3ecf80-5b84-11e9-8273-9377409a3070.png)

**Comment by Andrengg** [comment]
v.1.5
problems. ..
https://ibb.co/d50CC2P
https://ibb.co/cCkPJ9H

**Comment by igogo2** [comment]
[My](http://mytab.com.ua/ontario_2.html) device.
System - Windows 10 version 1809
My fonts.
![fonts](https://user-images.githubusercontent.com/6361239/55951836-dfa10b80-5c60-11e9-812c-6a4a678dfbaa.png)

**Comment by cedricp** [comment]
It's quite difficult to manage fonts issues for all platforms, and as long as there's so few donation, I can't afford hardware to test it...

**Comment by cedricp** [comment]
@igogo2 : I just commited a fix for font size (remove DPI denpendency)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
