### ISSUE TITLE
truncate values

### ISSUE THREAD

**Issue by pakoto** [cedricp/ddt4all#183]
Is possible to truncate decimals?

![WhatsApp Image 2019-04-11 at 16 34 53](https://user-images.githubusercontent.com/24203270/55984819-a2f40500-5c9e-11e9-9673-331a139bd4c5.jpeg)

Thanks!

**Comment by cedricp** [comment]
Yes, it's on my to-do list !

**Comment by pakoto** [comment]
![Screenshot_2019-04-17-18-58-01](https://user-images.githubusercontent.com/24203270/56307119-6c0d6b80-6144-11e9-87a0-1f5349dd01a1.png)
