### ISSUE TITLE
ECU Tweaker has stopped 

### ISSUE THREAD

**Issue by killuadk** [cedricp/ddt4all#185]
When i give him permissions to r/w in storage it keep stopping

**Comment by fedegiglio** [comment]
Hi Dear, on my Samsung S9 with Android 9 app stops everytime 5 seconds after started... any suggest?

**Comment by cedricp** [comment]
I fixed a crash in V1.71

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
