### ISSUE TITLE
when doing a scan of the ECU's with DDT4ALL what do the different colors mean?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#186]
when doing a scan of the ECU's with DDT4ALL what do the different colors mean in this part of the window, ie black, red, yellow and sometimes green? thanks.

![ddt4all](https://user-images.githubusercontent.com/49172217/56167501-3f384780-5fd0-11e9-855f-ab1f75db4efb.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
