### ISSUE TITLE
Megane 4 Support

### ISSUE THREAD

**Issue by Giuse1977** [cedricp/ddt4all#19]
Hi cedricp,
will ddt4all work with Renault Megane 4 in near future?

regards

Giuseppe

**Comment by cedricp** [comment]
It should already work. What is the problem ?

**Comment by Giuse1977** [comment]
Some users report that is possibile to read but not to write on it. I still had not time to try by myself, anyway..

**Comment by cedricp** [comment]
Well, it depends on the ECU you want to write on, I guess you're talking about MediaNav functions, right ?
Check older issues, there are a lot of information about it.

**Comment by Giuse1977** [comment]
Actually the head unit is R-Link2. Owners of other Renault cars with same head unit reported success, but so far no one on Megane 4 did. I repeat, I had no time to try by myself so far, unluckily 

Inviato da iPhone

Il giorno 29 nov 2017, alle ore 10:53, Cedric PAILLE <notifications@github.com> ha scritto:

Well, it depends on the ECU you want to write on, I guess you're talking about MediaNav functions, right ?
Check older issues, there are a lot of information about it.

**Comment by MeganeIVgrandcoupe** [comment]
It works on Megane IV!

**Comment by cedricp** [comment]
Perfect, so I close the issue
