### ISSUE TITLE
PIC18F2480 ou PIC18F25K80 ??

### ISSUE THREAD

**Issue by stylob** [cedricp/ddt4all#191]
Hi, For android use and for windows use, which one of those microcotrlr do you recommend in the interface ?

PIC18F2480 - PIC18F25K80 ???

Thx...

**Comment by cedricp** [comment]
Mine is a PIC18F25K80 and works correctly.

**Comment by koliveira23** [comment]
Mine is a PIC18F2480 and works correctly also

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
