### ISSUE TITLE
No tuning guidelines rear camara in a new rlink 2 unit v7

### ISSUE THREAD

**Issue by franeti** [cedricp/ddt4all#193]
Hi!

Renault changed me the old rlink2 with 2.2 software for a new unit with software 7. 

Now I haven’t guidelines in the rear camara. The camera is working fine but without the lines. 
They are investigating. They have activated it with canclip but the problem persists. 

With ddt I have desactivated and activated rear camera and guidelines. Reboot... Nothing.
In I/O control, rear camera, I tried to set the guideline, I used display button, the rlink show me the rear camera and ussing the 6 yellow button to set the guideline, nothing was showed in the rlink display. 

Any ideas? I have updated to the latest v7 rlink2 version.

Thanks in advance. Regards. 

![45E50CD4-8DFD-4C7B-A589-98CF340EA1BF](https://user-images.githubusercontent.com/45541582/57019742-a63c3a00-6c27-11e9-9a02-25300933728e.jpeg)

![96DE887F-81BF-4EB0-A74D-1517F419F17B](https://user-images.githubusercontent.com/45541582/57019912-11860c00-6c28-11e9-9b47-bd7b864d065e.jpeg)

![08C031D1-A951-4068-9370-4C02C11B7651](https://user-images.githubusercontent.com/45541582/57020027-69bd0e00-6c28-11e9-8bd0-f7c6233e0686.jpeg)

**Comment by franeti** [comment]
Nobody? 😞

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
