### ISSUE TITLE
nbx_swiss_cf and nbx_scandinav_running_lights_CF is in emm lighting?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#194]
Car: Renault Clio Mk4 2016  Edison EMM SW15 
any idea nbx_swiss_cf and nbx_scandinav_running_lights_CF is in emm lighting settings please?

does the nbx_scandinav_running_lights_CF turn on the 5w sidelight bulbs instead of the LED DRL lights or along with the LED DRL lights? 

![59389336_840877802946512_3133438771421249536_n(1)](https://user-images.githubusercontent.com/49172217/57194837-66d15e80-6f43-11e9-8daa-f62f79d5eff3.jpg)
![59389336_840877802946512_3133438771421249536_n(2)](https://user-images.githubusercontent.com/49172217/57194839-6769f500-6f43-11e9-889a-1b1114829f62.jpg)

thanks

**Comment by AndyIreland** [comment]
I have since found out that if you disable the DRL lights CF (0 instead of 1) and enable nbx_scandinav_running_lights_CF then the sidelights as well as the dipped headlights light up when engine is running...

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
