### ISSUE TITLE
 Steering Mode Configuration

### ISSUE THREAD

**Issue by aqngelrock** [cedricp/ddt4all#195]
Hi everyone. I own a Megane IV, with multi sense. There are as you know various modes of steering assistance (sports, neutral, comfort), which change the amount of steering assistance. Do you know how to change the assistance given for each setting? Because for my driving style, SPORT is too soft. Thanks a lot!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
