### ISSUE TITLE
Cannot update ECU Tweaker from version 1.0 to Version 1.6

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#196]
hello , I have ecu tweaker 1.0 on my android phone and am trying to update it to version 1.6 .. so I go to link  https://drive.google.com/file/d/14hf-nFOS3AWn9Zp6H9J39z0GAlSIX8ky/view and download  EcuTweaker-v1.6.apk and then download and install to my phone ... but when I go into 'manage' on my phone it still says 1.0 it doesnt update it to 1.6  - what am I doing wrong please? 

Even if I delete it off phone, and download and install EcuTweaker-v1.6.apk - when I go into manage apps it says I have 1.0 installed !

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
