### ISSUE TITLE
Change ECO Button Function

### ISSUE THREAD

**Issue by aqngelrock** [cedricp/ddt4all#198]
Hi for all,

Is it possible to change the function of the echo button on Megane IV? I would like to activate the SPORT function instead like on the GT version.
Many thanks for all.

**Comment by m0xz0r** [comment]
This is something I would really like to know too. For starters, does anyone know to which computer the button is connected?

**Comment by tomidix** [comment]
You can change it by changing HFE_BCM_DDT_8_0 -> Mmi -> Config -> Sport_mode_cf to true.
Then you open the Radnav 2.X v2.5 -> Radnav configuration 1.1 -> CF_Car_type from standard to GT or RS.
Then click On/Off Reset or Hard Reset (I do it with Hard reset always) and wait for Rlink to boot. After booting your "Eco" button should now trigger Sport Mode. 

**The problem with this modification is that you will lose your Eco mode and will have only Sport, Comfort, Normal and Perso.** However you can modify Perso to simulate Eco if you want. If you revert your changes, eco mode will come back. 
**Be wise and backup your settings before modifications.**

**Comment by m0xz0r** [comment]
Thanks for the tip! Do you happen to know if these parameters also apply to a 2017 Clio 4 TCe 120? The Clio 4 GT (with exactly the same engine) has an RS Drive button, no ECO.

**Comment by tomidix** [comment]
Don't know. You can try to change the values on your ecu if you have both of them..
Backup first!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
