### ISSUE TITLE
Wrong conversion float to int

### ISSUE THREAD

**Issue by shrlnm** [cedricp/ddt4all#2]
Module ecu.py lines 548-554.

        res = (value * float(self.step) + float(self.offset)) / float(self.divideby)
        if len(self.format) and '.' in self.format:
            acc = len(self.format.split('.')[1])
            fmt = '%.' + str(acc) + 'f'
            res = fmt % res
        else:
            res = int(res)

If a parameter has no format string then it always would be treated as an integer. I suppose that we should omit "else" clause

**Comment by cedricp** [comment]
Absolutely true !
