### ISSUE TITLE
Support for KKL 409.1 CH340

### ISSUE THREAD

**Issue by Inf3rnus187** [cedricp/ddt4all#20]
Salut et juste avant ma demande good job c'est vraiment top ce que t'as fait ;)  
Peu après que tu l'ai sorti j'avais commencer à faire un installateur mais étant pris à coté j'avais pas eu le temps de m'y remettre et je voie que t'as bien avancer ! 

Mon Elm est en puce ch340 bien reconnu et mon cable kkl aussi il est bien lister dans la selections des ports mais quant je le test j'obtiens 

**

> Tentative d'ouverture du portCOM4 @ 38400
> Erreur:could not open port 'COM4': WindowsError(5, 'Acc\xe8s refus\xe9.')

**

Je me demandais ou faire deux trois modif afin de pouvoir le choisir au début dans la sélection du port ? 

Hors sujet ...J'ai du matos j'ai du raspberry, linux, mac(hackintosh) windows(xp à 10) android ios de quoi souder de l'elm usb et bluetooth  un kkl 409.1 en foutu CH340 qui avec DDT me liste parfois les ECU et parfois non j'ai jamais pu en profiter...

Je commande ma Clip des Transpondeur et vais faire des test.

 D'ou mon idée de le test avec DDT4 All ;) 

JE code en python vb un peu de C# un peu de C etc j'ai de quoi apporter un peu d'aide test si ca te tente ... 
En espérant que tu passe par là merci à toi ;)

**Comment by Inf3rnus187** [comment]
Ben ce que je capte pas c'est justement la puce de mon elm 1.5a est la même....

Après oui c'est sur que  il est juste fait pour le protocole kwp2000 ce cable. 

Mais justement ma laguna 2 phase 2 de 2006 l'uch est en kwp et via ddt2000 et ce fameux cable ou même ddt4all et le cable ELM je n'arrive à rien dessus non plus, j'espérais que je pourrais me retourner avec ton soft est mon cable pour faire mes test. 

Juste au cas ou mon cable ELM est bien censer lire écrire sur le KWP2000 Fast init  ?

**Comment by cedricp** [comment]
Oui la lecture/ecriture doit fonctionner, apres, faut verifier que les PINs de l'adaptateur vont au bon endroit... Pour ma part j'ai jamais pu tester, mais on a fait des essais avec quelqu'un qui m'a reporte que son dacia arrivait a lire/ecrire en KWP2000 FastInit.

**Comment by justForHobby** [comment]
Hi, 
is there instructions in English for fix BUS INIT : BUS ERROR? 

I'm using Proscan automotive DDT4ALL adapter.
Issue is with Kangoo AC4 ph2-crash data reset
