### ISSUE TITLE
TPMS Renault Zoe

### ISSUE THREAD

**Issue by PeBueGo** [cedricp/ddt4all#202]
After I had changed the winter tires to summer tires I alway get tire warnings in my Zoe.
I think I have to write the new four TPMS-IDs into the Body Control Modul (BCM).
Have anybody done that and what are the new **TPMS-IDs ?

**Comment by premultiply** [comment]
https://www.goingelectric.de/wiki/Renault-ZOE-Andere-RDKS-Sensoren-anlernen/

**Comment by PeBueGo** [comment]
Thats  a very good description!
But I don't know the TPMS-IDs, because it seems that there is no autolearning in the Zoe

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
