### ISSUE TITLE
question ?! OBD activation - stepway urban 2019!

### ISSUE THREAD

**Issue by yo8aiv** [cedricp/ddt4all#203]
has anyone tested yet to add OBD activation on stepway urban 2019, or any operation yet ?!
Thanks in advance.

bjr. est-il possible ajouter l'obd de le faire avc elm327? ou quel interface je peut utiliser/est conseille?. 
Merci d'avance.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
