### ISSUE TITLE
ABS ECU not showing up when doing a search for ECU's

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#205]
Hello - its a Clio Mk4 1149cc 12v 2016 medianav dyaminque 

when clicking on magnifying glass in DDT4all  it finds all the normal ECU's like lights, cluster, injection, airbag etc but it does not automatically find the ABS/ESC ECU 

- I find I have to manually select ABSESC  - x10527998 version 3.8  

is that normal that I have to select the ABS/ESC ECU manually or should DDT4ALL find it automatically when I click on magnify glass ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
