### ISSUE TITLE
Unicode Warning

### ISSUE THREAD

**Issue by baggi166** [cedricp/ddt4all#206]
Hi Cedric,
I'm testind dd4all and  I get an error during the scan for ECU, du to unicode warning in ecu.py

`Initialisation ELM a la vitesse 38400...
Tentative d'ouverture du portCOM4 @ 38400
1784 ECU charg├®es en base de donn├®e.
Warning, address 5D is not mapped
Scanning ECU INSULATOR
Scanning ECU ACC
Scanning ECU IDM
Scanning ECU UCH
Scanning ECU UPC-EMM
Scanning ECU 4WS
Scanning ECU CSHV Airbag Vehicle stopped
Scanning ECU HVAC
Warning, address 404 is not mapped
Warning, address 401 is not mapped
Warning, address 400 is not mapped
Scanning ECU BSW
Skipping CAN extended address (not supported yet)  2D
Scanning ECU UBP
Scanning ECU Renault RemoteEntry
Scanning ECU ADP
Scanning ECU FRRAD
Scanning ECU Airbag-SRS
Scanning ECU Additional Heater
Scanning ECU MIU
Scanning ECU Navigation-UCC-ITM
Skipping CAN extended address (not supported yet)  16
Scanning ECU TDB
Scanning ECU TCU
Scanning ECU DLOCK
Scanning ECU 4WD
Scanning ECU Tachometer
Scanning ECU WCGS
Scanning ECU CAN Adapter / BAC
Scanning ECU VSP
Scanning ECU AAU
Scanning ECU C Box
Scanning ECU Suspension pilote
Scanning ECU ABS-VDC - ABS-ESP
Scanning ECU EMCU
Scanning ECU HLS
Scanning ECU Direction assiste
Scanning ECU TPMS
Scanning ECU MC HEV FSCM
Scanning ECU EPS
Scanning ECU SVS
Scanning ECU Step_Up
Scanning ECU SCRCM
Scanning ECU SCCM
Skipping CAN extended address (not supported yet)  E1
Skipping CAN extended address (not supported yet)  E0
Skipping CAN extended address (not supported yet)  E3
Skipping CAN extended address (not supported yet)  E2
Warning, address EE is not mapped
Scanning ECU Audio
Scanning ECU TCASE
Scanning ECU TPAD
Scanning ECU HU
Scanning ECU HFCK
Scanning ECU Frein de parking lectrique
Scanning ECU Aide au parking
Scanning ECU Superviseur-DCDC
Skipping CAN extended address (not supported yet)  60
Scanning ECU AVM
Scanning ECU FCAM
Scanning ECU SOW Left
Scanning ECU SOW Right
Scanning ECU VCCU
Scanning ECU BCB
Scanning ECU PEB
Scanning ECU HFM
Scanning ECU LBC (HEV)
Scanning ECU LBC (EV)
Scanning ECU (H) EVC
Scanning ECU PLC/PLGW
Scanning ECU ADAS-Sub
Scanning ECU Audio
C:\Program Files (x86)\ddt4all\ecu.py:1156: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if self.supplier.strip() != supplier.strip():
C:\Program Files (x86)\ddt4all\ecu.py:1142: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if supplier_strip != supplier.strip()[:len(supplier_strip)]:
Traceback (most recent call last):
  File ".\ddt4all.py", line 140, in scanselvehicle
    self.parent().parent().scan_project(project)
  File ".\ddt4all.py", line 707, in scan_project
    self.scan()
  File ".\ddt4all.py", line 763, in scan
    self.ecu_scan.scan(self.progressstatus, self.infostatus, None, self.canlinecombo.currentIndex())
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1609, in scan
    self.identify_old(addr, label)
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1437, in identify_old
    self.check_ecu(can_response, label, addr, "CAN")
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1679, in check_ecu
    self.check_ecu2(diagversion, supplier, soft, version, label, addr, protocol)
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1759, in check_ecu2
    % (ecu_type, diagversion, supplier, soft, version)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
`

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
