### ISSUE TITLE
renault I reset my car's radio with dd4all. The radio does not work.  on the radio screen. Install the diag device. warning

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#208]
.

**Comment by shrlnm** [comment]
What is the car?
What is the radio?
Which xml file did you use for reset?
Have you saved logs?

**Comment by JAzevedo351** [comment]
Hello, the car is SCENIC IV BOSE EDITION, the radio is R-link2 software version (3.3.15.416), unfortunately I did not save the logs before the modification, nor later, I used the .xml available in DDT4ALL version 5.4.0, XFA - SCENIC IV / RadNav 3.x v3.3), I hope these data will help, if it does not help I will give the necessary information, thank you very much for the readiness you undertook to help.
![P_20190531_095931_vHDR_Auto](https://user-images.githubusercontent.com/51206427/58703152-a43cd680-839f-11e9-8b10-c2044d4f1459.jpg)

**Comment by JAzevedo351** [comment]
Sorry, that questions not for me...

**Comment by atumelektronik** [comment]
> Araba nedir? 2011 Fluence
> Radyo nedir Oem no 281155040R
> Sıfırlama için hangi xml dosyasını kullandınız? ddt4all audio rest
> Günlükleri kaydettiniz mi?
problem. (connect diag unit)
[https://i.hizliresim.com/mXqyB4.png](url)
[https://www.drive2.ru/b/532332953708003369/](url)

**Comment by BarektE** [comment]
bu bilgiyi yazanlar bilgi sahibi değiller. sayfa yararlı değil
