### ISSUE TITLE
DDT4ALL not working some ecu configuration

### ISSUE THREAD

**Issue by hoonythink** [cedricp/ddt4all#21]
hi, long time no see. 
i have Koleos II and use OBDLINK SX (USB) for ddt4all.
"ddt4all" works very well and satisfactory.

However, recently one problem has been found.

"ESC___1540_HFE_XZG_Version_2.3_20170620T142408.xml"

Click the "Write" button has no effect.
No changes occur.
There is no error message too.

![default](https://user-images.githubusercontent.com/31832805/33541641-28bc3a92-d913-11e7-97be-a252ee4bb21e.JPG)

but, it works in a program called "RenOLink".

and Some users ask me. 
When they click the "Write button", the setting value("Read" side value) changes.
However, the setting values are initialized when reconnected.
do you know about this?

I always thank you for your hard work.

**Comment by cedricp** [comment]
It seems that the ELM doesn't wait enough to get the ECU response, try to increase **CAN Timeout** value to 600-800ms in the bottom of the screen and then send the request.

**Comment by hoonythink** [comment]
sorry, i'm late.
I tried and succeeded as you told me. 
thanks.

and....
Could you answer me the second question?

**Comment by cedricp** [comment]
I have no idea about the second point, sorry. Have you tried a soft reset ?

**Comment by hoonythink** [comment]
my car and obdii cable is working well.
someone told me the problem. 
I thought the problem was due to Bluetooth OBDII model.
But people who use the same cable as me are also experiencing the same problem.

Thank you for your attention.

**Comment by Ylmz038** [comment]
Merhaba ddt4all ile ABS yada ESP ayarlarını bozdum galiba ABS Işığı aracımda sürekli yanıyor yardım edin lütfen 

Uploading VID_20231003_171717.mp4…

**Comment by AndyIreland** [comment]
> Hello, I think I messed up the ABS or ESP settings with ddt4all. The ABS light is constantly on in my vehicle, please help.
> 
> Uploading VID_20231003_171717.mp4…

hi, either enable ABS/ESP back again or extinguish the light by going into your 'clustre' settings and choose 'no ABS' and/or ' no eps'
