### ISSUE TITLE
VIN

### ISSUE THREAD

**Issue by thomson56** [cedricp/ddt4all#212]
Hello, how to restore the number VIN after Virgin mode reset

**Comment by shrlnm** [comment]
RadNav_*.xml
menu "Diagnosis/Identification" in the bottom of screen

**Comment by thomson56** [comment]
Mais dans quel programme


Wysłane z aplikacji Poczta dla Windows 10

Od: shrlnm
Wysłano: niedziela, 2 czerwca 2019 20:02
Do: cedricp/ddt4all
DW: thomson56; Author
Temat: Re: [cedricp/ddt4all] VIN (#212)

RadNav_*.xml
menu "Diagnosis/Identification" in the bottom of screen

**Comment by shrlnm** [comment]
> Mais dans quel programme

ddt4all or pyren/mod_ddt

**Comment by thomson56** [comment]
Et vous pouvez utiliser DDT avec plus de précision, mais je ne sais pas où regarder, je ne le vois pas



Wysłane z aplikacji Poczta dla Windows 10

Od: shrlnm
Wysłano: niedziela, 2 czerwca 2019 20:48
Do: cedricp/ddt4all
DW: thomson56; Author
Temat: Re: [cedricp/ddt4all] VIN (#212)

Mais dans quel programme
ddt4all or pyren/mod_ddt

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
