### ISSUE TITLE
BCM/UCH FAl MMI Configuration

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#213]
hello 
If I start up 

DDT4ALL in **DEMO mode** 'T4_VS_BCM_BIS_DDT2000_SW15_1'   'Fal_ MMI_Configuration'  
there is a setting for ECO_SWITCH_TYPE and parameters of 'NO BUTTON SWITCH'  'ECO BUTTON SWITCH' and 'MEX BUTTON SWITCH' 

But if I start T4_VS_BCM_BIS_DDT2000_SW15_1  Fal_ MMI_Configuration 
actually connect it on my car the ECO_SWITCH_TYPE does not show at all

Why is this please?

![ecobutton](https://user-images.githubusercontent.com/49172217/58768439-1c1f2280-8593-11e9-83ff-8f5cefb68dd3.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by monalos** [comment]
> [#836](https://github.com/cedricp/ddt4all/issues/836)

Can you delete a post entirely?
