### ISSUE TITLE
Loss of touch response after applying mex

### ISSUE THREAD

**Issue by SnibboRen** [cedricp/ddt4all#215]
I have a Megane 4 with original rlink 2.2 upgraded to 3.3. I applied mex active and then performed a restart. Restart was quite slow and when finally up, the system no longer responded to touch inputs on the screen. All other functions are working correctly. Does anyone have any thought on  how to resolve?

**Comment by pcboys** [comment]
I have encountered a similar situation, and then reset the default value in radnav /Engineering configuration, and restore it after reboot.
Perhaps you can find the same type of rlink2, refer to its default parameters.

**Comment by SnibboRen** [comment]
Thanks @pcboys. When you say reset default,  are you referring to a particular variable or global defaults?

**Comment by pcboys** [comment]
My vehicle is kadjar and the parameter values are not for your vehicle.

**Comment by Dema323** [comment]
is mex = multisense ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
