### ISSUE TITLE
The latest versions of the program for Android do not work.

### ISSUE THREAD

**Issue by duh555** [cedricp/ddt4all#216]
Hey. Version of the program for Android, starting with version 1.1 and ending with version 1.6 work fine. Versions 1.7, 1.71 and 1.72 start and immediately collapse. What is the problem?

**Comment by cedricp** [comment]
No idea, could you plug your device to a PC and use Android tool 'logcat' to inspect the crash ?

**Comment by atumelektronik** [comment]
<a href="https://i.hizliresim.com/LvYGoJ.jpg"><img src="https://i.hizliresim.com/LvYGoJ.jpg"></a>

**Comment by duh555** [comment]
Hey. You probably do not understand me. I'm trying to use google translator. Version of my Android 5.1.1. Versions of Ecu Tweaker for Android, starting with version 1.1 and ending with version 1.6, work fine (1jpg). Versions 1.7, 1.71 and 1.72 are launched and immediately minimized (2jpg, 3jpg).
![1](https://user-images.githubusercontent.com/51461280/59218140-2d39e600-8bc8-11e9-8bf0-45aa501fdc5c.jpg)
![2](https://user-images.githubusercontent.com/51461280/59218163-388d1180-8bc8-11e9-9361-a11973000628.jpg)
![3](https://user-images.githubusercontent.com/51461280/59218173-3fb41f80-8bc8-11e9-8bd9-79c624933bad.jpg)

**Comment by cedricp** [comment]
V1.73 released today, test it and report

**Comment by duh555** [comment]
Скачал, установил - проблема осталась.

**Comment by atumelektronik** [comment]
> Hey. Sürüm 1.1 ile başlayan ve sürüm 1.6 ile biten Android için programın sürümü iyi çalışıyor. 1.7, 1.71 ve 1.72 sürümleri başlar ve hemen daraltılır. Sorun nedir?

sorun bluetooth yazar tam olarak bluetooth'u adapte edemedi programa wifi kullananlarda sorun yok

**Comment by duh555** [comment]
İpucu için teşekkürler. Wi-Fi adaptörü ile programın 1.73 sürümünü kontrol etti-program çalışıyor. 16.06.2019, 20:14, "atumelektronik" <notifications@github.com>:Hey. Sürüm 1.1 ile başlayan ve sürüm 1.6 ile biten Android için programın sürümü iyi çalışıyor. 1.7, 1.71 ve 1.72 sürümleri başlar ve hemen daraltılır. Sorun nedir?sorun bluetooth yazar tam olarak bluetooth'u adapte edemedi programa wifi kullananlarda sorun yok—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by duh555** [comment]
Thanks for the advice "atumelektronik". He told me to use a Wi-Fi adapter. I tried the version of the program 1.73 with Wi-Fi adapter - it works well.

**Comment by curiosopt** [comment]
The same happen on my OnePlus6, 1.7 and the latest versions of ecu tweaker stops like OP. Android 9

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
