### ISSUE TITLE
Renault Fluence second hand speedometer. How to reset the mileage ddt4all with

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#220]
Renault Fluence to my car. I bought a used speedometer. The original kilometer is 165,000 kilometers. The screen mileage I bought is 207 thousand. How can I reduce the display mileage to 165,000 with DDT4all?
![O0Rmmz](https://user-images.githubusercontent.com/43322396/59450973-19ce8b00-8e13-11e9-9a0e-e6a7444825ca.jpg)

### original

![7ff135b7-bade-4df8-83d7-74de392fb2b8](https://user-images.githubusercontent.com/43322396/59451185-88abe400-8e13-11e9-804d-69f8a9f47ddb.jpg)

**Comment by atumelektronik** [comment]
benden başka kimse çözemeyecek demek ki bu sorunu.

**Comment by BarektE** [comment]
bu bilgiyi yazanlar bilgi sahibi değiller. sayfa yararlı değil
