### ISSUE TITLE
ecu tweaker bluetooth the proplem

### ISSUE THREAD

**Issue by atumelektronik** [cedricp/ddt4all#221]
The author of the program could not solve the bluetooth problem. There is bluetooth problem in versions after 1.7. ecu tweaker stopped error. Turn off bluetooth is doing error when bluetooth is on.
![4acc3d30-c876-4365-93a7-f77a78aa87a1](https://user-images.githubusercontent.com/43322396/59551280-f2490100-8f7f-11e9-968c-66df322b091c.jpg)

**Comment by cedricp** [comment]
I did some upgrades recently, try it

**Comment by atumelektronik** [comment]
> Son zamanlarda bazı güncellemeler yaptım, dene

I've tried
![Ekran Alıntısı](https://user-images.githubusercontent.com/43322396/59557042-0ddff600-8fd8-11e9-9bd0-3bfcd3adb9ec.PNG)

**Comment by tomidix** [comment]
@cedricp just close the issue and mention this BT problem as unsupported if this works on newer Android... Don't spend your time bothering with Android which was released October 31, 2013 when the cars are mostly newer...

**Comment by cedricp** [comment]
This is probably not a big problem, but as I don't have an old Android device, I have no way to test it.
Could you try to connect your device to a PC and report logcat at the moment of the crash ?
https://developer.android.com/studio/command-line/logcat

**Comment by cedricp** [comment]
I fixed this issue on version 1.74c.

**Comment by atumelektronik** [comment]
> Bu sorunu 1.74c sürümünde düzelttim.

Dear cedricp DOWNLOAD LINK V1.74c has fixed the issue with this update. You are super. The correct diagnosis was easy to correct. I detected the Bluetooth problem and wrote it to you.

**Comment by atumelektronik** [comment]
> Bu sorunu 1.74c sürümünde düzelttim.

Dear cedricp DOWNLOAD LINK V1.74c has fixed the issue with this update. You are super. The correct diagnosis was easy to correct. I detected the Bluetooth problem and wrote it to you.
