### ISSUE TITLE
I want to hear the horn beep when I lock the doors.

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#224]
renault megane 3 I want to hear the horn beep when I lock the doors. Does anyone know how to do this with ddt4all?

**Comment by atumelektronik** [comment]
sonunda ddtall ile arabamın kapısını kilitleyince korna bip yapıyor ayarladım.

**Comment by tanerdogan** [comment]
Çözümü yazarsanız biz de deneyebiliriz?

**Comment by pcboys** [comment]
bcm/uch ->AlarmPerimetric->AlarmPerimetric-configuration ->BIPBIP_LOCK_CF ->true

**Comment by AndyIreland** [comment]
I have the Perimetric alarm enabled and it flashes the indicators for a while if someone where to break in , but no horn sounds - does anyone know why?

**Comment by EXcomZkko** [comment]
@atumelektronik  Hocam nasıl yaptınız, biraz detay verebilir misiniz? Önceden beri istediğim bir olay.

**Comment by BarektE** [comment]
bu sayfaya yazanlar bilgi sahibi değiller. sayfa yararlı değik
