### ISSUE TITLE
Close the glass, mirror and sunroof from the Megane 2 controller,

### ISSUE THREAD

**Issue by nersoy72** [cedricp/ddt4all#225]
Hi, Cedric. What should I do to close the window, mirror and sunroof from the remote control on my Megane 2 2005 model 1.6 16v vehicle?

**Comment by nersoy72** [comment]
Hello, Cedric. I figured out how to solve the problem. feature is activated when we press the lock button on the vehicle's card 3 times in a row. The next time you press twice is enough. But the problem is that it is not possible to close the mirror. Only 4 windows and the sunroof closes.

**Comment by AndyIreland** [comment]
hello - have you enabled 'auto folding' for the mirrors in DDT4All?

**Comment by nersoy72** [comment]
Hi, no unfortunately this is impossible because mirrors are not attached to the ecu.
