### ISSUE TITLE
Check or activate automatic window open/close on Clio IV

### ISSUE THREAD

**Issue by sirbig** [cedricp/ddt4all#229]
Hello,

After I unplugged and plugged back in the left window plug from the buttons controller, they stopped working just like that, there is no power reaching the plug lines and no fuses are blown.
I suspect that the issue is a possible desprogramming that ocurred in the BCM but I can't find the option to test/configure the front windows, I only have the Window Lift option that controls the activation of rear automatic windows...

Is there a way to find that option for the front windows using ddt4all/pyren?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
