### ISSUE TITLE
Work with the original adapter

### ISSUE THREAD

**Issue by RUNNO1** [cedricp/ddt4all#23]
Hey. I have an original CAN adapter. It is possible to make the original CAN adapter work with the program ddt4all?
Help to connect the original CAN
![dscn0521](https://user-images.githubusercontent.com/34477360/33883032-3fb0cf18-df4b-11e7-805a-9a36978533fc.JPG)
 adapter to your program.
Very grateful.

**Comment by cedricp** [comment]
Unfortunately, no. I have no documents on how to drive this adapter.

**Comment by RUNNO1** [comment]
Maybe I will help. What kind of information are you interested in?

**Comment by cedricp** [comment]
Documentation about the adapter (datasheet), and an adapter to do some testing...
