### ISSUE TITLE
Keyless Go & Headlight

### ISSUE THREAD

**Issue by tanerdogan** [cedricp/ddt4all#231]
Hello everyone, (2015 Icon 1.2 Turbo)

I have 2 question and need help. I think i broke some settings and dont know what happened.

**Problem 1**: Keyless Go doesn't work properly, most of times not realize auto lock. 
**Problem 2**: When I set headlight to auto, still lighting on after lock the car. Its doesn't seems like Follow home because not turn off after time (also checked in DDT4ALL, follow home parameter is false) (Watch problem video on Youtube: https://www.youtube.com/watch?v=jbAKYeB7i9Y)

**HELP:** Is there anyone knows exact setting for this issues OR is there any How to RESET ECU (SAFE!) example? I want to back default settings all my ECUs, possible? How?

Thank you for help, also thank you @cedricp  for this app i was used almost 6 month perfect but mine stupid acts broke some settings.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
