### ISSUE TITLE
Anyone tried ddt4all with older Koleos I OBD (2009)

### ISSUE THREAD

**Issue by arminlinder** [cedricp/ddt4all#235]
Does it work?

Thx, Armin.

**Comment by arminlinder** [comment]
Doesn't seem to work. Bought an Obelink SX cable and tried: 0 Ecu found.

**Comment by KarelSvo** [comment]
show your log files

**Comment by arminlinder** [comment]
Thanks for you reply. I am on vacation till beginning September, got word from Cederic that DDT4all is indeed supposed to work with Koleos I too, which is good news for me. I will look deeper into my issue and respond with logs right when I am back. Armin,

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
