### ISSUE TITLE
Modo virgen R link 2 megane 4

### ISSUE THREAD

**Issue by Shadowever** [cedricp/ddt4all#236]
Hola, necesito ayuda para salir del modo virgen.

**Comment by shrlnm** [comment]
Share your email please

**Comment by Shadowever** [comment]
Shadowever25@hotmail.com

**Comment by Emaromao123** [comment]
Good Evening,

Same problem, ive pressed virgin mode so what now?
I have Usb Elm interface, already tried pyren with the same macros and nothing, it seems that i cant have acess to CAN.

Any help? 

Ema-pt@hotmail.com

**Comment by Emaromao123** [comment]
> Share your email please

Can you help me getting out of virgin mode? Also tried pyren with the macros and nothing happens. I have wrong response with can. I'm using elm 327 USB. Can you help? Ema-pt@hotmail.com.
Thank you

**Comment by Rubele2** [comment]
Hola!
Necesito ayuda para reestablecer la pantalla del Rlink . Le he dado a Virgin Mode sin querer, he probado con las 4 macros de pyren y no funciona. Podrías ayudarme por favor?
Mi correo es rubele@hotmail.es.
Muchas gracias

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
