### ISSUE TITLE
unknown Navigation on R-Link

### ISSUE THREAD

**Issue by flegaigor** [cedricp/ddt4all#237]
hi,
today I have tried to turn on rear camera on my Renault megane III ph2. I made a change to Can bus wires and scan my car computers. DDT4all found Audio(radio) and MIU and Navigation with no relevant ECU file found: Diagversion [20] Supplier [329] Soft [333C] Version [4130].
How can I access this navigation and make changes?

**Comment by myshuker** [comment]
did you solved the problem ? and how if yes

**Comment by AndyIreland** [comment]
> Hello, I have a r link after the reset does not want to run, black screen. Via the modified cable both DDT4all and Reno link cannot find computers from navigation or radio. Can somebody help me?

does screen light up even if its black or blank, can you see the backlight of the screen. and try pressing home button 5 times . and try disconnecting 12v battery under bonnet for 10 mins then connect back up (if it does start up you may need to enter the r-link security code)
and you are sure the rewired lead or adaptor is wired properly yep?

**Comment by vraug666** [comment]
> 

I used to activate android car via modified cable. After that I found the upgrade, installed and the r link no longer wants to run. The car is a megane3 2015.
 Installed new radio, display, BIC, UCH and again does not respond. I don't know why I can't find computers from navi, radio and BIC.

**Comment by AndyIreland** [comment]
and does backlight of screen light up?

**Comment by vraug666** [comment]
> i svijetli li pozadinsko osvjetljenje ekrana?

Not. Everything is dead.

**Comment by AndyIreland** [comment]
checked the rlink fuse in the fuse box?

**Comment by vraug666** [comment]
Yes

uto, 21. lip 2022. 15:44 Andy Robus ***@***.***> je napisao:

**Comment by AndyIreland** [comment]
try pyren and tick box 'can2' and try searching , if not then sounds like boot img of rlink corrupted and needs re-flashing on a bench

**Comment by vraug666** [comment]
Ok. How to flash it again.

**Comment by vraug666** [comment]
> try pyren and tick box 'can2' and try searching , if not then sounds like boot img of rlink corrupted and needs re-flashing on a bench 
With a modified cable I scan or not?

**Comment by AndyIreland** [comment]
yep, use modified cable and select can2 box in pyren

**Comment by vraug666** [comment]
> da, koristite modificirani kabel i odaberite can2 box u pyrenu

OK

**Comment by vraug666** [comment]
> Ok. How to flash it again.

**Comment by AndyIreland** [comment]
well i dunno how to do it but this Guy in Romania I think fixes them and re-flashes them if you drop him a line see what he says:
https://www.facebook.com/iongeorgel.popa

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
