### ISSUE TITLE
Duster II - Wifi Konnwei KW903

### ISSUE THREAD

**Issue by dusterII** [cedricp/ddt4all#239]
Hi. I try to connect to my duster 2 with a wifi konnwei kw903.
It seems that it connects but I get "NO DATA" in the read pane.
I attach my logs. I use windows 10 Pro / 64bit.
Thank you in advance for your help.

[kw903_logs.zip](https://github.com/cedricp/ddt4all/files/3463858/kw903_logs.zip)

**Comment by KarelSvo** [comment]
Your Elm does not support AT CRA and AT FC SH.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
