### ISSUE TITLE
graphics on Screenview

### ISSUE THREAD

**Issue by 2xm** [cedricp/ddt4all#24]
![ddt4all_pics](https://user-images.githubusercontent.com/10902255/34256318-0c5786c8-e655-11e7-8fc8-febb3dd19ce9.JPG)

is it possible, to get the orginal images working in ddt4all ?
i have not found any option, to tell the programm to find the path of the pictures 

sry for my bad english

**Comment by cedricp** [comment]
Graphics added, enjoy :)

**Comment by 2xm** [comment]
i thank you so much !

**Comment by cedricp** [comment]
FYI : just fixed image scale

**Comment by MeganeIVgrandcoupe** [comment]
what can i use this function for?

**Comment by cedricp** [comment]
Just add images in screens
