### ISSUE TITLE
Display BLACK

### ISSUE THREAD

**Issue by chimichima** [cedricp/ddt4all#241]
Hello.Please help...
The screen turns black when the HIGH button is pressed in developer mode.
Radio and music can be heard without problems.
How can I fix it?

**Comment by shrlnm** [comment]
> How can I fix it?
https://github.com/cedricp/ddt4all/issues/123

**Comment by chimichima** [comment]
Thank you for information.
However...I don't have any tool for fix...

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
