### ISSUE TITLE
R-Link 2 Errors, please help me...

### ISSUE THREAD

**Issue by mavvi** [cedricp/ddt4all#242]
Hello. Please help...
Update v7 after
The camera is not active when reverse gear is engaged after the R-Link update.
The climate display does not show the set temperature.

**Comment by atumelektronik** [comment]
EEPROM'da ilk kapalı itme dikiş şeridinin girdap Flap Bayrağı
EEPROM'da açılan ilk açılan itme dikiş şeridinin Flap Bayrağı
Swirl Flap İlk kapalı baskı pozisyonu leamt'ın mevcut değeri
Swirl Flap Son kapalı baskı pozisyonu 'leamt'ın akım değeri
Swirl Flap 'Açılmış ilk itme pozisyonu gergisinin güncel değeri
Swirl Flap Açık açılan son konumdaki 'leamt

![AA](https://user-images.githubusercontent.com/43322396/64076966-22c54f00-ccd4-11e9-9fb3-a107a16a508a.JPG)

**Comment by comaly** [comment]
Merhabalar,
Bu konularda tecrubeli değilim.
Anlayabileceğim şekilde yazabilir misiniz?
Aracım Megane 4 HB ICON EDC DCI 2017 model

**Comment by atumelektronik** [comment]
bunları kontrol edin

![1](https://user-images.githubusercontent.com/43322396/64107261-bead9400-cd82-11e9-8e7e-9e616febef66.JPG)
![2](https://user-images.githubusercontent.com/43322396/64107262-bead9400-cd82-11e9-9777-c662f28a0f7c.JPG)

**Comment by comaly** [comment]
Sorun halen devam ediyor. / The problem still exists.

**Comment by yk2548** [comment]
merhaba sorunu çözebildiniz mi? aynı sorunu yaşıyorum şuan yardımcı olursanız sevinirim..

**Comment by yk2548** [comment]
ben servise gittim aynı sorun vardı yarım saat içinde yeniden programlayıp verdiler 63tl ücret aldılar. ddt4all ile yapılacak birşey değil. yükseltme yaparken eksik kalan birşeyler var ön yükleyici sürümü. bu sürümün güncellenmesi gerekli ve bunu sadece yetkili servis yapabiliyor. v2 den v7 ye kendim yükseltmiştim.

**Comment by BarektE** [comment]
> ben servise gittim aynı sorun vardı yarım saat içinde yeniden programlayıp verdiler 63tl ücret aldılar. ddt4all ile yapılacak birşey değil. yükseltme yaparken eksik kalan birşeyler var ön yükleyici sürümü. bu sürümün güncellenmesi gerekli ve bunu sadece yetkili servis yapabiliyor. v2 den v7 ye kendim yükseltmiştim.

Hangi servis olduğunu paylaşmanız mümkün mü? 63TL çok uygun

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
