### ISSUE TITLE
No remote AC or charge schedule after activate clock on dashboard

### ISSUE THREAD

**Issue by MarcosMar** [cedricp/ddt4all#243]
Hello.
I have a Zoe.
After do the mod to activate the clock and the outside temp in the dashboard, and choose the option "No mfd present" (because the clock is under the instant consummation), I really that I can't no more activate by the Renault app the remote AC, Ac schedule and charge schedule!
I put settings back but still don't work remotely, just on the car.

I saw that a lot of people that do this mode have the same issue..... Anyone have solved this problem ?

Sorry my English....

**Comment by MarcosMar** [comment]
I know that's not a ddt4all issue but if anyone have solved this problem please let me know.
Thanks

**Comment by KarelSvo** [comment]
No log file available?

**Comment by MarcosMar** [comment]
Sorry for my late answer.
I cannot retrieve the log.
I made the mode with the ecutweker android app and when I press view log, the app freezes and after 2 min suddenly close!

**Comment by cedricp** [comment]
You can get your logs in your Android device with adb or a file explorer here :
/data/data/org.quark.dr.canapp/files/log.txt
When the file is too big, it can overflow the clipboard.

**Comment by MarcosMar** [comment]
I open the discribed folder but it shows 0 files! ...

**Comment by cedricp** [comment]
Yes, you probably don't have permission to read it or you cleared it. I released v1.8, this version copies the log file to your download directory instead of showing it (and doesn't crash if log is too big !).

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
