### ISSUE TITLE
Cluster version in DDT4ALL Update 09/07/2019

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#244]
@cedricp here's a new issue I have found with the new database update 09/07/2019

Before in the previous database when I used the magnifying glass to search through the CAN on my  Clio Mk 4 2016 1.2 16v  it found a cluster of  Cluster X98_X87_X82_XHA_X98PH2_X87PH2_XHAPH2  **V7.8**

Now in this update it finds it as :
X98_X87_X82_XHA_X98PH2_X87PH2_XHAPH2  **V8.02**

whats more - if manually setting Clio IV as the vehicle there is no X98_X87_X82_XHA_X98PH2_X87PH2_XHAPH2  V7.8   - just  V8.02 or V2.4

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
