### ISSUE TITLE
Ecu.zip is not indexed.

### ISSUE THREAD

**Issue by fsulun** [cedricp/ddt4all#246]
I've installed ecu Tweaker v1.6.  You have an activation code.  However, the program closes before opening ecu.zip file.  My phone Samsung Galaxy J7 Pro Android 9. Please help.

**Comment by mclaudiopt** [comment]
some here

**Comment by cedricp** [comment]
The "ecu.zip" (case sensitive char) must be generated with DDT4All (pc version) in the file menu -> compress database. It uses a faster database for embedded devices.
You cannot just compress database then name it ecu.zip

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
