### ISSUE TITLE
does 'tail' mean rear lights?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#248]
all along I have been reading 'tail' settings in the lighting ecu section as being rear lights (as in tail lights) ... but I am thinking now , could tail mean the wire and not mean rear lights at all?

![pwm tail](https://user-images.githubusercontent.com/49172217/64496121-9d283d00-d299-11e9-94a3-89f64401ea91.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
