### ISSUE TITLE
DDT4ALL - New full installer request

### ISSUE THREAD

**Issue by bovirus** [cedricp/ddt4all#249]
@cedricp 

Could you please update the full installer (with all files and ECU)?

the latest build is dated November 2018 (quite 1 year ago).

Could you please also make a multi-language installer (I can help about it)?

The file in this post

https://www.drive2.ru/b/498093336985338243/

are not available anymore.
Do you know as we can contact Russian author?

Thanks.

**Comment by cedricp** [comment]
I'll try to generate a new installer with updates ASAP, but I cannot inclue DB files because they are copyrighted.
You wanna contact Zmiterm ?

**Comment by bovirus** [comment]
@cedricp 

Yes. If it possible I want to contact Zmiterm.

**Comment by AndyIreland** [comment]
> @cedricp
> 
> Could you please update the full installer (with all files and ECU)?
> 
> the latest build is dated November 2018 (quite 1 year ago).
> 
> Could you please also make a multi-language installer (I can help about it)?
> 
> The file in this post
> 
> https://www.drive2.ru/b/498093336985338243/
> 
> are not available anymore.
> Do you know as we can contact Russian author?
> 
> Thanks.

mine is pretty up to date version of 5.5.0 and ECU DB version of  9/7/2019 

[https://cloud.mail.ru/public/4mtR/2PLQ7JcmG](url)

**Comment by bovirus** [comment]
@AndyIreland 

The second link point to github.

How can contact the author (Zmiterm) of 

https://www.drive2.ru/b/498093336985338243/

I want to make the installer multilanguage..

**Comment by KarelSvo** [comment]
> How can contact the author (Zmiterm)

In the profile click on the button Cообщение.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
