### ISSUE TITLE
Follow me home working perfectly but I do not get a message in the cluster

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#251]
I have follow me home working perfectly, I pull the beam switch when I turn off engine and the front lights come on and then go off after a while, but when I pull the beam stalk I get no feedback whatsover from the Cluster info window (ie no “Follow-me home for _ _ _” ) in the display and I am wondering why?
Do i have to adjust something in TDB cluster in DDT4all to make the message show up and if I do , what setting am I looking at please?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
