### ISSUE TITLE
DDT4ALL freezes

### ISSUE THREAD

**Issue by mfarramadan** [cedricp/ddt4all#252]
Hello,

I got a USB elm327 and I am connected to it by DDT4ALL. Each time I choose the ECU and then go to the screens part and choose something it hangs and stays like this for more than 15 mins and then it gets no data out of the car.

I am using it on a MEGAN4.
[elm_ddt.txt](https://github.com/cedricp/ddt4all/files/3602701/elm_ddt.txt)

I tried to benchmark my adapter but it is not working.
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Trying to open portCOM3 @ 38400
Checking port speed: 38400
Start COM speed : 38400
Traceback (most recent call last):
  File ".\ddt4all.py", line 1201, in check_elm
    res = elm.elm_checker(port, speed, self.logview, core.QCoreApplication)
  File "C:\Program Files (x86)\ddt4all\elm.py", line 1333, in elm_checker
    print cm[2] + " " + res.strip()
  File "C:\Program Files (x86)\ddt4all\Python27\lib\codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 47: ordinal not in range(128)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

**Comment by KarelSvo** [comment]
<[1.009]ATZ
ü


ü = UnicodeDecodeError: 'ascii' 
a Scrap Elm

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 and you ??? freeze also ?
