### ISSUE TITLE
Can we lock the doors till the car is running?

### ISSUE THREAD

**Issue by vafko** [cedricp/ddt4all#253]
Hello, can we make this with keyless card on Fluence to lock the doors, when the engine is working? It will be very useful in the hot summer days. I have other car (not Renault) that this is working just fine.

Thank you!

**Comment by thodorisgo** [comment]
Rlink has built in option to lock the doors when you reach 20km. I think thats the only option. But what closing doors has to do with hot summer anyways ?

**Comment by mnigten** [comment]
I think to put airco on 10 minutes before leaving 😉
Same wish here

**Comment by AndyIreland** [comment]
can RES (remote engine start) be configured with the  Fluence and DDT4ALL? - then you could maybe put AC on and start up the engine remotely with keycard without opening doors?

**Comment by kenanyildiz55** [comment]
@AndyIreland Yes, it can be operated remotely. Using DDT4all. However, I do not know how. I'm throwing a video link.

https://www.youtube.com/watch?v=LPq0YwMq8B0

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by MiqdadAli2002** [comment]
> @AndyIreland Yes, it can be operated remotely. Using DDT4all. However, I do not know how. I'm throwing a video link.
> 
> https://www.youtube.com/watch?v=LPq0YwMq8B0

This video is private
Could you help me with programming or another video
