### ISSUE TITLE
No module named PyQt4.QtGui on MacOS

### ISSUE THREAD

**Issue by shrlnm** [cedricp/ddt4all#254]
Sometimes on macOS, it is impossible to start ddt4all.py. It stops with the message

Traceback (most recent call last):
File "/Applications/ddt4all-master/ddt4all.py", line 24, in 
import PyQt4.QtGui as gui
ImportError: No module named PyQt4.QtGui

Probably the problem in the python installed by brew.

If the pyqt4 is installed properly then for running ddt4all we have to change the shebang

from
#!/usr/bin/python
to
#!/usr/bin/env python

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 pyqt5 work good in last commits
