### ISSUE TITLE
config generale 3 in TDB cluster clio 4

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#256]
I have just looked in demo of DDT4ALL and see a config generale 3 section in TDB cluster . I had only seen config generale 1 & 2 before. its the first time I have seen this 3rd page. 

It says about 'water temp'  in the ADAC , does this mean if its enabled will the water temperature of the engine coolant wil be displayed on the satnav screen or scrolling through the info window on the speedo cluster? 

[https://www.pcrepairs.x10host.com/water_temp.jpg](url)

![water temp](https://user-images.githubusercontent.com/49172217/64998717-27e1eb00-d8dd-11e9-905c-0ef4ca4d86c8.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by AndyIreland** [comment]
> you managed to Activate coolant temperature on dash ?

no , it didnt do anything for me when i enabled it

**Comment by AndyIreland** [comment]
> I can't see ddt4all cluster tdb to change from mpg to L in my Megane IV. Any helps

This , if this is your correct found ecu?:

<img width="1266" height="468" alt="Image" src="https://github.com/user-attachments/assets/385e80a4-5eaf-4723-ba15-268e9c090abc" />
