### ISSUE TITLE
ddt4all wrong response

### ISSUE THREAD

**Issue by sunghoryu** [cedricp/ddt4all#257]
hi 
i try ddt4all at my fluence(2013)

elm327 v1.5 BT
connect COM4, 38400bps

but ddt4all show this message
: Bad ELM response : WRONG RESPONSE CFC0 Unknown
![image](https://user-images.githubusercontent.com/55446770/65047396-5cb57700-d99d-11e9-8b32-8bdd7f1d50b6.png)

and can't read data
it show NO DATA

ddt4all log is
############################################################
#connect to: BCM95_SW10_V10_6 Addr:26
############################################################
>[20:57:01.180]AT SH 745
<[0.016]AT SH 745
OK

>
>[20:57:01.196]AT CRA 765
<[0.015]AT CRA 765
OK

>
>[20:57:01.211]AT FC SH 745
<[0.016]AT FC SH 745
OK

>
>[20:57:01.227]AT FC SD 30 00 00
<[0.016]AT FC SD 30 00 00
OK

>
>[20:57:01.243]AT FC SM 1
<[0.031]AT FC SM 1
OK

>
>[20:57:01.274]AT SP 6
<[0.031]AT SP 6
OK

>
>[20:57:01.305]0210C0
<[0.063]0210C0
7F0211

>
>[20:57:01.368]at cfc0
<[0.015]at cfc0
OK

>
>[20:57:01.383]0210C01
<[0.078]0210C01
7F0211

>
#[20:57:07.508]KeepAlive
>[20:57:07.508]0210C01
<[0.101]0210C01
7F0211

>
>[20:57:07.609]023E011
<[0.062]023E011
7F0211

>
>[20:57:08.296]023E011
<[0.078]023E011
7F0211

>
>[20:57:09.812]023E011
<[0.062]023E011
7F0211

and click scan button at ddt4all, stop at 17%
help me please. thank you.

**Comment by KarelSvo** [comment]
What is the result of the Elm test?

**Comment by shrlnm** [comment]
<[0.062]023E011
7F0211

It means that you have wrong ELM. It don't support "AT CAF 0" mode

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
