### ISSUE TITLE
Megane IV - Update Error 

### ISSUE THREAD

**Issue by comaly** [cedricp/ddt4all#258]
Please help me.
Can't update or downgrade R-link.
I get the error in the picture in r-link all versions.

![Image of r-link](https://i.ibb.co/Bjh6Dc8/6a41c772-34bd-4b76-9772-e0ab50210dfa.jpg)

My Car: Megane 4 HB EDC DCI 2017

**Comment by shrlnm** [comment]
You'd better ask here https://www.msieurlolo.fr/forum/index.php?board=678.0

**Comment by comaly** [comment]
> You'd better ask here https://www.msieurlolo.fr/forum/index.php?board=678.0

"Le sujet ou la section que vous recherchez à l'air d'être manquant ou inaccessible pour vous."

I'm a member but the page you specified doesn't open.

**Comment by jaflo89** [comment]
> Please help me.
> Can't update or downgrade R-link.
> I get the error in the picture in r-link all versions.
> 
> ![Image of r-link](https://camo.githubusercontent.com/38736ff34270f544f06496282f78a01690a33627/68747470733a2f2f692e6962622e636f2f426a68364463382f36613431633737322d333462642d346237362d393737322d6530616235303231306466612e6a7067)
> 
> My Car: Megane 4 HB EDC DCI 2017

Hello! How was it solved? THx

**Comment by Tony2764** [comment]
Bonjour, 

Avez vous résolu le problème ?
Cordialement

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
