### ISSUE TITLE
2014 Model Dacia dokker Left Turn Signal Lamp Off. 

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#260]
How can I turn off and turn on the dacia dokker signal lamps 2014?
Closed from ECU
I want to turn on again with the short signal 
left signal closed ddt4all

![2019-09-21_20-46-49](https://user-images.githubusercontent.com/43322396/65377162-4a934b80-dcb1-11e9-8831-033f5476ce71.png)

**Comment by BarektE** [comment]
those who wrote on this page. they're all empty people. no benefits no.

**Comment by BarektE** [comment]
bu sayfanın yararlı olduğunu düşünmüyorum

**Comment by canibeyazmehmetali** [comment]
Merhabalar 
Ben bir konu hakkındaki düşüncelerini öğrenmek istiyorum.
Clio 4 2019 aracımın radio yanlışlıkla sildim ve şuna açılmıyor.
Bu konuda yardımcı olabilir misiniz lütfen

**Comment by KarelSvo** [comment]
> How can I turn off and turn on the dacia dokker signal lamps 2014?
> Closed from ECU
> I want to turn on again with the short signal
> left signal closed ddt4all
> 
> ![2019-09-21_20-46-49](https://user-images.githubusercontent.com/43322396/65377162-4a934b80-dcb1-11e9-8831-033f5476ce71.png)

You cannot own a Dokker 2  ;-)
