### ISSUE TITLE
is there anyone to help. 2011 Megane 3 Tomtom 

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#264]
renault megane tomtom ride. system unconfigured error. How to fix it with ddt4all. because it broke with him.
![e691d370-f23d-4130-b84b-b3cbc58ea332](https://user-images.githubusercontent.com/43322396/65681574-d6b2c380-e061-11e9-8894-be081fabd1a0.jpg)

**Comment by BarektE** [comment]
![bbdf76ae-8c2e-4504-90c2-1d78e81bede4](https://user-images.githubusercontent.com/43322396/65691475-9101f500-e079-11e9-9cf8-e46eea2fa8f6.jpg)

**Comment by cedricp** [comment]
Would be nice to explain what you did.

**Comment by BarektE** [comment]
> Ne yaptığını açıklamak güzel olurdu.

![megan 3 kamera orjinal yedek](https://user-images.githubusercontent.com/43322396/65704627-8eaa9580-e08f-11e9-8802-6cde7760c44b.PNG)

**Comment by BarektE** [comment]
**### **These are the error codes. Is there any help****

DTCStatus.pendingDTC : [00] No
DTCStatus.testFailedSinceLastClear : [01] Yes
DTCDeviceAndFailureTypeOBD : 37697 [0x9341]
DTCFailureType.ManufacturerOrSupplier : 5 [0x5]
DTCFailureType.Category : [05] System Programming Failures
DTCFailureType : [55] not configured
DTCStatus.testNotCompletedSinceLastClear : [00] No
DTCStatus.testNotCompletedThisMonitoringCycle : [00] No
DTCStatusAvailabilityMask : 57 [0x39]
DTCStatus.warningIndicatorRequested : [00] No
DTCStatus.confirmedDTC : [01] Yes
StatusOfDTC : 41 [0x29]
DTCStatus.testFailedThisMonitoringCycle : [00] No
DTCStatus.testFailed : [01] Yes
DTCDeviceIdentifier : [9341] Data

DTC #1
DTCStatus.pendingDTC : [00] No
DTCStatus.testFailedSinceLastClear : [00] No
DTCDeviceAndFailureTypeOBD : 37689 [0x9339]
DTCFailureType.ManufacturerOrSupplier : 3 [0x3]
DTCFailureType.Category : [01] General Electrical Failures
DTCFailureType : [13] circuit open
DTCStatus.testNotCompletedSinceLastClear : [01] Yes
DTCStatus.testNotCompletedThisMonitoringCycle : [00] No
DTCStatusAvailabilityMask : 41 [0x29]
DTCStatus.warningIndicatorRequested : [00] No
DTCStatus.confirmedDTC : [00] No
StatusOfDTC : 16 [0x10]
DTCStatus.testFailedThisMonitoringCycle : [00] No
DTCStatus.testFailed : [00] No
DTCDeviceIdentifier : [9339] CVBS In Line

![megan arıza](https://user-images.githubusercontent.com/43322396/65812587-c4f02e00-e1d1-11e9-9e9c-85d4d99f835c.PNG)

**Comment by shrlnm** [comment]
I may try to help but I need the dump made in pyren/mod_dd

**Comment by BarektE** [comment]
> 

I really need a lot of help. I would be grateful

**Comment by shrlnm** [comment]
I am waiting the dump from you

**Comment by BarektE** [comment]
> Senden bekliyorum bekliyorum

I did not understand what you're saying

**Comment by shrlnm** [comment]
There is other program named pyren
https://gitlab.com/py_ren/pyren
I may try to help you but I need that you get the dump file from r-link module  by pyren program and send it to me.

**Comment by BarektE** [comment]
I have a pyren program

**Comment by BarektE** [comment]
> Pyren
> https://gitlab.com/py_ren/pyren adında başka bir program var.
> Size yardım etmeye çalışabilirim ama drenaj dosyasını r-link modülünden pyren programı ile alıp bana göndermeniz gerekiyor.

I put a new format on my computer.
All programs will be reinstalled.

Let me reload the Pyren

**Comment by shrlnm** [comment]
Make a dump with pyren/mod_ddt and send it me

**Comment by BarektE** [comment]
ok

**Comment by BarektE** [comment]
> Pyren / mod_ddt ile bir döküm yap ve bana gönder

how do I get the dump from pyren. I do not know that

**Comment by BarektE** [comment]
> Make a dump with pyren/mod_ddt and send it me

mine is not r-link but carminat

**Comment by BarektE** [comment]
remote connection program. (teamviewer).
I have pyren pc 184 and
android tablet pyren 2.1 board

**Comment by shrlnm** [comment]
Ok give me your e-mail

**Comment by BarektE** [comment]
> Tamam e-postanı ver

mete.erim@hotmail.com

**Comment by Burkatronic** [comment]
Sorry to jump in on this!
Did the problem get resolved?
I've been trying ty fix it for months :/
