### ISSUE TITLE
Python2.x is not supported by brew anymore

### ISSUE THREAD

**Issue by makayk** [cedricp/ddt4all#267]
The latest version of brew (platform: Mac) is not supporting python2 so  DDT4ALL is not running. The homebrew-core team removed Python2 support. 

Related ticket:
https://github.com/Homebrew/homebrew-core/pull/43602

**Comment by makayk** [comment]
Additional information from clean installed MacOS+ Brew



bash-3.2$ python -V
Python 2.7.16
bash-3.2$ python3.7 -V
Python 3.7.4



bash-3.2$ python ./ddt4all-master/ddt4all.py 
Traceback (most recent call last):
  File "./ddt4all-master/ddt4all.py", line 24, in <module>
    import PyQt4.QtGui as gui
ImportError: No module named sip



bash-3.2$ python3.7 ./ddt4all-master/ddt4all.py 
  File "./ddt4all-master/ddt4all.py", line 258
    print name, group
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(name, group)?
bash-3.2$

**Comment by kostyukdv** [comment]
Any chance to run ddt4all by python3?

**Comment by makayk** [comment]
Here is the solution: https://github.com/cedricp/ddt4all/issues/320#issuecomment-680182687
