### ISSUE TITLE
DDT4ALL / Python 3 branch

### ISSUE THREAD

**Issue by makayk** [cedricp/ddt4all#268]
On Mac/brew if I start the app with python3.7 then I receive the following error message:

bash-3.2$ python3.7 ./ddt4all.py 
Traceback (most recent call last):
  File "./ddt4all.py", line 35, in <module>
    import parameters, ecu
  File "/====REMOVEDPATH=====/parameters.py", line 1080
    for key, value in reversed(sorted(labeldict.iteritems(), key=lambda (k,v): (v,k))):
                                                                        ^
SyntaxError: invalid syntax

**Comment by cedricp** [comment]
I pushed fixes for that issue, and also graphics loading BTW

**Comment by Virallata** [comment]
Now i got this:

  File "ddt4all.py", line 258
    print name, group
             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(name, group)?

**Comment by fritzmerwyn** [comment]
> Now i got this:
> 
> File "ddt4all.py", line 258
> print name, group
> ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(name, group)?

Same for me. I tried to execute ddt4all.py with python and get the same error. I could change the source code to print(...) but that takes like forever. Any help?

**Comment by makayk** [comment]
Here is the solution: https://github.com/cedricp/ddt4all/issues/320#issuecomment-680182687
