### ISSUE TITLE
cedricp bey Ecu Tweaker error. who else will know if the author of the program is unknown?

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#269]
cedricp bey son sürümü yükledim Ecu Tweaker durduruldu hatası alıyorum. önceki sürümleri de yüklüyorum yine aynı
![ae2e1248-acb0-42cb-b71f-b0d8f4401275](https://user-images.githubusercontent.com/43322396/66140314-94155c00-e60a-11e9-8b80-070d615c61d9.jpg)

**Comment by BarektE** [comment]
who else will know if the author of the program is unknown?

**Comment by cedricp** [comment]
Your ecu.zip must be generated with DDT4All PC version
File menu ->Zip database

**Comment by BarektE** [comment]
does not open error and closes. I've already been using

**Comment by BarektE** [comment]
This error occurred when you installed the latest version ecu.zip installed

**Comment by BarektE** [comment]
telefonu ingilizceye çeviriyorum yine düzelmiyor. daha önce ingilizce yapınca düzeliyordu
