### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tameratf** [cedricp/ddt4all#27]
hello ....
I need to ask you about adaptor ELM 327 .....
my adaptor ELM 327 usb (Prolific usb-to-Serial Comm Port)

my log ....
[elm_ddt.zip](https://github.com/cedricp/ddt4all/files/1596125/elm_ddt.zip)

screenshot ....
![ddt](https://user-images.githubusercontent.com/31937960/34468503-f133c00c-ef12-11e7-89d7-93ccb505cb1b.PNG)

I need to know if my adaptor is supported to work with ddt4all or no ; And if not supported i need 
to know where i buy adaptor ELM 327 bluetooth or link to buy from amazon site .

**Comment by cedricp** [comment]
Hi, you need an ELM with a genuine PIC18f25K80 chip. I unfortunately not have a link to provide.
Your adapter is not supported by DDT4All
