### ISSUE TITLE
Reversing camera guidelines Megane stationcar

### ISSUE THREAD

**Issue by martin-rene-c** [cedricp/ddt4all#272]
Do anyone know what settings my camera should be on my guidelines is Way to small and i dont know what crop should stay on

If someone could check yours megane stationcar it would be great
![AA22C438-9D74-4EA1-AC6E-F29342E55624](https://user-images.githubusercontent.com/55898023/66201959-e1460c00-e6a4-11e9-981d-93f625c7bf95.jpeg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
