### ISSUE TITLE
is there any way we can get to change these read only values with DDT4ALL?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#273]
hello - is there any way we can get to change these read only values with DDT4ALL? they seem to be read only , they appear in 'calibration' but in 'configuration' the parameters do not show up allowing to be changed.  Thank you,

![read only](https://user-images.githubusercontent.com/49172217/66312071-d343f580-e907-11e9-80d4-da9bff2a2110.jpg)

![wac calibration](https://user-images.githubusercontent.com/49172217/66312252-3766b980-e908-11e9-9c11-a695c235ef70.jpg)

**Comment by tomidix** [comment]
bump 
@cedricp I saw that you have mentioned to someone under #99 to restore calibration set of settings (Read_Window_Control_Calibration_Data) which are read only basically. Is there a way to change those settings or was it the configuration screen?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
