### ISSUE TITLE
Clio IV Exterior mirror. Closure with ddt4al

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#275]
Clio IV The exterior mirror closes from the inside. It doesn't close when you lock the door with the key. Anyone know I couldn't find a section on mirrors in ddt4all?

**Comment by AndyIreland** [comment]
hi , it should be under UPC-EMM  - EMM Autofolding config nbx_autofolding_cf - set from '0' to '1'
![autofolding mirrors](https://user-images.githubusercontent.com/49172217/67152912-0064b080-f2d7-11e9-8636-8d8163718ad0.jpg)

**Comment by BarektE** [comment]
AndyIreland  Teşekkür ederim

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
