### ISSUE TITLE
How do you reset / undo any changes?

### ISSUE THREAD

**Issue by pwalker1992** [cedricp/ddt4all#278]
How do you reset / undo any changes?
I will pay £50 paypal if you can walk me through it?
I have made changes in DDT4ALL on my Dacia Sandero Stepway and I want to change them back to factory settings.
Thank you!
Philip

**Comment by cedricp** [comment]
It may be possible to recover if you share your log files. Look at the file
screen.log, you it's a human readable format file.

**Comment by pwalker1992** [comment]
Thank you for your reply.
I have since reinstalled ddt4all so have lost the log files. Is there any way of resetting the ecu? Maybe by restoring from a working file?

**Comment by AndyIreland** [comment]
I havent got a Dacia. but i would imagine if some kind soul had the same ecu and version in theirs as yours but untouched they could screen grab their settings and email it to you and then you could put it back to how it was?

**Comment by pwalker1992** [comment]
That would be great if someone would do that.
I noticed that in the plugins section, there was a "megane uch reset". Do you know if there is one for dacia? Would this work?

**Comment by AndyIreland** [comment]
As cedric said, you dont want to do that because it would erase all settings

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
