### ISSUE TITLE
UCH reset / ECU reset

### ISSUE THREAD

**Issue by pwalker1992** [cedricp/ddt4all#279]
I noticed in the DDT4ALL plugins tab, there is a "megane UCH reset". Is there a dacia reset?

Would this set everything to factory settings?

**Comment by cedricp** [comment]
No, and you don't want to reset it ! Reset means clear all data (make it virgin to unlock keys associations)

**Comment by Rcarnero73** [comment]
how to reset a rlink with the anti theft active?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
