### ISSUE TITLE
Power Assisted Steering

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#282]
has anyone tried changing parameters for the power assisted steering in the PAS ecu and what is the difference between Normal Default and City mode (am presuming city mode makes steering lighter?) 

Thanks.

![pas](https://user-images.githubusercontent.com/49172217/67250194-62055600-f462-11e9-9275-41db9551e15a.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
