### ISSUE TITLE
DeveloperSide Display black megane 4

### ISSUE THREAD

**Issue by danieana** [cedricp/ddt4all#283]
Hello

First of all I wanted to thank you if you could help me.

I am new to this area, and unintentionally on mode developer side I uploaded it on the hight button

I've been looking for something like what happened to other users and did as in case # 110

but I can't change it. always give the same mistake.

attached I send the logs and screens.

need help?? thanks

[screens.txt](https://github.com/cedricp/ddt4all/files/3757296/screens.txt)
[ecu_ddt.txt](https://github.com/cedricp/ddt4all/files/3757305/ecu_ddt.txt)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
