### ISSUE TITLE
what does CSW Failure display stand for ?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#285]
in the lighting section on a clio IV there is a parameter for Nbx_CSW_failure_display_CF .. what does this do / what does CSW stand for - thanks. 

![csw](https://user-images.githubusercontent.com/49172217/67639394-1da50a80-f8e7-11e9-8c87-04dab22b1250.jpg)

**Comment by Icereturns** [comment]
I'm not sure, but that live doesn't mean it's failed. I think it means it will wait 1 minute before displaying it has failed.

**Comment by AndyIreland** [comment]
if I hover over the box I get this:

![ALS](https://user-images.githubusercontent.com/49172217/68816869-bd002680-0677-11ea-9201-8bc8c2ecd47e.jpg)


now I wonder what ALS stands for then?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
