### ISSUE TITLE
Problem with modus quickshift transmission 

### ISSUE THREAD

**Issue by Drago6884** [cedricp/ddt4all#286]
Hi. I have a renault modus with quickshift, bud transmission not working, pyren show me  rsp: :22:NR:Conditions Not Correct Or Request Sequence Error. I need help please.

**Comment by shrlnm** [comment]
> I have a renault modus with quickshift, bud transmission not working

Could you please provide more details. What are you going to change? Which ECU? May be screenshots?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
