### ISSUE TITLE
Change of R-Link Screen from 7'' to 8'7'' ... Procedure?

### ISSUE THREAD

**Issue by MichaelDK2300** [cedricp/ddt4all#287]
Hi,

Can anyone help me?

I have bougt a 8,7' Screen for my R-Link 2 (Talisman).

What settings do I need to change via Developer Mode and/or DDT4ALL.

If I need to tell you software information or hardware information...just let me know.

Many Thanks for your help,
Have a nice weekend,

Best Regards,
Michael / Denmark

**Comment by shrlnm** [comment]
Hi
Just apply one of this macro (HIGH1 or HIGH2) with pyren
https://gitlab.com/py_ren/pyren/tree/master/pyren/macro/rlink2

**Comment by MichaelDK2300** [comment]
> Hi
> Just apply one of this macro (HIGH1 or HIGH2) with pyren
> https://gitlab.com/py_ren/pyren/tree/master/pyren/macro/rlink2

So basically swap the two screens in my car, and apply either of those two?

Nothing else I need to do before? Software versions on R-Link 2 it wont work with?etc?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
