### ISSUE TITLE
Megane IV Luggage Compartment Light

### ISSUE THREAD

**Issue by aoshty** [cedricp/ddt4all#289]
In the Stock config the Megane IV cannot turn on the luggage compartment/boot light on the interior without having the cabin lights come on automatically. Is there a fix using ddt4all?

Thanks!

**Comment by BarektE** [comment]
Bagaj lambası iç ışıklara dahil değil, Bagaj ışığını ddt4all devre dışı yapabilirsiniz, iç ışıklar yanar.
Özelden yazarsanız tarif edebilirim. mete.erim@hotmail.com

**Comment by aoshty** [comment]
Hi Mete, I'm actually looking to do the opposite. I want the boot light to work and the interior lights to be off. Similar to other brands of car

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
