### ISSUE TITLE
DUSTER HJD AUTO LIGHTS

### ISSUE THREAD

**Issue by lisandru06** [cedricp/ddt4all#290]
Hello,
I have the Dacia Duster from 2018 with AUTO indicator on the handle and the light sensor in the dashboard. From begining the auto it works good but by mistake I deactivated from DDT4ALL.

I modified in the **UPC-EMM> T4 EMM VS v2.3> [UPC-EMM] T4 EMM VS v2.3> EXTERNAL LIGHTNING ALS>EXTERNAL LIGHTNING ALS - CONFIGURATIONS** on NBX_AUTO_LIGHT with deactivated. in the past it was a number 98 if I'm not wrong :( and after this the conection is not working anymore. I couldn't put it back to work automatically the lights. Can you send me please a solution for making again working?

Thanks in advance and You are the best in the cars software!

![image](https://user-images.githubusercontent.com/51473055/68550131-ba4bca00-0408-11ea-9287-a5c85bb64d72.png)

**Comment by BarektE** [comment]
![1](https://user-images.githubusercontent.com/43322396/68583607-a185f780-048e-11ea-9a73-f21a51da43f3.png)

**Comment by lisandru06** [comment]
I've tested again today and i compare with an original software.. the 2 settings are where i upload the picture but i cannot read and modify like reference due to out of range..
![20191113_183657](https://user-images.githubusercontent.com/51473055/68792236-9f20ca80-0653-11ea-816f-ff0e3de793cb.jpg)
![20191113_173114](https://user-images.githubusercontent.com/51473055/68792237-9f20ca80-0653-11ea-89ef-17ed5b57bc93.jpg)

**Comment by lisandru06** [comment]
![20191113_180944](https://user-images.githubusercontent.com/51473055/68792481-15253180-0654-11ea-9dc8-d5d7ce971995.jpg)

**Comment by KOPRajs** [comment]
Hi, I've just uploaded the complete default settings of this screen for my Dacia Duster 2020 here:
https://github.com/cedricp/ddt4all/issues/609

Do you remember which settings have you changed? What were you trying to accomplish?

I'm going to try to adjust the auto light sensor sensitivity so I hope not to break it as well.

**Comment by KOPRajs** [comment]
P.S. You might want to look at the following screen, maybe you can set the Nbx_Auto_Light_CF from there:
![RLSSEMMInterface_01](https://user-images.githubusercontent.com/13847813/131214774-633cd269-d3cf-40f4-8a50-230f9b416e58.png)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
