### ISSUE TITLE
Vehicle recognition CF setting 

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#294]
hello - does anyone know what the vehicle recognition  setting is in UPC EMM wiping & washing configuration . 

To me , the only thing I can think of with vehicle recognition is that automatic number plate recognition (ANR) - but if it is, why on earth is it in the wiping and washing section?

![vehicle_recognition](https://user-images.githubusercontent.com/49172217/68810011-127f0800-0665-11ea-99fe-df93c0b6eaa1.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
