### ISSUE TITLE
Auto Window Closing not working on Clio IV ph2

### ISSUE THREAD

**Issue by tergin76** [cedricp/ddt4all#298]
Hi;

Thanks for your hardwork and appreciated.
I have Clio 4 ph2, which is manufactured 06/2019. I enabled the setting under:
T4_VS_BCM_DDT2000_SW16_5->Windows Lift->AUTO_WINDOW_CLOSING false to **true**. But even I try to double or triple press lock button on key card, opened front and rear windows are not closing.  Doors are locking and side mirrors closing but not any windows. 
Do I have to change any other settings under anywhere on another menu? 

![6A311489-5A00-4FED-9D1D-68C27684D3BA](https://user-images.githubusercontent.com/58117231/69483135-967e8000-0e1b-11ea-9db4-1ea7497d433f.jpeg)

Any idea?

Thanks

**Comment by tergin76** [comment]
As I research, there should be an external module for "Auto Window Closing" feature installed seperatly for this option to work. Like "Enable Rear Parking Camera" option. If there is no camera, what will it be to enable. So, please corret me, if I'm wrong.

**Comment by tergin76** [comment]
That is what I mean;

WINSGO Auto Car Power Window Closer Automatically for Renault Koleos 2016+/Kadjar/Subaru XV 2
[https://www.aliexpress.com/item/32871739910.html](url)

**Comment by michalzahor** [comment]
I believe not, this product just get the signal that you lock the car and auto close windows. The T4_VS_BCM_DDT2000_SW16_5->Windows Lift->AUTO_WINDOW_CLOSING should set this behaviour in existing ECU in the car. For me, in Koleos 2018, it is also not working.

**Comment by m0xz0r** [comment]
From what I've read somewhere, the AUTO_WINDOW_CLOSING parameter only works when an official Renault alarm system (e.g. part# 8201656123) has been installed.

**Comment by michalzahor** [comment]
I have original Renault alarm (don't know part number) - but auto windows closing not working

Michal Zahor
mzahor@dtech.sk

**Comment by Doowayp** [comment]
D'après des informations que j'ai pu lire sur des forums, il faut avoir les boutons électrique à l'avant et à l'arrière avec les 2 crans.
Corrigez moi si c'est faux..
Mais j'ai activer cette option, mais cela ne fonctionne pas non plus pour moi.. déçu.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
