### ISSUE TITLE
Ecu-tweaker 1.81 crash

### ISSUE THREAD

**Issue by severusnt** [cedricp/ddt4all#299]
crashed under Android 9.0 immediately after aplication start

**Comment by severusnt** [comment]
From CatLog
11-24 21:40:02.240 W/m       (27561): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

**Comment by tyronecarrion** [comment]
Same here, but in my case it crashes only when selecting USB

**Comment by cedricp** [comment]
@severusnt Could you catlog with this debug version : 
https://drive.google.com/open?id=1x2J8-ckAoPugw3Q01-rcaigZ7eQdHZTz

**Comment by tyronecarrion** [comment]
Ok, Will do

Atenciosamente,
Tyrone Carrion

> Em 29 de jan de 2020, à(s) 18:02, Cedric PAILLE <notifications@github.com> escreveu:
> 

﻿
@severusnt Could you catlog with this debug version :
https://drive.google.com/open?id=1x2J8-ckAoPugw3Q01-rcaigZ7eQdHZTz

**Comment by trplsn** [comment]
@cedricp ciao ho installato app ECU-Tweaker su telefono android, riesco a collegarmi a ODB2 wifi e riesco a leggere tutti parametri ma non riesco a modificarli perché mi dice ERROR NO DATA. Sai dirmi il perché? Grazie

**Comment by AndyIreland** [comment]
> hello I have installed ECU-Tweaker app on android phone, I can connect to ODB2 wifi and I can read all parameters but I can't modify them because it tells me ERROR NO DATA. Can you tell me why? Thank you

what car have you got and what year?, it may have a gateway fitted to the CAN system whereby you can read parameters but to modify parameters you have to buy a token to unlock the gateway

**Comment by trplsn** [comment]
Ho una Renault Scenic IV del 2017, ho fatto il cambio del display con
quello da 8,7 pollici ma non riesco a modificare i parametri

Il sab 13 ago 2022, 14:55 Andy Robus ***@***.***> ha scritto:

**Comment by trplsn** [comment]
Come posso acquistare questo token? Mi potete aiutare per favore?

**Comment by AndyIreland** [comment]
https://asos.renault.com/#panel3v 

if you need to unlock gateway - I think Scenic IV Ph2 is Gateway locked ... but dont take my word for it

**Comment by trplsn** [comment]
Assurdo, ci sono un sacco di tutorial che spiegano come effettuare le modifiche tramite ddt4all con Renault Scenic IV ma nessuno ha mai parlato di sbloccare il gateway. Non vorrei che fosse un problema legato al apk ECU-Tweaker.

**Comment by KarelSvo** [comment]
2017 is not phase 2 ;-) Without log data and Elm test results, your problem cannot be defined and cannot be solved

**Comment by trplsn** [comment]
Ok proverò ad inserire i dati di registro

**Comment by Sartascn** [comment]
> 

stesso problema! Mi sapreste dire come avete risolto? Grazie

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
