### ISSUE TITLE
Megane 3 option to enable folding mirrors

### ISSUE THREAD

**Issue by charliehoward** [cedricp/ddt4all#300]
I'm going to be installing folding mirrors but cannot find any options that look like folding mirrors, does anyone know where it is?

**Comment by tergin76** [comment]
Hi;

If your car has a folding/unfolding capability, it should be under **UPC-EMM** section as **Auto_Folding**.

**Comment by BarektE** [comment]
e-mail yaz özelden tarif edeyim

**Comment by charliehoward** [comment]
Email what?
I can't find any options in UPC that look like folding but I did find a "folding" option in DDCM, would that be it?

**Comment by BarektE** [comment]
UPC do not already have the man crate you write the e-mail address where the active show where we said, but did not care, many tinnnn no longer describe the e-mail göstersende.

**Comment by BarektE** [comment]
UPC does not already exist. I don't think you need it.

**Comment by charliehoward** [comment]
Email me and we can discuss?

**Comment by charliehoward** [comment]
For reference I'm using the X95 ECU

**Comment by BarektE** [comment]
Just in case you don't need it.
![ayna](https://user-images.githubusercontent.com/43322396/69803865-525df780-11ee-11ea-85f8-38f41f3c4340.JPG)

**Comment by BarektE** [comment]
connection diagram

![mirr](https://user-images.githubusercontent.com/43322396/69804230-255e1480-11ef-11ea-89ae-0f8a2523d3c2.JPG)

**Comment by charliehoward** [comment]
I've found that in DDCM, is that right? It also says ECU requires reset after EEPROM writing paramater at the bottom, would this wipe a ECU map?

**Comment by BarektE** [comment]
Sonradan takıyorsan buda lazım olacaktır

![mirr](https://user-images.githubusercontent.com/43322396/69804489-bf25c180-11ef-11ea-93b0-64d8aae74abc.JPG)

**Comment by BarektE** [comment]
hepsi birden programlanması gerekiyor tek programlar san o bölümdeki her şey iptal olacaktır. Tek denemeyin.

**Comment by charliehoward** [comment]
So I tried programming it tonight and when I scanned for ECU's it found [PDCM] Pass DCM E95 SLOT v4.0 but there is no config, there is only read.
[A photo of the issue](https://i.imgur.com/cAkZEkP.jpg)
I also tried ones it couldn't find and it did change the values but they still do not fold.

**Comment by kadirayhantr** [comment]
> UPC zaten mevcut değil. İhtiyacın olduğunu sanmıyorum.
> İhtiyacınız olursa bana posta ile yazarsınız.
> ama artık yazmaya yardımcı olmayacak.

Hi, kadirayhantr@gmail.com  is my mail adresse. Can you tell me how can I programme my  UPC ?

**Comment by kadirayhantr** [comment]
> hepsi birden programlanması gerekiyor tek programlar san o bölümdeki her şey iptal olacaktır. Tek denemeyin.

536 969 55 27 bu işlerden anlayan birine benziyorsunuz. Watsap tan görüşebilir miyiz? Teşekkürler

**Comment by johnroberts2k** [comment]
Hey @charliehoward just came across this post. I am trying to do exactly that. My Megane 3 didn't come with folding mirrors, but I've purchased a pair of folding mirrors which seem to have an extra pin for the mirror motor. The wire coming from the driversdoor multiplex computer seems to have a wire for the motor pin. I also have the button on the window switch for folding and unfolding mirror. It doesn't work, so I am thinking maybe it is turned off somewhere in the ECU. The wiring is there but the car seems to be ignoring it.

Did you get anywhere with yours?

**Comment by charliehoward** [comment]
Yeah it needs to be coded in, follow my guide here - https://rsmegane.com/threads/retrofit-folding-mirrors.17826/

**Comment by johnroberts2k** [comment]
@charliehoward awesome man that is great. you've made my day :)

**Comment by johnroberts2k** [comment]
@charliehoward just wondering at the bottom of the DCM write section, what does it mean when it says: Warning: ECU reset is needed after each EEPROM writing parameter set to be apply by the SW?

From what I can see it sends all the parameters as a single send command right? Some sections when you work on configs they let you send each parameter and save it. The DCM write seems like you set everything and then press send right?

**Comment by BarektE** [comment]
> Hey @charliehoward az önce bu yazıya rastladı. Ben de tam olarak bunu yapmaya çalışıyorum. Megane 3'ümde katlanır aynalar yoktu, ancak ayna motoru için fazladan bir pimi varmış gibi görünen bir çift katlanır ayna satın aldım. Sürücü kapısı multipleks bilgisayardan gelen telde motor pimi için bir tel var gibi görünüyor. Aynayı katlamak ve açmak için pencere anahtarında da düğme var. Çalışmıyor, bu yüzden ECU'da bir yerlerde kapatılmış olabilir diye düşünüyorum. Kablolar orada ama araba onu görmezden geliyor gibi görünüyor.
> 
> Seninkiyle bir yere vardın mı?
> 
> Teşekkürler

Merhaba e posta yaz tarif edeyim

**Comment by EmreMegane** [comment]
> e-mail yaz özelden tarif edeyim

Merhabalar benim aracımda da aynı sorun var ddt4all ile OBD II cihazını bağladım sonra aynalarımda arıza çıktı bana yardımcı olurmusunuz
