### ISSUE TITLE
Megane 3 RES ?

### ISSUE THREAD

**Issue by yildizx** [cedricp/ddt4all#301]
**Hi, how can I be active in RES for Megane 3?**

**Comment by yildizx** [comment]
help ?

**Comment by ohayyam** [comment]
https://www.youtube.com/watch?reload=9&v=LPq0YwMq8B0

**Comment by yildizx** [comment]
Yeah, but the video owner didn't tell me how. :/

**Comment by Gaspaar13** [comment]
Solved?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 is not is same...
