### ISSUE TITLE
ne yapmam lazım

### ISSUE THREAD

**Issue by bilalyoney** [cedricp/ddt4all#302]
libpng warning: iCCP: known incorrect sRGB profile
1849 loaded ECUs in database.
libpng warning: iCCP: known incorrect sRGB profile
Traceback (most recent call last):
  File "C:\Program Files\ddt4all\ddt4all.py", line 584, in zipdb
    filename = str(filename_tuple)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 16: ordinal not in range(128)

**Comment by tergin76** [comment]
Hangi versiyonu kullanıyorsunuz? drive2.ru daki indirip 5.5.0 denediniz mi?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
