### ISSUE TITLE
 ACC (adaptive cruise control)  reconfiguring the speed limits.

### ISSUE THREAD

**Issue by bostu** [cedricp/ddt4all#307]
> Maybe I was not perfectly clear. I have a car with ACC and I'm looking into reconfiguring the speedlimits.
> Finally I managed to change the ACC speedlimits, however it only works temporarily. It seems the above referenced values are overwritten by an other ECU(?).
> After an engine stop and later restart the values are restored to the default ones.
> Originally ACC low limit is 50, below it is overridden to 30:
> ![2019-08-12_145520](https://user-images.githubusercontent.com/40005947/62866848-2fc4d300-bd12-11e9-8ae0-431216a3599d.png)
> I'm still looking for some hints if any of you managed to permanently change the values.

hi gabr777,
did you have any luck with speed limits in ACC... I have espace 2016 too and also would like to set lower speed limits, like new cars have
and can you tell me where in ddt4all are these settings?
bx

_Originally posted by @bostu in https://github.com/cedricp/ddt4all/issues/126#issuecomment-568157159_

**Comment by bostu** [comment]
I have espace 2016 and I would like to set lower speed limits, like new cars have
can you tell me where in ddt4all are these settings? or if this is even possible?
thanks
bx

**Comment by tanerdogan** [comment]
I was looking same thing for normal cruise control speed limit but didnt found anything. I have Clio 4 EDC and want to use CC from start but there is also speed limit 30km/h for that too...

**Comment by bostu** [comment]
I have ACC and automatic transmision, but I would like to have it from 0 km/h to drive in trafic jams

**Comment by ouguena** [comment]
ddt4all
ACC > CMF1   Frontal_rader_v4b_0_light > Configuration_state_management_kmh 


ACCToACCOFFSpeedThresholdLow  40    =>>   20    edit
ACCOFFToACCSpeedThresholdLow  47    =>>   27    edit
MinimalSpeedRequestLow  50    =>>  30    edit

(***If it is lower than this value, bsw interference occurs.**)

and, 

ddt4all
ACC > CMF1   Frontal_rader_v4b_0_light > soft_Reset

ecu reset menu > softreset.

acc The low speed setting value does not change.

**Comment by ouguena** [comment]
ddt4all
ACC > CMF1 Frontal_rader_v4b_0_light > Configuration_state_management_kmh

ACCToACCOFFSpeedThresholdLow 40 =>> 20 edit
ACCOFFToACCSpeedThresholdLow 47 =>> 27 edit
MinimalSpeedRequestLow 50 =>> 30 edit

(*If it is lower than this value, bsw interference occurs.)

and,

ddt4all
ACC > CMF1 Frontal_rader_v4b_0_light > soft_Reset

ecu reset menu > softreset.

acc The low speed setting value does not change.
![acc세팅 저속 세팅1](https://user-images.githubusercontent.com/62410347/77130415-3f23b000-6a9b-11ea-9b81-7bd7a5f2a4f2.png)
![acc세팅 저속 세팅2](https://user-images.githubusercontent.com/62410347/77130418-4054dd00-6a9b-11ea-98b2-581ef3f2d548.png)

**Comment by bostu** [comment]
Thank you, I will try it

**Comment by bostu** [comment]
Sorry for late answer, but I do this change yesterday. Everything works fine. thank you @ouguena. 
So if I understand right, it can go lower with speed limits?
 I could try but I am scared to do something stupid and then nothing works 😁. Can I destroy something if I try to go lower with speed limits or just it wont work and I will have to go up again with speed limits?
Thank you for answers

**Comment by kasperronberg** [comment]
> Sorry for late answer, but I do this change yesterday. Everything works fine. thank you @ouguena.
> So if I understand right, it can go lower with speed limits?
> I could try but I am scared to do something stupid and then nothing works 😁. Can I destroy something if I try to go lower with speed limits or just it wont work and I will have to go up again with speed limits?
> Thank you for answers

I have tried to change the values, and it works, but after you shut off, og turn on again, it changes back to old values.

Also it seams like the auto brakes don't work with low speed, only deaccelerate, so keep a foot on the brakes when you try 😉

**Comment by Zaloznx** [comment]
Всем привет подскажите пожалуйста мужики можно ли активировать активный круиз контроль на рено сценик 4 2017года Доустановил кнопку на руль  а что дальше? кто поможет буду благодарен

**Comment by Zaloznx** [comment]
нужны параметры активащии

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
