### ISSUE TITLE
 I connect with elm327 obd wifi but I can not reach the scan program interface

### ISSUE THREAD

**Issue by mrcfen** [cedricp/ddt4all#31]
hii cedricp
my car megane 4. elm327 obd2 I can connect with wifi. program ddt4all with megane 4> Audio> RadNav v2.3 after selecting the program does not respond. 
I want to turn on the video monitoring feature of my car on the move.
Thank you for your help....

**Comment by cedricp** [comment]
As I don't own a WiFi dongle, i'm currently not able to make test with it... I'll try to borrow one to make tests ASAP.

**Comment by mrcfen** [comment]
thanks cedric ... i am waiting for your results

**Comment by cedricp** [comment]
I tested a WiFi dongle this morning, but it's a bad Chinese clone, and indeed, there are a lot of bad behaviors. I think the program is not responsible. You better get a good USB dongle for that operation.
According to issue #15, wifi connection should work.

**Comment by KarelSvo** [comment]
Problem solved?

Did you connect with Media Can or Vehicle Can?
The CLIP database says RadNav speaks on Pin 7 + 14 Vehicle Can.

**Comment by Furtif** [comment]
for help or question uses https://github.com/cedricp/ddt4all/discussions please .
