### ISSUE TITLE
Clio 4 EMM Replacement

### ISSUE THREAD

**Issue by ecutechnology** [cedricp/ddt4all#312]
Hi, could someone tell me how to change VIN in EMM using ddt4all please. I am replacing with an identical used module.

Diagnosed faulty by dealer, no main headlights when engine running.

Clio 4 2016

Thanks,

Luke

**Comment by KarelSvo** [comment]
If not integrated in the screen, go to the list to Manual request.

![top42](https://user-images.githubusercontent.com/30380693/71795132-01d78680-3045-11ea-870b-8ae8ebbc7a3d.png)

**Comment by Siqy** [comment]
Hi all,

Sorry for opening an old issue but I have a question that follows up this issue.

You only have to fill in the complete VIN number of your car in the "Value" table on the right side of the table "key" "V.I.N. in ASCII"? nothing more nothing less?

Thanks in advance!

Joël

**Comment by Siqy** [comment]
Just installed the second hand EMM out a captur 2013 with the same codes as mine Clio 2013. Works without programming! Did not program the VIN of my car, read out the VIN or the module and it is different from my car.

on the other hand, DDT4all does not make a full match of the module for programming purposes (2019 database). Should I still program my cars VIN in the module or let it be?
The question above still remains.. answer would be nice!

Thank you in advance.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
