### ISSUE TITLE
Clio IV main horn

### ISSUE THREAD

**Issue by sirbig** [cedricp/ddt4all#313]
Hi everyone,

Does anyone know how to test/read the main horn?
So far I can only find it for the Instument Panel buzzer.

I searched in every ECU I have and no luck finding this fella...
![Screenshot_1](https://user-images.githubusercontent.com/35018700/71950407-0465e780-31cf-11ea-8a23-e22445ea6a96.png)

**Comment by premultiply** [comment]
Do you mean the main horn?

**Comment by sirbig** [comment]
> Do you mean the main horn?

Yes.

**Comment by AndyIreland** [comment]
do you mean the alarm 'blip blip' sound as you walk away and car locks?

**Comment by sirbig** [comment]
> do you mean the alarm 'blip blip' sound as you walk away and car locks?

No, the main horn, the one that you use on your steering wheel when someone does something stupid on the road!
I think "main horn" is pretty clear, lol.

**Comment by AndyIreland** [comment]
ah right I get you now. Thanks for clarifying it LOL ... but no, I havent seen a setting in PyREN for testing the horn or the steering wheel button soz.

**Comment by Mikescotland** [comment]
Clio IV (same as Clio III) has horn connected directly to the wheel buttons. It doesn't go via any can line (simple electrics). Therefore you can't control / check horn via obd.

**Comment by sirbig** [comment]
> Clio IV (same as Clio III) has horn connected directly to the wheel buttons. It doesn't go via any can line (simple electrics). Therefore you can't control / check horn via obd.

My solution was adding a RF Transmitor with a remote control to activate/deactivate the horn.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
