### ISSUE TITLE
BLack screen Talisman2018

### ISSUE THREAD

**Issue by Mo7arbie** [cedricp/ddt4all#315]
i was in Developerside and i touched DisplayMode Mid by accedint and now i have black screen how can i fix this problem ? 
Note :
all function is working but i still have a black screen

**Comment by shrlnm** [comment]
https://gitlab.com/py_ren/pyren/-/wikis/how%20to%20rlink2%20black%20screen

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
