### ISSUE TITLE
Change Time the Interior Light is on?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#318]
hi . in my Clio 4 there is a setting in my BCM/UCH ECU for  INTERIOR_LIGHTS_TM_TP and it is set for 20seconds in my car. I would like to increase to 30seconds or even 60seconds if I can but in the DDT4all window it loooks like it only reads the parameter and cannot right to the ECU - is this right? , is there no way I can change the on time of my interior lights through DDT4ALL? 

![interior lighting](https://user-images.githubusercontent.com/49172217/72691381-d496d800-3b1c-11ea-9ab7-2d5a3da14f9b.jpg)

**Comment by BarektE** [comment]
![5](https://user-images.githubusercontent.com/43322396/72711173-97acfe80-3b79-11ea-85e3-328583f7f9d6.JPG)

**Comment by AndyIreland** [comment]
thanks - will give it a go cheers

**Comment by AndyIreland** [comment]
Thanks for your suggestion 
all I got was this - but its not the TM and didnt have  'seconds' after it  - so I think it was just for enabling interior light (which it already is) 
![83616585_167379414522510_5753852431003811840_n](https://user-images.githubusercontent.com/49172217/72755230-ec746780-3bc1-11ea-93b3-236583605b35.jpg)

I then got hopeful when i saw this 
![83204254_217959155880810_3379734349615202304_n](https://user-images.githubusercontent.com/49172217/72755373-378e7a80-3bc2-11ea-88c6-41756191ff8c.jpg)

because I could actually change the figure in the box from 20 to 60 ... but it was short lived because when I press 'execute' it goes back to 20 seconds. - mind you thats because its 'read only' I suppose .

**Comment by BarektE** [comment]
I will try with Megane
I will inform if it happens

**Comment by BarektE** [comment]
![image](https://user-images.githubusercontent.com/43322396/72784142-3482a100-3c39-11ea-921c-aef25af801d7.png)

**Comment by BarektE** [comment]
![image](https://user-images.githubusercontent.com/43322396/72784413-d30f0200-3c39-11ea-81b6-49056f36e13d.png)

**Comment by org07** [comment]
Hello Andy Ireland Clio 4 right headlight does not light on my car, not electrical work, how to fix it with software work ddt4all.

**Comment by AndyIreland** [comment]
hello @org07 - i would say that the software wont fix it, i would say either loose wire, or blown fuse /relay or blown bulb

**Comment by org07** [comment]
thank you

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
