### ISSUE TITLE
Which RadNav version to use?

### ISSUE THREAD

**Issue by primo42** [cedricp/ddt4all#321]
Hi,

I have a Talisman, which originally had R-Link with the version 2.2.x.x installed, but then it was upgraded to 7.0.24.166 in a Renault workshop. Which RadNav version should I use inside Audio ECU part:
- 2.X v2.5 or
- 3.X v3.3?

Thanks!

**Comment by shrlnm** [comment]
2.X v2.5

**Comment by primo42** [comment]
Thanks! Just out of curiosity, what would happen if someone would choose a wrong RadNav version and then try to change a setting? I've read in some forum that it doesn't matter whether you choose 2.5 or 3.3, but i doubt that.

**Comment by shrlnm** [comment]
2.5 is for LGU versions v2 (with small exception) v3 and v7
3.x is for LGU v8 and upper.
The difference mostly in acoustic parameters length.
