### ISSUE TITLE
Affichages tronqués

### ISSUE THREAD

**Issue by GravuTrad** [cedricp/ddt4all#323]
Bonjour Cédric.

Tout d'abord un grand merci pour cet excellent soft. Grand Travail de réalisé.

En revanche j'aimerais savoir pourquoi certains panneaux sont tronqués sur mon ordi portable.

En effet autant certains rentrent bien automatiquement, d'autres ont besoin d'agrandir ou de rétrécir (pas un problème avec ton soft), mais certains sont coupés par exemple de moitié, et impossible d'y changer quoi que ce soit.

C'est dû à quoi? solution possible?

Merci d'avance.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
