### ISSUE TITLE
Ecu-tweaker crash on start

### ISSUE THREAD

**Issue by tyronecarrion** [cedricp/ddt4all#326]
It crashes immediately after start if USB is selected.

I’m using OBDLink SX adapter on an android HeadUnit with Android 8.1, Winca S200+

**Comment by cedricp** [comment]
OBDLink is not supported actually, only ELM327. Will try to make it work ASAP

**Comment by tyronecarrion** [comment]
Ok, understood.  Please keep posted, I’m very interested.

Thanks!

Atenciosamente,
Tyrone Carrion

> Em 29 de jan de 2020, à(s) 17:48, Cedric PAILLE <notifications@github.com> escreveu:
> 

﻿
OBDLink is not supported actually, only ELM327. Will try to make it work ASAP

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
