### ISSUE TITLE
RLINK v7 to v8 upgrade (dd4all in case of failure)

### ISSUE THREAD

**Issue by michalzahor** [cedricp/ddt4all#328]
Hi all,

is it possible to use DDT4ALL in case of failed upgrade of Rlink to restore old version or some other rescue operations ?

I see that there are multiple howtos about upgrade to Rlink v8. I don't know what the upgrade can cause on Koleos II 2018 RLINK v7.x so will be nice to know if there is a way how to roll back to v7.

Also if anybody tried upgrade to v8, pls share experience.

Thank you

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
