### ISSUE TITLE
Mirror folding activation on MEGANE III Ph2

### ISSUE THREAD

**Issue by kadirayhantr** [cedricp/ddt4all#329]
Hi Everybody, 
I hope I can solve my problem with your big help.
I changed my side mirrors and driver door window switch. I activate mirror folding option on DDT4ALL.  But my mirrors didn't fold.  I couldn't succeed on activating this feature. 
My all sockets and pins are OK and same with an mirror folding featured vehicle.
https://rsmegane.com/threads/retrofit-folding-mirrors.17826/?fbclid=IwAR0fJzZwxK6_WxNs5GbtJ92Xi0ncGa5Ga4y7KOoMT2Ev-05sWMN6OIlRF9c#post-201871   this link succeed of the same project.

I can test my DDCM features with ddt4all like opening windows, moving mirror glasse etc. But when I want to test of mirror folding feature,  dd4all says, '' Bad ELM response : WRONG RESPONSE : NR: SubFunction Not Supported(7F3012) ''   as screenshot. 
![Ekran Alıntısı](https://user-images.githubusercontent.com/60252458/73652288-a1fdeb00-4697-11ea-86b8-f3b12c8e22aa.JPG)

Does any body know what I need to do ?
Does any body have an idea ?

Thanks everybody...

**Comment by BarektE** [comment]
Ayna bu bloktan katlanmıyor. Başka bir bloktan katlanıyor, e-mail verirseniz tarfini yaparım.

**Comment by kadirayhantr** [comment]
I will be pleasure. Thanks.
kadirayhantr@gmail.com

**Comment by tanerdogan** [comment]
Selamlar, ELM cihazınız çin klonu olabilir, daha kaliteli bir cihazla deneyin.

**Comment by kadirayhantr** [comment]
> Selamlar, ELM cihazınız çin klonu olabilir, daha kaliteli bir cihazla deneyin.

Selam, Yok dostum sorun modüldenmiş. Modülde aynaların katlanma motoruna giden pin çıkışları yok. Aracın Aynalarının katlanması için DDCM modülünün parça numarası 807310016R  -   807310246R  - 807310596R -  807312028R  numaralarından biri olmak zorunda.

**Comment by MouadSoufiani** [comment]
> Hi Everybody,
> I hope I can solve my problem with your big help.
> I changed my side mirrors and driver door window switch. I activate mirror folding option on DDT4ALL. But my mirrors didn't fold. I couldn't succeed on activating this feature.
> My all sockets and pins are OK and same with an mirror folding featured vehicle.
> https://rsmegane.com/threads/retrofit-folding-mirrors.17826/?fbclid=IwAR0fJzZwxK6_WxNs5GbtJ92Xi0ncGa5Ga4y7KOoMT2Ev-05sWMN6OIlRF9c#post-201871 this link succeed of the same project.
> 
> I can test my DDCM features with ddt4all like opening windows, moving mirror glasse etc. But when I want to test of mirror folding feature, dd4all says, '' Bad ELM response : WRONG RESPONSE : NR: SubFunction Not Supported(7F3012) '' as screenshot.
> ![Ekran Alıntısı](https://user-images.githubusercontent.com/60252458/73652288-a1fdeb00-4697-11ea-86b8-f3b12c8e22aa.JPG)
> 
> Does any body know what I need to do ?
> Does any body have an idea ?
> 
> Thanks everybody...

Hi mate, can you send me an email? I want to retrofit those also. I have sended you message on Facebook. Check your spam please

**Comment by EmreMegane** [comment]
Sorunu ddt4all uygulaması üzerinden nasıl çözüme ulaştırabilirim ?
