### ISSUE TITLE
Abbreviations rev.12104a

### ISSUE THREAD

**Issue by ohayyam** [cedricp/ddt4all#332]
[ALL_INFO_12104.xlsx](https://github.com/cedricp/ddt4all/files/4176807/ALL_INFO_12104.xlsx)

Enjoy

**Comment by tomidix** [comment]
Thanks, can you write the source? Where have you taken the file / translations from?

**Comment by ohayyam** [comment]
Source is İnternet, documents, forums etc. + copy + paste to excel file + rearrange etc. etc. Finally SHARE :)

**Comment by ohayyam** [comment]
Hi to ALL,

AEBS = ADVANCED EMERGENCY BRAKING SYSTEM 

But what is the difference AEBS01 (used for Talisman) and AEBS05 (used for Scenic IV). I need more details about function and how many are there AEBS 01, 02, 03, ... ??? 

Thanks in Advance

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
