### ISSUE TITLE
ELM Test not 100% working

### ISSUE THREAD

**Issue by Speederman911** [cedricp/ddt4all#338]
Hello,
Thanks for your great job.
I have an issue with the Test ELM, my result is:
Résultat: 86 réussis sur 95
Version ELM maximum:v1.4 

That's my ELM: https://www.amazon.fr/gp/product/B07BWF7MTL/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

What should I do ?

Thanks in advance,

David.

**Comment by shrlnm** [comment]
Hello
86 from 96 it is acceptable result and the adapter looks good.
Have you tried to scan ECUs in your car? 
What is the result?

**Comment by Speederman911** [comment]
All is working ok, thanks guys
