### ISSUE TITLE
R-link with the anti theft active

### ISSUE THREAD

**Issue by Rcarnero73** [cedricp/ddt4all#339]
how to reset a rlink with the anti theft active?

**Comment by pagrandukas1978** [comment]
impossible I had that problem

**Comment by marrius30** [comment]
Hi, do you have any solutions for this problem?

**Comment by rttr67** [comment]
is the solution

**Comment by Rcarnero73** [comment]
> is the solution

what is the solution ?
regards

**Comment by rttr67** [comment]
hello everything is done on the table intervention inside with the programmer


2021-03-06, št, 00:07 Rcarnero73 <notifications@github.com> rašė:

**Comment by Koleosguy321** [comment]
Yeah, sadly no solution as far as I understand.

I've heard people rewrite the VIN using the programmer but for some reason that doesn't work.

You have to virgin mode it before you take it out of the salvage vehicle.

Sucks to say, but I'd call every single dealership you can until you find one that is willing to unlock it (However, a lot of them will refuse for legal reasons). I'd try and get some kind of proof of purchase from the salvage loot to show it wasn't stolen but even though I'd say your chances are slim.

**Comment by AlMeu** [comment]
I can reset VIN and atitheft, but if I have the unit on my desk.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
