### ISSUE TITLE
Tutorial of how to modify OBD connector?

### ISSUE THREAD

**Issue by pelisdev** [cedricp/ddt4all#34]
Hello, i tried to connect with OBD WiFi and another via bluetooh and all ok, can connect to my car (Megane 3 RS) but i want to activate android auto and see Navigation and Audios ECUS and see another ecus but always when i click on scan appears the same 11 ECUS and not audio or navigation, i read in all sites that i have to modify my obd connector pins 12 and 14 but i dont know how or what i need to do that, can some home give some instructions of how to do it? (For noobs) haha.

Where can i find the cable and how to change the pins from my obd?

Thanks!!

**Comment by cedricp** [comment]
https://github.com/cedricp/ddt4all/wiki#how-to-access-multimedia-can-bus

**Comment by fparmentier** [comment]
Hi have modified a Ford OBD adapter with a PIC18F25K80 chip. These adapters have a toggle switch to switch between different CAN networks of Ford. I changed the connections from pin 3 to pin 13 and pin 11 to pin 12. This way you can switch between the multimedia CAN bus and normal CAN bus.
The only thing you will need is a soldering iron and a screwdriver.

https://www.aliexpress.com/item/100-PIC18F25K80-Chip-ELM327-V1-5-USB-Switch-ELM-327-For-Ford-HS-CAN-MS-CAN/32829576979.html

**Comment by ohayyam** [comment]
Hello to all. 

Sorry for the delay but, between the work and the fever I have not had time to try to "explain" my developments. 
First I would like to warn you that, to complete the work, you need a little bit of familiarity with the use of soldering iron (preferably professional) and, in any case, as I said from the beginning, it's all at your responsibility. 
First step to where I started: make a PHOTO of the OBD socket of the car, as you can see (the pictures are all in the final link), has only 8 connected PIN. Here so I tried to find out what he was referring to the pin ( http://pinoutdiagram.com/renault-obd-ii-diagnostic-connector-pinout/) And I have tried to reproduce the same configuration interface ELM used for the various "procedures" well known. In this case, therefore, having to interact with the multimedia CAN bus, it is necessary to make a change of the cables which intercept the "high level" interface signal (6 and 14) and interposing a diverter that, using the same PIN, divert them toward those of "low level" (13:12) Renault (the diagram and photos of the links are always in the link below). Then, sore, it is necessary to remove the resistance (R04 from 120Ohm) which is located in the contact bridge (6 and 4) on the base of the ELM. Finally, once all closed, one may proceed by connecting the ELM to the machine, and then open the "mythical" DDT4ALL and enable (low level) in ' ECU A-IVI (In-Vehicle Infotainment Android) DAB parameter. Subsequently, returning to the ECU RadNav (high level), simply turn the DAB parameters that I had sent earlier to Loris. As always, at the end of it all it makes a nice reset the device and .... Bingo!

Read more at https://www.renaultclub.it/index.php?threads/radio-dab-su-scenic-iv-risolto.3172/page-5#06UxHvbSzy3GRtWh.99

he was mentioned to remove a resistance at forum. Any idea ?

**Comment by Seguro19** [comment]
Ok great but where can u find the cables? Because i think there are data cable right? Where can i but It?

**Comment by ohayyam** [comment]
https://www.drive2.ru/l/468057702971474426/    

But above link did not mention about removing resistance.

**Comment by cedricp** [comment]
Indeed, a 120 Ohm resistor shouldn't be integrated, as the vehicle bus has already a termination on each ends.
Thank you for the feedback.

**Comment by Seguro19** [comment]
Ok so... i recently get this 
![20180208_131904](https://user-images.githubusercontent.com/14854945/35974994-7dbf05e6-0cdb-11e8-83b4-667335af0248.jpg)
![20180208_131908](https://user-images.githubusercontent.com/14854945/35974997-7f02118c-0cdb-11e8-930c-980ba30ae9c9.jpg)
Can i establish the cable betweet my obd elm to the new adapter using this on the obd elm:
![10916](https://user-images.githubusercontent.com/14854945/35975046-aee79296-0cdb-11e8-873e-d2276b7346b5.jpg)
And then connect it to my car?

**Comment by ohayyam** [comment]
![mod baglanti sema](https://user-images.githubusercontent.com/35384108/35975709-b5587b5a-0cee-11e8-8ffd-13528242649d.jpg)

No need to second connection socket. just follow the link above for procedure.

**Comment by Banana009** [comment]
I modified according to the instructions above, remove the resistance  of ELM adapters (USB, wifi adapters).  Adapters communicate with RadNav without problems  but not with A-VI v0.9.  
 am not able to to read/write to A-VI v0.9 .When I switched to LS CAN,  scaned it , DDT4ALL found only Central Panel 7/8.7 :-) Nothing else  :-1: 
Can someone help me?
![central_panel_ecu](https://user-images.githubusercontent.com/35255691/36756291-e4997200-1c0e-11e8-9db1-65d9c2d81272.jpg)

**Comment by ohayyam** [comment]
I am not sure but next step is try to find original ELM327 chip which is 21 USD. Chines clone can work limited. Just check obdlink sx ( Red one when we open the program it is proper for ddt4all. )

If it will not work means we have to wait for updated database...

Thanks & Regards,

![redone](https://user-images.githubusercontent.com/35384108/36786448-78404550-1c97-11e8-8f55-093d863eb210.png)

**Comment by lucamagilla** [comment]
On the Italian site only one seems to have succeeded

**Comment by testeur70** [comment]
> Hi have modified a Ford OBD adapter with a PIC18F25K80 chip. These adapters have a toggle switch to switch between different CAN networks of Ford. I changed the connections from pin 3 to pin 13 and pin 11 to pin 12. This way you can switch between the multimedia CAN bus and normal CAN bus.
> The only thing you will need is a soldering iron and a screwdriver.
> 
> https://www.aliexpress.com/item/100-PIC18F25K80-Chip-ELM327-V1-5-USB-Switch-ELM-327-For-Ford-HS-CAN-MS-CAN/32829576979.html

Hello Felix, I have the same elm and want to use it with ddt on my scenic. Can you confirm that you just have to switch  pin 3 to pin 13 and pin 11 to pin 12, to have a fully working ELM with high and low CAN ?
Thanks

**Comment by fparmentier** [comment]
> > Hi have modified a Ford OBD adapter with a PIC18F25K80 chip. These adapters have a toggle switch to switch between different CAN networks of Ford. I changed the connections from pin 3 to pin 13 and pin 11 to pin 12. This way you can switch between the multimedia CAN bus and normal CAN bus.
> > The only thing you will need is a soldering iron and a screwdriver.
> > https://www.aliexpress.com/item/100-PIC18F25K80-Chip-ELM327-V1-5-USB-Switch-ELM-327-For-Ford-HS-CAN-MS-CAN/32829576979.html
> 
> Hello Felix, I have the same elm and want to use it with ddt on my scenic. Can you confirm that you just have to switch pin 3 to pin 13 and pin 11 to pin 12, to have a fully working ELM with high and low CAN ?
> Thanks

Hi,

Yes that's all. :)

**Comment by mnigten** [comment]
I have this one from August last year and modified as discribed. It works great.

**Comment by TimvdEijnden** [comment]
Yes this also worked great for me!

**Comment by myshuker** [comment]
hey friend 
can I use this ?
https://www.aliexpress.com/item/4000955430101.html?spm=a2g0o.detail.0.0.6ae92d1cdsLP9L&gps-id=pcDetailCartBuyAlsoBuy&scm=1007.12908.197732.0&scm_id=1007.12908.197732.0&scm-url=1007.12908.197732.0&pvid=2560a7d1-bf0a-4eac-818e-ee46eb6946be&_t=gps-id:pcDetailCartBuyAlsoBuy,scm-url:1007.12908.197732.0,pvid:2560a7d1-bf0a-4eac-818e-ee46eb6946be,tpp_buckets:668%230%23131923%238_668%23888%233325%233_668%232846%238110%231995_668%232717%237561%23306__668%235154%2323664%23130

**Comment by fparmentier** [comment]
Looks good to me :)

**Comment by myshuker** [comment]
> Looks good to me :)
so it can be used for renault and dacia cars?

**Comment by myshuker** [comment]
> Looks good to me :)

and witch chosse for renault cars is HS CAN or  MS CAN?

**Comment by fparmentier** [comment]
> 
> 
> > Looks good to me :)
> > so it can be used for renault and dacia cars?

I think so, but only after you change the wires for the media can bus. But I assume you are aware of that ;)

**Comment by myshuker** [comment]
> > > Looks good to me :)
> > > so it can be used for renault and dacia cars?
> 
> I think so, but only after you change the wires for the media can bus. But I assume you are aware of that ;)

thanks friend , but i assume they was already change the wires in this modul, because the y put a switch , is that correct?

**Comment by fparmentier** [comment]
> thanks friend , but i assume they was already change the wires in this modul, because the y put a switch , is that correct?

You are right, but Ford uses another pin assignment for the media can bus.
Change the wires connected to the pins as follows:

Media CAN L - Ford pin 3 change to pin 13
Media CAN H - Ford pin 11 change to pin 12

**Comment by myshuker** [comment]
ok ... BIG THANKS my friend

**Comment by luissilva1971** [comment]
What about pic18F25K80 ... is it required or not for DDT4all and Renault/Dacia Cars? the one the link is showing does not have it... it apears!
    Em quinta-feira, 28 de janeiro de 2021, 11:40:24 WET, Mohammad alshoker<notifications@github.com> escreveu:  
 
 


ok ... BIG THANKS my friend

**Comment by fparmentier** [comment]
> 
> What about pic18F25K80 ... is it required or not for DDT4all and Renault/Dacia Cars? the one the link is showing does not have it... it apears! 

It says it does. But you can always ask the seller to be more sure.
![elm](https://user-images.githubusercontent.com/933335/106137949-c5a12780-616b-11eb-9133-d3d976d2ff73.PNG)

**Comment by myshuker** [comment]
![Udklip](https://user-images.githubusercontent.com/26445354/106277615-b5577e00-6239-11eb-9069-9d1f7dcfd73b.PNG)

**Comment by myshuker** [comment]
![rallonge-768x366](https://user-images.githubusercontent.com/26445354/106277672-c607f400-6239-11eb-8f2c-a01f78d73125.png)

**Comment by VVitchfinder** [comment]
> > thanks friend , but i assume they was already change the wires in this modul, because the y put a switch , is that correct?
> 
> You are right, but Ford uses another pin assignment for the media can bus.
> Change the wires connected to the pins as follows:
> 
> Media CAN L - Ford pin 3 change to pin 13
> Media CAN H - Ford pin 11 change to pin 12

Hey Felix, hoping you can help. I have a Ford elm 327. I know I need to change the pins. They seem to be solded straight to the pin. So don’t see any actual wires. 
![45AF12FD-2B56-4785-9314-51A1A36BFA80](https://user-images.githubusercontent.com/87372217/125449428-b7cd80c7-83f3-4b76-8392-09a00cbed0ff.jpeg)

how to I swap 3 to 13 and 11 to 12 like this? Do I disconnect the pins somehow, or can I solder a wire from 3 to 13 and 11 to 12. I’m a complete novice so any help would be really appreciated.

**Comment by VVitchfinder** [comment]
I have an obdlink sx (red) do I have to mod this to get it to connect to my Renault? I have a new media nav with the system config message and I want to fix it in ddt4all. I was told it was just plug and play but it doesn’t seem to work.

**Comment by AndyIreland** [comment]
https://andyrobus.wordpress.com/2021/07/18/wiring-up-an-obd2-splitter-cable-to-read-a-renault-r-link-radio/

**Comment by charliehoward** [comment]
Can someone clarify, I connected the pins 6 to 13, and 14 to 12 in my adapter but it didn't work. What am I doing wrong?
![PXL_20210917_141712884](https://user-images.githubusercontent.com/17574576/133824919-ffe4691c-281f-48f6-bb78-83967b2cdcb2.jpg)
![PXL_20210917_141721280](https://user-images.githubusercontent.com/17574576/133824922-fdb40ca1-1d85-46b5-9d74-7d8fea476d69.jpg)

**Comment by charliehoward** [comment]
I'm not sure where I got those above pins from but I've removed them and followed the above using a Ford adapter -  pin 3 change to pin 13 and pin 11 change to pin 12. But it's still not working, when I plug it in I get loads of errors on the dash like braking system failure and ESC. Can someone help me out?

**Comment by AndyIreland** [comment]
> I'm not sure where I got those above pins from but I've removed them and followed the above using a Ford adapter - pin 3 change to pin 13 and pin 11 change to pin 12. But it's still not working, when I plug it in I get loads of errors on the dash like braking system failure and ESC. Can someone help me out?

When you do a 'find my ecu's' in the car using the DDT4ALL magnifying glass then sometimes the ABS light will light up and flash or flicker - and possibly a message about ESC as well and DDT4ALL is talking to the ECU's and connecting to them . 

What parameters are you trying to change on your car @charliehoward  ? - is it the rlink radio parameters or other ECU's? - if its the other ECU's of the car you do not have to make that adjustment of soldering the pins

**Comment by charliehoward** [comment]
I've got the adapter working now, I'm trying to edit R-Link, I want to enable this when reversing for the rear sensors but not sure where to look.
![239115882_4311272585625953_582585218229745720_n](https://user-images.githubusercontent.com/17574576/133921381-e44230ca-e59f-4303-b72c-d84d019f6f21.jpg)

**Comment by myshuker** [comment]
whitch car do you have ?

**Comment by charliehoward** [comment]
Megane 3 RS with R-Link retrofitted

**Comment by myshuker** [comment]
> Megane 3 RS with R-Link retrofitted

could you please explaen or take picture how you connect the reare view camera in R-Link system and hoe you activate it on the system??? PLEASE

**Comment by charliehoward** [comment]
I don't want the rear camera, just the reversing sensors like in the photo. I've been told it's possibly to enable I just don't know where to look

**Comment by myshuker** [comment]
> I don't want the rear camera, just the reversing sensors like in the photo. I've been told it's possibly to enable I just don't know where to look

I know that my friend .
But I want to know how to connect and activate it because I have megan3 and i want install rear view camera.
please can you help me

**Comment by charliehoward** [comment]
I haven't connected a rear camera so I can't help you sorry, if you do find out let me know

**Comment by AndyIreland** [comment]
@charliehoward - so you have the ultrasonic sensors fitted in your rear bumper yes? - and you just need to enable them in rlink? is that what you mean?

**Comment by charliehoward** [comment]
> 
> 
> @charliehoward - so you have the ultrasonic sensors fitted in your rear bumper yes? - and you just need to enable them in rlink? is that what you mean?

No, my car came with rear sensors from factory but I've retrofitted R-Link and want to enable the screen below with the sensors 
![Uploading 239115882_4311272585625953_582585218229745720_n.jpg…]()

**Comment by AndyIreland** [comment]
> @charliehoward - so you have the ultrasonic sensors fitted in your rear bumper yes? - and you just need to enable them in rlink? is that what you mean?
> 
> No, my car came with rear sensors from factory but I've retrofitted R-Link and want to enable the screen below with the sensors

OK - so , where did the beep beep warning come from these factory fitted rear bumper sensors ? - through the factory fitted radio/infotainment system or through a speaker in the boot or from dash where speedometer is?

**Comment by charliehoward** [comment]
No idea, it was all there when it left the factory. All I want to know is how to enable that screen shown above
![239115882_4311272585625953_582585218229745720_n](https://user-images.githubusercontent.com/17574576/134044997-ab8691b6-22ee-4cd8-b25b-23ae14a8a84b.jpg)

**Comment by AndyIreland** [comment]
Right, OK lets see. Have you got this reverse  sensors showing up in your list of ECU's  (Valeo) because i Reckon the rlink just works with Valeo UPA sensors (I could be wrong but thats what I reckon) 
![valeo upa ecu](https://user-images.githubusercontent.com/49172217/134045707-9d0e09d4-5314-468d-aed8-aba973e448ec.jpg)

**Comment by charliehoward** [comment]
https://user-images.githubusercontent.com/17574576/134045883-2d4767a7-1227-482f-a565-e3b31dc59581.mp4

This is what I had

**Comment by AndyIreland** [comment]
I cannot see any UPA (universal parking assist) sensors at all in your list of found ECU's and to me I think you will need that ECU for the information you want showing up on the MFD there (I could be wrong though) - maybe someone else would know. - its not like it takes the info from the reversing camera to light up those segments it takes the data from the bumper UPA sensors

**Comment by charliehoward** [comment]
Maybe for the rear sensors but I've been told it's in the R-Link part as it's just enabling a screen, I imagine it's in the same section as the rear camera, do you know where that is?

**Comment by AndyIreland** [comment]
in that case then , maybe this is the settings you have to make to the MFD settings?

![rear upa rlink](https://user-images.githubusercontent.com/49172217/134074839-ae6168b0-3ab0-40b6-b76d-7a01e266982b.jpg)

**Comment by charliehoward** [comment]
I've managed to get this screen up for the rear camera
![PXL_20210921_180719790](https://user-images.githubusercontent.com/17574576/134216451-f56576e9-9847-45d9-a84d-bfb16bad2ed7.jpg)
But can't find anywhere to make the sensors appear like this
![239115882_4311272585625953_582585218229745720_n](https://user-images.githubusercontent.com/17574576/134216529-02d858e8-c188-40c7-be27-95ddc3849c3b.jpg)

**Comment by charliehoward** [comment]
I haven't yet, I think you have to retrofit the newer parking module so I've made this adapter and will let you know if fitting the newer one works.
![PXL_20211009_175135337](https://user-images.githubusercontent.com/17574576/136667509-0f231f72-c97e-436d-a78b-6ab1078f545e.jpg)

**Comment by MellotronScratch** [comment]
You can also modify this VW cable and make a converter cable for the new type of pdc ECU. I've done it to make my sensors show up on the display.

https://a.aliexpress.com/_uju0dm

**Comment by charliehoward** [comment]
Anything else you need to do other than just fitting that module?

**Comment by AndyIreland** [comment]
> I haven't yet, I think you have to retrofit the newer parking module so I've made this adapter and will let you know if fitting the newer one works. ![PXL_20211009_175135337](https://user-images.githubusercontent.com/17574576/136667509-0f231f72-c97e-436d-a78b-6ab1078f545e.jpg)

You most probably know what you are doing but if its any help to you at all @charliehoward  - here is a wiring diagram for the Renault Zoe that uses that parking aid computer:

![0001](https://user-images.githubusercontent.com/49172217/136673040-2906fe99-f36e-4ce2-85c8-ff25a43e1fc1.jpg)

**Comment by MellotronScratch** [comment]
Does anyone know if this VGate VLinker cable will work with dtt4all? Especially the automatic switching sound interesting.
This looks like a good alternative to an ELS27 adapter to me.

https://aliexpress.com/item/1005003116796694.html
![Vgate-Vlinker-Fs-ELM327-Voor-Ford-Forscan-Hs-MS-CAN-Elm-327-Obd-2-OBD2-Auto jpg_Q90](https://user-images.githubusercontent.com/933335/159452856-bcf16308-e0bc-452d-8d61-e8de27c49288.jpg)

**Comment by MellotronScratch** [comment]
I decided to give it a try, the cable arrived a few days ago.
It seems ddt4all is able to read the main CAN bus (115200 baud or higher) with both ELM327 or ELS27 option selected. It is noticeably a lot faster than a normal ELM327 or OBDLink SX
I modified the connector to read pin 12 and 13 in stead of the Ford pins (3 and 11)  but unfortunately the Multimedia CAN bus is nog being read. I've attached some pictures of the PCB, it seems there are two CAN controllers (MCP2551) and two DPDT switches connected to a MIC3322. Unfortunately I cannot find any datasheet about it :(
Maybe somebody knows the code how the implement to read the CAN2 bus?
@cedricp 

![vLinker PCB](https://user-images.githubusercontent.com/933335/160232954-63430ee5-8509-422b-ac13-0c6b0aeb1d08.jpg)

**Comment by AndyIreland** [comment]
@MellotronScratch  - is there a PIC18F25K80 chip in there , I cannot see it

**Comment by MellotronScratch** [comment]
@AndyIreland No there isn't. The brain is a MIC3322.

**Comment by Furtif** [comment]
if not still repply move question to https://github.com/cedricp/ddt4all/discussions

**Comment by vicentmartinezmartinez** [comment]
> ![rallonge-768x366](https://user-images.githubusercontent.com/26445354/106277672-c607f400-6239-11eb-8f2c-a01f78d73125.png)
> 
> * pin 6 en el lado ELM a pin 13 en el lado OBD
> * pin 14 en el lado ELM a pin 12 en el lado OBD


Thank you all, I manage to connect to my renault zoe to activate the rear camera.
this pins changes on the obd2 are necessary.

![image](https://github.com/user-attachments/assets/a0f30162-85c1-43a7-90cd-267826bdb6d4)

**Comment by vicentmartinezmartinez** [comment]
DDT4ALL IS GREAT SOFTWARE.
I MANAGE TO ACTIVATE THE REAR CAMERA.

REMENBER TO RESET THE RLINK SYSTEM TO ACTIVATE THE CHANGES.

**Comment by AndyIreland** [comment]
> DDT4ALL IS GREAT SOFTWARE. I MANAGE TO ACTIVATE THE REAR CAMERA.
> 
> REMENBER TO RESET THE RLINK SYSTEM TO ACTIVATE THE CHANGES.

yeah .... but dont press the 'SOFT RESET' button whatever you do!! ;)

**Comment by vicentmartinezmartinez** [comment]
TAMBIEN MUY IMPORTANTE MODIFICAR LOS PINS DEL OBD2.
MUCHAS GRACIAS Andyireland.

**Comment by Talvien** [comment]
> I decided to give it a try, the cable arrived a few days ago. It seems ddt4all is able to read the main CAN bus (115200 baud or higher) with both ELM327 or ELS27 option selected. It is noticeably a lot faster than a normal ELM327 or OBDLink SX I modified the connector to read pin 12 and 13 in stead of the Ford pins (3 and 11) but unfortunately the Multimedia CAN bus is not being read. I've attached some pictures of the PCB, it seems there are two CAN controllers (MCP2551) and two DPDT switches connected to a MIC3322. ~Unfortunately I cannot find any datasheet about it :(~ Maybe somebody knows the code how the implement to read the CAN2 bus? [@cedricp](https://github.com/cedricp)
> 
> ![vLinker PCB](https://user-images.githubusercontent.com/933335/160232954-63430ee5-8509-422b-ac13-0c6b0aeb1d08.jpg)
> 
> Edit: datasheet found here: http://www.jinxusolu.com/sjsc

Thanks man, I got the PermissionError all the time with my VLinker. Selecting the correct Baudrate works.
