### ISSUE TITLE
Problem with Read data and write 

### ISSUE THREAD

**Issue by Saad-BinMansour** [cedricp/ddt4all#343]
Hello
Firstly, thanks for your efforts
Secondly I have a problem and I ask you to solve it: DDT4ALL cannot read or write data and I have tried more than one version of the program and more than one version of the database and the problem remains the same
![photo5951643951842832546](https://user-images.githubusercontent.com/55384777/75118010-5aabbe80-5687-11ea-84b6-27ae6a285473.jpg)
![photo5951643951842832548](https://user-images.githubusercontent.com/55384777/75118012-5e3f4580-5687-11ea-93ef-5b5867bc58a9.jpg)

I have attached the Benchmark of the OBD and also the message that comes to me when I change options
[Bunchmark logs.txt](https://github.com/cedricp/ddt4all/files/4242151/Bunchmark.log.txt)
[DDT4ALL logs.txt](https://github.com/cedricp/ddt4all/files/4242153/DDT4ALL.logs.txt)

**Comment by KarelSvo** [comment]
Show the file elm_ddt and ecu_ddt.

**Comment by Saad-BinMansour** [comment]
this Logs file
[logs.zip](https://github.com/cedricp/ddt4all/files/4247069/logs.zip)

**Comment by shrlnm** [comment]
Bad, unprecedented adapter.

**Comment by CRACKISH** [comment]
i have same error

[logs.zip](https://github.com/cedric
![error](https://user-images.githubusercontent.com/25606280/82923389-8c346e80-9f83-11ea-9a02-41a7dcfc8c97.jpg)
p/ddt4all/files/4683447/logs.zip)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
