### ISSUE TITLE
Error Prog and Stop light TMPS

### ISSUE THREAD

**Issue by garretspain** [cedricp/ddt4all#344]
Hello I tried to set up the TMPS option on my Laguna 3 ( not originally available on my car) with ECU Tweaker and as a result I produced an error prog and stop light on the dashboard. I tried to put the original values but the error remains ...anyone can help me?
Thanks

**Comment by pakoto** [comment]
Only need to revert tpms change and reset

**Comment by garretspain** [comment]
> Only need to revert tpms change and reset

Thank you Pakoto, when I started the car this morning the error and the red light have been disappeared itself.
