### ISSUE TITLE
Duster II security beeper disable

### ISSUE THREAD

**Issue by Daccsika** [cedricp/ddt4all#345]
Dear all,

I would like to disable one function on My Dacia duster II 2018. When I dont turn off the engine and exit the car with keyless card and close either door the car beeps 4 times very loudly. It is annoying me because I always leave the keyless card on My pocket. Anybody can help me with this problem? Thanks a lot!

**Comment by BarektE** [comment]
e-posta verin özelden göndereyim

**Comment by Daccsika** [comment]
Mazsola.boy@gmail.com

**Comment by BarektE** [comment]
sorunu nasıl çözeceğinizi. e-mail ile gönderdim

**Comment by KarelSvo** [comment]
> I would like to disable one function on My Dacia duster II 2018. When I dont turn off the engine and exit the car with keyless card and close either door the car beeps 4 times very loudly. It is annoying me because I always leave the keyless card on My pocket. Anybody can help me with this problem? Thanks a lot!

https://translate.google.com/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fwww.dacianer.de%2Fresources%2Ffunktionen-mit-ddt4all-freischalten-konfigurieren.40%2Fupdates%23resource-update-109

**Comment by Daccsika** [comment]
> > I would like to disable one function on My Dacia duster II 2018. When I dont turn off the engine and exit the car with keyless card and close either door the car beeps 4 times very loudly. It is annoying me because I always leave the keyless card on My pocket. Anybody can help me with this problem? Thanks a lot!
> 
> https://translate.google.com/translate?hl=en&sl=de&tl=en&u=https%3A%2F%2Fwww.dacianer.de%2Fresources%2Ffunktionen-mit-ddt4all-freischalten-konfigurieren.40%2Fupdates%23resource-update-109

It doesn’t help. It is not that beep what i need. :(

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
