### ISSUE TITLE
Identification Usm

### ISSUE THREAD

**Issue by Guedin88** [cedricp/ddt4all#346]
Bonjour à tous, 
tout d'abord un grand merci à Cédric pour son énorme boulot sur cette application.

Je voudrais ajouter le coming/leaving home sur la télécommande de ma Clio 4, je parviens à me connecter,  je fais une auto identification Usm

![Screenshot_20200229-224706](https://user-images.githubusercontent.com/61663321/75631599-90572700-5bf4-11ea-97dd-757d2965458f.png)
 
Mais ça ne reconnaît pas le calculateur en auto et ça ne correspond à rien dans la liste proposée. 
Pourriez-vous m'éclairer ?

Salutations,  Guedin.

**Comment by KarelSvo** [comment]
Maybe this answer will help you https://github.com/cedricp/ddt4all/issues/349#issuecomment-598697008

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
