### ISSUE TITLE
Which ABS/ESC ECU to choose?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#349]
Clio Mk4 16v 1.2 2016 petrol.
When searching for cars ECU's (using magnify glass) it never ever find the ABS/ESC ECU. 

If manually trying to choose there are 2 ECU's showing up for Clio 4 - which correct one to choose?

The 2 Brake ECU's listed are 
ABSESC - X105298 Version 2.6 ABS/ESC

and ABSESC - X10527998 Version 4.0 ABS/ESC

@cedricp  and others

**Comment by cedricp** [comment]
Can you copy/paste the log view after a scan ? It's possible that your database is not up to date.

**Comment by AndyIreland** [comment]
thanks for replying @cedricp - here are the only ECU's found when doing a search with magnifying glass. The ABS icon light does blink on the cluster at around 37% of doing its scan. but does not show up in the list of found ECU's: the version is 5.5.0 and database is 09/07/2019
![ecus-found](https://user-images.githubusercontent.com/49172217/76367089-ce0a2d00-6323-11ea-802b-2af701c2d5f5.jpg)

**Comment by KarelSvo** [comment]
Just take the latest ABS version.
Renault does not maintain the Autoident data in the ddt2000 database as installed in series production.
As this tool is not relevant for the authorized workshop.
The autoident function would work better, if you use the clip database as an example.
There is identification by Vehicle type and Diag version 
and by some ecus additionally according to Soft.

**Comment by AndyIreland** [comment]
> Just take the latest ABS version.
> Renault does not maintain the Autoident data in the ddt2000 database as installed in series production.
> As this tool is not relevant for the authorized workshop.
> The autoident function would work better, if you use the clip database as an example.
> There is identification by Vehicle type and Diag version
> and by some ecus additionally according to Soft.
> 
> ddt4all even declares ecus with a quadruple match as not perfect:
> Found ECU [Cluster] (not perfect match) :Cluster C1A_CMFB_15-40ph2_V2.26_RUN1 DIAGVERSION [22] SUPPLIER [10VisteonPalmela--EV ] SOFT [EV_V06.17] VERSION [1932 instead 1932]

thanks - so its safe to program by manually selecting 

ABSESC - X10527998 Version 4.0 ABS/ESC 

is it?

**Comment by shrlnm** [comment]
sometimes, it is possible to find an appropriate xml by the vin number

**Comment by AndyIreland** [comment]
> sometimes, it is possible to find an appropriate xml by the vin number

ah right thanks, How do I do that then please?

**Comment by shrlnm** [comment]
Give me email or a vin

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
