### ISSUE TITLE
Radio Connect diag unit error

### ISSUE THREAD

**Issue by org07** [cedricp/ddt4all#352]

**Comment by org07** [comment]
Can anyone other than Renault service do this?

The service wants more money from the radio itself.

Does anyone know this job that can help in this forum?

**Comment by org07** [comment]
There are a lot of people having this kind of problem, ddt4all will be on the market, and if someone does this, it will help a lot.

**Comment by Marianpol** [comment]
Service manual says that your radio configuration is not valid. Check if all options match to your vehicle configuration (check VIN your also).

**Comment by org07** [comment]
> Servis el kitabı radyo yapılandırmanızın geçerli olmadığını söylüyor. Tüm seçeneklerin araç yapılandırmanızla eşleşip eşleşmediğini kontrol edin (VIN'inizi de kontrol edin).

Marianpol thank you for your interest, Vin is correct

**Comment by org07** [comment]
I think the error is on these, but it won't let me fix it

![5](https://user-images.githubusercontent.com/62398726/77795453-9834aa80-707e-11ea-83e0-b1f60e0b247b.PNG)
![6](https://user-images.githubusercontent.com/62398726/77795461-9965d780-707e-11ea-93b8-f0ac56749b80.PNG)

**Comment by Marianpol** [comment]
Can you tell me your VIN? Maybe I will can check which option fits to your car.

**Comment by org07** [comment]
> Bana VIN'inizi söyleyebilir misiniz? Belki arabanıza hangi seçeneğin uyduğunu kontrol edebilirim.

VF1LZBB0644426153

**Comment by org07** [comment]
> Bana VIN'inizi söyleyebilir misiniz? Belki arabanıza hangi seçeneğin uyduğunu kontrol edebilirim.

VF1LZBB0644426153

**Comment by Marianpol** [comment]
> 
> VF1LZBB0644426153
I run through radio configuration from your VIN and LC005 configuration NAV0/AMP0/BOX0 is correct, but LC004 configuration should be AUX1/CDC0/SUB0. Try to change it.

**Comment by org07** [comment]
> > VF1LZBB0644426153
> 
> VIN ve LC005 yapılandırmanızdan NAV0 / AMP0 / BOX0 yapılandırmanızdan radyo yapılandırması yapıyorum, ancak LC004 yapılandırması AUX1 / CDC0 / SUB0 olmalıdır. Değiştirmeye çalışın.

**thank you i will keep trying**

**Comment by org07** [comment]
(00   ) NAV0/AMP0/BOX0
              : (20   ) NAV1/AMP0/BOX0
              : (40   ) NAV0/AMP0/BOX1
              : (60   ) NAV1/AMP0/BOX1
              : (80   ) NAV0/AMP1/BOX0
              : (A0   ) NAV1/AMP1/BOX0
              : (C0   ) NAV0/AMP1/BOX1
              : (E0   ) NAV1/AMP1/BOX1
serviceID    +
              : (63   ) 2E2B1B <Params>
              : (64   ) 1101
              : (65   ) 10C0

##########################  Current values  ##########################

LC005  external elements                                            NAV1/AMP0/BOX0

######################################################################

**Comment by org07** [comment]
I cannot change LC005

**Comment by Marianpol** [comment]
I forgot to ask - why this DTC showed up? Have you done something to your radio configuration? 

> I cannot change LC005

You cannot change back LC005 to NAV0/AMP0/BOX0? What is showing as a result of this configuration (resp)?

**Comment by org07** [comment]
> Sormayı unuttum - bu DTC neden ortaya çıktı? Radyo yapılandırmanız için bir şey yaptınız mı?
> 
> > LC005'i değiştiremiyorum
> 
> LC005'i NAV0 / AMP0 / BOX0 olarak değiştiremez misiniz? Bu yapılandırmanın sonucu olarak ne gösteriliyor?

This is the result **NAV1 / AMP0 / BOX0**

**Comment by Marianpol** [comment]
> This is the result **NAV1 / AMP0 / BOX0**

I understand. So LC005 configuration is wrong because you don't have factory navigation system in your car (i.e. Carminat DVD, Carminat TomTom, R-LINK). Change it to NAV0 / AMP0 / BOX0 and if LC004 is not AUX1/CDC0/SUB0 try to change it too.

**Comment by org07** [comment]
> > Bu sonuç **NAV1 / AMP0 / BOX0**
> 
> Anlıyorum. LC005 yapılandırması yanlış çünkü arabanızda fabrika navigasyon sistemi yok (yani Carminat DVD, Carminat TomTom, R-LINK). NAV0 / AMP0 / BOX0 olarak değiştirin ve LC004 AUX1 / CDC0 / SUB0 değilse de değiştirmeyi deneyin.

**no navigation, only radio indicator**

**Comment by org07** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/62398726/77908347-056d5900-7294-11ea-9c95-0380cd1a85e7.PNG)

**Comment by org07** [comment]
LC005 I changed it, but the radio didn't improve again

**Comment by Marianpol** [comment]
> LC005 I changed it, but the radio didn't improve again

Did you change LC004 allso?
I think without answreing my question I will not able to help you.

> Why this DTC showed up? Have you done something to your radio configuration?

**Comment by org07** [comment]
> > LC005 Değiştirdim, ancak radyo tekrar gelişmedi
> 
> LC004'ü de değiştirdiniz mi?
> Soruma cevap vermeden sana yardım edemeyeceğimi düşünüyorum.
> 
> > Bu DTC neden ortaya çıktı? Radyo yapılandırmanız için bir şey yaptınız mı?
LC004 yes

**Comment by org07** [comment]
I don't know if the numbers in the marked section are correct
![1](https://user-images.githubusercontent.com/62398726/77930786-fac2bc00-72b3-11ea-95d3-d1e74056ffba.PNG)

**Comment by Marianpol** [comment]
> I don't know if the numbers in the marked section are correct

In default settings they are different, but I don't what are they for and if they are cause of the problem.
So, if you done some changes to your radio please upload a elm_log from software (Pyren or DDT4ALL) you made those changes.

**Comment by org07** [comment]
**elm_log** i don't know what it is

**Comment by Marianpol** [comment]
> **elm_log** i don't know what it is

For PyRen search for your PyRen home directory then go to pyren/logs. There you should find it.
For DDT4ALL search for your DDT4ALL home directory then go to logs. Thee you find elm_ddt.
Upload both files if you can.

**Comment by org07** [comment]
![araç tanımı](https://user-images.githubusercontent.com/62398726/77934959-796e2800-72b9-11ea-9338-79f501e8cea3.PNG)

**Comment by org07** [comment]
I'm doing this with Pyren too

**Comment by org07** [comment]
TeamViewer can you connect remotely

**Comment by Marianpol** [comment]
> TeamViewer can you connect remotely

For now logs will be enough. I need to analyse it and then we can move further.

You have done CF007?

**Comment by org07** [comment]
> > TeamViewer uzaktan bağlanabiliyor musunuz?
> 
> Şimdilik günlükler yeterli olacak. Bunu analiz etmem gerekiyor ve sonra daha ileri gidebiliriz.
> 
> CF007 yaptınız mı?

**yes**

**Comment by org07** [comment]
**I can send it to you like I uploaded**

![araç tanımı](https://user-images.githubusercontent.com/62398726/77935840-abcc5500-72ba-11ea-9f7b-ee972f65c5b5.PNG)

**Comment by Marianpol** [comment]
> I can send it to you like

Don't send it for now.

> I uploaded
 
Unfortunately, I don't see it.

**Comment by org07** [comment]
> > Sana gönderebilirim
> 
> Şimdilik gönderme.
> 
> > yükledim
> 
> Ne yazık ki görmüyorum.

thank you, I'll be happy when you contact Team Viewer tomorrow

**Comment by org07** [comment]
Step by step pyren, operations

![pyren 1](https://user-images.githubusercontent.com/62398726/77940673-b76f4a00-72c1-11ea-8fd2-ecb9e6e91af1.PNG)
![pyren 2](https://user-images.githubusercontent.com/62398726/77940677-b8a07700-72c1-11ea-8a2b-f2fce93d29fb.PNG)
![pyren 3](https://user-images.githubusercontent.com/62398726/77940679-b9390d80-72c1-11ea-853b-6179a2df619c.PNG)
![pyren 4](https://user-images.githubusercontent.com/62398726/77940681-b9d1a400-72c1-11ea-8c56-7baad6465a55.PNG)
![pyren 5](https://user-images.githubusercontent.com/62398726/77940686-ba6a3a80-72c1-11ea-8a93-d18e419a29b8.PNG)
![pyren 6](https://user-images.githubusercontent.com/62398726/77940689-bb02d100-72c1-11ea-95fb-48152b3c4a74.PNG)
![pyren 7](https://user-images.githubusercontent.com/62398726/77940690-bb02d100-72c1-11ea-935e-81c5608fe5b4.PNG)
![pyren 8](https://user-images.githubusercontent.com/62398726/77940694-bb9b6780-72c1-11ea-857d-49b65685f119.PNG)
![pyren 9](https://user-images.githubusercontent.com/62398726/77940701-bccc9480-72c1-11ea-9d90-c557d938b7b1.PNG)

**Comment by org07** [comment]
I'm in the car as of now

**Comment by org07** [comment]
the last situation
![Ekran Alıntısı 1](https://user-images.githubusercontent.com/62398726/77941237-84798600-72c2-11ea-83d1-7e4ff5e1cf00.PNG)
### **first part**

![Ekran Alıntısı 2](https://user-images.githubusercontent.com/62398726/77941303-9fe49100-72c2-11ea-99f1-17d2335363e1.PNG)

**Comment by org07** [comment]
I took a video of the transactions I made, I can send

**Comment by org07** [comment]
Video link
[https://youtu.be/pQ01V_iqD_o](url)

**Comment by org07** [comment]
> Herhangi bir günlük yüklemediniz çünkü size yardım edemem. Bunu yapın ve belki de yardımcı olabilirim.

I wrote the video link, did you have a chance to watch it?
