### ISSUE TITLE
Écu reset dans diagnostic puis écran noir (kadjar) 

### ISSUE THREAD

**Issue by Soun30** [cedricp/ddt4all#353]
Bonjour à tous, 

Je rencontre un problème en voulant mettre mon rlink 2 en version usine à partir de ddt4all
 je vous décrit step by step 
Kadjar __audio __radnav3.xv3.3__diagnosis__ecu reset __hard reset __key off/key on reset __et pour finir configuration reset... Et depuis mon écran est noir et n'a pas redémarrer 😭

**Comment by Soun30** [comment]
Help please 😭😭

**Comment by shrlnm** [comment]
e-mail ???

**Comment by Soun30** [comment]
akna520@hotmail.fr

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
