### ISSUE TITLE
DDT4ALL for changing "start brand logo" in Smart 453 navigation media system

### ISSUE THREAD

**Issue by doctorcico** [cedricp/ddt4all#355]
Hi Friends I'm new member and sorry for my english....I like to "work" with this fantastic tool DDT4all from Cedric on my Smart 453 m.y.2019 with original Touch screen navigation Media System,,,I should change it's original "Smart start logo" with "JBL start logo" or better I should create a new one "Brabus" (see attached picture) but I'm not able to find the right folder where put the new Brabus icon (what is the right size?)
Is it correct the route in ddt4all for change "start logo"? (see attached picture)
Thanks in advance

(Smart 453 and TwingoIII use the same hardware firmware and software)

![Brabus_logo](https://user-images.githubusercontent.com/62837505/77854359-2a0cf680-71ea-11ea-9a27-9dff7f7da171.png)
![DDT4ALL](https://user-images.githubusercontent.com/62837505/77854363-31cc9b00-71ea-11ea-9f65-62396e528abc.png)

**Comment by n4th4ndev** [comment]
I thinks you can't

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
