### ISSUE TITLE
ddt4all android hangs choosing usb without it

### ISSUE THREAD

**Issue by pakoto** [cedricp/ddt4all#357]
When you select usb unintentionally, app close with error when start. You need to reinstall or try to switch quickly to wifi or bt before crash.

**Comment by Roms33** [comment]
Same problem

**Comment by pakoto** [comment]
more people could recreate bug? 

If you have elm bluetooth or nothing, select usb or wifi into ecu tweaker, and try to open app again. If it closes after 1 sec, please report and put android version here. You can try to open and quickly change to bluetooth and works again. Reinstall also works.

**Comment by Roms33** [comment]
I use elm usb. The app close when i choose usb. Android 10.

**Comment by localhost61** [comment]
No matter the USB device, you don't need to connect it to get the force close (French Android 9 for me)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by MTPro94** [comment]
On Android 13 Usb Elm doesn't work, it doesn't manage to find Ecu in Megane III 2014, or it closes when I select USB. I installed the application version 1.8, 1.85, 1.9. I copied ecu.zip to the internal memory, I think I did the steps correctly. Does anyone know how to solve it? Thank you .
