### ISSUE TITLE
activate horn lock from the key

### ISSUE THREAD

**Issue by ganhalimi** [cedricp/ddt4all#360]
hi all

Just wondering whether you would know how to activate horn lock from the key of Renault Grand Scenic? I sometimes forget where i park the car, and would like to locate the car by pressing the key (to hear the horn / beep / sound).

FYI i've tried enabling Bipbip_lock_CF (to true) but still there is no sound. 

Let me know?

**Comment by org07** [comment]
o özellik sadece kartlılarda var anahtarlı olanlarda yok.

**Comment by org07** [comment]
O özellik anahtarlı araçlarda aktif olmuyor sadece kartlı araçlarda aktif ediliyor.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
