### ISSUE TITLE
Cluster values interpretation - X98, LPG, fuel update

### ISSUE THREAD

**Issue by xormail** [cedricp/ddt4all#361]
There is possibility to change threshold of consumed fuel, which updates the fuel gauge. It is very useful for cars running also LPG, where no petrol is consumed. There are guides for Dacias, I did it for my X91, but this X98 (Clio 4) is slightly different. DDT4ALL detected Cluster_X98_X87_X82_V2.4_20121001T113250.xml for the cluster, setting should be in the  C_Recalage a C_Recalage_Plein, but values are not clear. What could be relation (formula) to convert 19050f and 252502 to liters? Screenshot with real (default) value:
https://photos.google.com/share/AF1QipOUjyN_dF-yHhgwCyIhxQg_6F9p1ixiBpm2k5vpjRu3xteA8OkAKZ7aVfF0D-Dcpw/photo/AF1QipPLIizGP9NEbHix87ftHLl16yhxFLnMIuUwmjZm?key=LWZ0MnJHdllKTmMtR1JZVDZ5X1VQZHdCa2N3MlNR

Many thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
