### ISSUE TITLE
Symbol 2014 cruise control

### ISSUE THREAD

**Issue by volkann60** [cedricp/ddt4all#365]

**Comment by volkann60** [comment]
Symbol 2014 cruise control

Hello, first of all, I use Google Translate, I don't know your language.

I have a Renault Symbol 2014 model vehicle. I want to turn it on for speed stabilization and limitation, but I am getting an error. Can you help with the issue?

The error I got

Sedding elm request: 2E222F01

Bad elm response: wrong response: rn: comditions not correct or request squence error (7F2E22)

**Comment by volkann60** [comment]
![0D043E69-9097-4A77-970D-7DD139874C54](https://user-images.githubusercontent.com/63704054/79311415-11991d80-7f06-11ea-8eaf-20396692579c.jpeg)
![4ECEA96A-F2A5-4298-9F01-D6BFD93D4878](https://user-images.githubusercontent.com/63704054/79311426-14940e00-7f06-11ea-992d-c6df01397e91.jpeg)
![08F43DE7-E076-40CB-9FBA-6A8FAB2E33CD](https://user-images.githubusercontent.com/63704054/79311427-152ca480-7f06-11ea-91c9-7e2799277542.jpeg)
![D420B5C2-E32A-4C63-8130-AA56B7616835](https://user-images.githubusercontent.com/63704054/79311428-15c53b00-7f06-11ea-8de2-aa0dbff6f196.jpeg)

**Comment by volkann60** [comment]
![18161A19-45CE-46AA-A987-D540DB49DE37](https://user-images.githubusercontent.com/63704054/79311726-8b310b80-7f06-11ea-89d7-95721dbfc605.jpeg)
![D08A2B85-469F-47F8-A280-EB2D7F562173](https://user-images.githubusercontent.com/63704054/79311756-9421dd00-7f06-11ea-90d8-ce3ec3ce3df8.jpeg)
![Uploading 8BF3E1CD-AC47-464C-9D33-2239B57684AD.jpeg…]()

**Comment by volkann60** [comment]
![Uploading 97BE4D0E-61D9-45F3-BAC6-88487E0F0162.jpeg…]()

**Comment by BarektE** [comment]
tesisatı hazır var mıydı yoksa kendiniz tesisat mı çektiniz? Direksiyon simidi üzerindeki 331 kodlu düğmelerin direnç değerlerini okuyamıyor enjeksiyon beyni
