### ISSUE TITLE
Create new Screens

### ISSUE THREAD

**Issue by PetarKleut** [cedricp/ddt4all#370]
Hi,
I would like to create some new screens. In edition mode I can create new category and screen and after pressing UI edit button I can create new label and button but that's all. 
How do I add parameters to the screen?

I do get an error "QLayout: Cannot add null widget to QHBoxLayout/" maybe that's disabling some part of UI. 

Thanks

**Comment by PetarKleut** [comment]
I was able to create the screen manually. After going to File/Save current ECU the file with the extension json.layout will be saved in json folder. Then I was editing this json.layout file using one of the ECU's from the database that I had as template. 
Quite slow but maybe it helps somebody with same issue.

**Comment by cedricp** [comment]
Oh, yes, haven't had time to finish that feature. But it should work this way, though

**Comment by KarelSvo** [comment]
> Hi,
> I would like to create some new screens.

I use this easier way:
Edit the xml files with the ddt2000 editor and only then create an ecu.zip archive.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
