### ISSUE TITLE
Extended CANId

### ISSUE THREAD

**Issue by PetarKleut** [cedricp/ddt4all#371]
Hi,
can DDT4all work with ECUs that use extended CANid?

This is how CANId is defined in XML file:
CANId Value="416998129" Extended="1"

When I try to connect with ECU I get the error that functional address could not be retrieved @ 18DAE2F1

**Comment by KarelSvo** [comment]
> can DDT4all work with ECUs that use extended CANid?

No, but it works on Pyrene mod_ddt.
https://gitlab.com/py_ren/pyren

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
