### ISSUE TITLE
Connection to ELM was Lost. Port Closed

### ISSUE THREAD

**Issue by nerdinary** [cedricp/ddt4all#372]
I'm using a wifi obd2 adaptor - seems to work fine with android apps. I can connect to it using ddt4all and things seem to work fine, till I select an actual ECU and then the program hangs.

On the console, I get a flood of messages saying:

"Connection to ELM was lost. Port Closed".

Only way to recover is to kill the program and try again.

**Comment by nikoul** [comment]
I have the exact same issue. @nerdinary did you find a solution eventually ?

**Comment by 11noobestplayer** [comment]
hi
same problem for me to, any solutions pls ?

**Comment by nerdinary** [comment]
Unfortunately I never found a solution. I've given up.

**Comment by KarelSvo** [comment]
Far too little information to analyze the problem remotely.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
