### ISSUE TITLE
Keyless Vehicle

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#373]
hello all , anyone got an Idea about why when I go into EMM Ignition that it says  Cbx_keylessVehicle_CF that it is set to '0' on my car (Clio 4 1.2 16v 2016) when the car has no physical key but a KeyCard instead? 
was tempting to see what would happen if I changed value to '1' but a bit cautious  just in case i break something?

Pic:
![keyless vehicle](https://user-images.githubusercontent.com/49172217/80130060-eced1780-858f-11ea-8cf7-8718a4650bf4.jpg)

**Comment by org07** [comment]
Cbx Keyless Vehicle not change from 0 to 1 ddt4all can not

**Comment by org07** [comment]
Cbx Keyless Tool does not change from 0 to 1, ddt4all cannot do this

**Comment by AndyIreland** [comment]
> Cbx Keyless Tool does not change from 0 to 1, ddt4all cannot do this

Oh, right so if i go to change from 0 to 1 it just wont accept it and stay on '0' anyway?

**Comment by org07** [comment]
Will stay at 0

**Comment by org07** [comment]
Will stay at 0 will not go to 1

**Comment by AndyIreland** [comment]
oh right - thank you. and thanks for the reply

**Comment by MohammedTarek14** [comment]
> Cbx Keyless Tool does not change from 0 to 1, ddt4all cannot do this

Which program can do it?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
