### ISSUE TITLE
compatibilité DDT4ALL

### ISSUE THREAD

**Issue by agn22** [cedricp/ddt4all#378]
Bonjour,
J'ai une interface EML327 V1.5 avec une puce PL-2303HX
J'ai installé DDT4ALL pour activer android auto sur ma mégane3 mais le bouton mode expert reste grisé, je n'ai donc pas accès aux menus déroulant
Quelqu’un saurait il si cette puce est compatible ?
J'ai cherché sur le forum mais je ne trouve pas la réponse.
Merci d'avance :)

**Comment by cedricp** [comment]
Le bouton expert ne sert qu'a bloquer les requetes d'ecritures par les boutons.
La puce PL2303 est le convertisseur USB vers bus serie, il faut verifier le chip ELM qui doit etre du type PIC18F...
Quelle version utilises tu ?

**Comment by agn22** [comment]
Merci pour ta réponse rapide, en effet, je n'avais pas regardé du bon côté de la carte électronique.... c'est bien un PIC18F25K80.
pour la version du logiciel j'utilise la release disponible ici https://github.com/cedricp/ddt4all/releases
c'est la V1.5 apparemment, avec affichage en noir (sur les captures d'écrans des forums c'est en blanc)

**Comment by cedricp** [comment]
Tu utilises bien le mode "connecte" au demarrage ? (pas le mode edition ?)

**Comment by agn22** [comment]
oui, je clique sur le mode connecté après avoir coché le disclaimer et j'arrive sur cette fenêtre :
[<a href="https://ibb.co/5XDjZtZ"><img src="https://i.ibb.co/WN9zCqC/ddt4.jpg" alt="ddt4" border="0"></a>](url)

**Comment by cedricp** [comment]
Apres, il faut selectionner le modele de vehicule et cliquer sur la loupe pour scanner les ECU.

**Comment by agn22** [comment]
ok, merci, je pensais que ça scannais d'abord...quel boulet je fais, désolé.
je tente ça dès que je peux :)

**Comment by agn22** [comment]
bonjour, j'ai finalement réussi à activer android, le tuto que j'avais suivi ne donnait pas les manips dans le bon ordre.
cependant le bouton expert reste grisé même s'il est possible de l'activer. peut être un bug d'affichage dû à l'interface sombre (sur les captures de forum on peut voir que le logiciel était en blanc avant) ?  je joint une capture
[<a href="https://ibb.co/Qpc6srw"><img src="https://i.ibb.co/tQhby8r/ddt4.png" alt="ddt4" border="0"></a>](url)
Merci en tout cas pour ton logiciel bien utile, je vais creuser les autres possibilités qu'il nous offre :)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
