### ISSUE TITLE
the same happened to me. 

### ISSUE THREAD

**Issue by yunusxcz** [cedricp/ddt4all#380]
I also have a problem in my vehicle Clio 4 and 2012 model. Please help me . 
![IMG-20200509-WA0005](https://user-images.githubusercontent.com/65073432/81473634-76dfe600-9208-11ea-8dad-72fbbb85d1e2.jpeg)

Renolink in my hand

**Comment by yunusxcz** [comment]
By mistake . I did Uch Virgin without knowing. How can I fix this

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
