### ISSUE TITLE
Plugin docs ?

### ISSUE THREAD

**Issue by jirikeller** [cedricp/ddt4all#381]
Documentation for plugins is missing or at least some "hello world" plugin (eg. showing some well-known OBD value available on standing vehicle such as battery voltage) - I have some plugin ideas, but do not have a place to start with. And, one more important question - are plugins planned for Android version as well ? Also in python ? Fully compatible with "adult" ddt4all ? 
My idea is saving some values locally on the device ("backup") and be able to put them back ("restore").

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
