### ISSUE TITLE
Installation of DDT4all

### ISSUE THREAD

**Issue by rldchua** [cedricp/ddt4all#384]
Hi... Tried to find new updates of the ddt4all installation file but am unsure which is the latest. Also, tried on some versions but I'm unable to find my vehicle, Grand scenic, in it. Can advise?

**Comment by AndyIreland** [comment]
try selecting 'all cars' from this site and then click on ddt4all link on desktop
https://www.drive2.ru/b/498093336985338243/?fbclid=IwAR0ydkVzn-kVo7oCTc9xEyN3zC0S6YZXF0ziZYr31upqEep-xbNmbE4cFeA

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
