### ISSUE TITLE
rLink1 video in motion

### ISSUE THREAD

**Issue by sebomaster** [cedricp/ddt4all#385]
In my ddt4all in video restriction i have 2 choice : restricted and limited feature. I not have permited button. Why?

**Comment by Marianpol** [comment]
Maybe your ECU does not support this function? Can you tell me which file exactly was found?

**Comment by mnigten** [comment]
I think this has to do with if it is permitted you would be albe to watch movies while driving. Therefore they use the limited option

**Comment by sebomaster** [comment]
Navi 4.6

**Comment by sebomaster** [comment]
I,m in demo mode and the same options

**Comment by sebomaster** [comment]
Maybe my data base is wrong? From 2019. My car is from 2018 renault twingo gt 3

**Comment by sebomaster** [comment]
![Uploading 20200516_122923.jpg…]()
Why?

**Comment by sebomaster** [comment]
![Uploading 20200516_122923.jpg…]()
Why?

**Comment by Marianpol** [comment]
There is simply no Permitted option in that ECU.
![2020-05-16](https://user-images.githubusercontent.com/35842708/82119652-8e771b80-9780-11ea-82f0-497140a39f4d.png)

**Comment by sebomaster** [comment]
Why?
Anybody know where is button deactivated restriction video in motion?

**Comment by sebomaster** [comment]
Limited feature? What is this?

**Comment by I-am-druny** [comment]
let me know if you found out. i have the same problem

**Comment by AndyIreland** [comment]
You could try this - it may work ... it may not work but give it a go - let us know (do at your own risk - always chance could brick rlink) 

Choose mfd v1.8 - do you see there you have 'permitted' and 'restricted' ? - try writing 'permitted' then press the home button on the rlink 1 to reboot it , then see if it works when driving along ?

![video enable](https://user-images.githubusercontent.com/49172217/143064705-1175ddc5-a235-45c3-af1a-8e6d931d2688.jpg)

**Comment by I-am-druny** [comment]
I'll give it a try tomorrow and tell you. thanks for your help!

AndyIreland ***@***.***> schrieb am Di., 23. Nov. 2021, 17:32:

**Comment by I-am-druny** [comment]
![Uploading IMG_20211124_163525054.jpg…]()

**Comment by I-am-druny** [comment]
![IMG_20211124_163525054](https://user-images.githubusercontent.com/94919917/143286315-39fb3ac2-e7f4-4a98-a646-3d611013adb0.jpg)

it shows that its already permitted but it doesn't work 🤔

**Comment by I-am-druny** [comment]
btw whats the deal with the rs display? 
![IMG_20211124_163934512](https://user-images.githubusercontent.com/94919917/143286551-67cfdf67-c166-4ff4-9148-9b5f9fdd738e.jpg)

**Comment by I-am-druny** [comment]
i have a laguna 3. would that work?

**Comment by AndyIreland** [comment]
> it shows that its already permitted but it doesn't work 🤔
Thats a shame . It was worth a go. 

Maybe you could give this a go
https://www.navinc.nl/9-tv-in-motion/video-in-motion-module-renault-r-link-system-can

I have never got the RS configuration working on my rlink1 for my Zoe .. I only think it works on RS turbo renault models , more than likely relies on extra module / hardware

**Comment by I-am-druny** [comment]
I'll keep it as an option. next step is that i root my phone to unlock apps like kodi and vanced youtube for android auto. if that works, I'm more than happy

**Comment by I-am-druny** [comment]
can ddt4all unlock rlink apps that you can normally buy in the rlink store? there was an app that lets you see the 4control work in real time but it isn't available anymore. actually I can't find any apps for my car in the rlink store

**Comment by AndyIreland** [comment]
> can ddt4all unlock rlink apps that you can normally buy in the rlink store? there was an app that lets you see the 4control work in real time but it isn't available anymore. actually I can't find any apps for my car in the rlink store

Not sure about the apps for the Laguna 3 sorry , because the rlink 1 in my car is Zoe EV and there are loads  of different apps for that , but EV related

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
