### ISSUE TITLE
I Have A Problem : "0 Loaded Ecu's"

### ISSUE THREAD

**Issue by Babareis41** [cedricp/ddt4all#387]
Hi,I Have 0 Loaded Ecu's Problem.How Can I Solve It ?

Thanks.

**Comment by tanerdogan** [comment]
Change ELM.

**Comment by Babareis41** [comment]
Reis senin kullandığın ve çalışan varsa linkler misin

**Comment by tanerdogan** [comment]
Senin ELM cihazın çakma çin malı değil dimi? Bundan eminsen ecu.zip indirmen lazım, bu program tek başına çalışmaz. ecu.zip link: https://yadi.sk/d/-oZOBfV03wTaoQ

**Comment by Babareis41** [comment]
Cihazı iade ettim cihazdandır dediler.Senin kullandığın obd2 cihazı varsa ddt4all uyumlu linkini atabilir misin oradan alayım bir de

**Comment by tanerdogan** [comment]
Ben 2 yıl önce almıştım, çoğu çin malı sahte. Deneyeceksin şansını başka net bi satıcı yoktur. Onlarda çinden çalışıyor diye alıyor, ne sattıklarını bile bilmiyorlar.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
