### ISSUE TITLE
Dacia Duster 2 Headlight problem

### ISSUE THREAD

**Issue by Hopealisko** [cedricp/ddt4all#389]
Hi!
I have a problem.
Now the headlight are on at the same time as the daytime running lights.
How can i change for example, at night only the headlights
Thanks for help

**Comment by EXcomZkko** [comment]
It should be like scandinavian running lights or something like this. On EMM>Lights menu.

**Comment by AndyIreland** [comment]
Hello - try adjusting this value , It accepts 0 or 1 or 2 or 3 in the box. 
I think '0' is no DRL on at all. 
'1' is DRL on daytime and off when headlights on
'2' is DRL on same time as headlights are on
'3' seems to be something to do with 'welcome/goodbye' lighting
hope this helps.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
