### ISSUE TITLE
looking for a step by step tutorial

### ISSUE THREAD

**Issue by redfirebrooks** [cedricp/ddt4all#390]
Hello,
not really an issue but I am looking for a simple and clear tutorial to start with ddt4all and also some clues to found an up to date data base. Thanks in advance.

**Comment by InvalidIP** [comment]
Hello,

 To download one of the latest versions please check here [LaMiaClio](https://lamiaclio.forumcommunity.net/?t=61363606) it's in Italian but if you need you can use Google Translate to translate the whole webpage. 
 For tutorials just use Google or Youtube and search your car + ddt4all word.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
