### ISSUE TITLE
R-Link 2 v9.x not supported?

### ISSUE THREAD

**Issue by funkybag** [cedricp/ddt4all#396]
I have a Kadjar with R-Link 2 running version 9.0.34.611 installed and I cannot use ddt4all. I can connect and scan the car profile but after it hits 100% it just times out and disconnects. I'm trying to enter and display settings of the Audio ECU but it just times out and disconnects. I see profiles for different RadNav systems, but the highest is v3.X. Nothing for v9.X?

Any idea how to solve this?

**Comment by dmitry-up** [comment]
Hello Friend! did you solve this problem?
@funkybag

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
