### ISSUE TITLE
UI/UX: Windows 10, 4K display, button sizes etc

### ISSUE THREAD

**Issue by supaplextor** [cedricp/ddt4all#398]
![image](https://user-images.githubusercontent.com/4638774/83809436-47879200-a66b-11ea-9aab-29d966ee4cce.png)
![image](https://user-images.githubusercontent.com/4638774/83809459-4fdfcd00-a66b-11ea-8d06-2911a82874ec.png)

There's a lot going on within this dialog. I have a bluetooth ELM327 that works okay on Android (Torque Lite). I can barely read the buttons. :) If there's a way to make the text bigger, with a tool-tip explaining what this button does (onhover over button), that'd be perfect.

Thanks!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
