### ISSUE TITLE
Testing with Bluetooth

### ISSUE THREAD

**Issue by valenciakva** [cedricp/ddt4all#4]
Thanks for sharing this.  This is an excelent project.  I am testing this using a laptop with Windows 10 and a Bluetooth ELM327 (Probably a clone) but I am not able to make it work.  I see the ELM327 is paired in bluetooh and two COM Ports are created (COM3 and COM4) but I cannot connect to either of those in the ddt4all software.

I know you recommended an USB ELM327 and W10 is not mentioned, just wanted to check if you have any recommendations.

I can also run this in Linux Mint and try to buy a USB ELM327.

Can you please recommend a USB ELM327 dongle that you know works with the software?  Any additional recommendation to run this in Mint?

Thanks!

**Comment by cedricp** [comment]
Hi, thank you for your participation (and donation!)
Is there any error message in the terminal ? What is the vehicle you are scanning ? (check if it's KWP or CAN protocol) 
About ELM327, you need a real one (not chinese clone) with pic18f25k80 chip (prefer USB version).
I sucessfully tested KW902 too and OBDLinkSX.
Cheers

**Comment by valenciakva** [comment]
Thanks a lot for your answer.  The error message says it is not able to connect so I am almost sure the issue is related to the Bluetooth ELM327 being used since it doesn't work with Torque in Android either. I placed an order for an USB OBDLinkSX and, as soon as I receive it, I will test again.  
Can you please confirm if your tool works in Windows 10?

**Comment by cedricp** [comment]
I tested it on a laptop with windows 10 and it worked. Actually, it should run on XP, 2000, vista (get the winXP branch), Linux and Mac.

**Comment by valenciakva** [comment]
Problem was related to low quality bluetooth ELM327 dongle.  I was using one from China but it is not even connecting to an Android phone.  Issue is now closed.
