### ISSUE TITLE
PyRen Demo shuts down on vers. 09p

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#400]
hi there - when I try demo mode with vers. 09p and select 46 - Clio IV the window shuts down with 
![pyren1](https://user-images.githubusercontent.com/49172217/83982874-f2c17100-a921-11ea-9b42-f99b3cb737b6.jpg)

so just to recap:
I select 09p
![pyren2](https://user-images.githubusercontent.com/49172217/83982914-374d0c80-a922-11ea-87f3-d86f6834bc2e.jpg)

I select  DEMO then 46 Clio IV
![pyren3](https://user-images.githubusercontent.com/49172217/83982973-9874e000-a922-11ea-8bc8-c394a5428907.jpg)

then it exits to this screen:
![pyren1](https://user-images.githubusercontent.com/49172217/83982994-bd695300-a922-11ea-999d-5ebb2fb1679e.jpg)

@shrlnm  @cedricp  and any others that may be able to help please?

**Comment by Marianpol** [comment]
It's normal, becouse you have selected demo mode.
What do you want to do? Explore all car files or a particular one?
If you want to view module file in demo you need find it's ID and enter it in the Other options input e.g:
-e 10779,11069
IDs can be found in TCOM file (for CLIO IV it's TCOM_155.xml) in the PyRen_home_dir/Vehicle/.
If you want to load all files of a car you need to update pyren and then instead of module IDs you put TCOM file number e.g:
-e 155

**Comment by AndyIreland** [comment]
> It's normal, because you have selected demo mode.
> What do you want to do? Explore all car files or a particular one?
> If you want to view module file in demo you need find it's ID and enter it in the Other options input e.g:
> -e 10779,11069
> IDs can be found in TCOM file (for CLIO IV it's TCOM_155.xml) in the PyRen_home_dir/Vehicle/.
> If you want to load all files of a car you need to update PyRen and then, instead of module IDs, you put TCOM file number e.g:
> -e 155

Thank you for the reply, I shall try all of that. No, its just that I downloaded the 09p file and didnt have the car around at that time and wanted to look at what was new by pressing DEMO. 

See if I press DEMO when ' ./pyren ' is in the version box it started up it goes into demo mode no problem , but when I choose 09p in the version box it just exited out of pyren. 

later on today I shall have the car to test on anyway so I wont be using the demo

**Comment by Marianpol** [comment]
> > It's normal, because you have selected demo mode.
> > What do you want to do? Explore all car files or a particular one?
> > If you want to view module file in demo you need find it's ID and enter it in the Other options input e.g:
> > -e 10779,11069
> > IDs can be found in TCOM file (for CLIO IV it's TCOM_155.xml) in the PyRen_home_dir/Vehicle/.
> > If you want to load all files of a car you need to update PyRen and then, instead of module IDs, you put TCOM file number e.g:
> > -e 155
> 
> Thank you for the reply, I shall try all of that. No, its just that I downloaded the 09p file and didnt have the car around at that time and wanted to look at what was new by pressing DEMO.
> 
> See if I press DEMO when ' ./pyren ' is in the version box it started up it goes into demo mode no problem , but when I choose 09p in the version box it just exited out of pyren.
> 
> later on today I shall have the car to test on anyway so I wont be using the demo

Now I probably understand you. You have already used Pyren before with './pyren' version and now you have downloaded 'new' version './pyren09p' (it's quite old actually) and you cannot explore your previous scanned modules in the demo mode?

If so, just go to pyren_home_dir/pyren/, search for savedEcus.p file and then copy it to pyren_home_dir/pyren09p/.
Now in demo mode you should be able to explore your previous scanned modules.

**Comment by AndyIreland** [comment]
thank you for your help @Marianpol  - so pyren09p is old now? - can you tell me what latest version  is please?

**Comment by gobo-ws** [comment]
@AndyIreland The pyren project can be found at https://gitlab.com/py_ren/pyren

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 nada temos a ver com o pyren rapaz ...
