### ISSUE TITLE
Bad response : ERROR : NO DATA to request

### ISSUE THREAD

**Issue by mbizzaro** [cedricp/ddt4all#401]
Hi Guys,

I'm using ECU TWEAKER V1.81
While writing data I'm getting a bad response message:

Bad response : ERROR : NO DATA to request '3B640F64647C42A90064640AF00AF00AF00AF01964145013EC11940AF014500AF00AF00AF0011E1E070725D401D58105'

Any idea/help/suggestion?
Thank you
Marco

**Comment by djsweat** [comment]
Yes, usually the Bluetooth module receives a lot of data and desicronisation occurs, you need to use a WIFI (not tested) or USB device,
Regards.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
