### ISSUE TITLE
Bosch Failure = Dfp_PFltTempPre_mp

### ISSUE THREAD

**Issue by Cliveski2004** [cedricp/ddt4all#402]
Hello people,
My 2009 Laguna Coupe 2.0 dci 180bhp GT is failing to regenerate it's DPF.

My DDT4ALL gives me the following error code:
Dfp_PFltTempPre_mp
(status bosh 1 = 96).

I'm not 100% certain if this is the pre turbo temperature sensor or the pre DPF temperature sensor? Can anyone confirm? 

Thank you, Clive

**Comment by Cliveski2004** [comment]
Is there a list of error codes with their full word meaning anywhere?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
