### ISSUE TITLE
Calibration for edc megane4

### ISSUE THREAD

**Issue by mozcengel** [cedricp/ddt4all#406]
hello how to do edc gear calibration for megane 4?  can you help me about the steps

**Comment by tanerdogan** [comment]
Did you find the correct page under AT ecu? If not, look again all parameters... There is a steps available, i am not sure its works or not but its assist you well. Good luck.

**Comment by cvjensen** [comment]
@tanerdogan what is AT ecu ? I need help calibrating my megane 3 edc.

**Comment by AndyIreland** [comment]
> @tanerdogan what is AT ecu ? I need help calibrating my megane 3 edc.

AT normally stands for automatic transmission ... IE not manual gears

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
