### ISSUE TITLE
How to make the blinker noise higher

### ISSUE THREAD

**Issue by robertalks** [cedricp/ddt4all#407]
Hello, since I got my R-link2 upgraded to version 7, when I put my blinkers on, I can't really hear them, always have the impression it's not on. Any ideas how to set the 'volume' higher?

**Comment by robertalks** [comment]
Nobody, really?

**Comment by tomidix** [comment]
You should be able to define that in the Rlink2 "User settings" menu:
https://world.e-guides.renault.com/sites/default/files/statics_pdfs/MUL/R-Link2-NX1062_ENG.pdf

Page: 6.22

**Comment by robertalks** [comment]
> You should be able to define that in the Rlink2 "User settings" menu:
> https://world.e-guides.renault.com/sites/default/files/statics_pdfs/MUL/R-Link2-NX1062_ENG.pdf
> 
> Page: 6.22

Yeah, that worked 👍

**Comment by robertalks** [comment]
closing
