### ISSUE TITLE
Renault Megane 4 "diag has been set invalid value gen1_1 " Error 

### ISSUE THREAD

**Issue by Flavius08** [cedricp/ddt4all#408]
Hi group I also have a problem if someone can help me I would be grateful.  I entered Developer mode and changed 2 settings (first picture) to both it wrote disabled and I set as in the first picture, SPORT and COMFORT and after I saved and restarted the radio I got an error (picture 2) and  I can't do anything anymore, please if anyone can help me.
![20200621_000656](https://user-images.githubusercontent.com/67219974/85219573-58434200-b3a5-11ea-8718-b9868a06aa7c.jpg)
![20200620_182420](https://user-images.githubusercontent.com/67219974/85219575-5f6a5000-b3a5-11ea-890c-46746a624159.jpg)

**Comment by Joakim02** [comment]
Hello, did you solve your problem?

**Comment by Flavius08** [comment]
Yes, I reset the system with a diagnostic device. I don't know exactly how I did it with my uncle.I had 3 diagnostic devices but only one worked

**Comment by Joakim02** [comment]
OK thanks you.

**Comment by sallythe** [comment]
> Yes, I reset the system with a diagnostic device. I don't know exactly how I did it with my uncle.I had 3 diagnostic devices but only one worked

hi Flavious08 am having the same trouble as you can you tell how to remove it. thanks

**Comment by sallythe** [comment]
hi Flavious08 am having the same trouble as you can you tell how to remove it. thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by firatkacmaz72** [comment]
I HAVE THİS PROBLEM TOO PLEASE HELP ME

**Comment by gontsendala8-rgb** [comment]
Hi anyone who was able to reset

**Comment by karim03-afk** [comment]
![Image](https://github.com/user-attachments/assets/62d8282f-b2d3-4f47-bfea-09f213fb4b07)
Bonjour à tous j’ai ce problème là pouvez vous m’aider s’il vous plait j’ai tout essayer (débrancher la batterie, les fusibles éteindre l’écran ect..)
