### ISSUE TITLE
Changing WAC Jingle

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#411]
hello all - anyone got any ideas how to change the WAC (walk away config) Jingle/bleep? - i can disable it in another screen but I dont want to do that I just want to change the Hz so it will change the tune when the car locks when I walk away and the car locks. I have looked in the manual command in DDT4ALL and it cannot be changed in that either. Thanks.
![wac](https://user-images.githubusercontent.com/49172217/86156737-547a9280-bafe-11ea-88fe-91d0fc9a39af.jpg)

**Comment by JABICHOCU** [comment]
Same story here on my 2013my Captur, I have the option of turning it off but nothing like changing sound level as in the parking system buzzer

**Comment by JABICHOCU** [comment]
I don´t see any way of changing this 
![hfm walk away chime](https://user-images.githubusercontent.com/66420341/87912144-20dfb800-ca6d-11ea-9215-67dfd60d9220.jpg)

**Comment by JABICHOCU** [comment]
Hello again ,AndyIreland...any advances on this one?  As I said before, there´s no way on my car to change those parameters. On the configuration section of the HFM module I have this options...do you know what they do? regards
![12](https://user-images.githubusercontent.com/66420341/194750652-c93e2e63-790a-411a-be3f-7d87efefc821.jpg)

**Comment by AndyIreland** [comment]
> Hello again ,AndyIreland...any advances on this one? As I said before, there´s no way on my car to change those parameters. On the configuration section of the HFM module I have this options...do you know what they do? regards ![12](https://user-images.githubusercontent.com/66420341/194750652-c93e2e63-790a-411a-be3f-7d87efefc821.jpg)

no further forward in changing the parameters - only think they can be read . I am not sure if you can manually change using one of these buttons in DDT4ALL on the top bar:

![image](https://user-images.githubusercontent.com/49172217/194757503-7d177f03-2f85-4d20-bca1-60e68499d628.png)

WAC - is walk away config - if you were to set that to 'false' then the 'blip blip' sound will be disabled as you walk away from the car.

VSC stands for 'keyless vehicle' 

not sure what the other settings do so I didnt even attempt to change them just in case an error.

I dont think any of them changed the actual sound of the 'blip blip' tune though

**Comment by KarelSvo** [comment]
If the sound element is a bugle like the Duster II, it cannot produce a melody.

**Comment by JABICHOCU** [comment]
It´s a pity...besides being too loud, I think it is too long as well. Thanx anyway

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
