### ISSUE TITLE
Start-stop inhibition 

### ISSUE THREAD

**Issue by JABICHOCU** [cedricp/ddt4all#413]
Hello to all of you, I´ve seen that on many cars it ´s possible to access "STOPSTARTINHIBIT" on the BCM  by changing configuration on "GEE" options...but I don´t have this on my BCM :-1: 
![imagen](https://user-images.githubusercontent.com/66420341/87221441-50573c00-c36c-11ea-8ce7-a8b9266692d3.png)

On my 2013 Captur , I have found  a similar thing on  EMM_EDISON_DDT2000_SW11_1_V1_6_3  with these  options in the "alternator management" section

![imagen](https://user-images.githubusercontent.com/66420341/87221543-0884e480-c36d-11ea-90fb-6fa775b3a058.png)

Will this be the way to inhibit S&S ??? I have fear of bricking the module by doing this...any help would be much appreciated, thanks :+1:

**Comment by JABICHOCU** [comment]
No ideas?? @Pakoto...where are you??? :)

**Comment by pakoto** [comment]
EMM = lights controller
What is your BCM? t4....

**Comment by JABICHOCU** [comment]
Hello Pakoto...good to see you around here. This is my BCM >
![imagen](https://user-images.githubusercontent.com/66420341/88054517-ce31f900-cb5d-11ea-98f2-cb15bd654b78.png)

But this options I see them on the EMM module

**Comment by KarelSvo** [comment]
Better to deactivate the stop start in the engine control unit.

**Comment by JABICHOCU** [comment]
> Better to deactivate the stop start in the engine control unit.

Hello Karelsvo, can you tell me which module is the control unit on Captur x87?

**Comment by AndyIreland** [comment]
if you have not got it listed in your ECU then what can you do apart from changing the BCM module to a later one or try and update the SW11 to a later software number (if that is even possible) 
Thats why I said in your other post , why not remove the stop & start lead off the 12v battery under the bonnet then extinguish the warning light and message on the dash about stop start ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
