### ISSUE TITLE
Changing buzzer sound level on parking system

### ISSUE THREAD

**Issue by JABICHOCU** [cedricp/ddt4all#416]
Hello to you @ll again, I´ve been researching on how to change buzzer sound on my 2013 Captur cause it´s always been a bit loud and distorted. On my UPA parking system unit (original one by Valeo) I´ve managed to find these options>

![imagen](https://user-images.githubusercontent.com/66420341/87654463-3b591f00-c757-11ea-9db1-384bf82fb714.png)

As you can see it says "buzzer sound index=LEVEL 3" I´ve changed this to other levels to see if it works but it doesn´t change the sound...any ideas on this one??

**Comment by ulasatar** [comment]
it doesn't matter.
Make cfg.BuzzerFrequency.Reardetection====1000hz. 
This will increase the volume a little

**Comment by JABICHOCU** [comment]
OK, but it is the opposite.I want to decrease the volume!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
