### ISSUE TITLE
DDT4ALL for all cars doesn't show x54 Safrane - how to add it ?

### ISSUE THREAD

**Issue by telemach1337** [cedricp/ddt4all#417]
I am using 

ddt4all All cars.exe (20.07.2019). Version 5.5.0 with database 09/07/2019

it has Megane, Scenic, Laguna I but there is no Safrane

can you add it or guide me which one version of DDT4ALL has support for Safrane 96-00 ?

**Comment by KarelSvo** [comment]
For model code X54, the ddt2000 database contains only one motor ecu type MP 7.0 and a defective file for Bosch ABS 5.3.

**Comment by telemach1337** [comment]
OK but at least I can choose Safrane in DDT2000 and make some changes

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
