### ISSUE TITLE
Scanning Adress Injection issue

### ISSUE THREAD

**Issue by MouadSoufiani** [cedricp/ddt4all#419]
Hi, 

I'm using my ddt4all on my Megane 3 and it works perfect! I got today an Clio 4 from 2017 and connected it to DDt4all. I did the autoscan and got the options to scan the ecu or kfw (or something like that).

The scan didnt complete because of an error. This is the error:

CAN scannen
Found ECU (not perfect match) :Cluster X98_X87_X82_xHA_X98ph2_X87ph2_v7.5 DIAGVERSION [28] SUPPLIER [ANC] SOFT [0062] VERSION [2005 instead 1000]
Identified ECU : X98_X87_CAMAN_V4_2_20161025T110618.json DIAGVERSION [8]SUPPLIER [950] SOFT [0001] VERSION [0707]
Identified ECU : X98_X87_CAMAN_V4_2_20161025T110618.json DIAGVERSION [8]SUPPLIER [950] SOFT [0001] VERSION [0707]
Identified ECU : CAMAN_X98-X87_V4_1_20120316T121340_20150409T143110.json DIAGVERSION [8]SUPPLIER [950] SOFT [0001] VERSION [0707]
Identified ECU : CAMAN_X98-X87_V4_1_20120316T121340_20150409T143110.json DIAGVERSION [8]SUPPLIER [950] SOFT [0001] VERSION [0707]

on python i got this:

1849 ECU's in database geladen.
Scanning address ECU Cluster/TdB
Scanning address ECU Climatisation
Skipping CAN extended address (not supported yet)  D2
Scanning address ECU Injection
Traceback (most recent call last):
  File "C:\Program Files (x86)\ddt4all\ddt4all.py", line 92, in scanselvehicle
    self.parent().parent().scan_project(project)
  File "C:\Program Files (x86)\ddt4all\ddt4all.py", line 561, in scan_project
    self.scan()
  File "C:\Program Files (x86)\ddt4all\ddt4all.py", line 617, in scan
    self.ecu_scan.scan(self.progressstatus, self.infostatus)
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1536, in scan
    if not self.identify_new(addr, label):
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1483, in identify_new
    self.check_ecu2(diagversion, supplier, soft, soft_version, label, addr, "CAN")
  File "C:\Program Files (x86)\ddt4all\ecu.py", line 1651, in check_ecu2
    delta = abs(int('0x' + tgt.version, 16) - int('0x' + version, 16))
ValueError: invalid literal for int() with base 16: '0x7M00

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
