### ISSUE TITLE
Invisible commands in dd4all

### ISSUE THREAD

**Issue by Banana009** [cedricp/ddt4all#42]
I noticed that there are many commands in .xml files that are not visible on the Screen. For example this one: Is possible to read/write this parameter LDW_LKA.LDW_LKA_SelectionState_memorized ?
![ldw_activation_state](https://user-images.githubusercontent.com/35255691/37313887-7afa7130-2651-11e8-8981-fee45b51b7cc.JPG)

**Comment by cedricp** [comment]
That should be possible, but you need to find the requests that read/write that data item before.

**Comment by Banana009** [comment]
And how? I did not find this option in Screen menu.

**Comment by Banana009** [comment]
Can I send/read a command directly from the bookmark Requests?

**Comment by cedricp** [comment]
Unfortunately not, you must build a screen with parameters/buttons.

**Comment by Banana009** [comment]
Would it do the next version of ddt4ll ? It would be very useful. :-)

**Comment by Banana009** [comment]
How to add a write button?  According to your instructions, I have only a command, I can not read and write to the ECU.  See:  
![test_buton](https://user-images.githubusercontent.com/35255691/37374689-8bc0a446-271c-11e8-840f-b8d8a488889e.JPG)
Thanks for the help

**Comment by Potty06** [comment]
Do you found somthing for puddle lights?(wing mirror lights)? I want to activate it

**Comment by cedricp** [comment]
Go to the screen, enable "**UI EDIT**", right click on the screen -> "**add button**"
Go to button tab, select the request you want to send (_LDW_LKA.LDW_LKA_SelectionState_memorized_) and click "**ADD**"
Save your file, then reopen the app in connected mode, and you should be OK

**Comment by cedricp** [comment]
You can use the plugin system to do it also, but it's a bit more complicated

**Comment by Banana009** [comment]
I will try the first way.  :-)
By the way, why are not all commands in the Screen with buttons for read/write to the ECU?

**Comment by cedricp** [comment]
Because the request must be tagged "manual" in the request spreadsheet (last column).

**Comment by Banana009** [comment]
I can not open it in the Connected mode. Screens are empty. In the Edition mode I can save an ECU just  like .jcon .
There is only this option. I created testing ECU, see here: 
![test_myecu](https://user-images.githubusercontent.com/35255691/37434075-ae63d334-27de-11e8-9677-89c3d592f4e3.JPG)

**Comment by arifcalhan** [comment]
![emniyet kemeri](https://user-images.githubusercontent.com/48242282/53803523-1004d400-3f56-11e9-8fc7-fed37b48f823.png)
iyi günler ustatlar emniyet kemeri sekmesini nasıl aktif hale getirebilirim yardımcı olurmusunuz?

**Comment by xormail** [comment]
Hi, I am trying to edit, but I just says:
To be able to edit your screen, first export it in JSON format

So I go File-Save current ECU-> give name, Save and no change. Also the Requests and Data tabs are "locked". Thanks

**Comment by cedricp** [comment]
You need to convert your database in JSon format, go to File->Zip database. It's a long process...
Once done, you should find an ecu.zip file. Remove ecu directory (the one containing XML files) and you're done. You can now edit requests/data/screens.

**Comment by arifcalhan** [comment]
yorumlarınız için teşekkür ederim fakat yapamadım json dosyasını oluşturup mail olarak paylamanız mümkün olabilir mi? cluster b95 L38 ph3 V192 fluence(x38) mail adresim ( arifcalhan@hotmail.com ) şimdiden çok teşekkür ederim iyi günler

**Comment by Furtif** [comment]
seem a stuff but not a issue move question to https://github.com/cedricp/ddt4all/discussions
