### ISSUE TITLE
BCM/UCH Editing

### ISSUE THREAD

**Issue by ustunkaya07** [cedricp/ddt4all#422]
Hi all.
I want to edit my BCM/UCH Ecu. I want to activate Remote Engine Start. I edited BCM/UCH ecu's json files and create a new ecu but if i try to enter the menu, this menu meet me. has anybody an idea to fix the problem?
![res ddt4all](https://user-images.githubusercontent.com/65688723/88465180-957d8100-cec9-11ea-9301-2f6c4c3700d5.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
