### ISSUE TITLE
The renault Zoe parameters are all in french!

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#424]
My french is almost non existant - I can use Google translate but its very time consuming and may not even give correct translation . 

I want to turn off the notification that says '0' rear seatbelts connected on the TFT screen of the Zoe when you first start up. - I am pretty sure it can be done . 

So I go into cluster/TDB
Then Ecran configuration
Then config General 01 

but then what?

I can see the inhib SBR_av but I think that just the inhibit front SBR reminder beep 

Any help please?

@cedricp  - and others 
![zoe cluster config](https://user-images.githubusercontent.com/49172217/88741731-50ab5180-d138-11ea-896d-193b82199306.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
