### ISSUE TITLE
Virgin Mode Renault IV GTline

### ISSUE THREAD

**Issue by Emaromao123** [cedricp/ddt4all#425]
Good  Evening,

Im trying to solve my problem with RLINK 2.

I've pressed the "Virgin Mode" Button on the Developer side menu, wrongly.

Now how can i solve this? There is some way to fix without going to Renault?

Maybe with dt4all? I have Black screen, no radio and no lights on Doors inside.

Thank you.

**Comment by tomidix** [comment]
You can try this:
https://gitlab.com/py_ren/pyren/-/wikis/how-to-rlink2-black-screen

**Comment by Emaromao123** [comment]
> You can try this:
> https://gitlab.com/py_ren/pyren/-/wikis/how-to-rlink2-black-screen

I've tried before and nothing happens... 
I'm using elm 327 USB for now, with Bluetooth I can't connect. When I execute the macro choosing all the different available nothing happens.. Any idea how I can solve this? With Dt4all it seems that can open the app but I can't conect to the elm.

Thank you

**Comment by maddpower** [comment]
Have you fixed the problem?
I'm on the same boat...I don't know how to fix this.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by stocky777** [comment]
> You can try this:
> 
> https://gitlab.com/py_ren/pyren/-/wikis/how-to-rlink2-black-screen

Where are the files?

**Comment by AndyIreland** [comment]
I didnt think clio 4 came with an r-link 2 - thought clio 4 came with medianav / medianav evo / rlink1 or medianav2 ?
Are you sure its rlink2 have you a picture of it?
