### ISSUE TITLE
DiagRw_car the car appears as Eletric

### ISSUE THREAD

**Issue by kellvembarbosa** [cedricp/ddt4all#426]
Follow this tutorial to upgrade the R-link 2.2.19.300 to 3.3.x

https://www.foroclub.es/megane4/viewtopic.php?f=420&t=20311

My update was simple, at first everything was fine, but I went to update the value of the reverse camera lines and from there everything was strange.

- My start / stop no longer works, the green icon appears in the speed panel but does not turn off.
- Strangely in DiagRw_car the car appears as Eletric

Here is an image, can anyone help me finish the setup? Otherwise, apparently everything is working ...

Since I'm a new user I can't post photos, follow the link to see how it looks in developer mode:
https://i.postimg.cc/05d8trMG/Whats-App-Image-2020-08-01-at-17-42-23.jpg

Can you tell if this could damage my car?

He's a Megane IV 11/2016 Sport Tourier Diesel

@cedricp help

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
