### ISSUE TITLE
PB Bluetooth Megane IV

### ISSUE THREAD

**Issue by spchl12** [cedricp/ddt4all#427]
Hello, 

since I made an auto configue of my R-LINK 2 in V8 with Canclip 198 and DVD reprog 185 I lost the sound of the calls in reception and transmission in bluetooth, I tried the macros as mentioned in the answers # 115 the macro works but that doesnt fix the problem, if you could help me.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
