### ISSUE TITLE
Scan but no show any ecu's

### ISSUE THREAD

**Issue by ghost** [cedricp/ddt4all#428]
Hi i recently download ddt4all and I have the elm327 conector, I run ddt4all and run a can scan to identify my car ecu's, on the log show's the ecu's found but the program just freeze and does't show the ecu's and the only way its close it. can someone orient me what's wrong? I download the windows installer from here and paste the new patches but keeps the same

**Comment by AndyIreland** [comment]
have you tried download from here and should have all the ecu lists  - select 'all cars' 
https://www.drive2.ru/b/498093336985338243/

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
