### ISSUE TITLE
où est ce bouton?  // where is this button?

### ISSUE THREAD

**Issue by aldomic** [cedricp/ddt4all#429]
Je n'ai pas pu voir où se trouve ce bouton. Quelqu'un le sait-il?

I couldn't see where this button is. Does anyone knows?

![dsgv](https://user-images.githubusercontent.com/69316747/89555289-87f4bf00-d818-11ea-9a28-b8dfda036c4f.jpg)

**Comment by KarelSvo** [comment]
![sgw](https://user-images.githubusercontent.com/30380693/89674538-9dd1b500-d8e8-11ea-9a1a-258347daa4e6.png)

**Comment by aldomic** [comment]
Which devices does ddt2000 work with?

**Comment by KarelSvo** [comment]
https://i.ebayimg.com/images/g/hycAAOSwsdtdvEt8/s-l500.jpg

This button only works if you have a accredited access to the Renault server.
