### ISSUE TITLE
Megane 3 - External Temperature Display on Cluster

### ISSUE THREAD

**Issue by johnroberts2k** [cedricp/ddt4all#432]
Does anyone know if it's possible to display the external temperature on the cluster on a Megane 3? If so, where do I find the config parameter? What about the clock and time too?

**Comment by Marianpol** [comment]
![clock](https://user-images.githubusercontent.com/35842708/89711648-cf4f8c80-d98b-11ea-94d8-4a88f4a0e51a.png)

**Comment by charliehoward** [comment]
I would also like to know this, tried a few times to get it on my 265 but haven't got it working

**Comment by AndyIreland** [comment]
I think after making a change you might have to press the #prise en ...~ button at the bottom 
![prise button](https://user-images.githubusercontent.com/49172217/90337559-2207f480-dfdb-11ea-8e24-61702e0fe513.jpg)

**Comment by charliehoward** [comment]
All of my other settings have worked fine, might try it again though

**Comment by fparmentier** [comment]
This is not working on older cluster types.
Like mine, its from 2010 and doesnt' support it :(

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
