### ISSUE TITLE
Which Ecu's

### ISSUE THREAD

**Issue by MouadSoufiani** [cedricp/ddt4all#437]
Is there an external possiblity to know which ecu's my car have? Without using the magnifying glass? Would it be possible with Pyren?

Thanks!

**Comment by AndyIreland** [comment]
yes PyREN has a scan facility where you can scan for ecus - the android port of ddt4all called ecutweaker should be able to find the ecu's too

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
