### ISSUE TITLE
Help please!! How to release the rear pads (Electric handbrake) of Megane 3?

### ISSUE THREAD

**Issue by aliloup85** [cedricp/ddt4all#440]
please, someone can help me to activate the maintenance mode on rear brake pads on Megane 3 with DDT4ALL? 

Thanks a lot.

**Comment by BarektE** [comment]
gönder mail adresini tarif edeyim

**Comment by aliloup85** [comment]
> gönder mail adresini tarif edeyim

Mouhammedali on my Gmail address. Thanks a lot.

**Comment by BarektE** [comment]
mouhammedali@gmail.com adresine nasıl yapacağınızın tarifini gönderdim

**Comment by BarektE** [comment]
Where I marked the number 1, press start, the lining will be released, after replacing the lining, the number 2 is pressing the start.

**Comment by aliloup85** [comment]
> Where I marked the number 1, press start, the lining will be released, after replacing the lining, the number 2 is pressing the start.

Thanks so much 🙏🙏🙏🙏🙏

**Comment by avramg** [comment]
Hi can send to me also the procedure
thanx 
avram_gigel@yahoo.com

Best Regards

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
