### ISSUE TITLE
Engineering of the 1940s 

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#441]
**Off topic but important**

Engineering of the 1940s made a slide motor. 
Year 2020, greetings to the engineers 
who removed the bumper to change headlights.
ights. BarektE

![kızaklı](https://user-images.githubusercontent.com/43322396/90486827-3a465380-e142-11ea-888a-6aba2e432efb.jpg)

**Comment by AndyIreland** [comment]
you could even take out the headlamps easily in that too!

**Comment by BarektE** [comment]
> farları bile kolayca çıkarabilirsin!

Front bumper for fog lights and daytime running lights cannot be installed without removing.

Also, I didn't mean just the Renault group, it applies to all brands. ;)
