### ISSUE TITLE
Search/reading does not return complete set of options

### ISSUE THREAD

**Issue by DrFsn** [cedricp/ddt4all#443]
Hi all,

I would like to ask for some help, trick, what can be the problem or what am I doing wrong ... The base problem is, that once I click on magnifying glass, in the middle section, I do not receive all the options as I should it. Two different ELMs were used, same result. 

I managed to activate Android auto without any problems, but I have to manually chose car, ‘Navigation’ - ‘MFD v4.6’ - ‘[ Navigation ] MFD v4.6’ - ‘Configuration’ ‘13 - ECU Configuration’. For other setting, like EMM, after manual selection it returns no data. Expected, as also magnifying glass does not find it in previous step …

Logs and PrtScrs attached. Thanks for any help. 
Dan

![search_no_full_result](https://user-images.githubusercontent.com/70209805/91178068-ea88fe80-e6e4-11ea-9227-3ebe4bf054cc.png)
![ManualSelection-NoData](https://user-images.githubusercontent.com/70209805/91178108-fa084780-e6e4-11ea-8e67-c6ab1453926a.png)
[log_file.txt](https://github.com/cedricp/ddt4all/files/5123893/log_file.txt)

**Comment by DrFsn** [comment]
And this is how the search result should look like (marked with green on some PrtScr from web) …

![search_result_should_be_like_that](https://user-images.githubusercontent.com/70209805/91178524-861a6f00-e6e5-11ea-9f29-838b8425ef74.jpg)

**Comment by BarektE** [comment]
You are probably opening the ddt4all program in a demo jacket.


![Ekran Alıntısı](https://user-images.githubusercontent.com/43322396/91288891-347fec00-e79a-11ea-83e2-f7c40ce5fe4c.JPG)

**Comment by DrFsn** [comment]
Thx, but nope, this is not the case. I used Connected mode and as I explain above, I manage to change Android Auto settings … Any other idea, are there any more useful logs to check?

**Comment by xmenmaxx** [comment]
Hello,

I also have the same problem with a Kadjar 2016, I tried with two different OBD v1.5 interfaces and the result is the same, I don't realize what it could be, I use the latest database that is installed with ddt4all 5.5.0.
#cedricp, can you help us please?
Thanks in advance!
![ddtkadjar](https://user-images.githubusercontent.com/18633889/91457280-d97af180-e88c-11ea-88b0-54dd80b0313f.jpg)
![error](https://user-images.githubusercontent.com/18633889/91457329-e7307700-e88c-11ea-9e5a-67009a72fef5.jpg)

**Comment by DrFsn** [comment]
Can be engine related? What kind of engine do you have @xmenmaxx? Mine is 1.6 dci, 130 PS ...

**Comment by xmenmaxx** [comment]
> Can be engine related? What kind of engine do you have @xmenmaxx? Mine is 1.6 dci, 130 PS ...

I also have 1.6 dci, 4x4, 130 hp

**Comment by KarelSvo** [comment]
> Hello,
> 
> I also have the same problem with a Kadjar 2016, I tried with two different OBD v1.5 interfaces and the result is the same, I don't realize what it could be, I use the latest database that is installed with ddt4all 5.5.0.
 


The latest Ecu database is from July 2020. But Renault does not update the Autoident data in the Ecu files.
Therefore there is no match for many ecus.

**Comment by xmenmaxx** [comment]
> For green results you must to add the data manually.

How can I do this? I am a beginner in using ddt4all ....

**Comment by xmenmaxx** [comment]
> The latest Ecu database is from July 2020.

@KarelSvo  where can I find the latest database?

**Comment by DrFsn** [comment]
The point (in my case) is, that there are no or at least not all of expected “green results”. After manual navigating to some section, there is "no data" information. As I understand expected, as even “search” did not find it …

Not sure about database, my car is model year 2015, this engine is available at least from 2013 and my database is 2019, so that need to be covered or is there any other explanation?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
