### ISSUE TITLE
Wrong response on force DPF regen request

### ISSUE THREAD

**Issue by aspx1981** [cedricp/ddt4all#444]
Dear All,

I'm trying to force the DPF regeneration but I got a WRONG RESPONSE: NR Conditions Not Correct OR Request Sequence Error.
![clio](https://user-images.githubusercontent.com/70290029/91348323-e1328b80-e7e3-11ea-923d-0ceda78e0a15.PNG)

Thanks,
Bye,

Alessandro.

**Comment by pakoto** [comment]
Try with pyren or pyclip.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
