### ISSUE TITLE
how can i activate gear shift light in dacia ??

### ISSUE THREAD

**Issue by rachidoooo** [cedricp/ddt4all#449]
thanks to answer me about how can we activate gear shift light for dacia by ddt4all

**Comment by pakoto** [comment]
![Capture](https://user-images.githubusercontent.com/24203270/91756390-f6852c80-ebcc-11ea-96b9-949e99dead14.JPG)

**Comment by rachidoooo** [comment]
Thanks you so mutch
Please if you have a document of description of ddt4all options send me it.

Thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
