### ISSUE TITLE
Installing a ECU from one car to another

### ISSUE THREAD

**Issue by johnroberts2k** [cedricp/ddt4all#450]
When installing a used ECU like a UCH or UPC or DCM etc, when querying that ECU with CLIP it actually shows the original VIN number of the car that it came from. Although it works and everything the VIN seems to be programmed into every ECU. Just wondering if there is a way in ddt4all to change a vin on these ECU's so I can have it matching my car?

**Comment by shrlnm** [comment]
@johnroberts2k not all ECU allows to change their VIN. Some of them require special configuration reset before changing

**Comment by johnroberts2k** [comment]
@shrlnm I am looking at the UPC ECU, I swapped out my UPC for another one from a salvage scrap. The new one seems to be working and everything but if I read the VIN number from the configuration of that ECU it displays the other cars VIN number. Do you know if the UPC VIN number can be changed?

**Comment by cedricp** [comment]
Which car and ecu model is it?

**Comment by johnroberts2k** [comment]
> Which car and ecu model is it?

@cedricp it's a Megane 3, the ECU is "UPC - USM 95 BDKE - Sot C2/C3/C4 v3" that's the one that gets detected as green when I scan or ECU's

**Comment by cedricp** [comment]
If you use DDT4All in edit mode, you can find the write VIN command : 
![vin_frame](https://user-images.githubusercontent.com/5940937/92086756-e9ce2780-edca-11ea-94a0-eb1fe768491b.png)
You can see '3B81' is the command to do it, replace the remaining zeros with you VIN/CRC (I think you can get it from another ECU, or recalculate it)
Then, with the manual command button (0x), write your car's VIN.
![vin_write](https://user-images.githubusercontent.com/5940937/92087149-72e55e80-edcb-11ea-8ffb-6db2edace28c.png)

**Comment by pakoto** [comment]
Renolink have a separate option to change VIN to ECUS. Is difficult to add into ddt4all? Thanks

**Comment by cedricp** [comment]
That could be possible, but I'm very busy with other stuff right now to improve it.

**Comment by pakoto** [comment]
![Capture](https://user-images.githubusercontent.com/24203270/92089300-41ba5d80-edce-11ea-8a4d-79e7601404a1.JPG)

**Comment by johnroberts2k** [comment]
@cedricp thanks for that. I am fairly new to ddt4all. I've been able to make configuration changes but the instructions above i am a bit lost. You mentioned to run ddt4all in edit mode, is that the expert mode? I don't see any of those tabs like Request etc, not sure if its because i'm running in Demo mode outside the live environment. And what exactly is the CRC?

**Comment by cedricp** [comment]
You can start the app with 2 modes (connected or edition), maybe you're running an old version...
The CRC is a code generated from VIN to ensure its validity. Give me your VIN, I'll send you the command to send.

**Comment by johnroberts2k** [comment]
@cedricp the only options I see when DDT4ALL is loaded is Connected Mode, Demo and ELM Benchmark. I don't see edition. My version says: Version 5.4.0 ALL CARS Edition (Database 11/02/2019). Is this out of date version and what about the database version? Can I email me my VIN as I don't feel comfortable putting it on a public chat? Thanks.

**Comment by BarektE** [comment]
![DDTT](https://user-images.githubusercontent.com/43322396/92684086-49818100-f33d-11ea-8a8d-55ffaef8863b.PNG)

**Comment by TA1988** [comment]
Hi, I need to replace a faulty UPC ECU with a used one on a Renault Captur (X87): which ECU should I use to rewrite the VIN and CRC? Thank you!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by aslanbey8371** [comment]
> ![Capture](https://user-images.githubusercontent.com/24203270/92089300-41ba5d80-edce-11ea-8a4d-79e7601404a1.JPG)

hi help crc code
