### ISSUE TITLE
Cannot find HANDFREE_DISABLE_AFTER_RKE_CF setting for Renault Zoe

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#451]
Hello , I dont know if I am looking in the wrong place or just cannot find it or its just not there but I cannot find the HANDFREE_DISABLE_AFTER_RKE_CF setting for my 2013 Renault Zoe - have looked all in doorlock area and BCM and cannot find it. 
I want to be able to open the doors always by handsfree and not have the feature break when I use button on keycard . Managed to do it on a Clio mk4 but cannot find it for the renault zoe. 
Any ideas please?

**Comment by BarektE** [comment]
Я сподіваюся, це працює для вас. Якщо ви не можете знайти блоки, я надішлю їх електронною поштою


![handes](https://user-images.githubusercontent.com/43322396/92685620-cbbf7480-f340-11ea-979f-cf36c3281e65.PNG)

**Comment by BarektE** [comment]
Я сподіваюся, це працює для вас. Якщо ви не можете знайти блоки, я надішлю їх електронною поштою

![handes](https://user-images.githubusercontent.com/43322396/92685966-6cae2f80-f341-11ea-969c-dd4990dfa690.PNG)

**Comment by AndyIreland** [comment]
> Я сподіваюся, це працює для вас. Якщо ви не можете знайти блоки, я надішлю їх електронною поштою
> 
> це не спрацює, якщо немає антени.
> 
> ![handes](https://user-images.githubusercontent.com/43322396/92685966-6cae2f80-f341-11ea-969c-dd4990dfa690.PNG)

Thank you @BarektE for the reply - yes I found that setting when I was trying and it was set to 'With' already ... but it still breaks the handsfree feature if I choose to open or lock the door with the keycard button until I put the keycard in the slot and start the engine to reset handsfree again. 
In clio mk4 ecu it was a setting saying something like "disable RKE after button press" and then i chose 'disabled' but I just cannot find it in any of the Zoe ecu's

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by xspawn86** [comment]
If you use Ecu tweaker try  "Hand Free Module / Access By Switch / Access By Switch - Configuration"
