### ISSUE TITLE
Quelqu'un connaît la procédure de reprogrammation R-LINK?

### ISSUE THREAD

**Issue by aldomic** [cedricp/ddt4all#455]
Quelqu'un connaît-il la procédure de reprogrammation R-LINK nouvellement achetée / non utilisée?

J'ai le programme et le périphérique CLIP, et R-usb Reprog.

**Comment by AlMeu** [comment]
A complete new unit and clean can be written and configured with any CanClip, Ddt4all, DDT2000, RenOLink.
But one took from a donor car no chance.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
