### ISSUE TITLE
OBDLink MX+ connect to multimedia can

### ISSUE THREAD

**Issue by Ex4nder** [cedricp/ddt4all#456]
Hi, 
Maybe I'm missing something, OBDLink MX+ bluetooth dongle should be able of natively access all the can buses, without pin route modification, is there an option in the software to do it in the android port (ecu-tweaker)? and in the  ddt4all?
thank you,
Ex4nder

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
