### ISSUE TITLE
DDT2000 database

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#457]
Just wondering who writes the actual DDT2000 Database so that the parameters can be changed on the ECU's ? 

I am using what I think is the latest ECU database 09/07/2019 (unless someone knows of newer?) 

I have 2 Renault cars at the moment a Clio Mk4 and a Renault Zoe electric vehicle. 

On the cluster for the Clio Mk4   **Cluster X98_X87_X82_xHA_X98ph2_X87ph2_xHAph2_v8.02 Cluster/TDB**
I can change various parameters such as disable rear seatbelt reminder on dashboard cluster and Disable EPS warning on Dashboard cluster among other things .

On the Renault Zoe cluster setting    **TdB_X10_V1.12 Cluster/TDB**  I want to disable those 2 warnings , but apart from the fact that the cluster parameter settings in the x10 Zoe is all written in french, in DDT4ALL I cannot find any settings to disable the EPS and rear seatbelt warnings in the parameters for the dashboard cluster of the Zoe .  - the Zoe cluster has a totally TFT screen by the way and the Clio mk4 has dials and a matrix screen. 

I was going to try and take a chance to disable EPS and rear seatbelt warning using the parameters of the  X98_X87_X82_xHA_X98ph2_X87ph2_xHAph2_v8.02 Cluster/TDB for the Zoe but decided against because it could damage the ecu or cluster for the zoe using the wrong ECU settings I should imagine. 

any ideas ? thanks. 
@cedricp and others 

Here is Cluster TDB settings for Renault Zoe EV:
![zoe cluster tdb](https://user-images.githubusercontent.com/49172217/93472966-4f530580-f8ed-11ea-9298-62a45cdc0124.jpg)

Here is setting for Clio Mk4 
![clio4 tdb cluster1](https://user-images.githubusercontent.com/49172217/93473615-1ebf9b80-f8ee-11ea-9b24-77fae4c721bf.jpg)

![clio4 tdb cluster2](https://user-images.githubusercontent.com/49172217/93473654-2bdc8a80-f8ee-11ea-8dbf-b826b76e52c9.jpg)

**Comment by KarelSvo** [comment]
Config Generale_Inhib SBR_av
ON -  Buzzer SBR avant non inhibé (par défaut)
OFF - Buzzer SBR avant inhibe

**Comment by AndyIreland** [comment]
> Config Generale_Inhib SBR_av
> ON - Buzzer SBR avant non inhibé (par défaut)
> OFF - Buzzer SBR avant inhibe

Thank you - but that just turns off the buzzer - it does not get rid of the message on the cluster saying '0 rear sealtbelts connected'

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by manio** [comment]
@AndyIreland 
> > Config Generale_Inhib SBR_av
> > ON - Buzzer SBR avant non inhibé (par défaut)
> > OFF - Buzzer SBR avant inhibe
> 
> Thank you - but that just turns off the buzzer - it does not get rid of the message on the cluster saying '0 rear sealtbelts connected'

Andy, I want to do the same change on ZOE (inhibit the buzzer) also I also has this in french.
Some questions - maybe you remember and can tell me:
1. How to prepare? Do i need to start the engine (brake pedal + P), or this is irrelevant ? Is there some specific procedure before writing the "Meter cluster" settings?
2. I assume that I need to click yellow button 'Inhibit SBR av' after a value change, so this single setting is saved, but what next - is the "Prise en compte des configurations" sufficient, or I also need to click "Retour a la config  par default" at the very bottom ?

**Comment by AndyIreland** [comment]
@manio  - here you go:

just do it with car not ready ('engine' off) and keycard in slot
when you press Prise en compte des configurations  dash will briefly go dark/blank and you may get a few error messages briefly like ' Check ESC/HILL START/ABS' - dont worry about that , as long as the dash lights up again you should be OK. 
** DO AT YOUR OWN RISK**

![image](https://github.com/cedricp/ddt4all/assets/49172217/b532319c-1f28-443f-9924-1fddbbf673a4)

![image](https://github.com/cedricp/ddt4all/assets/49172217/30b6660e-2c08-4920-bf2d-96b06baa1569)

**Comment by manio** [comment]
Thank you very much, Andy! :)
