### ISSUE TITLE
Modification for new EasyLink

### ISSUE THREAD

**Issue by igno77** [cedricp/ddt4all#459]
If I have understood, in this moment, it's not possible to save modification on the new EasyLink (Captur II, Clio V and Megane ph2) due to a limitation of a gateway ecu. Someone have tried it? Did you find a way for write on it?
Thanks

**Comment by jjaemny** [comment]
I have the same problem. Have you solved the problem?

**Comment by KarelSvo** [comment]
You need to remove the glove box in order to establish a direct connection to CANH and CANL of the Easylink Ecu.
CANH pin 18, 19 and 20
CANL pin 38, 39 and 40
![easylink](https://user-images.githubusercontent.com/30380693/95016862-11c4db00-0656-11eb-963e-88012c127ca3.png)

**Comment by igno77** [comment]
What's you mean for "glove box"? Never seen before a can with 3 signal for each channel....

**Comment by KarelSvo** [comment]
The Easylink Ecu is located above, behind the glove compartment of the Clio and Captur.

**Comment by jjaemny** [comment]
If I have to use elm327 to modify the ecu equipped with an easylink system, should I connect elm327 to 38-40 pin?

**Comment by cetinyusuf** [comment]
clio 5 CANH VE CANL nerede tam olarak obd soketine nasıl bağlantı yapabilirm güvenlik ğeçidini geçebirmiyim @KarelSvo

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
