### ISSUE TITLE
Help radio DAB Scenic 4

### ISSUE THREAD

**Issue by lucamagilla** [cedricp/ddt4all#46]
Hello to all I have a Scenic IV and I would like to activate via dd4all the dab radio but I have the problem that I can not read the screen A-IVI 09, I changed the obd socket by diverting the signal from the poles 6-14 to 13-12 but nothing I can not read. Does anyone have any ideas? Thanks

**Comment by Banana009** [comment]
Unfortunately, no one has yet been able to activate DAB (read from A-IVI 09). Only one person at the Italian forum, which is strange.
I have tried 3 types of ELMs without success.
I would also like someone to solve this problem and have more success than I do.

**Comment by lucamagilla** [comment]
Hi Banana, I'm Magilla from the Italian renault forum, I've also tried more obd jacks and at this point I have the doubt that it is a lie that of magellano of the italian forum

**Comment by ohayyam** [comment]
Did you check your radio that have digitale antenna socket and digital antenna connected ?
![rlink2 radio cikislar](https://user-images.githubusercontent.com/35384108/37949408-2fc37c14-319d-11e8-9178-5cd426fc0fd7.png)

**Comment by gvaldo** [comment]
Hi ! I have a problem with parking sensors. they do not work, error message (help check parking). I can check with ddt4all where the error is.

**Comment by Banana009** [comment]
I have tried 3 types of OBD adapters without success!! It's a lie. Do not waste money on other OBD2 adapters. It cost me around 100 EURO!!
Another problem is, as Ohayyam wrote, that we need another antenna for DAB. Is it not clear if an antenna is connected?

**Comment by mishu28nmv** [comment]
I activated DABwith ddt4all. It showed on my Rlink1 display but there is no signal so... I need to buy an external antenna and a box from a site autodab. com and that will work only if you have the brown connector, wich Rlink1 doesn't.
picture: [https://imgur.com/a/LcP04XJ](url)

**Comment by Rcarnero73** [comment]
> Did you check your radio that have digitale antenna socket and digital radio antenna connected ?
> ![rlink2 radio cikislar](https://user-images.githubusercontent.com/35384108/37949408-2fc37c14-319d-11e8-9178-5cd426fc0fd7.png)
> 
> As far as I understand, Renault only hides the ongoing features of the Renault engineers' development work, which are not fully functional, so the features that can be opened with ddt4all are hidden and not fully functional. I think that the features that do not work with DDT4all are caused by lack of hardware.

Do you have the complete pinout for Rlink 2?

**Comment by ohayyam** [comment]
pinout diagrams depends your car and radio type. tell me your car and radio type ?

**Comment by bokkoman** [comment]
> I activated DABwith ddt4all. It showed on my Rlink1 display but there is no signal so... I need to buy an external antenna and a box from a site autodab. com and that will work only if you have the brown connector, wich Rlink1 doesn't, at least on the back of the display.
> [Rlink1 display back connectors](https://imgur.com/a/LcP04XJ)

The DAB connector would be at the radio module, not behind the display unit.
Rlink has a display unit and a separate radio module/unit. In the Clio 4 it is behind the glovebox, which you can take it very easily if you look at the hinges (you can slide them to the side).

**Comment by mishu28nmv** [comment]
> > I activated DABwith ddt4all. It showed on my Rlink1 display but there is no signal so... I need to buy an external antenna and a box from a site autodab. com and that will work only if you have the brown connector, wich Rlink1 doesn't, at least on the back of the display.
> > [Rlink1 display back connectors](https://imgur.com/a/LcP04XJ)
> 
> The DAB connector would be at the radio module, not behind the display unit.
> Rlink has a display unit and a separate radio module/unit. In the Clio 4 it is behind the glovebox, which you can take it very easily if you look at the hinges (you can slide them to the side).
> 
> Can you tell me how you have activated DAB with ddt4all?

<a href="https://ibb.co/YDyBNgY"><img src="https://i.ibb.co/YDyBNgY/IMG-20190306-WA0003.jpg" alt="IMG-20190306-WA0003" border="0"></a>
With ddt4all go to  MFD vX.X then 1.Configuration then 12.ECU configuration then look for Digital Radio option.
I hope this help!

**Comment by bokkoman** [comment]
> 
> [![IMG-20190306-WA0003](https://camo.githubusercontent.com/d71f0eda3323826ff36d9231220cf9d31a50ba4a/68747470733a2f2f692e6962622e636f2f594479424e67592f494d472d32303139303330362d5741303030332e6a7067)](https://ibb.co/YDyBNgY)
> With ddt4all go to MFD vX.X then 1.Configuration then 12.ECU configuration then look for Digital Radio option.
> I hope this help!
Which database version do you have?
My mfd goes to version 4.6. You have a higher version.

**Comment by mishu28nmv** [comment]
I have Laguna 3 with R-Link1 wich has/is MFD v4.6. It does not care what MFD you have. Just follow the steps.
As for a module and an antenna:
1. I don't know where is the radio module located in Laguna
2. I don't have an antenna (just an external gps antenna with Fakra connector😂)
3. I don't know what connectors has the module
4. I wish you luck 😉

**Comment by bokkoman** [comment]
> I have Laguna 3 with R-Link1 wich has/is MFD v4.6. It does not care what MFD you have. Just follow the steps.
> As for a module and an antenna:
> 
> 1. I don't know where is the radio module located in Laguna
> 2. I don't have an antenna (just an external gps antenna with Fakra connectorjoy)
> 3. I don't know what connectors has the module
> 4. I wish you luck wink

Thanks haha. I have a Clio, i know where the module is located (behind glovebox). I was just wondering if replacing the module would make DAB work.

**Comment by mishu28nmv** [comment]
I think we need to buy something like this:
https://www.niq.de/dab-autodab/dab-dab-modul-fuer-diverse-renault-modelle-mit-iso-stecker.html?language=en
and it's expensive at 230 € 😱
Or maybe something cheaper but I don't know yet what 🤣

**Comment by bokkoman** [comment]
> I think we need to buy something like this:
> https://www.niq.de/dab-autodab/dab-dab-modul-fuer-diverse-renault-modelle-mit-iso-stecker.html?language=de
> and it's expensive at 230 € 
> Or maybe something cheaper but I don't know yet what

No. I'm looking at buying an official radio module for Rlink.
Rlink consists of 2 parts. The screen and a separate radio module.
My radio module only has am/fm. But there are newer Rlinks that came with DAB. Soooo what I'm looking at is new radio module with dab that came from a torn apart car (wrecked renault car).
I think that way i add an official antenna as well and then i have DAB radio.

**Comment by mishu28nmv** [comment]
Ok. Good luck and have fun! 😁

**Comment by myshuker** [comment]
Hey friends
anyone can help me where can I find 32 pin connector in Scenic iv  because I want to fit rear view camera ?
and if there are a video to how to remove radio unit ?

**Comment by myshuker** [comment]
any one has 32 pin r-link 2 connector pins diagram ?

**Comment by bokkoman** [comment]
> Hey friends anyone can help me where can I find 32 pin connector in Scenic iv because I want to fit rear view camera ? and if there are a video to how to remove radio unit ?

You need to find the radio unit.
The radio unit holds the rca plug for video. 
Then just activate it with ddt4all.

**Comment by myshuker** [comment]
> 
thanks for replaying
but I want to know witch pin is for rear gear also please I have 12v camera,

**Comment by bokkoman** [comment]
> > 
> 
> thanks for replaying but I want to know witch pin is for rear gear also please I have 12v camera,

You put the 12v wire to the reverse light. 
So mount camera, or red wire to reverse light 12v, black to ground. And the rca to the radio unit input.

**Comment by myshuker** [comment]
I can just find 24 pin connector for Medianav on Clio4 on the internet 
but i cant fint 32 pin connector 
https://ibb.co/0q2DpD2

**Comment by myshuker** [comment]
> You put the 12v wire to the reverse light.
in this case there are problem, because whe I relase the gear the screen be black for about 5 secound because there are not power on reverse light anymore to energize the camera

**Comment by bokkoman** [comment]
> > You put the 12v wire to the reverse light.
> 
> in this case there are problem, because when I release the gear the screen be black for about 5 secound because there are not power on reverse light anymore to energize the camera

I have no clue beyond this.
Sounds like a trip to a (Renault) garage wouldn't hurt.

**Comment by myshuker** [comment]
yeah,
But thanks for you friend 👍 
:)
