### ISSUE TITLE
ddt4all "Program error" with "Stop" light on, Renault Talisman

### ISSUE THREAD

**Issue by dadoblu2000** [cedricp/ddt4all#461]
Hello everyone I write here hoping that you can help me solve a problem that I combined with ddt4all, in practice I touched some value that I should not touch, I wanted to reset the errors that were displayed but now the dashboard displays progra error and the warning light stop on, in addition, the language set is French and I cannot change it, while the other settings can be changed, the car works regularly, which is why I went to a renault workshop in my area and it informed me that a new one must be reprogrammed. ECU, I was not told which one it is and that I have to replace the front lambda probe, total intervention value 700 euros, I hope you can help me solve it on your own, the model is Talisman 1.6 130CV, here are some photos

![IMG_4940](https://user-images.githubusercontent.com/40566527/94236367-6311f380-ff0d-11ea-8c4f-7ca6565f9719.jpg)
![IMG_4941](https://user-images.githubusercontent.com/40566527/94236388-6907d480-ff0d-11ea-8a3b-ec6c3798de4b.jpg)
![IMG_4942](https://user-images.githubusercontent.com/40566527/94236343-5beae580-ff0d-11ea-9d7b-e2dfb3befce0.jpg)
![IMG_4943](https://user-images.githubusercontent.com/40566527/94236378-660ce400-ff0d-11ea-8218-e12f5332982f.jpg)

**Comment by pakoto** [comment]
err prog means that you enable an option into cluster that not enabled into ecus, or viceversa.

i.e. disable start-stop or tpms into cluster, when is enabled into BCM.

**Comment by dadoblu2000** [comment]
is there a method to be able to tipristinsre how it was before?  between us I do not know what I could have activated / deactivated, but I have noticed that when I activate when I activate the high beams in automatic mode they no longer work, in addition to the settings that appear in the instrument panel when I try to change the language from French to Italian the  command takes it for an idtante but then returns to the French language ... can you tell me which control unit to check?

**Comment by dadoblu2000** [comment]
thanks for your information, I solved it by configuring the Conf_MPU scheme by setting everything to absent all, now the spy is gone.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
