### ISSUE TITLE
Cedricp DDT4ALL

### ISSUE THREAD

**Issue by BarektE** [cedricp/ddt4all#462]
Mr. Cedricp Do you have any new work on DDT4ALL? if there is, how will we pack it? Thanks Zmiterm was packing new software and we were using it without any mistakes. I think we lost Zmiterm in Covid 19, it does not appear anywhere. We need someone more like him to make our job easier

**Comment by pakoto** [comment]
I packed last version using last 07.2020 database, modifying car list and bypassing expert mode and security warning: no need to check "old man icon" before write changes. 

This unofficial version is informed to Cedric, but not supported here in github.

https://dacieros.forumfree.it/?t=77922033

**Comment by BarektE** [comment]
> Son sürümü 07.2020 veritabanını kullanarak, araç listesini değiştirerek ve uzman modunu ve güvenlik uyarısını atlayarak paketledim: değişiklikleri yazmadan önce "yaşlı adam simgesini" kontrol etmeye gerek yok.
> 
> Bu resmi olmayan sürüm Cedric'e bildirilir, ancak burada github'da desteklenmemektedir.
> 
> https://dacieros.forumfree.it/?t=77922033

The addition of different languages ​​is great. But languages ​​are missing. Is one of the largest markets throughout the world as the Renault car project has made Turkey the addition of Turkish missing. For me, the old man's getting up was not good for security.

**Comment by pakoto** [comment]
I could make new version "with old man". Turkey installation messages could be easily added. If not exist in-app translation, you could modify spanish file replacing messages and we could add translation.

[ddt4all.zip](https://github.com/cedricp/ddt4all/files/5292238/ddt4all.zip)

**Comment by BarektE** [comment]
> "Yaşlı adamla" yeni versiyon yapabilirim. Türkiye kurulum mesajları kolaylıkla eklenebilir. Uygulama içi çeviri yoksa, İspanyolca dosyasını mesajları değiştirerek değiştirebilirsiniz ve biz çeviri ekleyebiliriz.
> 
> [ddt4all.zip](https://github.com/cedricp/ddt4all/files/5292238/ddt4all.zip)

now i'm installing ddt4all you edited, let me check

**Comment by pakoto** [comment]
.po file i sent now can be opened with notepad, and replace all spanish messages with your language. Don´t touch english messages.

**Comment by BarektE** [comment]
ok

**Comment by pakoto** [comment]
you can take other language .po file from /locale if is easier for you to translate it.

**Comment by BarektE** [comment]
I am translating, I will send you when I translate

**Comment by BarektE** [comment]
Lo traduje al turco. 

¿Cómo agrego este archivo a ddt4all? 

28/09/2020 15:41, pakoto yazmış:

> I could make new version "with old man". Turkey installation messages could be easily added. If not exist in-app translation, you could modify spanish file replacing messages and we could add translation. 
> 
> ddt4all.zip [1] 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

 

Links:
------
[1] https://github.com/cedricp/ddt4all/files/5292238/ddt4all.zip
[2] https://github.com/cedricp/ddt4all/issues/462#issuecomment-699981273
[3]

**Comment by BarektE** [comment]
I translated the file I sent you

**Comment by pakoto** [comment]
only drag file into a comment.

**Comment by BarektE** [comment]
does not install the zip file

**Comment by pakoto** [comment]
i can´t understand. Only need to zip your .po modified file an drag into comment

File .po don´t work with ddt4all, need to be convert. I can do it.

**Comment by BarektE** [comment]
[ddt4all Turkish.zip](https://github.com/cedricp/ddt4all/files/5293191/ddt4all.Turkish.zip)

**Comment by pakoto** [comment]
I see file without translate

msgid "Goto data"
msgstr "Ir a Datos"

msgid "Remove"
msgstr "Eliminar"

msgid "Add to screen"
msgstr "Añadir pantalla"
.
.
.


i suppose that would be something like this

msgid "Goto data"
msgstr "verilere git"

msgid "Remove"
msgstr "Kaldırmak"

msgid "Add to screen"
msgstr "bir ekran ekle"

(i´m using google translate)

**Comment by BarektE** [comment]
![2](https://user-images.githubusercontent.com/43322396/94456851-74345c00-01bc-11eb-85c7-f5c85032f47e.PNG)

**Comment by pakoto** [comment]
ok, you only need to translate plugin messages? You could translate whole file and Cedric adds as language.

**Comment by BarektE** [comment]
Yes

**Comment by BarektE** [comment]
> tamam, sadece eklenti mesajlarını çevirmeniz mi gerekiyor? Tüm dosyayı çevirebilirsiniz ve Cedric dil olarak ekler.

I will translate them all

**Comment by BarektE** [comment]
> tamam, sadece eklenti mesajlarını çevirmeniz mi gerekiyor? Tüm dosyayı çevirebilirsiniz ve Cedric dil olarak ekler.

Tamamlandığında dosyayı e-posta ile göndereceğim

**Comment by pakoto** [comment]
You unzip into /locale and test. I don´t know if Cedric needs to modify ddt4all to add tr language.

[tr.zip](https://github.com/cedricp/ddt4all/files/5293738/tr.zip)

**Comment by BarektE** [comment]
> / Locale içine açıp test edersiniz. Cedric'in tr dilini eklemek için ddt4all'ı değiştirmesi gerekip gerekmediğini bilmiyorum.
> 
> [tr.zip](https://github.com/cedricp/ddt4all/files/5293738/tr.zip)

Cedric had told me before and had sent me the file of the ecu tweaker translation so that I would add it if you translate it, and I had it translated to someone else. Now I'm turning it myself

**Comment by BarektE** [comment]
I turned most of them already, there is little left

**Comment by pakoto** [comment]
i sent only for test, if reads your first translated messages, I don´t know if ddt4all detects language code from windows, and if it´s TR or TK.

**Comment by BarektE** [comment]
Türkçe tr

**Comment by BarektE** [comment]
I translated I sent to Cedric PAILLE by e-mail

**Comment by pakoto** [comment]
if you send here, i could create a full version install with it included to test.

**Comment by BarektE** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5298504/tr.zip)

**Comment by BarektE** [comment]
> Buraya gönderirseniz, test etmek için dahil edilmiş bir tam sürüm kurulumu oluşturabilirim.

gönderdim

**Comment by BarektE** [comment]
gönderdim

**Comment by BarektE** [comment]
> Buraya gönderirseniz, test etmek için dahil edilmiş bir tam sürüm kurulumu oluşturabilirim.

**Comment by BarektE** [comment]
> / Locale içine açıp test edersiniz. Cedric'in tr dilini eklemek için ddt4all'ı değiştirmesi gerekip gerekmediğini bilmiyorum.
> 
> [tr.zip](https://github.com/cedricp/ddt4all/files/5293738/tr.zip)

**Comment by pakoto** [comment]
i'm trying to convert. Some errors with " into messages, instead '

**Comment by BarektE** [comment]
> dönüştürmeye çalışıyorum. Bunun yerine "mesajlara" ile ilgili bazı hatalar

gracias

**Comment by pakoto** [comment]
https://mega.nz/file/XBsiiSoa#kKkbbF67ehvLwbuY46nHf278OHPb6SxW_O_xBK19iAI
Could you try to install?

**Comment by BarektE** [comment]
> https://mega.nz/file/XBsiiSoa#kKkbbF67ehvLwbuY46nHf278OHPb6SxW_O_xBK19iAI
> Yüklemeyi deneyebilir misiniz?

estoy intentando

**Comment by BarektE** [comment]
Turco al instalar pero después de instalar ddt4all no se abre

**Comment by BarektE** [comment]
ddt4all no se abre después de la instalación

**Comment by BarektE** [comment]
![5](https://user-images.githubusercontent.com/43322396/94555017-9f25bb00-0263-11eb-9612-164b3bda2dd8.PNG)

**Comment by BarektE** [comment]
Probé en modo demo y déjame probar el auto

**Comment by pakoto** [comment]
msgid "Diag version;Supplier;Soft;Version"
msgstr "Diag versiyonu; Tedarikçi; Yumuşak; Versiyon"

**Comment by pakoto** [comment]
LETTER  Windows-1254    ISO-8859-9  latin5      UTF-8
ğ       b'\xf0'         b'\xf0'     b'\xf0'     b'\xc4\x9f'
ı       b'\xfd'         b'\xfd'     b'\xfd'     b'\xc4\xb1'
ş       b'\xfe'         b'\xfe'     b'\xfe'     b'\xc5\x9f'
ü       b'\xfc'         b'\xfc'     b'\xfc'     b'\xc3\xbc'
ö       b'\xf6'         b'\xf6'     b'\xf6'     b'\xc3\xb6'
ç       b'\xe7'         b'\xe7'     b'\xe7'     b'\xc3\xa7'
Ğ       b'\xd0'         b'\xd0'     b'\xd0'     b'\xc4\x9e'
Ü       b'\xdc'         b'\xdc'     b'\xdc'     b'\xc3\x9c'
Ş       b'\xde'         b'\xde'     b'\xde'     b'\xc5\x9e'
İ       b'\xdd'         b'\xdd'     b'\xdd'     b'\xc4\xb0'
Ö       b'\xd6'         b'\xd6'     b'\xd6'     b'\xc3\x96'
Ç       b'\xc7'         b'\xc7'     b'\xc7'     b'\xc3\x87'

**Comment by BarektE** [comment]
> LETTER Windows-1254 ISO-8859-9 latin5 UTF-8
> ğ b'\xf0' b'\xf0' b'\xf0' b'\xc4\x9f'
> ı b'\xfd' b'\xfd' b'\xfd' b'\xc4\xb1'
> ş b'\xfe' b'\xfe' b'\xfe' b'\xc5\x9f'
> ü b'\xfc' b'\xfc' b'\xfc' b'\xc3\xbc'
> ö b'\xf6' b'\xf6' b'\xf6' b'\xc3\xb6'
> ç b'\xe7' b'\xe7' b'\xe7' b'\xc3\xa7'
> Ğ b'\xd0' b'\xd0' b'\xd0' b'\xc4\x9e'
> Ü b'\xdc' b'\xdc' b'\xdc' b'\xc3\x9c'
> Ş b'\xde' b'\xde' b'\xde' b'\xc5\x9e'
> İ b'\xdd' b'\xdd' b'\xdd' b'\xc4\xb0'
> Ö b'\xd6' b'\xd6' b'\xd6' b'\xc3\x96'
> Ç b'\xc7' b'\xc7' b'\xc7' b'\xc3\x87'

the car also works. Doesn't work in demo mode

**Comment by BarektE** [comment]
I think the error of LETTER Windows-1254 ISO-8859-9 latin5 UTF-8 startup message is due to this.

**Comment by pakoto** [comment]
only fails into dataeditor.py
I suppose that Cedric could fix it. 
i only can remove that line and use it in english

**Comment by BarektE** [comment]
> yalnızca dataeditor.py'de başarısız olur,
> sanırım Cedric bunu düzeltebilir.
> sadece bu satırı kaldırıp ingilizce kullanabilirim

would be

**Comment by BarektE** [comment]
Cedric PAILLE
Added to the GIT repository, Said she added

**Comment by pakoto** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5298938/tr.zip)
modified only that line replacing Ç with C, could you test?

**Comment by BarektE** [comment]
ok

**Comment by BarektE** [comment]
Pakoto Thank you very much worked

**Comment by pakoto** [comment]
now full works? i´ll packet again if you confirm it

**Comment by BarektE** [comment]
> şimdi tam çalışıyor mu? Onaylarsan tekrar paketleyeceğim

şimdi tam olarak çalışıyor, olduğu gibi yeniden paketler misiniz?

**Comment by pakoto** [comment]
https://mega.nz/file/LIVmzBJC#z6mK5POpATYOE6VX_q4DgQWS_14-osYn-_fBJ3mX9Ng
untouched DDT4all + 07.2020+tr language with line modified to bypass error.

**Comment by BarektE** [comment]
pakoto thank you very much, works smoothly

**Comment by BarektE** [comment]
![6](https://user-images.githubusercontent.com/43322396/94581961-61855a00-0284-11eb-9172-e808e282ace9.PNG)

**Comment by BarektE** [comment]
there is problem. I haven't tried this place

**Comment by pakoto** [comment]
older ddt4all version. try to open 4th tab
![Capture](https://user-images.githubusercontent.com/24203270/94596507-81b91700-028c-11eb-84ec-1ad6bd263151.JPG)

**Comment by BarektE** [comment]
> eski ddt4all sürümü otomatik olarak 4. sekmeyi açar
> 
> ![Ele geçirmek](https://user-images.githubusercontent.com/24203270/94596755-dceb0980-028c-11eb-9aef-2e9b5ee0e438.JPG)
> 
> ![Ele geçirmek](https://user-images.githubusercontent.com/24203270/94596507-81b91700-028c-11eb-84ec-1ad6bd263151.JPG)

it doesn't open up anywhere

**Comment by pakoto** [comment]
i think that ecu don´t have "screen"
Renolink don´t show anything

![Uploading Capture.JPG…]()

**Comment by BarektE** [comment]
![7](https://user-images.githubusercontent.com/43322396/94597484-4b809500-0296-11eb-917d-f888aab6c274.PNG)

**Comment by BarektE** [comment]
I have Renolink, uploaded

**Comment by BarektE** [comment]
çeviride bir hata gördüm ondan olabilir mi?

**Comment by pakoto** [comment]
could you paste error? some errors only shows into console

**Comment by BarektE** [comment]
![8](https://user-images.githubusercontent.com/43322396/94598396-8d5e0b00-0297-11eb-9c06-a2d181afec87.PNG)

**Comment by pakoto** [comment]
show errors here?

![Capture](https://user-images.githubusercontent.com/24203270/94598549-61d72280-028f-11eb-8f1a-ec92d2884b67.JPG)

**Comment by BarektE** [comment]
![9](https://user-images.githubusercontent.com/43322396/94598831-3b69b500-0298-11eb-8054-4c9fcd559e4a.PNG)

**Comment by pakoto** [comment]
yes, more errors with special characters...

**Comment by BarektE** [comment]
![10](https://user-images.githubusercontent.com/43322396/94599474-27728300-0299-11eb-92f1-30074f4f1b23.PNG)
Can you correct the place I marked

**Comment by pakoto** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5301064/tr.zip)
 unicode 0130 I with . replaced with I

**Comment by BarektE** [comment]
![11](https://user-images.githubusercontent.com/43322396/94600519-a7e5b380-029a-11eb-8138-da86ac29d28d.PNG)

**Comment by BarektE** [comment]
> [tr.zip](https://github.com/cedricp/ddt4all/files/5301064/tr.zip)
> unicode 0130 I ile. I ile değiştirildi

I tried it it didn't improve

**Comment by BarektE** [comment]
![13](https://user-images.githubusercontent.com/43322396/94601056-94871800-029b-11eb-8c29-0cf3eecfdbcd.PNG)

**Comment by BarektE** [comment]
this is what should be (uses)

**Comment by pakoto** [comment]
msgid "ECU uses SDS "
msgstr "ECU ABD SDS"

**Comment by BarektE** [comment]
![14](https://user-images.githubusercontent.com/43322396/94601891-cfd61680-029c-11eb-98b0-47595721dea0.PNG)

**Comment by BarektE** [comment]
for the mistake I made here in my opinion. does not open

**Comment by pakoto** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5301229/tr.zip)

**Comment by BarektE** [comment]
> [tr.zip](https://github.com/cedricp/ddt4all/files/5301229/tr.zip)

Yine olmadı ABD yazan yer değişmesi gerekiyor

**Comment by pakoto** [comment]
"ecu uses SDS" google translated as "ECU kullanır SDS" into last tr.zip

**Comment by BarektE** [comment]
problema, en este archivo, la sección que dice que EE.UU. debe eliminarse.

[ddt4all.zip](https://github.com/cedricp/ddt4all/files/5301358/ddt4all.zip)

**Comment by pakoto** [comment]
mo file compiles from po file. You can use .po any language from /locale and edit

i think you need to maintain this untouched

# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2019-01-21 15:12+0100\n"
"PO-Revision-Date: 2020-09-11 14:02+0200\n"
"Last-Translator: Atum Elektronik Ali Bey <atumelektronik@gmail.com>\n"
"Language-Team: \n"
"Language: tr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.0.7\n"
"X-Poedit-SourceCharset: UTF-8\n"


only modify msgstr lines between " " 
Don´t use " into translated text.

**Comment by BarektE** [comment]
Esta noche solucionaré el problema, funciona bien cuando haga la primera traducción, traduciré el resto

**Comment by BarektE** [comment]
I change it. Can you adapt this?

[tr.zip](https://github.com/cedricp/ddt4all/files/5301536/tr.zip)

**Comment by BarektE** [comment]
I change it. Can you adapt this?

[tr.zip](https://github.com/cedricp/ddt4all/files/5301572/tr.zip)

**Comment by pakoto** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5301571/tr.zip)

unzip into /locale

**Comment by BarektE** [comment]
çalışmadı :(

**Comment by pakoto** [comment]
I think you can´t use special characters until Cedric solve errors with unicode.

**Comment by BarektE** [comment]
> Cedric hataları unicode ile çözene kadar özel karakterleri kullanamayacağınızı düşünüyorum.

there are errors in one or two places. if I translate part by section and send it. Can you edit it tomorrow

**Comment by BarektE** [comment]
e-posta: barekte34@gmail.com

**Comment by BarektE** [comment]
> Cedric hataları unicode ile çözene kadar özel karakterleri kullanamayacağınızı düşünüyorum.

Los lugares equivocados están arreglados
[tr.zip](https://github.com/cedricp/ddt4all/files/5303469/tr.zip)

**Comment by BarektE** [comment]
Los lugares equivocados están arreglados

[tr.zip](https://github.com/cedricp/ddt4all/files/5303479/tr.zip)

**Comment by pakoto** [comment]
I see special characters like İ ç ş that fails with current ddt4all version. I can´t fix that, only replace with something like I c s

**Comment by BarektE** [comment]
(ç c) ( i I) (ş s) ( ğ g) (ü u) ( ı L)  Puede reemplazar los punteados con los sin punto

**Comment by BarektE** [comment]
(i ı ) ( I L)

**Comment by BarektE** [comment]
( I L)

**Comment by BarektE** [comment]
( l L )

**Comment by BarektE** [comment]
La última traducción que envié funcionará, porque cometí errores en la otra, no cometí esos errores en esta traducción.

**Comment by BarektE** [comment]
Lo intentaré si crea un archivo (tr) y lo envía a una prohibición que envié por última vez

**Comment by pakoto** [comment]
[tr_wait_fix_error.zip](https://github.com/cedricp/ddt4all/files/5304126/tr_wait_fix_error.zip)

This will work when Cedric fix dataeditor unicode error. Save for later.

**Comment by BarektE** [comment]
This car also worked, but the Demo also does not work. I made a wrong translation in 2 places and corrected it. I have added 2 translations to it, can you make it suitable again? No problem if you fix it in demo mode. Thank you from now.

[tr.zip](https://github.com/cedricp/ddt4all/files/5304590/tr.zip)

**Comment by pakoto** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5304784/tr.zip)

**Comment by BarektE** [comment]
no problem except demo mode. thanks for everything

**Comment by pakoto** [comment]
You are welcome. Waiting to Cedric for fix into dataeditor.py

**Comment by pakoto** [comment]
Could you test this?

[dataeditor.zip](https://github.com/cedricp/ddt4all/files/5304949/dataeditor.zip)

**Comment by BarektE** [comment]
The demo I tried is not working

**Comment by BarektE** [comment]
Closing when opening

**Comment by BarektE** [comment]
teşekkür

**Comment by BarektE** [comment]
Cedric added yesterday but where do we download what she added

**Comment by tanerdogan** [comment]
Hello I am a software developer, is there any help needed I can translate PO file into Turkish. Because its not handle with Google Translate. For example;

```
msgid "Little"
msgstr ""

msgid "Big"
msgstr ""
```

Thats about Endian (https://tr.wikipedia.org/wiki/Endian) -- You can not translate this "Küçük/Büyük" 

So I think I should translate default ddt4all.pot file...
