### ISSUE TITLE
Turkish Translate

### ISSUE THREAD

**Issue by tanerdogan** [cedricp/ddt4all#463]
Hi,

As I said before, I am software developer and want to help about translate.

So I work on /locales/ddt4all.pot file and new file 
[dd4all_tr.po.zip](https://github.com/cedricp/ddt4all/files/5305668/dd4all_tr.po.zip)

I'be happy if someone merge...

Happy coding...

**Comment by pakoto** [comment]
[tr.zip](https://github.com/cedricp/ddt4all/files/5305899/tr.zip)

**Comment by pakoto** [comment]
works?

**Comment by SedatAklar** [comment]
Taner bey şu ddt4all da mausun tekerleği yüzünden yanlışlıkla değişiklik sebebiyle dünyada bir çok kişinin cihazı bozuluyor. Sayfayı kaydırayım derken parametreler değişiyor ama hangisi değişti bunuda bilmek imkansız oluyor. Tekerlek çevirerek parametre değişimini iptal edebilirsen insanlar rahat edecek.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
