### ISSUE TITLE
The write button in ddt4all doesn't work.

### ISSUE THREAD

**Issue by jjaemny** [cedricp/ddt4all#465]
Hi, I have a some problem using DDT4all.

I know Using DDT4all is very simple.
1) turn on DDT4all
2) select my car
3) click "Einstein" and modification
4) click "write".

But.. I have a trouble.. 4) step.
After modificaion click "write", it is not save..

Those who succeed in coding say that it is possible to have an expensive product over $1,000, and they are charged 70 dollars each for coding. I feel this is unfair and try to spread the coding method to everyone.

i use ELM327, my car is XM3 UK named arkana.

below, error picture.
![ddt4all](https://user-images.githubusercontent.com/19282740/94877294-08404500-0495-11eb-988f-e345739c5b99.jpg)
![ddt4all2](https://user-images.githubusercontent.com/19282740/94877301-13937080-0495-11eb-8a39-7c70933345ce.jpg)

**Comment by KarelSvo** [comment]
What's your VIN?

**Comment by jjaemny** [comment]
My VIN is KNMK5B2RMLPxxxxxx

**Comment by pilotkalem** [comment]
just connect can lines of the ELM directly to BCM can lines. OBD can lines are behind CGW - a secutiry gateway module so it will not allow you to WRITE ECU. BCM can lines are connected directly to INTERNAL NETWORK. 70$ is expencive for a basic cabling work :)

**Comment by jjaemny** [comment]
> just connect can lines of the ELM directly to BCM can lines. OBD can lines are behind CGW - a security gateway module so it will not allow you to WRITE ECU. BCM can lines are connected directly to INTERNAL NETWORK. 70$ is expencive for a basic cabling work :)

Thank you for the good information. But is the bcm module compatible with elm327? From the naked eye, it is not possible to connect an elm327 module like an obd module.

**Comment by jjaemny** [comment]
> What's your VIN?

Looking at the answer to the #404 issue and pilotkalem's answer, it seems that changes can be made by connecting ELM327 to BCM and running ddt4all.
But I don't know how to connect ELM327 to BCM.
Can you tell me how to connect ELM327 to BCM?
Thanks.

@pilotkalem @KarelSvo

**Comment by bokkoman** [comment]
> > What's your VIN?
> 
> Looking at the answer to the #404 issue and pilotkalem's answer, it seems that changes can be made by connecting ELM327 to BCM and running ddt4all.
> But I don't know how to connect ELM327 to BCM.
> Can you tell me how to connect ELM327 to BCM?
> Thanks.
> 
> @pilotkalem @KarelSvo

I am wondering myself as well.
They tell us to just connect to BCM, but not how. 
If you succeeded in bypassing the security gateway, tell us exactly how.
Where do we connect? What cables? What connector? Where is the device located?

Please help fellow ddt4all users out 

@pilotkalem

**Comment by AndyIreland** [comment]
> I am wondering myself as well.
> They tell us to just connect to BCM, but not how.
> If you succeeded in bypassing the security gateway, tell us exactly how.
> Where do we connect? What cables? What connector? Where is the device located?
> 
> Please help fellow ddt4all users out
> 
> @pilotkalem

would be good alright if we had some more info

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
