### ISSUE TITLE
Deactivate "antipollution control" warning light with "wrench warning light" and "engine warning light"

### ISSUE THREAD

**Issue by dadoblu2000** [cedricp/ddt4all#466]
the "antipollution control" warning lights came on with "wrench warning light" and "engine warning light", I went to a renault dealer and they diagnosed me with a problem with the front lambda probe, I replaced the probe on my own, but the warning lights are still lit, is there a procedure to reset errors?
thank you

**Comment by dadoblu2000** [comment]
with ddt4all you can't clear the dtc errors, i used the car scanner app and everything i solved.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
