### ISSUE TITLE
DTC95334A

### ISSUE THREAD

**Issue by org07** [cedricp/ddt4all#467]
Does anyone know the causes of this fault code? DTC95334A

**Comment by org07** [comment]
Gerek kalmadı çözüldü

**Comment by Tony2764** [comment]
Hello, what is this defect? 
My car shows the same fault and I cannot find where the problem is coming from.

**Comment by cedricp** [comment]
Which ECU and vehicule ? How did you get that DTC ?

**Comment by Tony2764** [comment]
rlink2 radio control unit, talisman ip 1.6 160 edc.

I don't know why i have this default

**Comment by yasinklc** [comment]
Aynı sorun bende de mevcut sorunun çözümü buldunuz mu

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
