### ISSUE TITLE
renault r-link 2 downgrade ??

### ISSUE THREAD

**Issue by acgunner** [cedricp/ddt4all#468]
hello, ive installed software upgrade 9.9xxx into my 2016 renault kadjar, its not working, blew speakers, volume knob not working , phone connectivity not working, ect the list goes on !!
how do you downgrade back to the units original software 2.2.17.803 please ?? before i get a big bill off my local renault dealer??

**Comment by AlMeu** [comment]
Big mistake.
Upgrade from 2.2 or 3.3 to 7.0 is making only at Renault dealers trough their servers.
It's a small chance to bring it back. If I have it on my desk I will give a try.

**Comment by acgunner** [comment]
I still have my radio ,now covids over could i post it to you to see if you could save it for me ??

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
