### ISSUE TITLE
Ecu found but no relevant file

### ISSUE THREAD

**Issue by freeday01** [cedricp/ddt4all#472]
Hello

Can somebody help me with this Problem? The ecu is found but i can not operate on it.

What i am doing wrong? 

![image](https://user-images.githubusercontent.com/59029232/96195867-3e2e0080-0f4e-11eb-9ddd-0d2dbe1c3ba9.jpeg)

**Comment by freeday01** [comment]
Nobody?

**Comment by Marianpol** [comment]
NO DATA issuse is caused, because DDT4ALL is choosing wrong CAN protocol.
Laguna 2 PH2 has CAN 250kbps, but DDT4ALL selects CAN 500kbps.

[Here](https://github.com/cedricp/ddt4all/issues/415#issuecomment-658121266) I explained a bit about this error and how to resolve it.

**Comment by freeday01** [comment]
I have changed this in the ecu.py file and now this happens ![image](https://user-images.githubusercontent.com/59029232/96310371-878e5680-1007-11eb-8a47-42e70daa8749.jpeg)

**Comment by Marianpol** [comment]
Now you have your connection with ECM is set up correctly and you are receiving a messages.
SubFunctionNotSupported for 3E (testerPresent service) is nothing that your really need to care about.

Can you receive any data successfully from any of your screens or you only got NO DATA values on any of them?

**Comment by freeday01** [comment]
Thank you! Now it works! But It is not what i expected. 
Is there any chance to deactivate the second O2 Sensor in the ecu? Or did i have issuese to translate the french language

**Comment by Marianpol** [comment]
Unfortunately, there is no way to disable the second O2 sensor using the DDT4ALL. It cannot read/write FLASH/EEPROM.

**Comment by freeday01** [comment]
Thank you for your answer. Is there an Programm that can make ist happen? Do you know that?

**Comment by cedricp** [comment]
You will save time by replacing the O2 sensor, the ECU program is designed to work with it. Or it may be more simple to send a valid (I guess 0.5V) voltage to the O2 sensor input of the ECU's so it doesn't detect of fault.

**Comment by freeday01** [comment]
Okay thank you

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
