### ISSUE TITLE
Can I Set My Radio Clock with ddt4all ?

### ISSUE THREAD

**Issue by yavbuneaq** [cedricp/ddt4all#475]
Hi. I have a x38 renault fluence. I installed an afterstock radio (receiver or tape ? i don't know the exact word excuse me for my english)  to my car and can't change the radio clock because you can only set the clock via the original radio. The clock always flashes and it bugs me. I wan't to set it or close the display of clock. I'm curious if i can set it with ddt4all. I'm familiar with the program so if there is an option, if you can guide me through it i would appreciate it. Thank you and have a nice day

**Comment by BarektE** [comment]
tatbiki ayarlarsınız

**Comment by BarektE** [comment]
ELM 327 cihazınız CAN2 protokolünü destekliyorsa çok basit. 

![55](https://user-images.githubusercontent.com/43322396/97118492-2b1feb00-171b-11eb-9c5a-01620fa156d9.JPG)

**Comment by yavbuneaq** [comment]
> ELM 327 cihazınız CAN2 protokolünü destekliyorsa çok basit.
> 
> ![55](https://user-images.githubusercontent.com/43322396/97118492-2b1feb00-171b-11eb-9c5a-01620fa156d9.JPG)

Hocam bu menüye nasıl ulaşabilirim ? Girmediğim menü kalmadı yine de bu ayarı bulamadım. Teşekkür ederim

**Comment by BarektE** [comment]
e- mail yazın oradan göndereyim. Ancak ELM 327 teybi desteklemesi şart

**Comment by yavbuneaq** [comment]
> tatbiki ayarlarsınız

hocam bi süredir bakamıyorum buraya mail adresinizi öğrenebilir miyim menüye nasıl girebileceğim ile ilgili bilgi almak isterim. İyi günler

**Comment by localhost61** [comment]
Did you look into "Meter Cluster" then "BICxxx" then "RDBI/WDBI" and finally "Configuration"

**Comment by BarektE** [comment]
> > tatbiki ayarlarsınız
> 
> hocam bi ile bakamıyorum buraya mail adresinizi öğrenebilir miyim menüye nasıl girebileceğim ile ilgili bilgi almak isterim. İyi günler

E-postanızı yazın oradan nasıl yapacağınızla ilgili fotoğraf atarım

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
