### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adicretu97** [cedricp/ddt4all#48]
i use ddt4all with Vgate icar3 WIFI and i have this red error's, i open some ECU's but i can modify them or make something, all options is with red pls help me
i have RENAULT LAGUNA 2 1.9 DCI 2001 YEAR
![err](https://user-images.githubusercontent.com/37985106/38176651-8b87de88-35a7-11e8-8dd2-6daeb7a6f82d.jpg)

**Comment by KarelSvo** [comment]
RED in your photo because your exact ECU software version is not listed in the ECU file.

**Comment by adicretu97** [comment]
Aha, thx
And what can i do? Looking for another database with more ecu's?

Lun, 2 apr. 2018, 11:28 KarelSvo <notifications@github.com> a scris:

**Comment by KarelSvo** [comment]
Your ECUs are yes in the database.
No one hundred percent match is no problem, just a beauty bug.

**Comment by cedricp** [comment]
Yes, it looks like your version is very old, try updating it and retry. Some bugs have been fixed for KWP2000 protocol handling.
Red lines with **no relevant ecufile found**  mean that there's no XML file to support the found ECU.
Those with **no perfect match** mean that XML file is found but not with the exact soft version.

**Comment by KarelSvo** [comment]
I would say that all relevant ECUs are available in the database.
Only the maintenance of the data status of the software versions is not particularly good.

I had to complete the software version of two ECUs of my vehicle, otherwise these will not be found during automatic scanning.

I would not overrate this data comparison.

**Comment by cedricp** [comment]
Interested to get that patch, would you share it ?

**Comment by KarelSvo** [comment]
I have only opened the ECU xml in the text editor and updated with my actual ECU data.

<AutoIdent DiagVersion=" " Supplier="  " Soft="    " Version="    "/>

**Comment by adicretu97** [comment]
I will try tomorrow with kkl interface 409.1 with usb
Thx for answers

Lun, 2 apr. 2018, 15:26 Cedric PAILLE <notifications@github.com> a scris:

**Comment by cedricp** [comment]
Not sure it'll work with _kkl interface 409.1_, it's not ELM327 compatible...
@KarelSvo : Ok, I understand

**Comment by adicretu97** [comment]
I need elm with a specific chipset code no?

Lun, 2 apr. 2018, 15:46 Cedric PAILLE <notifications@github.com> a scris:
