### ISSUE TITLE
Clio Mk4 2016 1.5d GT Line

### ISSUE THREAD

**Issue by destruxon** [cedricp/ddt4all#481]
hi all,

thanks in advance for any help. i have the above car and trying to change a few settings like constant drl's and welcome/goodbye lights. i already had a good elm327 usb device from my ford which i have wired to the Renault specs 6-13 & 14-12 and it is reading as suspected from other posts ive seen 7 ecus found, 3 green 3 red and it seems the upc_emm edison is red but not showing in the left window and as version not found, which as you know is what i need to change the settings. i assumed that even though its a gt line it was still basically a dynamic s as thats on the log book. i have tried 2-3 different ddt databases and they all give me the same output, also have tried at different time outs and still the same. i have attached shots of my output.

![ecus_found](https://user-images.githubusercontent.com/54324002/97969720-5dcf8080-1db8-11eb-8581-9dafa14126ba.jpg)
![emm_edison](https://user-images.githubusercontent.com/54324002/97969725-5f00ad80-1db8-11eb-92e4-d269ea141f5a.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
