### ISSUE TITLE
Error installing on windows 7 64bit

### ISSUE THREAD

**Issue by jrmarins** [cedricp/ddt4all#484]
When finishing the installation on windows using the installer (Release November 2020 Python 3 64bit) the following error appears:

![image](https://user-images.githubusercontent.com/11929307/98257971-120b0b80-1f5f-11eb-977a-10a996709c45.png)

And when trying to open the program, windows cannot find the application.

**Comment by cedricp** [comment]
This is not an error, just a bug of the installer, you should read "don't forget to install database"
If it doesn't start, can you tell me the error, working for me.

**Comment by jrmarins** [comment]
> This is not an error, just a bug of the installer, you should read "don't forget to install database"
> If it doesn't start, can you tell me the error, working for me.

Thank you reply.
When I try to open the application, this error appears:

![image](https://user-images.githubusercontent.com/11929307/98266716-64512a00-1f69-11eb-98c2-6fd8037d845c.png)

Looking at the shortcut properties, under "destination" it looks like this:

"C:\Program Files (x86)\ddt4all\Python27\python.exe" "C:\Program Files (x86)\ddt4all\ddt4all.py"

**Comment by cedricp** [comment]
shortcut is likely the old one, try to start from start menu or launch DDT4ALL.BAT in install dir

**Comment by jrmarins** [comment]
using DDT4ALL.BAT opened, I can't test the connection now, but it seems to work normal.
