### ISSUE TITLE
Renault scienic 2 add card key

### ISSUE THREAD

**Issue by Forsmod** [cedricp/ddt4all#485]
Hello)
How can i add second card key to my Renault scienic 2 2007y? I found a way for scienic 2, <2006y. But this way didn't work on car 2007y.
I'll be very thankful for your reply))

**Comment by abecikxp** [comment]
You need dump uch memory by mcu programmer for read pin to code new card

**Comment by Forsmod** [comment]
I managed to read the code here. This is it?
![image](https://user-images.githubusercontent.com/72306801/98441177-c9458500-210d-11eb-84b6-3c07a9b880a2.png)

**Comment by Forsmod** [comment]
> You need dump uch memory by mcu programmer for read pin to code new card

I managed to read the code here. This is it?
<details>
  <summary>Image</summary>
![image](https://user-images.githubusercontent.com/72306801/98441275-5688d980-210e-11eb-8583-06f2f2867398.png)

</details>

**Comment by cedricp** [comment]
ISK reading has been scrambled after 2006 (phase 2), you need to read it from EEPROM, but don't have more information.

**Comment by Forsmod** [comment]
Ok, thank you :(

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
