### ISSUE TITLE
Remplacement radnav

### ISSUE THREAD

**Issue by sobaid13** [cedricp/ddt4all#486]
Bonjour j'aimerais savoir la procédure après un remplacement d autoradio sur Mégane 4 rad nav 3.3 en sachant que j en ai pris un d occasion merci

**Comment by AlMeu** [comment]
It is quite complicate to remove on Megane 4. Better do on a workshop.
Changing the unit be carefull that is tricky. Unit must be without VIN and antitheft code, otherwise is useless.

**Comment by sobaid13** [comment]
sàlut and for the survey the anti-theft code how I should do with which tools, and for the wine I put what in place thank you

Télécharger Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by AlMeu** [comment]
Only VIN is not enough. When you will try install in car you will get blocked by antitheft code.
I can clean by VIN and antitheft code the unit, but I need it on my desk.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
