### ISSUE TITLE
Talisman R-link2 8.7inch screen activate wifi function

### ISSUE THREAD

**Issue by bulentinan** [cedricp/ddt4all#49]
Hi,

Is it possible to activate the WIFI function in R-link 2? It is under ECU-->  RadNav v2.3-->ECU configuration Part-I -->TCU Network. 
My 3G connection package susbcribtion is ended. Maybe I may restore the car internet connection using phone wifi Hotspot.

**Comment by Necminecmi** [comment]
bu konuyu biraz daha açabilirmisiniz

**Comment by bulentinan** [comment]
The subject is to connect the car to internet using Wifi. I heard this feature is enabled on SM6 vehicles that are sold in Korea. By the way I've renewed my internet connection pack (digital pack 1 year) for €29. So the issue is not critical for me now. But if there's a solution its may ve useful for other R-link2 users.

**Comment by Furtif** [comment]
if not please move discution to https://github.com/cedricp/ddt4all/discussions
