### ISSUE TITLE
Can't read/write data for Megane IV Sedan

### ISSUE THREAD

**Issue by MazenMuhammad** [cedricp/ddt4all#491]
I have the Megane IV sedan 2021 but I can't read/write data for any ECU, I get the NO Data red box for every thing and writing data has no effect

**Comment by BarektE** [comment]
Megan 4 and Talisman Da ddt4all and peyren, Most functions do not, unfortunately

**Comment by BarektE** [comment]
Megan 4 and talisman are also ddt4all and peyren, unable to perform most functions.

**Comment by KarelSvo** [comment]
How is someone supposed to help without seeing your ddt4all log files?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
