### ISSUE TITLE
Turn off ESP warning light & spanner on Renault Zoe X10 Dash?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#493]
There is not a setting in the cluster setting in X10 Zoe to turn off ESP (ASC) warning icon and Spanner light for the dash of the Renault Zoe X10 Zoe TdB_X10_V1.12 Cluster/TDB 

- anyone know of another way to turn off these warning lights when esp is disabled? - I can disable ESP/ASR/Traction control on my Zoe but I want to be able to extinguish these warning lights from the dash when ESP is disabled.

Thanks.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
