### ISSUE TITLE
Anyone know what C_RPM_EngineThreshold setting does?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#494]
Anyone know what C_RPM_EngineThreshold setting does in UPC-EMM USM ECU? 

Renault Zoe ZE20 Electric vehicle 2013

![rpm engine threshold](https://user-images.githubusercontent.com/49172217/99193223-8c156e80-276f-11eb-8259-2180d6ac6e23.jpg)

**Comment by shrlnm** [comment]
"RPM value used for Oil Level warning."
May it be just a rudiment on electric car?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
