### ISSUE TITLE
DDT4ALL.bat error while opening

### ISSUE THREAD

**Issue by SzkarlatnyPumpernikiel** [cedricp/ddt4all#495]
![image](https://user-images.githubusercontent.com/74507931/99193764-6f7f3380-277b-11eb-96cc-32ea9336d9e0.png)

Do I have to enter my correct python path before opening?

**Comment by KarelSvo** [comment]
Have you tried the installer yet? simple start via desktop icon
You only need to insert the ecu database there.
https://github.com/cedricp/ddt4all/releases

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
