### ISSUE TITLE
SSPP VelSatis

### ISSUE THREAD

**Issue by bobipln** [cedricp/ddt4all#497]
Hello. I try to write wheel sensor with PyRen in DDT mode, but command not work. I'm in ExpertMode, I write the code of sensor and put the "Mise a jour" button.
![127449344_415276183215274_1095292769848859963_n](https://user-images.githubusercontent.com/74957061/100070332-7aecf180-2e42-11eb-869c-23c080e5d0ac.jpg)
![127199979_379888773276232_8821721818776269826_n](https://user-images.githubusercontent.com/74957061/100070334-7b858800-2e42-11eb-9089-d713426094fe.jpg)
![127181081_205663597743284_912831622385765152_n](https://user-images.githubusercontent.com/74957061/100070335-7b858800-2e42-11eb-9966-8ff2148a8cf1.jpg)

**Comment by shrlnm** [comment]
It is looks like you are using outdated code. Try to update by pressing "Update" button in launcher.

**Comment by bobipln** [comment]
I was able to enter the codes from the box below, showing which code applies to which wheel. But I have a problem with the visualization of the dashboard display. Whatever code I enter for the front right wheel, it does not want to show pressure and after a while it makes an error with a missing sensor. My question is where to look for the problem?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
