### ISSUE TITLE
PyRen

### ISSUE THREAD

**Issue by org07** [cedricp/ddt4all#498]
Is there an updated version of PyRen other than this link? Where can I download it packaged if available?
https://www.drive2.ru/b/501493851572142178/

**Comment by org07** [comment]
Where can I download the current version of PyRen, don't anyone even know?

**Comment by org07** [comment]
Où puis-je télécharger la version actuelle de PyRen, personne ne le sait?

**Comment by org07** [comment]
¿Dónde puedo descargar la versión actual de PyRen, nadie lo sabe?

**Comment by org07** [comment]
Где скачать актуальную версию PyRen, никто даже не знает?

**Comment by org07** [comment]
Wo kann ich die aktuelle Version von PyRen herunterladen? Weiß es noch niemand?

**Comment by shrlnm** [comment]
https://gitlab.com/py_ren/pyren/-/tree/master

**Comment by shrlnm** [comment]
In current versions there is a button "update" in a launcher, it actually updates all files from gitlab.

**Comment by org07** [comment]
> https://gitlab.com/py_ren/pyren/-/tree/master

Thank you for your answer, but here only, (PyRen-Master) has it loaded into (pyrene), it scans the ECUs in the car and finds them all, but when it comes to the end it gives the error I uploaded the photo. Packaged (PyRen), not available?

![pyren](https://user-images.githubusercontent.com/62398726/100275723-707d4580-2f71-11eb-984a-913c3f2b4516.PNG)

**Comment by shrlnm** [comment]
These are not errors of software. It is statistic of ELM errors during last session. On your screen all counters are zeroes so it means that your ELM worked very well with ECUs. Packaged version has no advantages as so it have to be unpackaged to *.py files before usage.

**Comment by org07** [comment]
> Bunlar yazılım hataları değildir. Son seanstaki ELM hatalarının istatistiğidir. Ekranınızdaki tüm sayaçlar sıfırdır, bu nedenle ELM'nizin ECU'larla çok iyi çalıştığı anlamına gelir. Paketlenmiş sürümün hiçbir avantajı yoktur, bu nedenle kullanımdan önce * .py dosyalarına paketten çıkarılması gerekir.
 shrlnm thank you. However this. https://www.drive2.ru/b/501493851572142178/  in this link

I am using PyRen184-installer.exe I have no problems. But when I install pyren-master it is having problems. I couldn't find the reason

**Comment by shrlnm** [comment]
@org07 please explain what type of problem do you experience?

**Comment by org07** [comment]
> @ org07 lütfen ne tür bir sorun yaşadığınızı açıklayın?

I will shoot the video tomorrow

**Comment by org07** [comment]
> @ org07 lütfen ne tür bir sorun yaşadığınızı açıklayın?

I'll make a video of the problem tomorrow, I'll share it here

**Comment by KarelSvo** [comment]
> 
> I am using PyRen184-installer.exe I have no problems. But when I install pyren-master it is having problems. I couldn't find the reason

how did you install? new files thrown in old program folder?

**Comment by org07** [comment]
> > PyRen184-installer.exe kullanıyorum, hiçbir sorunum yok. Ama pyren-master'ı kurduğumda sorun yaşıyor. Sebebini bulamadım
> 
> nasıl kurdun eski program klasörüne yeni dosyalar mı atılır?

Yes, the files inside (pyren-master). I threw it into the old program that was installed.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 yhis is ddt4all normaly
