### ISSUE TITLE
Ubuntu 17.04. ImportError: No module named QtWebKit

### ISSUE THREAD

**Issue by Sehok** [cedricp/ddt4all#5]
Hello!
I cant run this on Ubuntu 17.04/17.10. Can someone help with this?
`$ python ddt4all.py `
` Traceback (most recent call last): `
` File "ddt4all.py", line 10, in <module> `
` import PyQt4.QtWebKit as webkit `
` ImportError: No module named QtWebKit`

I tried to install python-qt4 and other python2.7 and qt4 packages. I tried to install PyQt4 (make and build it), but nothing helped.

**Comment by cedricp** [comment]
On Ubuntu 16, python-qt4 installs this file : /usr/lib/python2.7/dist-packages/PyQt4/QtWebKit.so
Can you locate it ?

**Comment by Sehok** [comment]
Thanks for the reply!
This file is missing, but I found information and solution why.
After version 4.11.2 python-qt4 package in [Debian](https://packages.debian.org/search?keywords=python-qt4&searchon=names&suite=all&section=all) does not contain QtWebKit. For ddt4all need python-qt4=<4.11.2.
So, solution, may be useful:
- First, install **old** python-sip 4.16.4. This is dependency of python-qt.
- `wget http://ftp.ru.debian.org/debian/pool/main/s/sip4/python-sip_4.16.4+dfsg-1_amd64.deb`
- `sudo apt install --reinstall ./python-sip_4.16.4+dfsg-1_amd64.deb`
- download and install python-qt
- `wget http://ftp.ru.debian.org/debian/pool/main/p/python-qt4/python-qt4_4.11.2+dfsg-1_amd64.deb`
- `sudo apt install --reinstall ./python-qt4_4.11.2+dfsg-1_amd64.deb`
Also add an old repository and install from there.
