### ISSUE TITLE
rlink 2 antitheft fix

### ISSUE THREAD

**Issue by Vuk031** [cedricp/ddt4all#503]
I have Renault Scenic 4
On device r link 2 on screen i have antitheft.
I virgined device with ddt, after that r link changed the vin number ( same as car vin) but i have same problem with antitheft on screen.
can anyone fix it?

**Comment by KarelSvo** [comment]
How is someone supposed to help without seeing your ddt4all log files?

**Comment by Timmytubby** [comment]
> I have Renault Scenic 4
> 
> On device r link 2 on screen i have antitheft.
> 
> I virgined device with ddt, after that r link changed the vin number ( same as car vin) but i have same problem with antitheft on screen.
> 
> can anyone fix it?

How do you Virgin it? Can figure out the procedure.

**Comment by AlMeu** [comment]
@Vuk031 
I can remove the antitheft code but I need the unit on my desk.

**Comment by Pekora78** [comment]
Buenas tardes. tengo 2  r-link 2  con el antirrobo activado ¿alguien tiene alguna solución?

**Comment by AlMeu** [comment]
@Pekora78 
An email and maybe I can help you.

**Comment by Pekora78** [comment]
daviciyo_78@hotmail.com este es mi correo y estaría muy agradecido por tu ayuda.

**Comment by florin2025** [comment]
Hello.
can you send an email, maybe you can help me with an antithelf code.
thank you

**Comment by AlMeu** [comment]
> @Vuk031 I can remove the antitheft code but I need the unit on my desk.

@florin2025 leave your email.

**Comment by florin2025** [comment]
florin_2013@yahoo.com thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by Arnaudkadjar** [comment]
Can someone help me with anti theth locked in R link Renault Kadjar. I ve tried to change VIN with renolink but no way, it doesn t change.thank

**Comment by AlMeu** [comment]
@Arnaudkadjar leave an email and perhaps I can help you.

**Comment by AlMeu** [comment]
@Arnaudkadjar you have to login on site for leave an email.

**Comment by Arnaudkadjar** [comment]
My email adress 
Arnaud.gugnot@gmail.com

**Comment by Zener-hub** [comment]
@AlMeu I have replaced my R-link two from another car after original unit got bricked. Changed the VIN on new unit before install but still antitheft activated. Can you help me removing antitheft? Thx

**Comment by AlMeu** [comment]
@Zener-hub leave an email and we can talk.

**Comment by Zener-hub** [comment]
Great, chandithp@yahoo.com
Thanks

**Comment by lklik** [comment]
Hi AIMeu i have the same problem this is my email ; azizouaankour@yahoo.fr

**Comment by gmzr0** [comment]
> @Zener-hub leave an email and we can talk.

is there any chance u could help me?

**Comment by Goran-Barznje** [comment]
Hi, someone help for same issues after replaced the nav radio for Rlink2.
goran_barznje@yahoo.com

**Comment by JohnnyX99** [comment]
Hello someone figured out how to virgin and deactivate theft mode ?
