### ISSUE TITLE
cornering and coming/leaving home possible in clio 4??

### ISSUE THREAD

**Issue by blade909** [cedricp/ddt4all#51]
i activated succesfull econometer and hour in dashboard of my clio IV with ddt4all,works great..but anybody knows if its possible to activate cornering function and coming home?where to search??
any help will be apreciated.

**Comment by karadas87** [comment]
![viraj aydinlatma](https://user-images.githubusercontent.com/37343989/38583840-fd1899a8-3d1c-11e8-94f8-a11b958f291d.jpg)

**Comment by blade909** [comment]
thanks ill try as soon as possible

**Comment by nasskach** [comment]
@blade909 Did you manage to enable that feature on your Clio 4 ? I'm also interested by enabling it on my Clio 4 Initiale Paris 2015.

**Comment by blade909** [comment]
not tried yet cause my clio is in garage for painting rear bumper but some pals in clioIV forum tried and works,even in traffic III,i hope try by the end of this week

**Comment by nasskach** [comment]
Yes I think that there is no specific device component needed other than the fog lights. Follow me home should be also something that we could enable (I don't know if I already have it on my Clio 4).

**Comment by blade909** [comment]
yesss it works,thank u so much karadas87 
you know if its possible comin home leaving home on clio 2014 expression?

**Comment by ZAFER1646** [comment]
2013 renault symbol viraj aydınlatma varmı içerizinde ve alarmı sesli olarak aktif oluyormu ? şimdiden teşekkürler

**Comment by blade909** [comment]
ZAFER1646  2013 yılının renault sembolü bir EMM bilgisayarına sahip değildir, bu nedenle aydınlatma eğrilerde etkinleştirilemez.
alarm hakkında cevap yok
Hangi bilgisayarları gördüğünüzü görmek için aracı taramanız gerekecek.

**Comment by ZAFER1646** [comment]
2014 renault symbol ve üzeri araçların yokuş kalkış desteği (HSA )açılmıyor ona göre yeni proğram varmı acaba siteden eylül ayında yayınlanan proğram çalışmıyor

iPhone’umdan gönderildi

blade909 <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (2 Eki 2018 01:09):


ZAFER1646 2013 yılının renault sembolü bir EMM bilgisayarına sahip değildir, bu nedenle aydınlatma eğrilerde etkinleştirilemez.
alarm hakkında cevap yok
Hangi bilgisayarları gördüğünüzü görmek için aracı taramanız gerekecek.

**Comment by ZAFER1646** [comment]
Esc sistemi mevcut fakat 2013 modelleri yapabiliyorum fakat 2013 üstü modelleri yapamıyorum orjinal clip cihazı ile açılıyor

iPhone’umdan gönderildi

blade909 <notifications@github.com<mailto:notifications@github.com>> şunları yazdı (3 Eki 2018 00:23):


Aracınız ABS sistemi ile birlikte ESC sistemi ile donatılmış mı?
ESC sisteminiz yoksa, HSA'yı etkinleştirmek mümkün değildir.

**Comment by ZAFER1646** [comment]
Merhaba benim araç renault symbol ecu kodu resimde var sis lambası viraj aydınlatma  nasıl aktif edebilirim ?




iPhone’umdan gönderildi

**Comment by mechatronicengineer** [comment]
I can't do active HSA option for my Dacia Sandero Stepway 2016 on Android App. I was able to change  T_Pulse_CF and LINK_WITH_REVERSE_CF opsions but I get an error message when I change the HSA option

**Comment by ZAFER1646** [comment]
Bunlarda viraj aydınlatması yok bende yapamadım

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________
From: zafer yilmaz <zafer1646@hotmail.com>
Sent: Friday, October 12, 2018 2:20:00 AM
To: reply@reply.github.com <reply@reply.github.com>
Subject: Viraj aydınlatma

Merhaba benim araç renault symbol ecu kodu resimde var sis lambası viraj aydınlatma  nasıl aktif edebilirim ?
