### ISSUE TITLE
ddt4all.exe 2.0 not working in windows 7 x32

### ISSUE THREAD

**Issue by alchired** [cedricp/ddt4all#513]
not working/ error python exe not x32 or x64 proggramm

**Comment by AndyIreland** [comment]
try downloading from here (download install and use at your own risk) 
[https://www.drive2.com/b/498093336985338243/](url) choose 'all cars' for renault and place an icon on the desktop when installing

**Comment by alchired** [comment]
Link not work....

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
