### ISSUE TITLE
ddt4all on easylink

### ISSUE THREAD

**Issue by jordirs2004** [cedricp/ddt4all#515]
Hello,

I have a clio 5 with easylink and I would like to activate the Wifi, Android Auto Wireless and Carplay Wireless on it.
My cable and my obd adapter work fine on my clio 4 with Rlink

On Easylink, I can read the value but I can't send the new value to it.

Is there anything special to modify it?

Thanks a lot.

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all/issues/404

**Comment by jordirs2004** [comment]
> #404

sorry, I haven't seen this topic, I'm going to read it

thx
