### ISSUE TITLE
How to activate Renault Koleos Talisman Megan 4 gear lever symbols

### ISSUE THREAD

**Issue by maistorqgata** [cedricp/ddt4all#521]
How to activate Renault Koleos Talisman  cvt automatic gear lever symbols light  P, D, N, R for ddt4all 
![Screenshot_20210118_233947](https://user-images.githubusercontent.com/77249091/104994469-2e322b00-5a2d-11eb-82a3-eabe4dba7325.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
