### ISSUE TITLE
Easy Link Megane 4 Phase 2 DDT4ALL

### ISSUE THREAD

**Issue by Squamifer** [cedricp/ddt4all#527]
Good morning all,

I currently own the new Megane 4 RS Line with the Easy Link. I wanted to know if it was possible to make changes with DDT4ALL and if so how to do it please, thanks.

They wrote on a german forum that writing to memory is blocked and it is necessary to have a renault decoder. However, I think someone could find a solution in time.

I tried it with DDT4ALL 7/9/2020 database, I have some information but I can't write it seems stuck and does nothing in memory. However, he manages to get the information.

Cordially.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
