### ISSUE TITLE
debian buster python3 qt.qpa.screen could not connect to any display

### ISSUE THREAD

**Issue by mikael35** [cedricp/ddt4all#528]
Bonjour Cédric,

It is not an issue, as I guess that someone as already run it on debian buster (ubuntu no support anymore 32bits cpu).
Maybe someone here has the solution, running as root: python3 ddt4all.py give me:
qt.qpa.screen: QXcbConnection: Could not connect to display
Could not connect to any X display.

Là le nouveau que je suis à linux bloque.

Regards,
Mikaël

**Comment by cedricp** [comment]
The question is : why do you run it as root ?
Do you have an X server running ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
