### ISSUE TITLE
change the seats belt warning

### ISSUE THREAD

**Issue by dexter2111** [cedricp/ddt4all#529]
Hello,
By default for Renault Captur 2019 the warning not to wear a seat belt is set at 22 km / h. 
Can the warning speed be changed? 
Thanks.

**Comment by EXcomZkko** [comment]
I'm not sure but you should check the BCM-->Doorlock screen.

**Comment by dexter2111** [comment]
Thank you for reply, but in the door lock i not find nothing about the belts.

**Comment by dexter2111** [comment]
it seems that no one knows the answer.  :(

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
