### ISSUE TITLE
Avaible options for a Clio 4 of 2015

### ISSUE THREAD

**Issue by ghost** [cedricp/ddt4all#53]
Hi,

I'm wondering what are interesting features that could be enabled on my Clio 4 Initiale Paris 2015. I already enabled Android Auto.

Thanks !

**Comment by blade909** [comment]
clio 5??sure you want say clio IV
tried econometer light in dashboard and hour
some pals with medianav evo tried rear sensors displayed on it

**Comment by nasskach** [comment]
@blade909 Yes sorry, it is a clio 4 of course.

**Comment by man0s** [comment]
@blade909 Did they managed to enable rear sensor display? If yes, do we have a tutorial/setting's name to enable it?

**Comment by blade909** [comment]
only way to enable rear sensor display is in micom settings on medianav,
you have to enter micom manager and enable HMI button on second line on menu,
depends of medianav version of course

**Comment by man0s** [comment]
Thanks for your response @blade909 👍

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/834
