### ISSUE TITLE
Bad ELM messages for TCU of Rlink1 Renault Zoe EV

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#531]
Hello - i cannot seem to change anything on my TCU of my Renault ZOE EV (X10)  in the DCM Renault part 
TCU is not being recognised when searching for ECU's  and if I select manually , lot of red boxes and 'Bad ELM' messages in window. - I am sure its not the ELM as I dont get 'bad ELM' on other settings and I have tried 3 different ELM's obd2 adaptors (2 Bluetooth ones and 1 wifi 802.11) 

any ideas please?

**Comment by KarelSvo** [comment]
> any ideas please?

without your log files?

**Comment by KarelSvo** [comment]
> any ideas please?

without your log files?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
