### ISSUE TITLE
Anyone know what MAX_TURN_POWER_LEVEL_X_ON_TM_CF (sec) does?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#534]
in the course of changing something I think I might have changed this accidently to '1' (1sec) or maybe not  in the BCM body control module settings and dont know what it should be set at by default (I know I should have took a picture of it beforehand , but unfortunately I didnt ) 

 MAX_TURN_POWER_LEVEL_X_ON_TM_CF (sec)
 
 the TM I should imagine = time  but that's all I know - does anyone know what it controls please?
 
 
![power level tm ddt4all](https://user-images.githubusercontent.com/49172217/107683854-fddf5480-6c99-11eb-854a-fa3a6605abc7.jpg)

**Comment by AndyIreland** [comment]
UPDATE:
I looked in the Log and it looks like the parameter is '5' as its default .

would still like to know what MAX_TURN_POWER_LEVEL_X_ON_TM_CF (sec) does though if anyone knows

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
