### ISSUE TITLE
Change VIN rlink 2

### ISSUE THREAD

**Issue by x3877** [cedricp/ddt4all#536]
Hi,I can’t change VIN on ddt4all of rlink 2 on megane 4.
Cant virgin because system lock
![8106FB2A-572E-4751-BD50-A01F076F3EA7](https://user-images.githubusercontent.com/78986743/107829582-57bf4780-6d8a-11eb-82d4-dcc6315e5546.jpeg)
Please, help me

**Comment by Tino1973** [comment]
Hello, did you solve it?

**Comment by Tino1973** [comment]
Hello, did you solve it?

**Comment by AlMeu** [comment]
Perhaps one testing desk can be solved.

**Comment by x3877** [comment]
> Hello, did you solve it?

Not solved

**Comment by x3877** [comment]
> Perhaps on testing desk can be solved.

I have juste can clip, ddt4all, and fvdi (all clone)

**Comment by AlMeu** [comment]
I believe., can't be erased with any interface in this status..
That's why I said, not in car.

**Comment by AlMeu** [comment]
Did you solve it?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
