### ISSUE TITLE
Change Calibration in BCM module (its read only) 

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#537]
**in an experiment say if I wanted to change REMOTE_LIGHTING_TM_TP (sec)  from 20 seconds to 30 seconds timeout :**
![change seconds remote lighting](https://user-images.githubusercontent.com/49172217/107999465-4fac1580-6fdf-11eb-9457-2cdc3dba0797.jpg)
**and there is no 'write' available - how can I change this figure?**

**If i find the BCM95_SW25_V1.1_20150429T131442.xml folder and open it up in notepad.exe on my laptop in the DDT4ALL folder and find:
REMOTE_LIGHTING_TM_TP (sec) this is what I get:**

![remote lighting time](https://user-images.githubusercontent.com/49172217/108000070-f47b2280-6fe0-11eb-80b4-01c8cb948093.jpg)
**is there anything i can change in that area to make it stay on 30 seconds instead of 20seconds? - if so what do I need to change or add?** 

thanks.

@KarelSvo @cedricp @

**Comment by AndyIreland** [comment]
> **in an experiment say if I wanted to change REMOTE_LIGHTING_TM_TP (sec) from 20 seconds to 30 seconds timeout :**
> ![change seconds remote lighting](https://user-images.githubusercontent.com/49172217/107999465-4fac1580-6fdf-11eb-9457-2cdc3dba0797.jpg)
> **and there is no 'write' available - how can I change this figure?**
> 
> **If i find the BCM95_SW25_V1.1_20150429T131442.xml folder and open it up in notepad.exe on my laptop in the DDT4ALL folder and find: REMOTE_LIGHTING_TM_TP (sec) this is what I get:**
> ![remote lighting time](https://user-images.githubusercontent.com/49172217/108000070-f47b2280-6fe0-11eb-80b4-01c8cb948093.jpg)
> **is there anything i can change in that area to make it stay on 30 seconds instead of 20seconds? - if so what do I need to change or add?**
> 
> thanks.

@KarelSvo @cedricp

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
