### ISSUE TITLE
R-LINK écran noir ,Renault talisman ,mise à jours,,merci ,et le bonjours à vous.

### ISSUE THREAD

**Issue by michel3108** [cedricp/ddt4all#539]
j'ai fais une mise à jours ,j'ai la radio ,mais l'écran reste noir,..

**Comment by michel3108** [comment]
Bonjour  j ai mi logiciel  ddt4all  je suis aller sur fracture  niveau display  moi il et déjà  activais sauf que j ai toujours écran noir

**Comment by AlMeu** [comment]
Depend what kind of upgrade you made.
If you made an upgrade not permitted by Renault for yor unit, perhaps you broken the unit.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
