### ISSUE TITLE
Hello I installed ddt4all latest version but it gives the error in the picture

### ISSUE THREAD

**Issue by org07** [cedricp/ddt4all#540]
Hello I installed ddt4all latest version but it gives the error in the picture
Also, it cannot find any ECU.

![ddt4all 1](https://user-images.githubusercontent.com/62398726/109176741-2a19cb80-7798-11eb-980d-03ffc71ddff3.PNG)

**Comment by org07** [comment]
![dd8](https://user-images.githubusercontent.com/62398726/109177392-cfcd3a80-7798-11eb-9c4c-2f57e29a3917.PNG)

**Comment by org07** [comment]
looking for a valiant to solve this problem

**Comment by AndyIreland** [comment]
hello - try download from here it includes ecu and will put a shortcut on your windows desktop for DDT4ALL - if you want to use on Renault choose "All Cars" download hope this helps (should be safe but use site at your own risk): 

https://www.drive2.com/b/498093336985338243/

**Comment by org07** [comment]
> merhaba - buradan indirmeyi deneyin, ecu içerir ve DDT4ALL için Windows masaüstünüze bir kısayol koyacaktır - Renault'da kullanmak istiyorsanız "Tüm Arabalar" indirmesini seçin, bunun yardımcı olacağını umuyoruz (güvenli olmalı, ancak siteyi kendi sorumluluğunuzdadır):
> 
> https://www.drive2.com/b/498093336985338243/

Thank you dear AndyIreland, already ddt4all and pyrene after ddt4all and pyreni are properly packaged, we are still downloading from Zmiterm blog. Nobody packs the update, they just patch

**Comment by KarelSvo** [comment]
Your error message says, that the ddt2000 ECU database is missing. 
Cedric is not the legal owner of this database, so he cannot add it.
You must to find the database yourself and copy it into the ddt4all folder.
I am not using this ddt4all Python 3 update. Some functions are still faulty there.

**Comment by org07** [comment]
> Hata mesajınız ddt2000 ECU veritabanının eksik olduğunu söylüyor.
> Cedric bu veritabanının yasal sahibi olmadığı için ekleyemez.
> Veritabanını kendiniz bulmanız ve ddt4all klasörüne kopyalamanız gerekir.
> Bu yeni ddt4all Python 3 güncellemesini kullanmıyorum. Orada hala bazı işlevler hatalı.

Can't download the latest version from here? I downloaded from here, it gives the errors I uploaded the picture above, it does not find any ECU

![ecu](https://user-images.githubusercontent.com/62398726/109378668-850d0900-78e5-11eb-8bcb-fa461613811a.JPG)

**Comment by KarelSvo** [comment]
This download is without the Ecu database. I have already explained to you why this is so.

**Comment by org07** [comment]
> Bu indirme Ecu veritabanı olmadan yapılır. Bunun neden böyle olduğunu size zaten açıkladım.
> 
> Ve bu güncelleme henüz tam olarak geliştirilmemiştir. Örneğin Wifi Elm çalışmıyor veya bayt 2180'e göre ECU tanımlaması yapmıyor.

Thank you very much KarelSvo for the information. If you weren't here, there is no one who has the skills to answer

**Comment by AndyIreland** [comment]
am I allowed to mention this here - if not sorry and feel free to delete . the DDT4all with ECU's and a shortcut on your desktop can be downloaded from here (visit site and download at your own risk) 

https://www.drive2.com/b/498093336985338243/

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
