### ISSUE TITLE
trying to read TCU - Bad ELM (7F3E21) messages

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#542]
Hello can someone help me please - I have tried 3 different ELM's 2 Bluetooth ones and a wi-fi one. 

My Rlink Store is greyed out on my rlink as is my TomTom live services. - I have subscriptions to both. Both in date. 

I decided then to see what provisions services were activated on my TCU. 

DDT4all would not find the TCU when doing search with magnifying glass, so rather than blindly picking a TCU I loaded PyREN on my laptop and it found the TCU in my car of  TCU_GEN2_V3.2 DCM

So I chose TCU_GEN2_V3.2 DCM in DDT4ALL.  with my Bluetooth ELM327 with a PIC18F25K80 and go to Services to see if Internet Widget Store and TomTom Live services is all 'activated' but when I try to read all I get is red boxes and 'No Data' in the window it says 'Bad ELM (7F3E21) ' see pic:

![155267206_258846722283790_3448830900158612627_n](https://user-images.githubusercontent.com/49172217/109439040-a9233400-7a24-11eb-932e-ab75054d46eb.jpg)

![155296947_346614729901507_252321711802510174_n](https://user-images.githubusercontent.com/49172217/109439084-ceb03d80-7a24-11eb-9e2e-1bb1266a0ac7.jpg)

![155811488_438253050934943_5877942343802584974_n](https://user-images.githubusercontent.com/49172217/109439107-eedffc80-7a24-11eb-8cd0-6931956077b2.jpg)

![tcu services](https://user-images.githubusercontent.com/49172217/109439254-82b1c880-7a25-11eb-8acb-af919cf49d03.jpg)

and look they are all red:
![156135183_2823048477937541_3781084704154495939_n](https://user-images.githubusercontent.com/49172217/109439305-b68cee00-7a25-11eb-909b-750d79d81397.jpg)

so there is no way of telling what is activated or deactivated in the services - I am almost sure this maybe why the icons are greyed out on my R-link and cannot be accessed? 

Here is what PyREN reports all of them deactivated!! :( 
![156228940_2390612841084506_3289569912394479565_n](https://user-images.githubusercontent.com/49172217/109439492-6e220000-7a26-11eb-9c5b-8116acb767e5.jpg)

here is log files - i cannot understand them or what they mean , maybe they throw some light on the matter?

[screens.txt](https://github.com/cedricp/ddt4all/files/6058497/screens.txt)

Many thanks for help I really want to get these activated if I can 

**EDIT: Actually this is a strange thing before when I have read the TCU (or rather PyREN has found the TCU) its found it as a  TCU_GEN2_V3.2     but tonight it says its a ECU : 11258  TCU_LC_0000_05_REFB
thats strange!**

**Comment by KarelSvo** [comment]
> here is log files

No ddt4all and pyrene log files available, only screens.txt.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
