### ISSUE TITLE
Can't connect over BT ELM327 - invalid literal for int() with base 10 error

### ISSUE THREAD

**Issue by szumial** [cedricp/ddt4all#544]
Hi! I am having an issue with a Bluetooth ELM327 adapter + modified cable. The BT module is an iCar VGATE2 which I have seen some colleagues working with. The DDT4All screen flashes and disappears after selecting bluetooth connection. I managed to take a screenshot of the error message. Interestingly, I can connect to the program when selecting the standard USB cable icon, but then the ECUs are empty and the program does not read any values. What could be the issue?

I am using the latest DDT4All version from the releases section and my car is a Laguna 3 PH3.
![2](https://user-images.githubusercontent.com/55056818/109658805-49817180-7b67-11eb-902b-85cc415f2d4e.png)

**Comment by KarelSvo** [comment]
> I am using the latest DDT4All version from the releases

This version still has various bugs.

**Comment by szumial** [comment]
Can you suggest which release should I use instead?

**Comment by KarelSvo** [comment]
https://www.drive2.ru/b/498093336985338243/

**Comment by tomasz-soltysik** [comment]
This issue was fixed in #511. There is no release yet with this change, but you can clone repo or download it.

**Comment by meerkovo37** [comment]
> This issue was fixed in #511. There is no release yet with this change, but you can clone repo or download it.

How would I go about downloading this to solve this issue, just had this happen with my Bluetooth ELM scanner today

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
