### ISSUE TITLE
"Float" object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Cahouete21** [cedricp/ddt4all#547]
Hi Cedric !

With the live data in "Megane III" -> "ECM" -> "EMS3110_RD9_xxx_X95_L38_B32_L43_X91..." -> "Lecture" -> "Sondes & Richesse", I can crash DDT4ALL :

![image](https://user-images.githubusercontent.com/62177601/110766417-6ef03880-8255-11eb-8881-94c30ef44784.png)

I guess there is a casting "Float" -> "Integer" that is not intended to be done there... I'm not sure to well understand the crash cause.

**Comment by cedricp** [comment]
Try to replace some lines above : 
**nframes = nbytes / 7 + 1**
with
**nframes = int(nbytes / 7) + 1**

**Comment by cedricp** [comment]
Python3 porting issue

**Comment by figs1** [comment]
Also having same issue !

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
