### ISSUE TITLE
Upgrading my  2017 Koleos 7 inch display to a 8.7 inch display

### ISSUE THREAD

**Issue by Koleosguy321** [cedricp/ddt4all#548]
Hey, so getting a 8.7 inch from a salvage 2017 Koleos Intens to replace my 7 inch display on my 2017 Koleos Zen

Got a few questions regarding this.

Before I remove the unit in the salvage car, I have to enter dev mode via usb method and go on 'virgin mode' to reset the VIN. Is this correct? 

After I do this, I install the head unit into my car..This is the part where I'm not sure what I have to do. 

Do I need to take it to a dealership to finish the process? Or do I need to write my car's vin into the unit now? (if so, how?) What do I do at this stage? Also, correct me if I am wrong on any other step.

Thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
