### ISSUE TITLE
would anyone have a dump of 1615489415_Radio_2012_V2.4_20130604T134716.txt ?

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#549]
would anyone have a dump backup of 1615489415_Radio_2012_V2.4_20130604T134716.txt for the r-link1 of Zoe they can send me please or upload to drive etc? 

I realise the car section of the dump will have another cars VIN and CRC but what I am thinking is that i could put my car's VIN and CRC in the boxes instead and it will be OK ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
