### ISSUE TITLE
bad elm response wrong response cfc0 unknown

### ISSUE THREAD

**Issue by mrhappychappy83** [cedricp/ddt4all#55]
Hi there, I too am trying to activate Android Auto in my Renault Megane III with R-Link 1.  I have followed all steps, made the modified cable, and my OBD scanner seems to be communicating with the ECU but not properly.  When I try to write the new Navigation settings, I get the error in DDT4All which reads: "bad elm response wrong response cfc0 unknown".

I have no idea what this means or what could be causing the problem. Can anyone help? Attached are the log files also. Appreciate your time in advance.

[elm_ddt_log.zip](https://github.com/cedricp/ddt4all/files/1983754/elm_ddt_log.zip)

**Comment by mrhappychappy83** [comment]
BTW, my R-Link is updated already to the latest version

**Comment by cedricp** [comment]
It looks like a bad ELM327 clone... Did you try to start a benchmark on the first window ? If it ends up with "**incompatible ARM core**", you'll need to get a _real_ ELM with PIC18F25K80 chip.

**Comment by mrhappychappy83** [comment]
Thanks for the fast reply, Cedric!I ran the benchmark test blue and got 0 of 95 successful and the incompatible ARM core message :(
Just to confirm, when I run this test, is ok if the cable is not connected to the car? I only connected to the computer by USB.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Cedric PAILLE <notifications@github.com> Date: 8/5/18  10:51 pm  (GMT+10:00) To: cedricp/ddt4all <ddt4all@noreply.github.com> Cc: mrhappychappy83 <dariopaolini@me.com>, Author <author@noreply.github.com> Subject: Re: [cedricp/ddt4all] bad elm response wrong response cfc0 unknown (#55) 
It looks like a bad ELM327 clone... Did you try to start a benchmark on the first window ? If it ends up with "incompatible ARM core", you'll need to get a real ELM with PIC18F25K80 chip.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cedricp/ddt4all","title":"cedricp/ddt4all","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cedricp/ddt4all"}},"updates":{"snippets":[{"icon":"PERSON","message":"@cedricp in #55: It looks like a bad ELM327 clone... Did you try to start a benchmark on the first window ? If it ends up with \"**incompatible ARM core**\", you'll need to get a _real_ ELM with PIC18F25K80 chip."}],"action":{"name":"View Issue","url":"https://github.com/cedricp/ddt4all/issues/55#issuecomment-387391539"}}}

**Comment by cedricp** [comment]
Yes, you can do the test disconnected from the car. Your interface is definitely not the good one.

**Comment by mrhappychappy83** [comment]
OK that's a shame but thank you for helping me work this out. I will buy one with the proper chip and try again.


On May 09, 2018, at 06:56 AM, Cedric PAILLE <notifications@github.com> wrote:

Yes, you can do the test disconnected from the car. Your interface is definitely not the good one.

**Comment by fd007s** [comment]
I also have a clone chip " incompatible ARM core message 90/95" . I managed to resolve "bad elm response wrong response cfc0" by changing the driver.
Now i have a new problem: I have a red column with " No data" after i enter on dt4all- megane 3 -navigation-...etc. I can't flash anything.
I don't know what seems to be the problem: wrong chip, wrong wiring.
So i made a test: i connected the elm device to laptop but not to car.
i had the same result "No data"
Is there a way to check the cable or the connection between elm device and car?
Sorry for my bad english.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/834
