### ISSUE TITLE
How to turn off traction control (esp) on Captur 2

### ISSUE THREAD

**Issue by Pogachnik** [cedricp/ddt4all#552]
I have try to turn off like on a megane 4 but this is immposible.

**Comment by AndyIreland** [comment]
I have managed to turn off esp / traction control on the wife's Clio mk4 before once no problem - its in the ABS braking ECU ... then an error light and spanner comes up on dash as well as a car skidding icon but even them can all be removed with the ddt cluster ecu settings

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by AndyIreland** [comment]
> How can I enable Sport Mode using the DDT4All program on a 2023 Duster Essential without MediaNav?

you more than likey will have to unlock the security gateway with a token first before doing any adjustments using DDT4ALL
