### ISSUE TITLE
DDT4All NO DATA

### ISSUE THREAD

**Issue by Koleosguy321** [cedricp/ddt4all#557]
Hello, so I'm trying to active Android Auto on my rlink2 system on my 2017 Koleos, but when I connect using Bluetooth ELM 327, it shows all "NO DATA" in the audio section. I have 09/07/2019 database

Anyone know why is this?

EDIT:

Researching this, it does not seem to be a common problem and when it does occurs, it is usually because a bad clone was used so I'll try to buy a different device and see if it works after that. Will keep this post updated for people that have this issue in the future

EDIT2:

Decided just to get it to work via developer mode instead.

EDIT3:

Finally resolved. I used a bluetooth ELM 327 and this seems to have issues with the program. Heard and seen WIFI ELM 327 used successfully, but the solution for me was to get the USB ELM327 then install the ELM327 window drivers from totalcardiagnostics by following every step of their guide. This ended up resolving the issue I had

**Comment by ElTurco19** [comment]
Hello Koleos you should use an adapter with USB, BBFly or Vint brand is a good product. Good luck.

**Comment by Koleosguy321** [comment]
> Hello Koleos you should use an adapter with USB, BBFly or Vint brand is a good product. Good luck.

Thanks for the help. I ordered a USB elm327, so I'll try that and if it doesn't work then I'll try one of those brands you mentioned.

**Comment by ElTurco19** [comment]
Hi,

be careful to choose a chip Pic18f24k80 or better Pic18f2480 and also the quartz 4000 mhz. The ideal would be a 2x faster stn1170 but no worries with the Elm 

good luck.

**Comment by Koleosguy321** [comment]
> Hi,
> 
> be careful to choose a chip Pic18f24k80 or better Pic18f2480 and also the quartz 4000 mhz. The ideal would be a 2x faster stn1170 but no worries with the Elm
> 
> good luck.

Hey so the eln327 USB one was even worse, didn't even detect it on my ddt4all.

I need to get obd MX+ for a different car. You reckon that one will work fine?

Could you link me one that will work?
