### ISSUE TITLE
bunları nasıl aktif edebilirim megan 2

### ISSUE THREAD

**Issue by tcebe** [cedricp/ddt4all#558]
![Ek Açıklama 2021-04-02 174901](https://user-images.githubusercontent.com/81833450/113457917-c11e1700-9419-11eb-874e-e85cec8f2b0f.jpg)

**Comment by org07** [comment]
:) 
bunlar aktif zaten

**Comment by org07** [comment]
sen buncacık bilgiyle arabayı bozarsın çok fazla karıştırma hatta hiç karıştırma benden söylemesi

**Comment by tcebe** [comment]
org07 sende fazla bilgi varsa anlat bi zahmet bilgimiz olsun ?
aktif olsa çalışır herhalde pyren programından baktıgımızda bu ekran cıktı..

**Comment by ElTurco19** [comment]
Hi tcebe you should already start by greeting people and writing in English so that everyone understands and supports you.

Selam tcebe, öncelikle bir yazıya başlarken insanları selamlamak en az terbiye gerektiren bir bilgidir. Sonra ingilizce sorarsan daha çok insan anlar ve yardım eder sana.

**Comment by org07** [comment]
1 tanesinin örneğini vereyim o klima isteği devre dışı demesi senin klimanın kapalı olduğunu söylüyor klimayı açtın mı orada KLİMA aktif yazacak onun için diyorum samimi diyorum sen o programlarla arabanı kurcalama kesin bozarsın ve baya bir maliyetli olur.  Programın yazarı **Shrlnm** Türkçe bilseydi seni bu forumda banlardı ;)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
