### ISSUE TITLE
Adding relays to switch CAN1 to CAN2

### ISSUE THREAD

**Issue by ElTurco19** [cedricp/ddt4all#559]
Hello to all Git members. 

Is it possible to add a relay module to switch from CAN mode to CAN Multimedia mode automatically? 

Thank you.

**Comment by KarelSvo** [comment]
An interface with STN 1170 chip has 2 CAN channels that can be selected via software commands.

**Comment by ElTurco19** [comment]
Hi KarelSvo 

Thank you for the information, actually i saw a relay module assembly for Ford software, the person uses a stn1170 but he has the possibility to choose the mode (manual with switch) or (automatic with a relay) which is not available on DDT4ALL. 

If you have a tip i could try and share the diagram and the end result. 

Thank you.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
