### ISSUE TITLE
Need DDT4ALL values for 8.7 inch rlink2 system (anyone with 8.7 inch rlink2 screen + DDT4ALL can help)

### ISSUE THREAD

**Issue by Koleosguy321** [cedricp/ddt4all#561]
Hello, so upgrading my 7 inch to 8.7 inch, but I need to know certain DDT4ALL values to do this.

If someone could connect their rlink2 8.7 inch screen to DDT4ALL and take a screenshot of 

AUDIO -->RADNAV --> ENGINEERING CONFIGURATION --> Central panel-display parameters (at the bottom). 

Next and finally, I need

HVAC --> ClimBoxGen2_v29 (or whatever you have thats similar) --> CLIMBOX+ --> Global-configuration --> CL_WithControlPanel.

Appreciate anyone who helps me out, thanks.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
