### ISSUE TITLE
After Ecu reset I can't hear voice on my Kadjar  hands-free. Media streaming is working fine. Can someone help me please!

### ISSUE THREAD

**Issue by alexal100** [cedricp/ddt4all#562]
After Ecu reset I can't hear voice on my Kadjar  hands-free. Media streaming is working fine. Can someone help me please!

_Originally posted by @alexal100 in https://github.com/cedricp/ddt4all/issues/114#issuecomment-821309131_

**Comment by ElTurco19** [comment]
Hi friend, more info should be given, why did you reset, how did you reset ...

**Comment by alexal100** [comment]
I had some issues with R-Link 2 and I thought the reset fixes everything. Wrong  :)
I was able to set it again, only phone parameters ar missing now. I have tried to implement the two acustic macro providet, didn't work for me.
