### ISSUE TITLE
How to fix black screen 

### ISSUE THREAD

**Issue by shahram241** [cedricp/ddt4all#563]
Hi, I updated version 3 to version 8 and then to version 9, but my R-link is not working properly. Please help me?
Many items do not work.
there is no sound.
The air conditione turns on automatically

@shrlnm

**Comment by shrlnm** [comment]
Hi
What is micom version? If you did not upgrade it in an official garage then I afraid I can not help you. You may only try to downgrade it back to original version 3

**Comment by shahram241** [comment]
hi @shrlnm 
What is micom version?
I upgraded myself with unofficial software: version 3.3.6.980 to 9.0.34.616
Please help me?

**Comment by shrlnm** [comment]
micom version should have 4 digits. 5276 for example

**Comment by shahram241** [comment]
version is 5276

**Comment by shrlnm** [comment]
Then there is no way. 5276 is incompatible with LGU v7 and upper.

**Comment by shahram241** [comment]
Where should I go?

**Comment by shahram241** [comment]
I was able to reduce the R-link version to 2.2.19.301
But after the upgrade, it turned black to version 3 pages and remained in boot mode.
You can guide me
https://uupload.ir/files/a2gv_2.2.jpg
@shrlnm

**Comment by shrlnm** [comment]
@shahram241 did you downgrade to 2.2.19.301 or to 3.3.16.986?

**Comment by shahram241** [comment]
@shrlnm Yes, I downgraded to  version 2, but when I tried to return to the original version, the screen turned black

**Comment by shahram241** [comment]
@shrlnm I installed the files you gave me, but the screen is still black.The air conditione turns on automatically
cmdr_radnav_high_repair.py
mod_elm.py
mod_globals.py

**Comment by shrlnm** [comment]
If these scripts repaired the box before but now not help, then I afraid the box is dead (

**Comment by shahram241** [comment]
@shrlnm You gave these scripts to Virgin mode.
Can a new script help?

**Comment by shahram241** [comment]
@shrlnm The old scripts had 290 errors when running

**Comment by shahram241** [comment]
@tina2004 Hello, has your problem been solved?

**Comment by shrlnm** [comment]
I can help only after virginizing or configuration reset. Unfortunately I can not help after wrong upgrade/downgrade procedure.

**Comment by shahram241** [comment]
@shrlnm After downgrade to the lower version 2.2.19.300, I clicked on this option and the screen turned black
1.Clear DTC
2.Configuration Reset
3.Hard Reset
https://uupload.ir/files/v6uk_2.2.jpg

**Comment by shrlnm** [comment]
@shahram241 if it was reset then give me your email and I try to help

**Comment by shahram241** [comment]
@shrlnm shl241@yahoo.com

**Comment by shahram241** [comment]
Hello
I can install this unit for my car, is it compatible?
Talisman 2017
Thank you
RADYO MULTİMEDYA BEYNİ LANR 16 ORİJİNAL LG 281156817R 281154385R 281157255R

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
RADYO MULTİMEDYA BEYNİ LANR 16 ORİJİNAL LG 281156817R 281154385R 281157255R

Renault Megane 4, Talisman, Kadjar Radyo Beyni Uygun Fiyata Bonpar'la Hemen Kapınıza Gelsin.
 |

 |

 |




    On Sunday, April 18, 2021, 9:02:40 PM GMT+4:30, shrlnm ***@***.***> wrote:  
 
 


Then there is no way. 5276 is incompatible with LGU v7 and upper.
