### ISSUE TITLE
Clio III ph2 can't change c3i injector code 

### ISSUE THREAD

**Issue by Mikescotland** [cedricp/ddt4all#564]
Trying to change 20 digit injector code via Ecu tweaker and ddt4all. Elm Bluetooth.
Reads fine, writing returns error and codes stay the same 
Any thoughts please?

DCM34 - P4BCx_X61_X77_X85_X44_V16
CAN SENT: [21-04-02:52:13] 10C0
CAN RECV: [21-04-02:52:13] 50C0
CAN SENT: [21-04-02:52:13] 2EFD28304C574D47423831543554554135503344435530
CAN RECV: [21-04-02:52:13] ERROR : 23435530
NO DATA

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
