### ISSUE TITLE
I cant connection to ecu

### ISSUE THREAD

**Issue by Ba2aribakisli** [cedricp/ddt4all#571]
Hi,I connected my obd2 device but when ı tried connecting any ecu app has freeze on the initializing CAN protocol section.Can you help me ?

![Screenshot_20210511_142529_org quark dr canapp](https://user-images.githubusercontent.com/84018970/117811009-bea8ab80-b268-11eb-9d78-fd8a5370dc66.jpg)

**Comment by KarelSvo** [comment]
Do an Elm test with ELM327 Identifier https://play.google.com/store/apps/details?id=com.applagapp.elm327identifier&hl=tr&gl=US
Show the RAW data from this test.  If ATPPS is not supported, your Elm is probably not suitable. 
Also read this documentation on poorly copied Elm interfaces https://cvtz50.info/en/elm327/

**Comment by Ba2aribakisli** [comment]
I did elm test and my device not supported ATPPS.
Thanks for help.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
