### ISSUE TITLE
Official V2.0 distribution does not work under 32bit Windows 7 (wrong python version is installed)

### ISSUE THREAD

**Issue by tjwasiak** [cedricp/ddt4all#579]
Could you provide download link to Python and it's libraries compatible with 32bit Windows 7?

**Comment by tjwasiak** [comment]
If anyone needs x86 python with all required libraries it could be downloaded [here](https://mega.nz/file/VkFH2Ipa#9tzDutSrn7JVj19X885oka9vSOFZo4UFniGEQ3fc2bw). This was created using official python 3.8.10 x86 distribution with all required modules installed using pip.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
