### ISSUE TITLE
do you need to solder other wires

### ISSUE THREAD

**Issue by sgouman** [cedricp/ddt4all#58]
hello.

I want to enable android auto on my renault clio iv GT from 2014 with rlink1.

i want to buy this obd tool.

https://nl.aliexpress.com/item/p-c18f25k80-chip-super-obd2-elm327-w-f-bluetooth-v1-5-hardware-works-android-ios-elm/32856391100.html?spm=

do i need to solder any wires if i open that case and if so what cables?

or does it work out of the box?

**Comment by Voytexgpl** [comment]
Yes, you have to.
I did it and it works with Laguna 2014

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/834
