### ISSUE TITLE
Stuck in console

### ISSUE THREAD

**Issue by ioneld** [cedricp/ddt4all#584]
Hi guys, i'm trying to connect ddt4all with elm327 but it stuck in console, it says ddt4all pause. For all versions. Im using windows7 x86.
Elm was tested with ddt and it sais it is ok!
What i am doing wrong?

**Comment by ioneld** [comment]
![Uploading 20210624_151040.jpg…]()

**Comment by ioneld** [comment]
![20210624_150938](https://user-images.githubusercontent.com/50890199/123260634-7387e680-d4fe-11eb-80cf-75b2cd726cc7.jpg)

**Comment by KarelSvo** [comment]
The current python 3 version has unrepaired bugs.Use the latest python 2 version and everything works fine.

**Comment by ioneld** [comment]
Thanks, i will try python 2!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
