### ISSUE TITLE
Synchronisation ABS wirh dashboard Megane 3 1.9dci 2009

### ISSUE THREAD

**Issue by aliloup85** [cedricp/ddt4all#585]
Hi all, and sorry for my poor english;

I've changed my Abs calculator, i had red message error that there is a brake problem. The mechanic did a test at first and the error was gone, but the dashboard displays a new odometer: 350.000km instead of 220.000km!!

I took the car to another mechanic to preplace the old calculator and he has corrected the display and it returned 220.000km; but when i do a scan with DDT4all I find a different info inside the ABS calculator: another VIN with more than 350.000km. 

My question: is there any solution on DDT4all to synchronise my ABS calculator with my original dashboard?

**Comment by Marianpol** [comment]
There is nothing you can do with the DDT4ALL. You need to download content of a ABS EEPROM memory (it's a 95160), edit mileage stored there and write the data back into the ABS EEPROM. Read and write of a memory can be done using programmer.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
