### ISSUE TITLE
ddt4all: crashes on ecu scan

### ISSUE THREAD

**Issue by Sig2018** [cedricp/ddt4all#586]
I've switched Hard drive then I reinstalled ddt4.
It works if I go to a specific ECu but If I scan ECUs then ddt4 crashes and shut down.
The curious thing is the error doesn't show in the same percentage of scan, sometimes is sooner than others.
I-m not sure where the crash log is but I have a screen shot of lines and error.
The final line is: AttributeError: 'filter' object has no attribute 'strip'
Please take a look and let me know if you can help me with this issue.
Thank you
![ddt4 crash](https://user-images.githubusercontent.com/39195035/123529276-a972c980-d6bc-11eb-8ef5-e2785fa659cb.JPG)

**Comment by KarelSvo** [comment]
What exactly from which source did you install?

**Comment by Sig2018** [comment]
Hi @KarelSvo , Thank you for your quick answer.
I'm almost sure it is version form drive2.ru forum ddt4all All cars.exe
What I'm not really sure is if I replaced the original ecu file for a new one.
Maybe I did something wrong in new installation but same version was working on previous hard drive.
It has something to do with source or it is ecu or something else?

**Comment by Sig2018** [comment]
@KarelSvo  any idea in what may cause that error?
Thank you.

**Comment by SoaAlex** [comment]
I have the exact same issue :( Does someone know what it could be ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
