### ISSUE TITLE
RLink2 antitheft mode active

### ISSUE THREAD

**Issue by Pedrom92ps** [cedricp/ddt4all#589]
Hello, its possible remove antitheft mode? Have Changed unit but antitheft mode activate. Try Change VIN with DDT4ALL but not working.

**Comment by AlMeu** [comment]
I can help you, if I get the the unit.

**Comment by Pedrom92ps** [comment]
Para onde teria de enviar?Em 14/07/2021 06:31, NeeK ***@***.***> escreveu:
I can help you, if I get the the unit.

**Comment by AlMeu** [comment]
> 
> Para onde teria de enviar?Em 14/07/2021 06:31, NeeK ***@***.***> escreveu: I can help you, if I get the the unit. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

?????

**Comment by Pedrom92ps** [comment]
where would it have to ship?Em 14/07/2021 15:59, NeeK ***@***.***> escreveu:



Para onde teria de enviar?Em 14/07/2021 06:31, NeeK @.***> escreveu: I can help you, if I get the the unit. —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.



?????

**Comment by AlMeu** [comment]
write in clear your email because as you see is nothing.

**Comment by AlMeu** [comment]
log in on github and write the email address, do not reply by email, because as you can see it will show your email as *** @ ***. ***

**Comment by Grazi77** [comment]
> I can help you, if I get the the unit.

ciao, i have rlink2 blocked with antitheft actived.
help me!!! g.torazza@gmail.com

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
