### ISSUE TITLE
code injectors - Megane 3

### ISSUE THREAD

**Issue by marcuscl** [cedricp/ddt4all#590]
Hello, i can't find where to code new injectors in DDT4ALL, can anyone help me out? :)

Renault Megane 3 2011
![118553337-76a1f100-b760-11eb-9c02-a8144db2af5b](https://user-images.githubusercontent.com/33003105/124840644-be3c4080-df8b-11eb-9c47-257cca13e778.png)

**Comment by KarelSvo** [comment]
What is the Diagversion of your SID305?
Which new codes should be assigned to which cylinder?

**Comment by marcuscl** [comment]
> What is the Diagversion of your SID305?
> Which new codes should be assigned to which cylinder?
> The code must be sent divided into 2 parameters.
> And there are 2 different methods, depending on the diagnostic version of the control unit.
> The difference is the emission standard euro 4 or 5. Do you also use Pyren? https://gitlab.com/py_ren/pyren In ddt4all, the code can only be sent via manual input, which is a complex process at euro 5. What language do you speak? With Pyren is easier to write the code and Pyren supports different languages.

Hello, thanks for you reply :)
How do i check the Diagversion? 

I haven't got the injectors yet because, i first got the wrong injectors. I think my car is Euro V. 
I have Pyren and have tried to change to injector codes but it says "There is a scenariumi do not support them!!".

**Comment by Marianpol** [comment]
> Hello, thanks for you reply :)
> How do i check the Diagversion?
> 
> I haven't got the injectors yet because, i first got the wrong injectors. I think my car is Euro V.
> I have Pyren and have tried to change to injector codes but it says "There is a scenariumi do not support them!!".

Here is the instruction how to do it in PyRen.
https://www.drive2.ru/l/561334222158037462

**Comment by marcuscl** [comment]
> > Hello, thanks for you reply :)
> > How do i check the Diagversion?
> > I haven't got the injectors yet because, i first got the wrong injectors. I think my car is Euro V.
> > I have Pyren and have tried to change to injector codes but it says "There is a scenariumi do not support them!!".
> 
> Here is the instruction how to do it in PyRen.
> https://www.drive2.ru/l/561334222158037462

Thanks! :)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by InsanityM** [comment]
> > Hello, thanks for you reply :)
> > How do i check the Diagversion?
> > I haven't got the injectors yet because, i first got the wrong injectors. I think my car is Euro V.
> > I have Pyren and have tried to change to injector codes but it says "There is a scenariumi do not support them!!".
> 
> Here is the instruction how to do it in PyRen. https://www.drive2.ru/l/561334222158037462

Hi, I read that tutorial and the others made by the same guy, but i found a video on youtube and that guy was writing the codes fro injectors on a lagune 2 without the hassle from this tutorial, but for me it is not working. Here is the video https://www.youtube.com/watch?v=G2M7R14Ut4c&t=195s
