### ISSUE TITLE
Je me doute bien qu'une simple Led ne va pas résoudre le problème, par contre changer les résistances, le condensateur et modifier quelques pistes n'a rien d'insurmontable et serais moins couteux que de changer le volant.

### ISSUE THREAD

**Issue by Guigui63118** [cedricp/ddt4all#592]
Je me doute bien qu'une simple Led ne va pas résoudre le problème, par contre changer les résistances, le condensateur et modifier quelques pistes n'a rien d'insurmontable et serais moins couteux que de changer le volant. 
Peut être que c'est pas possible mais je serais bien tenté d'essayer quand même. Après tout cela n'engage que moi non ??  ;-);-);-) 
Et si ça marche c'est cool pour tous le monde !!!!
Mais pour cela j'ai besoin des photos du modèle pour essayer de le reproduire. Si J'y parviens, je m'engage à fournir un tuto complet de la procédure.
D'avance merci...

_Originally posted by @Guigui63118 in https://github.com/cedricp/ddt4all/issues/47#issuecomment-877865768_

**Comment by logic7986** [comment]
I don’t have photoes of the disassembleded buttons. It is on glue, my friend opened it but no photo.
I bought almost new steering wheel with heating and acc button in Poland for 100€. 
There is a klondike of spare parts))))
