### ISSUE TITLE
Activating TPMS

### ISSUE THREAD

**Issue by mfarramadan** [cedricp/ddt4all#595]
Hello,
I bought 4 TPMS as my car was not equipped with any. Now I installed and activated them in the dashboard and the screen. I aslo noticed that the car did autolearn their ID after a ride. As it is avaikabe in the TPMS screen in ddt4all.
Still i am not getting the tpms readings on the screen. Is there anything else i need to do in ddt4all ?
My car is a Megane 4 2018 1.6

**Comment by AndyIreland** [comment]
have you enabled the TPMS presence in the BCM/UCH ECU on your car? 
![tpms](https://user-images.githubusercontent.com/49172217/126082815-9df4ae44-7d0d-4d2f-8a33-0f472d2b697e.jpg)

**Comment by mfarramadan** [comment]
Yes tried it and it gives me prgm error in the cluster screen.

**Comment by AndyIreland** [comment]
Ah right, on the Clio mk4 there were 2 types of TPMS  'indirect' TPMS and 'direct' TPMS  if it was set wrong you got a programme error  like that I think
are they original Renault TPMS valves you have put in the wheels?

**Comment by mfarramadan** [comment]
> Ah right, on the Clio mk4 there were 2 types of TPMS 'indirect' TPMS and 'direct' TPMS if it was set wrong you got a programme error like that I think
> are they original Renault TPMS valves you have put in the wheels?

Nope. Copy ones

**Comment by mfarramadan** [comment]
But still they are direct ones as they are connected to the air valve.

**Comment by AndyIreland** [comment]
cannot think then sorry hope someone else can help

**Comment by mfarramadan** [comment]
> cannot think then sorry hope someone else can help

Thanks a lot for ur help.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
