### ISSUE TITLE
Rest.activate for talisman xfd

### ISSUE THREAD

**Issue by alireza6631** [cedricp/ddt4all#598]
Hi guys
![20210704_183832](https://user-images.githubusercontent.com/45830886/126468052-778edd7a-7320-472c-a7cf-6df32a6cbac9.jpg)

I want to start the car with the remote but I had a 
problem. I activated all the wiring but the software has not been activated yet. Does anyone know how to help me? Thank you.

**Comment by Furtif** [comment]
same stuf as res by MICOM https://github.com/cedricp/ddt4all/issues/836 find it
