### ISSUE TITLE
Dtc95334A ddt4all ile işlem yaparken bu şekilde bir hata aldım araç tek Marş yapıp kalıyor 

### ISSUE THREAD

**Issue by yasinklc** [cedricp/ddt4all#601]
Lütfen nasıl yapacağım konusunda yardımcı olurmusunuz

**Comment by KarelSvo** [comment]
Zero information on vehicle and control unit  ;-)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
