### ISSUE TITLE
ddt4all will not connect to Wifi but phone will connect using different applications

### ISSUE THREAD

**Issue by s-demp** [cedricp/ddt4all#602]
I have a Wifi obd2 that other users have said works with ddt4all.  Phone can connect and read using multiple different apps.

When connecting using laptop and ddt4all (Windows 10) the terminal just sits trying to connect to the ip and port.  It doesn't time out.  The ELM check doesn't work either.

If I select a different port it fails automatically so it does seem to be making some sort of connection.  

Are there any settings that I can change to fix this?

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all/issues/591

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
