### ISSUE TITLE
Renault megane IV parking sensors wiring

### ISSUE THREAD

**Issue by Pedrom92ps** [cedricp/ddt4all#603]
hello, does anyone have the wiring diagram for renault megane IV sedan parking sensors? I have a megane that doesn't have sensors at the back or the front, I wanted to put the sensors and rear camera. for the camera I already have the manual for the sensors that I still haven't got.

Thanks

**Comment by Vmfgabi** [comment]
> 
[senzori pdc.pdf](https://github.com/cedricp/ddt4all/files/7449275/senzori.pdc.pdf)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
