### ISSUE TITLE
Rlink 2 écran noir

### ISSUE THREAD

**Issue by Titiyam14** [cedricp/ddt4all#606]
Bonsoir ,j ai une megane 4 2016 avec r link2 en version 2.2 etc j ai voulu passer en version 3. Etc et je me suis trompé de fichier j ai installer la version 7 et là écran noir tableau de bord qui clignote et le rlink ne veux plus rien savoir et le lecteur usb ne veux pas détecter ma clé 
Si une personne a une idée de comment faire merci d avance .Ps j ai ddt4all et pyren mais je sais pas trop comment m en servir

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836  ????
