### ISSUE TITLE
Écran noir peux plus rien faire et usb ne marche plus

### ISSUE THREAD

**Issue by Titiyam14** [cedricp/ddt4all#608]
Bonjour,j ai un soucis rlink2 j ai voulu installer une maj et mon écran reste noir j ai voulu installer la maj 7.etc comment je peux faire merci j ai ddt4all,pyren avec Elm327 usb 
Merci de vos réponse

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836  ???
