### ISSUE TITLE
Light sensitivity adjustment

### ISSUE THREAD

**Issue by Hopealisko** [cedricp/ddt4all#609]
Hi!  Can I adjust the sensitivity of the headlights?  Now that I drive under the bridge and there is a shadow, the headlights turn on too easily.

I found help for another character, but I didn't find it in Dacia's settings.

My car Dacia Duster -18 Tce 150 4x4

Thanks for helping 🙂

**Comment by KOPRajs** [comment]
Hi, I'm having the same problem on my Dacia Duster 2020 (TCe 150 4x4).

There are 2 parameters I would like to adjust:
1. lower the sensitivity itself - turn the lights on in lower light conditions (in conjuction with the tail lights always on)
2. increase the delay before the lights turn on to minimize the flickering under the bridges, trees, shadows etc.

I expect that the configuration can be changed on the following screen, but I'm not sure which section is the correct one:

![ExternalLighting_ALS_01](https://user-images.githubusercontent.com/13847813/131213532-2134471c-a40c-4ccd-89bd-fe558ed156e2.png)
![ExternalLighting_ALS_02](https://user-images.githubusercontent.com/13847813/131213543-ba52429b-8a47-478e-a0c6-62688957a315.png)
![ExternalLighting_ALS_03](https://user-images.githubusercontent.com/13847813/131213547-4f20ed15-5312-43f4-8691-019806e28ede.png)

1. Does anybody know what the "LO" and "PL" in the options names mean?
2. What is the difference between the "QUICK" prepended options and the regular ones?

Thank you.

P.S. Please adjust the title of this issue to reflect it is about Dacia Duster.
