### ISSUE TITLE
Disable ACC from Talisman?

### ISSUE THREAD

**Issue by Vodeba599** [cedricp/ddt4all#610]
Hello,

I have Talisman with factory fitted ACC. I would like to disable that to regular Cruise because ACC is annoying to drive with even in very light traffic. Has anyone done it? Is it enough if I modify this one setting : UCEPresent_CF.Presence_ACC from With ACC to Without ACC? If I later want to sell the car, can I change it back and ACC works again?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ???????????
