### ISSUE TITLE
Programmation clé Mégane 2 phase 2

### ISSUE THREAD

**Issue by Flavien-Panunzio** [cedricp/ddt4all#611]
Bonjour, j'ai vu sur divers forum que la Mégane 2 phase 2 avait le numéro ISK qui était crypé il me semble, est-ce que quelqu'un à une solution à ce jour pour ajouter une clé à cette voiture sans passer par une concession ? J'ai acheté un ELM327 en USB pensant que j'allais être capable de le faire avec ça mais évidement j'ai pas la bonne phase pour le faire simplement.. Je suis donc à l'écoute de vos proposition de solutions pour enfin ajouter un double de clés 😅
Merci.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ?????????????????????????????????????????????????????
