### ISSUE TITLE
Clio 5

### ISSUE THREAD

**Issue by Ahmet068787** [cedricp/ddt4all#612]
Normal bir elm327 kablosunu nasıl yapacağımızı biri izah etsede yapsak adam akıllı olmaz Mı?

**Comment by Ahmet068787** [comment]
Clio 5

**Comment by AndyIreland** [comment]
> Normal bir elm327 kablosunu nasıl yapacağımızı biri izah etsede yapsak adam akıllı olmaz Mı?

A cable for reading multimedia through the OBD2scocket? or wiring to bypass the gateway and wire direct to BCM do you mean?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
