### ISSUE TITLE
Rlink2 errore message

### ISSUE THREAD

**Issue by Giuper1978** [cedricp/ddt4all#613]
![IMG-20210822-WA0001](https://user-images.githubusercontent.com/90481379/132920380-d06192b1-cbe8-41bf-85a2-5ca3d7a86a87.jpg)

Help me

**Comment by Giuper1978** [comment]
Rlink2 Kadjar 2016

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
