### ISSUE TITLE
ELS27 connection problem

### ISSUE THREAD

**Issue by oolbap** [cedricp/ddt4all#614]
Hi everyone!
I have a problem with my Chineese ELS27. It's a STN1170 chip with FTDI (FT232RL). When I connected by USB to COM1 38400 bps (Windows 10 64 bit) and chose ELM237 it looks ok - I made a test (89/93, v.1.4b). But when I chose ELS27 and 115200 bps (and any other speed) I can't connect - see screen.  I've updated drivers, made a wire inside (pin connection for Renault), I used ELS27 baudrate soft and still nothing.

![els27 problem](https://user-images.githubusercontent.com/90873348/133692417-005ea31a-436f-4466-886e-27ac820e1f08.png)

**Comment by AndyIreland** [comment]
Well for a start it should be a ELM327 with the required PIC chip thats recommended by DDT4all by the developer on github and advise against Chinese clones. 

Also, you only need to turn it into a ELS27 (by re-wiring) if you want to read the multimedia (like an rlink radio) through the OBD2 socket - everything else can be changed without re-wiring and leaving it as a ELM327

**Comment by oolbap** [comment]
Thanks for your answer. I explain more detailed:
1. my rewired ELS27, with PIC24HJ128GP504 chip

2. screens with ELM327 test - first at 38400bps, second at 115200bps
![ELM 38400](https://user-images.githubusercontent.com/90873348/133745770-bdc67bcb-7045-4e62-8ac3-4bf2feaf7590.png)

![ELM 115200](https://user-images.githubusercontent.com/90873348/133745876-6278a80c-4909-4e2e-b420-3e67b85a84a4.png)

3. I can't connect to DDT4ALL as ELS27 - see my first post (ddt recognized it as ELM), only as ELM327 is ok
4. I connected as ELM327 to my Grand Scenic II, found ECUs, but any data, can't erase any faults (No DTS)
5. I can't upgrade PIC chip's firmware - now it's 3.3.1, the newest one is 5.6.7

**Comment by KarelSvo** [comment]
Which ddt4all version are you using?
show the files elm_ddt and ecu_ddt.

**Comment by oolbap** [comment]
Latest github version - Release November 2020 Python 3
Files: [logs.zip](https://github.com/cedricp/ddt4all/files/7189484/logs.zip)

**Comment by KarelSvo** [comment]
The python 3 version still contains many bugs. The Elm test looks good in elm_ddt. Test again with the python 2 version.

**Comment by oolbap** [comment]
Thx, some success. I downgraded to 2018 version from github. Now I can connect interface as ELS27 115200bps, but ddt can't find any ECU. I tried with card in slot, ignition on and off, Canline 1 and Canline 2. One time ddt found UCH, but wrote somethinig about not full compatibility. And I can't do it again - ddt can't find any ecus now. 
[logs.zip](https://github.com/cedricp/ddt4all/files/7189902/logs.zip)

**Comment by AndyIreland** [comment]
why dont you try download DDT4all from here it includes the ECU files and places a shortcut on the desktop to start DDT4ALL and it seems safe, free of malware: - Choose 'All Cars EXE ' 
https://www.drive2.com/b/498093336985338243/

**Comment by KarelSvo** [comment]
> Thx, some success. 

Copy the scan results in red and green from the screen log window below.

**Comment by oolbap** [comment]
> why dont you try download DDT4all from here it includes the ECU files and places a shortcut on the desktop to start DDT4ALL and it seems safe, free of malware: - Choose 'All Cars EXE '
> https://www.drive2.com/b/498093336985338243/

I don't trust Russian sites. But now I will try ;)

**Comment by oolbap** [comment]
> > Thx, some success.
> 
> Copy the scan results in red and green from the screen log window below.
> There are problems when starting the diagnostic session (SDS command) when connecting directly to the UCH.
> few problems when scanning.

Nothing found... I tried with ingnition on/off, Can 1 and Can2.
![ddt screen](https://user-images.githubusercontent.com/90873348/133895449-48d2c11c-6390-494e-874f-2f1c79efce8f.png)

**Comment by AndyIreland** [comment]
what car are you using it on @oolbap  - its not one of the newer renault's with the gateway firewall protected OBD2 socket is it?

**Comment by oolbap** [comment]
@AndyIreland Grand Scenic II from 10/2006

**Comment by oolbap** [comment]
Not radio, any other ecu's. I'd like to know something about dtc in my car.

But... I tried Pyren and success. Connected, found 7 ecus and some dtc too. Now I'm trying to learn it.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
