### ISSUE TITLE
Megane 3 tail lights on with DRL

### ISSUE THREAD

**Issue by charliehoward** [cedricp/ddt4all#617]
Does anyone know how to make the rear tail/position lights come on with the DRL's, I remember seeing the option somewhere but can't find it now?

**Comment by AndyIreland** [comment]
its in the edison lighting ECU (if its there at all in your ECU fitted to your car)

**Comment by AndyIreland** [comment]
example - 
On my car (Renault Clio mk4 2016) its here. - on your megane 3 it could be on another ECU or not even there at all (especially on earlier renaults) 

![rear tail with drl_2](https://user-images.githubusercontent.com/49172217/134435451-ff18481a-1f89-47c5-9dbe-df09e2a506a3.jpg)

**Comment by srayala** [comment]
> example - On my car (Renault Clio mk4 2016) its here. - on your megane 3 it could be on another ECU or not even there at all (especially on earlier renaults)
> 
> ![rear tail with drl_2](https://user-images.githubusercontent.com/49172217/134435451-ff18481a-1f89-47c5-9dbe-df09e2a506a3.jpg)

To AndyIreland:
Did you scan and have the Edison ECU? I'm asking because I need to select it manually, but unfortunately that specific parameter is in red with NO DATA legend.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
