### ISSUE TITLE
Side Parking Sensors problems after upgrade v2 to v3

### ISSUE THREAD

**Issue by luis8097** [cedricp/ddt4all#618]
Hello community,

After upgrade from v2 to v3 (Kajar 2016) I encountered problem with parking sensors. Namely, when I park and have obstacle on my right side, instead of having warning on the screen for right sensors, I have warning on the rlink2 screen for left sensors instead of right sensors. What can I do about it and where to look in ddt4all to adapt this? 

Thanks in advance

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
