### ISSUE TITLE
ECU USES SDS 10C0 - ODOMETRY RESET - remise a zéro de l'odometrie

### ISSUE THREAD

**Issue by hdano1** [cedricp/ddt4all#619]
Hi,

it is not possible to reset odometer of ABS/ESP ECU , I get message  ECU USES SDS 10C0 
Can someone please tell me if it is possible to reset it?
I successfully overwrote VIN, but my original km is 88k, after replacing second hand ABS my dashboard shows 138k instead :-(

Fluence 2010, 1.6 81kW
ABS is part nr. 476608102R

![20211007_125058](https://user-images.githubusercontent.com/33659868/136392445-31490572-d02d-4f6f-a4ce-5d40bca459b5.jpg)
![20211007_125904](https://user-images.githubusercontent.com/33659868/136392460-10f2a829-4d6f-44f8-b3bd-11437329fca6.jpg)

**Comment by AndyIreland** [comment]
what car have you got?

**Comment by hdano1** [comment]
Oh sorry, Fluence 2010,  1.6 81kW
ABS is part nr. 476608102R

**Comment by hdano1** [comment]
For Cluster ,
 if I click on "actual total mileage value reading", I get "button request not found: Actual total mileage value reading_0"
Any idea?
By the way, 
In ABS/ESC if I click reset, 
now I get response 61 05 00 D3 8B 7D

**Comment by hdano1** [comment]
Yes, same here, and top one after click says "button request not found: Actual total mileage value reading_0"
Si can I just simply write my real mileage and click just the bottom one WRITING?

**Comment by KarelSvo** [comment]
> I know this is the Clio Mk4 ABS/ESC settings but it looks like you can add odometer settings in that , although I have not tried it @hdano1
> 
> ![abs odometer](https://user-images.githubusercontent.com/49172217/136618342-5110d62e-6e1c-4bcb-b190-944fd5fec5ef.jpg)

You can read that this is only a factory reset for new vehicles under 100km?
When a test drive is necessary after the assembly line production.

**Comment by AndyIreland** [comment]
ah right yes sorry so it is -  I missed that

**Comment by hdano1** [comment]
Ok, now it is clear, closing...

**Comment by InsanityM** [comment]
> > Hi,
> > I successfully overwrote VIN, but my original km is 88k, after replacing second hand ABS my dashboard shows 138k instead :-(
> 
> This is completely normal. The ABS is the master control unit for the odometer reading. Ddt4all cannot change anything. The adjust kilometers function is only for the dashboard. But with this only kilometers can be increased in exchange dashboard, not decreased. A dashboard with higher mileage stays high. A dashboard with lower mileage is adjusted to ABS mileage.

Hi, i am in this situation. My dashboard shows a lower value than the value from ABS. But i have the same problem like a @AndyIreland . DDt4all can't read the odometer. I just want to make it sync with ABS to show the real value that is higher
