### ISSUE TITLE
Blank Screen after "VirginMode" button pressed

### ISSUE THREAD

**Issue by maddpower** [cedricp/ddt4all#620]
Hello to all
Yesterday, after trying to activate the android auto capability using this method: https://www.youtube.com/watch?v=EDycDBTLrmc
This consists in using a PEN USB with some files and enter in a development menu. When I was trying to select the correct option, I pressed by mistake the VirginMode button.
Now I don´t have any image...a black screen.
I don´t know what dies this button, but I think is erases the VIN of the car, it´s only what I think I´m not sure.
Anyone can help me fixing this issue? How can I activate the screen again?
I have the DDT4ALL and the OBDlink SX that works with DDT4ALL, it is possible with this tool repair my mistake?
Thank you in advance for any help

I've already tryed use pryer with macros (Mid and High macros) with no success

Car: Megane IV
Rlink2 7" screen

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
