### ISSUE TITLE
Megane MK3 fitting xenons

### ISSUE THREAD

**Issue by charliehoward** [cedricp/ddt4all#622]
When you fit xenon headlights to a Megane MK3 that came with halogens they will flicker after a while, is it possible to code it so the car thinks it came with xenons and will not flicker?

**Comment by charliehoward** [comment]
I couldn't get it to work, had to install decoders in the end. Do you know if it's possible to code LED indicators so I don't need load resistors for them?

**Comment by AndyIreland** [comment]
not much to change on the flashers on the BCM module from what i can see:

![flashers](https://user-images.githubusercontent.com/49172217/140551080-0e8cafea-bb0e-459a-a9f3-cccd4863382d.jpg)

**Comment by charliehoward** [comment]
Think I've found how to code xenons, not tried it yet but apparently it's in your cluster called LCBS

**Comment by AndyIreland** [comment]
> Think I've found how to code xenons, not tried it yet but apparently it's in your cluster called LCBS

Ah right I wondered what that meant / stood for 

i have not got LBCS in my Zoe cluster settings

**Comment by charliehoward** [comment]
Might be different on the Zoe but I've found it in my Megane cluster, just not tried it yet

**Comment by AndyIreland** [comment]
wouldnt it be strange tho that the cluster settings would change the headlight system for when you have xennon bulbs though? - i dont see how

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
