### ISSUE TITLE
Megan 4 multimedia vin

### ISSUE THREAD

**Issue by Dark976** [cedricp/ddt4all#623]
Hi. İ am trying to get multimedia vin number from the car by connecting a fat32 usb in the slot and expecting the car to write a file in rlink folder. it does not happen in all my trys. is there any way i can read this value using ddt4all ?

**Comment by KarelSvo** [comment]
yes

**Comment by Dark976** [comment]
:) very nice of you to gice that much detail

**Comment by AndyIreland** [comment]
by ddt4all:

![megane 4 radio vin](https://user-images.githubusercontent.com/49172217/139592997-bc546d62-c7b8-4609-b68c-bbd79d70db23.jpg)

**Comment by Dark976** [comment]
Thank you ver much 👍

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
