### ISSUE TITLE
Renault R2 Radio "Connect Diag Unit" problem after writing configuration

### ISSUE THREAD

**Issue by amp3r1** [cedricp/ddt4all#625]
Hi, i have problem because my R2 Radio in Clio III stopped working after change language in configuration tab in ddt4all.
Radio returns an error DF030 Configuration Error in ddt4all and "Connect Diag Unit" in display.
Radio worked fine before, all settings fits to my car and were not changed anytime NAV1/CBOX0 and AUX1/CDC0/SUB0.

Anybody can help me solve this problem? :(

**Comment by BuM3GT** [comment]
Hi @amp3r1 
Have you found the solution to your problem?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by kalinavet** [comment]
У меня такая же история с блоком радио и такая же конфигурация для авто. кто-нибудь нашёл решение данной проблемы?
