### ISSUE TITLE
media nav 4.1.0 connect diag tool :( help pleaseeee.. :(

### ISSUE THREAD

**Issue by flame00111** [cedricp/ddt4all#626]
Hi i go in test mode in media nav. And i press clear virgin now its gone... it says in black screen connect diag tool. Please help me.

**Comment by flame00111** [comment]
Please help me... thank you

**Comment by AndyIreland** [comment]
try copying this LGU file to formatted fat32 usb stick and plug into usb socket of car and wait over half hour with engine running and see if it reloads the firmware for your medianav, it might work?
https://drive.google.com/file/d/1GyD8LgKEVRQcdg0akL4IpCk3zkZGZ2ur/view

**Comment by flame00111** [comment]
No bro its update file nothinf happen... :(

**Comment by AndyIreland** [comment]
ah right mate this page any help to you?
https://lisandru.eu/automotive/renault-dacia-medianav-tips/medianav-stucked-at-logo-or-inside-of-the-interface-or-pushing-the-clean-virgin.html

**Comment by flame00111** [comment]
Yes thank you my friend... its very basic. Just plug in usb and wait a 5 min and tadaaa wince 6.0 :) thank you again my friend have a nice day

**Comment by nearyux16** [comment]
@flame00111 how you fix this please help the ling doesnt work anymore

**Comment by nearyux16** [comment]
@AndyIreland @flame00111 please help me guys

**Comment by AndyIreland** [comment]
> @flame00111 how you fix this please help the ling doesnt work anymore

no, site has closed - here is his facebook profile, maybe send a message through messenger and he may respond? :

https://www.facebook.com/lisandru06

**Comment by nearyux16** [comment]
@AndyIreland thanks i send him a message, im waiting for a response. Maybe you know another solution, or know how to fix this?

**Comment by AndyIreland** [comment]
if its media nav version 1 (not evolution) 4.1.0 you can try copy the file upgrade.lgu  to a formatted fat32 USB stick and with car engine running and see if this fixes it 

https://drive.google.com/file/d/1GyD8LgKEVRQcdg0akL4IpCk3zkZGZ2ur/view?usp=sharing

**Comment by flame00111** [comment]
> @AndyIreland @flame00111 please help me guys

Hey hi bro. This link fix me. You dont need lgu file. You need nk explorer and dmicom test file i give you link. Watch this and your medianav comeback. Note: use usb 2.0 flashdisk dont use 3.0. And wait 3-5 minutes dont be speedy ok. 

https://youtu.be/Be5SnrjW16U

**Comment by flame00111** [comment]
> @flame00111 how you fix this please help the ling doesnt work anymore

Hey hi bro. This link fix me. You dont need lgu file. You need nk explorer and dmicom test file i give you link. Watch this and your medianav comeback. Note: use usb 2.0 flashdisk dont use 3.0. And wait 3-5 minutes dont be speedy ok.

https://youtu.be/Be5SnrjW16U

**Comment by flame00111** [comment]
> @flame00111 how you fix this please help the ling doesnt work anymore

Hey hi bro. This link fix me. You dont need lgu file. You need nk explorer and dmicom test file i give you link. Watch this and your medianav comeback. Note: use usb 2.0 flashdisk dont use 3.0. And wait 3-5 minutes dont be speedy ok.

https://youtu.be/Be5SnrjW16U

**Comment by flame00111** [comment]
Hey hi bro. This link fix me. You dont need lgu file. You need nk explorer and dmicom test file i give you link. Watch this and your medianav comeback. Note: use usb 2.0 flashdisk dont use 3.0. And wait 3-5 minutes dont be speedy ok.

https://youtu.be/Be5SnrjW16U

**Comment by flame00111** [comment]
@nearyux16  how you fix this please help the ling doesnt work anymore

Hey hi bro. This link fix me. You dont need lgu file. You need nk explorer and dmicom test file i give you link. Watch this and your medianav comeback. Note: use usb 2.0 flashdisk dont use 3.0. And wait 3-5 minutes dont be speedy ok.

https://youtu.be/Be5SnrjW16U

**Comment by nearyux16** [comment]
Hey guys i try yours solution but anything hapened

**Comment by nearyux16** [comment]
@flame00111 i did exatly what he said, but when i put the usb in the medianav, anything hapened

**Comment by Emanuel2011Paiva** [comment]
> 

Hmmmm... private video

**Comment by medianav59** [comment]
salut jai mon medianav version 4.1.0 bloquer sur connect diag tool comment faire merci

**Comment by Furtif** [comment]
> salut jai mon medianav version 4.1.0 bloquer sur connect diag tool comment faire merci

normalement avec ddt4all mais les ELM327 normal ne sont pas ok ou alors il vous faut un avec câble croisé sinon un usb Derlec http://www.derelek.com/nos-produits/

**Comment by medianav59** [comment]
J'ai le logiciel ddt4all avec le câble OBD ELM327 
Mais je n'arrive pas j'envoie les vidéos que j'ai fait 
https://youtu.be/FsJfw1GKH3k
 https://youtu.be/ybe0LXX85wQ
https://youtu.be/9sKPYIn6eGI

**Comment by Furtif** [comment]
> J'ai le logiciel ddt4all avec le câble OBD ELM327 Mais je n'arrive pas j'envoie les vidéos que j'ai fait https://youtu.be/FsJfw1GKH3k https://youtu.be/ybe0LXX85wQ https://youtu.be/9sKPYIn6eGI

normal que marche pas car les sondes DERLec ou câble croise c'est justement pour accéder a partie can multimédia les ODB Elm327 normaux on accès seulement a une partie can par exemple derlec y a un buton que change can par can2 soit ecus moteur vers ecu multimédia pareil se que fait le russe dans sont tuto https://www.drive2.ru/l/468057702971474426/ soit créer un ODB croisé

**Comment by Furtif** [comment]
voir image 
![image](https://user-images.githubusercontent.com/11375035/221857922-e8a1f91d-7094-45c6-88cc-595bb86b6029.png)

**Comment by medianav59** [comment]
Il faut que je fait quoi pour débloquer du coup

**Comment by Furtif** [comment]
> Il faut que je fait quoi pour débloquer du coup

j'ai actualiser le comm image en haut

**Comment by Furtif** [comment]
shema 
![image](https://user-images.githubusercontent.com/11375035/221858792-1bdaae45-2f4a-4f2a-b20c-6df8395a3c73.png)

**Comment by medianav59** [comment]
Wouah trop compliqué pour moi ça 😔 (problème de compréhension) 😒

**Comment by Furtif** [comment]
> Wouah trop compliqué pour moi ça 😔 (problème de compréhension) 😒

lol certes c'est pas evident mais vous pouvais toute fois demander de l'aide a Jeremy ici https://www.facebook.com/groups/140606960090892

**Comment by medianav59** [comment]
J'avais fait un poste et voici ça réponse 
La procédure est longue pour le remettre en rte et ça ne vaut vraiment pas le coup de le réparer
Achete un mn2 ou 3 a la place tu va économiser de ton temps

**Comment by medianav59** [comment]
D'accord merci beaucoup

**Comment by Furtif** [comment]
position normal cest 6 - 6 14 - 14 pour croiser sa faut changer 6 - 13 et 14 - 12

**Comment by Furtif** [comment]
fautdra fust couper files 6 12 13 14 pas beoin de decouper tous dans la rallonge puis les inverser ou croiser

**Comment by Furtif** [comment]
ou y a plus simple voir video ici https://www.youtube.com/watch?v=iDfbmN-OfdM @medianav59

**Comment by medianav59** [comment]
Je vais regarder merci

**Comment by medianav59** [comment]
Il est possible de faire sur ça 
https://ibb.co/sy17kPP 
https://ibb.co/CBLqB4b

**Comment by Furtif** [comment]
> Il est possible de faire sur ça https://ibb.co/sy17kPP https://ibb.co/CBLqB4b

complique par fois les pins sont soudé direct de dans c'est pas évident après la sortie fil noir c'est USB sa na rien a voir avec les pins pour cela que je parlais en rallonge comme sa il n'y a pas a endommager le ODB, voir ceci https://www.amazon.fr/Gorgeri-Diagnostic-Connector-Adaptateur-Connecteur/dp/B082V6RVDQ par exemple mais bon dans mon cas j'ai découper le câble noir car le truc en pastique est monobloc après Jai croise les fils a la place de changer pins comme dans la vidéo plus haut, mais doive avoir des rallonges plus simples a bricoler.

**Comment by Furtif** [comment]
voir celui la comme rallonge ou adaptateur https://www.amazon.fr/bbfly-B6-Splitter-extension-Adaptateur-dextension/dp/B073Y519FG peut-etre plus simples a bricoler les pins comme dans la vidéo

**Comment by Furtif** [comment]
dans la description Produits fréquemment achetés ensemble y a ton odb je crois

**Comment by Furtif** [comment]
apres sa se passe par la dans un ecu de se style 
![image](https://user-images.githubusercontent.com/11375035/221880206-3e47d075-67cc-4e7e-93d0-407edf8508ea.png)

**Comment by Furtif** [comment]
![691D600D-20B8-4644-93B5-64FF36EBEEB0](https://user-images.githubusercontent.com/11375035/221887235-5175a703-1ab5-4272-a8f4-24f67e9fa0c0.jpeg)

si souder comme sa c’est pas trop facile à croiser les pins @medianav59

**Comment by medianav59** [comment]
Merci

**Comment by shrlnm** [comment]
Hi @Furtif. Do you know which part of configuration (which parameters) should be restored/configured for removing the message "connect diag tool"?  I have a positive experience with R-Link 1 but not with radnav. Anyway, I may generate the autoconfiguration macro for pyren by the vin of this Capture

**Comment by Furtif** [comment]
> Hi @Furtif. Do you know which part of configuration (which parameters) should be restored/configured for removing the message "connect diag tool"? I have a positive experience with R-Link 1 but not with radnav. Anyway, I may generate the autoconfiguration macro for pyren by the vin of this Capture

it is basically the micom configuration test the configuration of that ecu saying that if you press the “make virgin” button on micom it deletes the micom configuration files, these files were easy to access with media nav 1 and 2 which were in windows c and now in linux I don't know there's no way to have an explorer or code to enter linux

**Comment by Furtif** [comment]
on the ecu screens there is also a make virgin button etc like the res aha and other things that are precisely in micon test .. but if make virgin you don't even have access to the micom test

**Comment by Furtif** [comment]
most users who have this problem “connect diag tool” either did shit or pressed “make virgin” or bought a new unconfigured device

**Comment by shrlnm** [comment]
@Furtif Thank you 
@medianav59 I may generate a configuration by your vin, but I don't know if someone test it on medianav before.

**Comment by Furtif** [comment]
> I may generate a configuration by your vin, but I don't know if someone test it on medianav before.
problem will be how to put the configuration inside the medianav ???? if this is virgin I believe that the configuration can only be recreated via can2 (multimedia can) in WindowsCE versions it could start in inverted memory that is to say having the system in a usb key but it has 4.0.1 I suppose it is WindowsCE, now in new medianav like 3 with linux there complicated

**Comment by Furtif** [comment]
look this https://www.youtube.com/watch?v=be8BB6lahvg&list=UUXssGOw0US5JXiktmnN6ImQ
is french but description go be translated

**Comment by Furtif** [comment]
that is to say that for a good usb key in inverted memory it would be to have created it before making a mistake with the same data of each MD or partition of windowsCE

**Comment by Furtif** [comment]
I don't know if this method of using inverted memory works in MNV 3 maybe copying the device's hdd with dd if=/dev/sda of=/dev/sdb (usb key) but ready I don't know
