### ISSUE TITLE
hi help with ddt4all... :(

### ISSUE THREAD

**Issue by flame00111** [cedricp/ddt4all#628]
Hi guys one qiestion. When i start scan witch elm327 bluetooth its find a lot of ecu. And 2 red letters. I see 2 uch/bcm ecus wt...:s why its finding 2 uch/bcm ? And its not finding abs ecu why ? I want see my kilometrage... (Sorry for my bad english) thank you... one ddt2000 sw 8.3 one is ddt2000 sw 11.0. My car is 2014 clio 1.5 dci 90 hp x98.

![20211103_001005](https://user-images.githubusercontent.com/93628809/140595627-3ff7329f-3e59-491a-b2de-d052afae9393.jpg)

**Comment by KarelSvo** [comment]
Why don't you show a photo of the scan result?
Did you select your vehicle model before scanning in order to limit the results to your vehicle type?

**Comment by AndyIreland** [comment]
I think red ones are "be extra careful at changing parameters on this ECU" - or 'not a perfect match / what was expected" 

also - if it cannot find ABS ECU automatically , then select it from the list manually you can

**Comment by flame00111** [comment]
No my friend. I read xml and json files not perfect match. Im searching what can i do. Thank you

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
