### ISSUE TITLE
Renault  Espace V // Developer Mode MID HIGH

### ISSUE THREAD

**Issue by MouadSoufiani** [cedricp/ddt4all#629]
Hi

I changed by accident in developer mode to MID. i have the big screen in my Espace V. The screen is now rotated for some reason. I tried to put it back to Portrait, but it didnt help. What can I do please?

**Comment by AndyIreland** [comment]
maybe with special wired lead or special soldered elm327 and ddt4all you can change this parameter :

![display espace](https://user-images.githubusercontent.com/49172217/140618309-c6b3e549-578c-4e7d-9df0-00e37a3e53be.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
