### ISSUE TITLE
Loads of emails about commits

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#637]
for last couple of weeks have been getting a plethora of emails every day on my windows laptop from --=FurtiF™=-- about commits for ddt4all what is that about?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/pull/634

**Comment by AndyIreland** [comment]
> #634
> 
> i not a issue this lol that is because you watch or fallow activity of this repo.

why such a lot of messages / changes coming through  every day?  just wondering? thanks

**Comment by Furtif** [comment]
@AndyIreland test pr #634

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
