### ISSUE TITLE
RENAULT TALISMAN STANDARD FRONT DRL SEQUENCE - DDT4ALL

### ISSUE THREAD

**Issue by alexunderbases** [cedricp/ddt4all#642]
Hello!
Can anybody please teach me how to reset the welcome settings of the DRL?
A few days ago, i tried to replace the high beam halogen bulb and replace it with LED.
In DDT4ALL, I changed the settings from HALOGEN to LED, but I got the "Check Lights" error. Seeing this, i came back to that setting and changed it back to halogen, restarted the car and the error dissappeared.
BUT, this left me with something strange happening with my DRL Welcome sequence:
**When I open my car, the DRL light up very very bright and very fast, after wich, it returns to it's normal brightness when the engine is off and when the car is running.**
If anyone can help me return to my original setting, i can be reached on Whatsup at +40736284508 or on Facebook @ https://www.facebook.com/alexandru.gabriel.31392410
RENAULT TALISMAN 2016 ZEN
Thank you in advance!!!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/discussions
