### ISSUE TITLE
Connection problem from Ubuntu 20.04 Python 3.8

### ISSUE THREAD

**Issue by adriancouesnon** [cedricp/ddt4all#647]
Hi @cedricp , everybody, 

I try to use ddt4all from Ubuntu 20.04 but it still not working correctly. 

If I click on "Test ELM", he stays blocked on "Tentative d'ouverture du port192.168.0.10:35000 @ 38400". 

In Connected mode, it's same. 

![Capture d’écran de 2021-12-09 18-05-18](https://user-images.githubusercontent.com/16871507/145442703-b2f5f5a4-af2a-45c0-9da6-9237fac7dbff.png)

Do I have to download special dependenties or not (Except PyQT5 because I already have installed it) ? 

I use the Wifi ELM and he's working good from Windows Package.

Thanks for your reply.

**Comment by KarelSvo** [comment]
> 
> I use the Wifi ELM and he's working good from Windows Package.
> 

Which Windows package, with Python 2 or 3? 
In my tests
Python 3 version on Windows and Linux - Wifi doesn't work
a ddt4all problem

Python 2 version on Windows and Linux - Wifi works
Bluetooth works on Linux v18.04 but not on v20.04
a Linux problem

**Comment by adriancouesnon** [comment]
Hi @KarelSvo, 

With Python 2 Package. 

ddt4all can't work with Python 2 on Ubuntu 20.04.

**Comment by KarelSvo** [comment]
> ddt4all can't work with Python 2 on Ubuntu 20.04.

I have installed 

#python 2
sudo apt-add-repository universe
sudo apt-get update
sudo apt-get install python2-minimal
#serial
sudo apt-get install  python3-pip
sudo pip install pyserial==2.7  -t /lib/python2.7
#pyqt5
https://askubuntu.com/questions/1254347/how-to-get-pyqt5-for-python2-on-ubuntu-20-04

**Comment by davidea72** [comment]
@adriancouesnon  if you launch it with 

python3 ddt4all

you are using python3

@cedricp 

if i'm right i've found the problem (at least with my adapter)
in the file elm.py , function init_wifi() you are setting the socket timeout to null with

self.hdr.setblocking(True)

in the function read() , you are reading the socket 
byte= self.hdr.recv(1)

but there is nothing in the buffer to read, it hangs waiting for a byte to come ....

if i add in the init function

self.hdr.settimeout(5)

and remove the line

self.hdr.setblocking(True)

it seems to work, at least at home i can query the adapter with the "EML benchmark" button

**Comment by davidea72** [comment]
i use it today with my adapter on my twizy and it works

**Comment by Furtif** [comment]
This is solved in https://github.com/cedricp/ddt4all/pull/779 

Resync you code and close issue

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 not need py 3.10.x
