### ISSUE TITLE
Bluetooth Phone Connection Problems

### ISSUE THREAD

**Issue by shahram241** [cedricp/ddt4all#648]
Hi,
I own a Renault talisman  and I am having problems with the bluetooth connection for my phone.

The device is paired and it connects as soon as I get into the car with bluetooth turned on, however, if I receieve a call, it no sound longer comes through the in car system. I am also unable to make calls despite being able to find people in my phone's address book.
Of course, I have no problem with playing music.
Renault Talisman 2017
R-link2 version 9.0.33.432
Thanks for any replies in advance

**Comment by shahram241** [comment]
Please Help Me.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 @shahram241 is hard!!!! not help
