### ISSUE TITLE
Disable GPF

### ISSUE THREAD

**Issue by LuzzM4RS** [cedricp/ddt4all#649]
Hello,
I have a Megane 4 rs Trophy.
There is a particle filter on this vehicule. I'll will ramplace it with a sport catalyst but i have to electronically deactivate the gpf.
Do you know if it's possible to do this with DDT4all ?
Thanks :)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 no comment... puff i have comment!!!!
