### ISSUE TITLE
Syntax error in DDT4ALL.PY

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#650]
Hello can someone tell me the problem here please? - 

I have downloaded ddt4all.py from github here and renamed my existing ddt4all.py to ddt4all.pyold in the program files (386) folder and now when i start up DDT4all from the desktop shortcut I get a syntax error and cannot go any further.

Thanks:

![ddt4all syntax error](https://user-images.githubusercontent.com/49172217/147412140-ec680057-58f6-4ffc-9253-c5255f375c77.jpg)

**Comment by KarelSvo** [comment]
A good example of, what mixing different versions of files does ;-)

**Comment by AndyIreland** [comment]
> A good example of, what mixing different versions of files does ;-)

and ... - any solution? :)

**Comment by KarelSvo** [comment]
well just don't throw files from different versions together  :D

**Comment by AndyIreland** [comment]
OK , so I just tried downloading from github @cedricp & @KarelSvo  and I cannot get DDT4ALL to start I just get this when I press ddt4all.bat  then press any key to continue

![ddt4all not starting](https://user-images.githubusercontent.com/49172217/147687353-76bbbe14-4430-437b-8196-b777bdbc4291.jpg)

 ... but the screen goes away and DDT4all will not start. I have put the ecu, vehicles, and python38 folders in the right place what am I doing wrong with the official download from github?

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all/releases

**Comment by AndyIreland** [comment]
> https://github.com/cedricp/ddt4all/releases

Thanks @KarelSvo - i found the installer file - installed it , copied my large ecu folder of 3gb to ddt4all folder in program files (386) and DDT4all starts up fine now but choose edition mode (demo) and it says 1 ecu found ... any ideas what is going on there and why it hasnt loaded the ecu's ? thanks.

**Comment by KarelSvo** [comment]
I have already written very often that I am not using this Python 3 version because it still contains some bugs.
What exactly your problem is cannot be deduced from your description. 
An uncompressed ECU database must contain a suitable ECU list so that the database can be loaded.
With the database compression function built into ddt4all, a suitable ECU list is created automatically.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 need first about a litle know prog for it....
