### ISSUE TITLE
ddt4all 2.0 Release November 2020 Python 3 not starting

### ISSUE THREAD

**Issue by AlMeu** [cedricp/ddt4all#654]
I tried and install under Win7 x32 like old version also this new version.
But when I try run it I get this error:

![2022-01-15_192723](https://user-images.githubusercontent.com/55224357/149631657-3e48db16-caf6-4adf-981c-6323eee1d717.png)

What I miss or I am doing wrong?

**Comment by AndyIreland** [comment]
i dunno - but try downloading DDT4ALL from here and choose 'all Cars' 
https://www.drive2.com/b/498093336985338243/

**Comment by AlMeu** [comment]
@AndyIreland 
If I want test new version, for what I have to download old version?
I am interested to see what's new in this version, but it starts with wrong foot.

**Comment by AndyIreland** [comment]
I have tried both but I find https://www.drive2.com/b/498093336985338243/ all cars more reliable/stable

**Comment by KarelSvo** [comment]
https://www.python.org/downloads/windows/

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 need py 3.10.x
