### ISSUE TITLE
[Megane IV] Is there a way to change the max AC temperature?

### ISSUE THREAD

**Issue by emrex89** [cedricp/ddt4all#656]
Hello there,

I have a small issue with my '17 Megane IV HB's AC.

The problem is maximum degree I can set in AC is 25.5, after that it goes to  "HI" mode.

I wonder if there is a way to add more temperatures up to 27 degrees celcius. All my cars before this had let me change it up to 27-27,5. 

In a nutshell, 25.5 degrees Celcius is not hot enough where HI is too hot :)

I tried looking in DDT4all HVAC settings, couldn't find anything useful..

Thanks 4ALL

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
