### ISSUE TITLE
[Scenic IV] how to activate heated and electric seats?

### ISSUE THREAD

**Issue by szeryf85** [cedricp/ddt4all#661]
Hi :)
I bought heated and electrically operated seats. I made a wiring harness and connected the seats to the car's electrical system. The problem is that the CAN Clip is not detecting the modules in the seats. Is there any way to activate this in ddt4all?

Regards,
Lukas

**Comment by AndyIreland** [comment]
Have you enabled them in the infotainment / HMI system of your car? - this is for Scenic 4 phase 1 :

![heated seats scenic](https://user-images.githubusercontent.com/49172217/153262978-e2b48d2d-4628-44ca-a481-c4b36719b419.jpg)

**Comment by szeryf85** [comment]
@AndyIreland thank you for your response.
after entering the module settings there was something like this:
![20220209_195328](https://user-images.githubusercontent.com/63209961/153287395-0827cf13-5ed9-41cf-b459-6776857bcc4b.jpg)

after changing to "with heating" and trying to save I have this error:
![20220209_194037](https://user-images.githubusercontent.com/63209961/153287578-e7d26e9e-ef63-4648-a03e-592ff0c2e100.jpg)
Request aborted (look at red paramters entries): NO DATA

and this is the only line with the entry "NO DATA"
![20220209_194049](https://user-images.githubusercontent.com/63209961/153287752-af2016e9-5051-483f-b5de-fd567f1c5520.jpg)

was there a connection problem? the interface is ok, because it connects to other modules.

**Comment by AndyIreland** [comment]
OK , so you have the specially wired ELM327 or soldered lead so that you can read the radio/infotainment system through the CAN socket yes?
Other than that , try changing the CAN timeout to 600ms and hit the refresh button and make sure the red No data has gone

**Comment by szeryf85** [comment]
I have an ELM cable with a switch between CAN_H (6), CAN_L (14) and CAN_H (13), CAN_L (12) - low speed CAN. Which CAN line should I choose for this connection? I tried both, and it didn't work. I will increase the CAN timeout to 600ms.

**Comment by AndyIreland** [comment]
This wiring diagram should help out and try make sure you are using an ELM327 with a PIC18F25K80 chip in it too if you can
![obd2 wiring](https://user-images.githubusercontent.com/49172217/153297566-0e93c4ba-914a-4a10-bb02-3abe21c8e5d1.jpg)
https://www.gps-rlink.com/r-link-1/activate-android-auto-waze-on-r-link-1/

**Comment by szeryf85** [comment]
ok, so should I choose CAN_H (13), CAN_L (12) for this connection?

**Comment by AndyIreland** [comment]
I *think* its CAN H for reading the radio / infotainment system

**Comment by szeryf85** [comment]
still the same error. I checked and I have ELM327 with a PIC18F25K80 chip.

**Comment by AndyIreland** [comment]
shame that - and you done a search for the ecu's in your car using the magnifying glass in ddt4all did you and see what come, not just pick the ecu manually?

**Comment by szeryf85** [comment]
I tried searching but it did not find this module. only that it connects easily with some modules that it does not find. I'm looking for a different Elm327 interface.

**Comment by BarektE** [comment]
Of course you need to activate 1. From UCH 2. From TDB

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 rapport it to diccussions
