### ISSUE TITLE
[Scenic IV] error "Request aborted (look at red parameters entries): NO DATA"

### ISSUE THREAD

**Issue by szeryf85** [cedricp/ddt4all#663]
Hi :)
I have such an error when I try to write to the module Navigation > A-IVI v.0.9 > HMI config:
"Request aborted (look at red parameters entries): NO DATA".
What can it result from?
I have ELM327 with a PIC18F25K80 chip.

Regards,
Lukas

**Comment by flame00111** [comment]
I think its china elm. Your error for this...

**Comment by szeryf85** [comment]
Maybe it is china elm, but PIC18F25K80 chip is inside.

**Comment by KarelSvo** [comment]
>  What can it result from? 

You have not supplied any ddt4all log files.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
