### ISSUE TITLE
Virginised uch

### ISSUE THREAD

**Issue by mike1991101** [cedricp/ddt4all#668]
Have a little bit of an issue with a renault Megane ph2. Whilst programming a key with Obd star the process deletes the keys before adding them. Then we've got into a situation where the uch has been reset as virgin. I have the Isk but no working key. Will I be able to reprogram the uch? I have DDT4ALL running through a ELM327 device 

Thanks 
Mike

**Comment by cedricp** [comment]
Hi,
Things are going to be complicated... The ISK on the PH2 is encrypted. Easiest way to recover is to get a full ECU package (UCH/Injection/Keys).

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
