### ISSUE TITLE
ELM 327 Bluetooth DdT4All error

### ISSUE THREAD

**Issue by org07** [cedricp/ddt4all#680]
Hello everyone, I have a problem, I want support from those who have information. My ELM 327 bluetooth device works with PYREN, but DDT4ALL gives an OBD com error how can I solve this problem?

**Comment by AndyIreland** [comment]
make sure you choose the correct port, and try reducing the baud rate and try reducing the ms CAN timeout settings

**Comment by KarelSvo** [comment]
show the error message

**Comment by org07** [comment]
It works fine in PyRen, I tried everything in ddt4all, it doesn't work. error message com port not found

**Comment by AndyIreland** [comment]
strange . Is it USB , Bluetooth or wiFi ELM327?

**Comment by AndyIreland** [comment]
> It works fine in PyRen, I tried everything in ddt4all, it doesn't work. error message com port not found

do you exit fully out of pyREN before trying to connect with DDT4ALL? 

and try this version of DDT4ALL and select 'ALL CARS' 

https://www.drive2.com/b/498093336985338243/

**Comment by org07** [comment]
I was already using it all the time, the bluetooth ELM327 I used before is broken, I am having this problem on the device I bought later. The strange thing is that although PyRen and Ddt4all use the same infrastructure, it works in one but not in the other

![obd](https://user-images.githubusercontent.com/62398726/167287507-b9e83a60-a77f-41f7-9249-f1770836d7dd.JPG)
.

**Comment by org07** [comment]
Let me point out that I am not a newbie in using it.

**Comment by KarelSvo** [comment]
WiFi Elm and ddt4all with Python 3 produce a connection error.  https://github.com/cedricp/ddt4all/pull/659/files

**Comment by org07** [comment]
> Python 3 ile WiFi Elm ve ddt4all bir bağlantı sorunu olmuyor. https://github.com/cedricp/ddt4all/pull/659/files

the picture shows wifi but the device i bought has bluetooth

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all/pull/679/files

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all/pull/679/files

**Comment by org07** [comment]
> https://github.com/cedricp/ddt4all/pull/679/files

Mr. Karel Svo this is the problem

![masa](https://user-images.githubusercontent.com/62398726/167289550-1cef9b4e-42ce-4c46-9ff2-1ec36e88faf9.JPG)

**Comment by org07** [comment]
Does anyone know what the source of this problem is?

**Comment by org07** [comment]
It also works with Android ECU Tweaker app. Only PC doesn't work with ddt4all. Isn't there a person to help?

**Comment by AndyIreland** [comment]
go into add/remove bluetooth device in windows and remove the obd2 adaptor (if it shows up) then go into device manager of windows and delete all ports (if COM ports show up) and remove them , Then go into add remove bluetooth device and re add the bluetooth obdII adaptor and see if that works. If your BT adaptor works on the Android version of DDT4ALL (ECU tweaker) and Pyren I cannot see why it will not work with your windows laptop PC - if it dont then i would say its a problem up the laptop end settings or the laptop's bluetooth adaptor

**Comment by Furtif** [comment]
Serial bug if com3 err try https://github.com/cedricp/ddt4all/pull/634

**Comment by org07** [comment]
> Windows'ta bluetooth aygıtı ekle/kaldır'a gidin ve obd2 bağdaştırıcısını kaldırın (görünürse), ardından pencerelerin aygıt yöneticisine gidin ve tüm bağlantı noktalarını silin (COM bağlantı noktaları görünüyorsa) ve bunları kaldırın, Ardından Bluetooth aygıtını ekle'ye gidin ve bluetooth obdII adaptörünü yeniden ekleyin ve işe yarayıp yaramadığına bakın. BT adaptörünüz DDT4ALL (ECU tweaker) ve Pyren'in Android sürümünde çalışıyorsa, Windows dizüstü bilgisayarınızla neden çalışmayacağını göremiyorum - çalışmıyorsa, dizüstü bilgisayar uç ayarlarında veya dizüstü bilgisayarın bluetooth'unda bir sorun olduğunu söyleyebilirim. adaptör

Dear Andy Ireland also sees PyRen on the computer. I did all of what you said, but ddt4all doesn't work with ELM327 bluetootht. I believe 2 people will solve this problem here. 1. Cedric PAILLE 2. shrlnm I trust these two so much

**Comment by org07** [comment]
> 



> [com3 hatası #](https://github.com/cedricp/ddt4all/pull/634) 634'ü denediğinde seri hata[](https://github.com/cedricp/ddt4all/pull/634)

Dear Furtif, I did not understand anything from this link, but thank you for your interest.

**Comment by Furtif** [comment]
@org07 this link is an open pull request its quite simple to use just clone the repo, install pyrhon 3.x and run dtt4all.bat ..

**Comment by Furtif** [comment]
if you prefer you can also create an updated setup with that.. your problem and just use the setup content without being interested in anything else .. in open pull there are new cars according to the latest data bases ..

**Comment by org07** [comment]
> @org07 this link is an open pull request its quite simple to use just clone the repo, install pyrhon 3.x and run dtt4all.bat ..

I already have Python 3.10.4 installed on my computer.

**Comment by org07** [comment]
> @org07 this link is an open pull request its quite simple to use just clone the repo, install pyrhon 3.x and run dtt4all.bat ..

I don't know how to do what you said :(

**Comment by Furtif** [comment]
@org07 it's easy if you have git.  installed just open a terminal and run what is in readme otherwise you can download it in zip

**Comment by Furtif** [comment]
if all fine ok if not use this zip 
[dtt4all-furtif-branch.zip](https://github.com/cedricp/ddt4all/files/8653022/dtt4all-furtif-branch.zip)
drop this wherever you want to launch ddt4all double click on dtt4all.bat or dtt4all.sh if using linux or mac os

**Comment by Furtif** [comment]
if not ok need install venv remove rem of bat file in lines echo install venv etc... or use this
[DDT4ALL.zip](https://github.com/cedricp/ddt4all/files/8653055/DDT4ALL.zip) *.bat ok ... i have zipe mine i have already venv installed ... 
```
@echo off
echo Install new venv ...
python -m venv ./venv
echo Activate venv ...
call venv\Scripts\activate.bat
python -m pip install --upgrade pip
echo Install requirements ...
pip install -r requirements.txt
echo Run's app ...
python ddt4all.py
rem echo Deactivate venv ...
rem call venv\Scripts\deactivate.bat
pause
```
fine

**Comment by Furtif** [comment]
@org07 don't forget to copy the database inside as @cedricp mentions in readme file

**Comment by Furtif** [comment]
python 3.10.4  maybe get some errs this works fine in python 3.8

**Comment by org07** [comment]
Dear Furtif, thank you very much, I'll try it tomorrow and let you know

**Comment by Furtif** [comment]
ok @org07 better installer for not get bugs... uninstall old  and install this [dtt4all_win_installer_2.0.1](https://github.com/Furtif/ddt4all/releases/tag/V2.0.1)

### `This pull request contains all dependencies updated with the latest versions:`
### `Dependencies :`
* [Python 3.9](https://www.python.org/downloads/release/python-390/) 
* [PyQt 5](https://pypi.org/project/PyQt5/)
* [pyusb](https://pypi.org/project/pyusb/)
* [pyserial](https://pypi.org/project/pyserial/)
* [crcmod](https://pypi.org/project/crcmod/)
* _**Hardware:**_ _An ELM327, ELS327 or OBDLink SX_ 
* [Python virtual environment](https://gist.github.com/dreamorosi/e2947827e5de92b69df68c88475eba38)

## `Cloning Source Code`
Next, you need to get the source code.  This source code repository uses git submodules. So when you clone the source code, you will need to clone recursively:

```
git clone --recursive https://github.com/cedricp/ddt4all.git
```

Or if you already cloned without the recursive option, you can update the submodules by running:

```
git clone --recursive https://github.com/cedricp/ddt4all.git
cd ddt4all
git submodule update --init --recursive
```

In cas for clone my branch is:
```
git clone --recursive https://github.com/Furtif/ddt4all.git
```
Or
```
git clone --recursive  https://github.com/Furtif/ddt4all.git
cd ddt4all
git submodule update --init --recursive
```

**Comment by org07** [comment]
> tamam@org07hata almamak için daha iyi yükleyici... eskiyi kaldırın ve bunu yükleyin [dtt4all_win_installer_2.0.1](https://github.com/Furtif/ddt4all/releases/tag/V2.0.1)
> 
> ### `This pull request contains all dependencies updated with the latest versions:`
> ### `Dependencies :`
> * [Python 3.9](https://www.python.org/downloads/release/python-390/)
> * [PyQt 5](https://pypi.org/project/PyQt5/)
> * [pyusb](https://pypi.org/project/pyusb/)
> * [pyserial](https://pypi.org/project/pyserial/)
> * [crcmod](https://pypi.org/project/crcmod/)
> * _**Donanım:**_ _ Bir ELM327, ELS327 veya OBDLink SX_
> * [Python sanal ortamı](https://gist.github.com/dreamorosi/e2947827e5de92b69df68c88475eba38)
> 
> ## `Cloning Source Code`
> Ardından, kaynak kodunu almanız gerekir. Bu kaynak kod deposu, git alt modüllerini kullanır. Bu nedenle, kaynak kodunu klonladığınızda, yinelemeli olarak klonlamanız gerekecektir:
> 
> ```
> git clone --recursive https://github.com/cedricp/ddt4all.git
> ```
> 
> Veya özyinelemeli seçenek olmadan zaten klonladıysanız, aşağıdakileri çalıştırarak alt modülleri güncelleyebilirsiniz:
> 
> ```
> git clone --recursive https://github.com/cedricp/ddt4all.git
> cd ddt4all
> git submodule update --init --recursive
> ```
> 
> Klon için cas'ta şubem:
> 
> ```
> git clone --recursive https://github.com/Furtif/ddt4all.git
> ```
> 
> Veya
> 
> ```
> git clone --recursive  https://github.com/Furtif/ddt4all.git
> cd ddt4all
> git submodule update --init --recursive
> ```

you're super it's better like this

**Comment by Furtif** [comment]
fine .

**Comment by org07** [comment]
I installed ddt4all-win-installer_2.0.1, it closes without opening :(

**Comment by Furtif** [comment]
> I installed ddt4all-win-installer_2.0.1, it closes without opening :(

have you istalled a DataBase ??

**Comment by org07** [comment]
I don't know how to set up the database

**Comment by Furtif** [comment]
![image](https://user-images.githubusercontent.com/11375035/167469180-b1c33f93-02e8-4980-b178-3a4f21d0cd8c.png)

**Comment by Furtif** [comment]
is this you err ?

**Comment by org07** [comment]
does not give an error message. shuts down before

**Comment by org07** [comment]
> * c:\programfiles'e gidin (x86\ dtt4all klasörünü yeniden yükleyin
> * veritabanınızı c:\programfiles (x86\dtt4all) klasörüne kopyalayın
> * tüm bunlarla ilgili çelişkileriniz var burada iyi !!!
> * veritabanınız yoksa apk dosyasının ecus.zip dosyasını kullanın, bunu dtt4all klasörüne kopyalayın/yapıştırın.

ok

**Comment by org07** [comment]
first I installed the old version, then I did not open it, I downloaded the ddt4all-win-installer_2.0.1 that you sent, I opened it in demo mode, no problem, I will try it on cars tomorrow. Sorry for making you tired, I'll let you know if it works tomorrow

**Comment by Furtif** [comment]
her şeyi yanlış yaptın .... eski sürümü hiç kurmamalısın... yenisini kullanmak için bunu kaldırmalısın, sadece yeni kurulumla kullanmak için veritabanını yedeklemelisin 
Tanrı aşkına... her sene değiştirirsen, yine de senin sorunun bizde olacak...

**Comment by org07** [comment]
I will remove the old version and install the new one, now

**Comment by org07** [comment]
I uninstalled the old version, I installed the new version you gave me, I didn't make any copies, it works in demo mode, if it works in bluetooth, it's ok

**Comment by Furtif** [comment]
normally it works with everything since I use dependency updates, there will be a problem if you go to the control panel and have a driver that is not ok this will no longer be a dtt4all problem but a windows driver problem if you have a driver with /!\ in the panel control devices see its ID and search in google in general there will be good things... other than that if it works with pyren the driver is ok only you have a mess that even you don't understand.

**Comment by org07** [comment]
Another windows 10. I have a computer that I use for 32 bit CAN Clip, I tried it on it, it has the same problem. It works with pyren, but it does not work with ddt4all. Wired works on both my computers, but not on both computers with bluetooth. 32 and 64 bit

**Comment by Furtif** [comment]
as I said above https://github.com/cedricp/ddt4all/issues/680#issuecomment-1121362648 this has the latest versions of dependencies, test it later if it doesn't work ok we will test some fixes that are in open pull request but you don't know how to do a git --clone or git --pull then I'll have to make your life easier with intallers..

Test before...

**Comment by Furtif** [comment]
pyserial == manage COM ports ...
etc...

**Comment by Furtif** [comment]
![Uploading F04E65F8-8DEE-4EE4-B688-C426AB3DC9B5.jpeg…]()

**Comment by org07** [comment]
Computer Ddt4all does not run this device. This device runs PyReni. It runs both on an android phone. Can someone who knows the solution to this help?
this is the link i bought. https://tr.aliexpress.com/item/32572206764.html?spm=a2g0o.order_list.0.0.37cf3d12I7QB6o&gatewayAdapt=glo2tu
![06fdd497-1674-4eb6-92bd-0b0a0f0b455c](https://user-images.githubusercontent.com/62398726/167560531-3d45a8fa-a360-4d45-b198-f6833abf28a3.jpg)
![06fdd497-1674-4eb6-92bd-0b0a0f0b455c](https://user-images.githubusercontent.com/62398726/167560574-43dd87c3-ab56-4675-9f0e-2fd5516bf70a.jpg)
r

**Comment by org07** [comment]
> normally it works with everything since I use dependency updates, there will be a problem if you go to the control panel and have a driver that is not ok this will no longer be a dtt4all problem but a windows driver problem if you have a driver with /!\ in the panel control devices see its ID and search in google in general there will be good things... other than that if it works with pyren the driver is ok only you have a mess that even you don't understand.

Thanks for your efforts, it doesn't work, also ddt4all-win-installer_2.0.1 is running very slow.

 Even the Renault CAN CLIP is faster.

I don't use the CLIP device as it is too slow, I just use it for Renault (Token) to auto promote the car via France
in mandatory times

**Comment by AndyIreland** [comment]
I have that Kingbolen bluetooth make. And it works on my win 10 lenovo laptop  with DDT4ALL and I have split it open once and it does have the required PIC chip in it too

**Comment by org07** [comment]
> 

As of now, I'm dealing with it. PyRen is working on all computers, but ddt4all is not working.

**Comment by org07** [comment]
Someone must know this problem

**Comment by AndyIreland** [comment]
you are doing it in the correct order? 

![ddt4all order](https://user-images.githubusercontent.com/49172217/167661076-acc6e29e-d9f8-47f2-8f1a-9c760b6cda9e.jpg)

**Comment by org07** [comment]
> you are doing it in the correct order?
> 
> ![ddt4all order](https://user-images.githubusercontent.com/49172217/167661076-acc6e29e-d9f8-47f2-8f1a-9c760b6cda9e.jpg)
![6](https://user-images.githubusercontent.com/62398726/167668101-a11229e0-1653-4f15-b305-05d47643047f.JPG)

**Comment by Furtif** [comment]
so the boy is still having problems ??... as @ shows well in his image bluethooh is using COMx that is pyserial , now I don't know what your hardware is, many are ok with the version I gave above even mine is ok works perfectly I'll buy it here https://www.elm327.fr/
from what I see he goes to COM 4 instead of 3 .... COM4 is what? your telephone ? disable blue on your phone avoid interference

**Comment by Furtif** [comment]
need maybe add something better like 'Use Item selected' in list of COM's

**Comment by AndyIreland** [comment]
so in number 6 - no elm on com4 found . - does your pyREN work on com4? - if so do you exit totally out of PyREN before starting up DDT4ALL @org07  ?

**Comment by AndyIreland** [comment]
if you download anydesk.exe from anydesk.com onto your windows laptop (with internet in your car area)  @org07 would you like me to remotely see if i can see anything stopping it working in DDT4ALL - if so give me a shout

**Comment by Furtif** [comment]
or go inside your devices manager look for your Elm327 bluethooh properties -> port settings-> switch to COM 4

**Comment by org07** [comment]
![6](https://user-images.githubusercontent.com/62398726/167673113-a49230ea-2def-4d9c-bc47-c1a2a5da8fa7.JPG)

**Comment by Furtif** [comment]
look @org07 @AndyIreland 
normally i not have rights to send this, but download full usual stuff, and says if ok i go delete this post  https://drive.google.com/file/d/1WrI39WV5jEtF4NuoF1kj-XGUjiyilW7V/view?usp=sharing

**Comment by org07** [comment]
> ![resim](https://user-images.githubusercontent.com/11375035/167671624-0e7a6f35-a19f-4881-aad2-864c516bbc45.png)
> 
> # com kullanan başka bir cihaz için örnek (aynı zamanda bir ELM327'dir ancak yalnızca USB'dir)
> ![resim](https://user-images.githubusercontent.com/11375035/167671959-e9184214-14c5-4cd0-b34d-95e98e184cb3.png)
> 
> ![resim](https://user-images.githubusercontent.com/11375035/167672088-b0cbcf4c-5b05-42e0-a057-10ad5aabba02.png)
> 
> ![resim](https://user-images.githubusercontent.com/11375035/167672239-ca62d5d6-d9e8-454b-b50e-dc5c03fa3d4e.png)
![167672088-b0cbcf4c-5b05-42e0-a057-10ad5aabba02](https://user-images.githubusercontent.com/62398726/167674159-97878161-7253-439c-b157-f4b546e82a4f.png)

**Comment by Furtif** [comment]
@org07 readed post UP ?? @AndyIreland  ???

**Comment by AndyIreland** [comment]
> @org07 readed post UP ?? @AndyIreland ???

i dont get what you mean sorry

**Comment by AndyIreland** [comment]
> ok install [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122600405) (not need database all is in ) Pyren and Dtt2000 module
> 
> ALL IN ONE too data i need delete this post get it ans says if ok

sorry i still do not understand - something is getting lost in translation to english

**Comment by Furtif** [comment]
runs Pyren setup install open set you conf... and runs pyren as DTT mode

**Comment by AndyIreland** [comment]
ah right i think you are saying 'open up pyren and run DDT4all mode' is that correct?

**Comment by Furtif** [comment]
if getted go delete post ... all data normally is not ok share that i have open exception only ...

**Comment by Furtif** [comment]
> well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> 
> ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)

YEP
setup as all in one not need add notting as both database

**Comment by org07** [comment]
PyRen's this block is not useful for everything in the same thing they are not used much, they do not use this too much of great importance ( ECM : Extended instruction set) this block does not exist

**Comment by Furtif** [comment]
> PyRen's this block is not useful for everything in the same thing they are not used much, they do not use this too much of great importance ( ECM : Extended instruction set) this block does not exist

right ... ignore , do not edit do as it does not exist

**Comment by org07** [comment]
> > well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> > ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)
> 
> YEP setup as all in one not need add notting as both database What you didn't understand is that the setup I gave above has all this without going with additions, just install everything ok, it's not for nothing that this install is 1GB due to containing the two recent base data...
> 
> #### deleted post

the most important block to be in this (ECM : Extended command set). none

**Comment by Furtif** [comment]
> > > well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> > > ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)
> > 
> > 
> > YEP setup as all in one not need add notting as both database What you didn't understand is that the setup I gave above has all this without going with additions, just install everything ok, it's not for nothing that this install is 1GB due to containing the two recent base data...
> > #### deleted post
> 
> the most important block to be in this (ECM : Extended command set). none
https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122634712

**Comment by org07** [comment]
I will solve this problem tonight, God willing

**Comment by Furtif** [comment]
@AndyIreland  ``` Choose pyren 184 ``` setup sended as 214 clip and DDT 21/11/2021

**Comment by Furtif** [comment]
both database fine ... https://drive.google.com/file/d/1WrI39WV5jEtF4NuoF1kj-XGUjiyilW7V/view?usp=sharing (1.01 GB)

**Comment by Furtif** [comment]
did you see this??? @org07 @AndyIreland

**Comment by Furtif** [comment]
sorry for tag yours..

**Comment by org07** [comment]
I downloaded it, I'm installing it, but it won't be used because it's not very useful.

 I'm just installing to see if ddt4all is working

**Comment by Furtif** [comment]
> I downloaded it, I'm installing it, but it won't be used because it's not very useful.
> 
> I'm just installing to see if ddt4all is working

fine

**Comment by Furtif** [comment]
> > sorry for tag yours..
> > ### Deleted [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122639644)
> 
> Thank you so much for everything you put in so much effort.

fine, I'm dev in spare time that help you

**Comment by org07** [comment]
> > > > well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> > > > ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)
> > > 
> > > 
> > > YEP setup as all in one not need add notting as both database What you didn't understand is that the setup I gave above has all this without going with additions, just install everything ok, it's not for nothing that this install is 1GB due to containing the two recent base data...
> > > #### deleted post
> > 
> > 
> > the most important block to be in this (ECM : Extended command set). none
> > [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122634712)

My newly installed PyRen does not open on the computer, I think it is suitable for 32-bit computers, my computer is 64-bit

**Comment by Furtif** [comment]
> > > > > well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> > > > > ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)
> > > > 
> > > > 
> > > > YEP setup as all in one not need add notting as both database What you didn't understand is that the setup I gave above has all this without going with additions, just install everything ok, it's not for nothing that this install is 1GB due to containing the two recent base data...
> > > > #### deleted post
> > > 
> > > 
> > > the most important block to be in this (ECM : Extended command set). none
> > > [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122634712)
> 
> My newly installed PyRen does not open on the computer, I think it is suitable for 32-bit computers, my computer is 64-bit

works same......

**Comment by Furtif** [comment]
> > > > > > well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> > > > > > ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)
> > > > > 
> > > > > 
> > > > > YEP setup as all in one not need add notting as both database What you didn't understand is that the setup I gave above has all this without going with additions, just install everything ok, it's not for nothing that this install is 1GB due to containing the two recent base data...
> > > > > #### deleted post
> > > > 
> > > > 
> > > > the most important block to be in this (ECM : Extended command set). none
> > > > [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122634712)
> > 
> > 
> > My newly installed PyRen does not open on the computer, I think it is suitable for 32-bit computers, my computer is 64-bit
> 
> works same......

specific configuration in general the 64 bit takes into account the 32 without any problem

**Comment by org07** [comment]
> > > > > > > well if @org07 can run PyRen but not DDT4all he could startup pyren and press DDT4all in Pyren and use DDT4all through PyRen insted:
> > > > > > > ![ddt in pyren](https://user-images.githubusercontent.com/49172217/167677395-5b08d9f6-99f4-43d7-8a15-7a645769c61a.jpg)
> > > > > > 
> > > > > > 
> > > > > > YEP setup as all in one not need add notting as both database What you didn't understand is that the setup I gave above has all this without going with additions, just install everything ok, it's not for nothing that this install is 1GB due to containing the two recent base data...
> > > > > > #### deleted post
> > > > > 
> > > > > 
> > > > > the most important block to be in this (ECM : Extended command set). none
> > > > > [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122634712)
> > > 
> > > 
> > > My newly installed PyRen does not open on the computer, I think it is suitable for 32-bit computers, my computer is 64-bit
> > 
> > 
> > works same......
> 
> specific configuration in general the 64 bit takes into account the 32 without any problem

You are a good person

**Comment by Furtif** [comment]
Please don't confuse everything...

**Comment by Furtif** [comment]
## If error after install pyren , make you sure you hahe python 2.7 if error reinstall that at  [python2.7](https://www.python.org/download/releases/2.7/)
![image](https://user-images.githubusercontent.com/11375035/167686049-7099a4e6-daaa-4053-93ed-db274be8db2b.png)

**Comment by Furtif** [comment]
if you're not happy it's exactly the same... are you happy?

**Comment by org07** [comment]
> ## If error after install pyren , make you sure you hahe python 2.7 if error reinstall that at [python2.7](https://www.python.org/download/releases/2.7/)
> ![image](https://user-images.githubusercontent.com/11375035/167686049-7099a4e6-daaa-4053-93ed-db274be8db2b.png)

ok

**Comment by org07** [comment]
> if you're not happy it's exactly the same... are you happy?

no problem

**Comment by org07** [comment]
![image](https://user-images.githubusercontent.com/62398726/167688800-60da4873-d224-494f-930e-e76127ee2ea6.png)

**Comment by Furtif** [comment]
yep as one

> > https://stackoverflow.com/questions/24517754/python-official-installer-missing-python27-dll
> 
> Yes, I read that, I installed that program, but there was no solution.
yes he has


either you use one or use the other... where do you get this that has nothing to do ??  https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122683485

**Comment by org07** [comment]
> yep as one
> 
> > > https://stackoverflow.com/questions/24517754/python-official-installer-missing-python27-dll
> > 
> > 
> > Yes, I read that, I installed that program, but there was no solution.
> > yes he has
> 
> either you use one or use the other... where do you get this that has nothing to do ?? [#680 (comment)](https://github.com/cedricp/ddt4all/issues/680#issuecomment-1122683485)

:)

**Comment by Furtif** [comment]
On a 64-bit version of Windows, the default folder for 32-bit DLL files is:
C:\Windows\SysWOW64\
, and for 64-bit DLLs
C:\Windows\System32\
[python27.zip](https://github.com/cedricp/ddt4all/files/8663813/python27.zip)

**Comment by org07** [comment]
PyREN won't turn on

**Comment by org07** [comment]
I uninstalled PyREN from the computer and did a clean install because it doesn't work

**Comment by org07** [comment]
![image](https://user-images.githubusercontent.com/62398726/167690934-770f80e6-ae30-4f3e-9dd8-d7d167a062e9.png)
Control Panel

**Comment by Furtif** [comment]
ok install 2.7 python 32 bits... fine ... because pyren make current platforms workable

**Comment by Furtif** [comment]
https://www.python.org/ftp/python/2.7/python-2.7.msi

**Comment by Furtif** [comment]
32 works in 64 but invers not ...

**Comment by org07** [comment]
![image](https://user-images.githubusercontent.com/62398726/167693084-abf1b194-3344-4a31-9c72-854a71d5796f.png)

gave this error

**Comment by Furtif** [comment]
> ![image](https://user-images.githubusercontent.com/62398726/167693084-abf1b194-3344-4a31-9c72-854a71d5796f.png)
> 
> gave this error

google a big friend

**Comment by Furtif** [comment]
import pip
ImportError: No module named pip


maybe this bug..

**Comment by Furtif** [comment]
chiness mode ...
```ptython 
if osname == 'nt':
    import pip

    try:
        import serial
    except ImportError:
        pip.main(['install', 'pyserial'])
try:
    import androidhelper as android

    osname = 'android'
    ```

**Comment by org07** [comment]
> chiness mode ...
> 
> ```
> if osname == 'nt':
>     import pip
> 
>     try:
>         import serial
>     except ImportError:
>         pip.main(['install', 'pyserial'])
> try:
>     import androidhelper as android
> 
>     osname = 'android'
> ```

I don't know where to upload this :(

**Comment by org07** [comment]
> This place is very confused, my friend, people forget what they know, in this complexity, give me your e-mail and I'll take care of your problem right away.

oorg622@gmail.com

**Comment by org07** [comment]
![image](https://user-images.githubusercontent.com/62398726/167703440-8ebbb051-933c-4284-b38e-3d4c99be4828.png)
solved, thanks a lot BerektE

**Comment by org07** [comment]
> This place is very confused, my friend, people forget what they know, in this complexity, give me your e-mail and I'll take care of your problem right away.

solved, thanks a lot BerektE

**Comment by Furtif** [comment]
> > This place is very confused, my friend, people forget what they know, in this complexity, give me your e-mail and I'll take care of your problem right away.
> 
> solved, thanks a lot BerektE

if solved close this issue, thanks

**Comment by Furtif** [comment]
and thanks also to @BarektE ;)

**Comment by org07** [comment]
> 



> and thanks also to @BarektE ;)

Thank you very much Furtif

**Comment by AndyIreland** [comment]
@Furtif 

I try downloading:
https://drive.google.com/file/d/1WrI39WV5jEtF4NuoF1kj-XGUjiyilW7V/view?usp=sharing (1.01 GB)

First of all microsoft smart screen say it suspicious - then AVG thinks it has virus 

But i eventually download it then I press on Pyren desktop link 
"C:\Program Files (x86)\PyREN\Python27\python.exe" "C:\Program Files (x86)\PyREN\_pyren_launcher.py"

and it starts and then shuts down 

PYREN.BAT gives this :

Run's app ...
Traceback (most recent call last):
  File "_pyren_launcher.py", line 46, in <module>
    pip.main(['install', 'pyserial'])
AttributeError: 'module' object has no attribute 'main'
Press any key to continue . . .

I press any key and it just shuts off.

No error messages in box
its win10 laptop 64bit but installed PYREN in x86 (32bit folder) 

Any ideas please?

—

**Comment by Furtif** [comment]
@org07 clone repo run https://github.com/cedricp/ddt4all/issues/680#issuecomment-1121249600
