### ISSUE TITLE
Renault Taliant Gizli Özellik

### ISSUE THREAD

**Issue by EserSe** [cedricp/ddt4all#681]
Merhaba mevcut ddt4 ile seçeneklerden taliant aracimj secemiyorum nasıl özellik açarım?

**Comment by KarelSvo** [comment]
XJF Logan III

**Comment by EserSe** [comment]
Denedim no data çıkıyor daha önce deneme şansınız oldumu birde Logan 2 görüyorum hangi sürümde Logan 3 var

**Comment by EserSe** [comment]
Haziranda yeni 2021 güncelleme geleceği dogrumu ?

**Comment by Furtif** [comment]
@KarelSvo XJF Logan III https://github.com/cedricp/ddt4all/issues/680#issuecomment-1121260954 

@EserSe https://github.com/cedricp/ddt4all/issues/680#issuecomment-1121362648 

maybe solve this, if ok please close issue.

**Comment by Ruygh** [comment]
@EserSe  Çözdünüz mü?
