### ISSUE TITLE
ddt4all error to connect with elm327 wifi

### ISSUE THREAD

**Issue by seawave27** [cedricp/ddt4all#682]
Hello,

I can't connect my device elm327 wifi with ddt4all,
If someone knows how i can fix it?
![IMG_20220515_163405](https://user-images.githubusercontent.com/57664760/168478526-ab7a0489-8a20-435f-ba47-36216f1f7f8f.jpg)

Thanks

**Comment by AndyIreland** [comment]
Has your wifi dongle got the correct PIC chip in it or is it a cheap chinese clone?

**Comment by AndyIreland** [comment]
sure fire way split it open and with a magnifier glass look for PIC18F25K80 stamped onto a square chip

**Comment by seawave27** [comment]
@AndyIreland i didn't instead your respons can you please guve me more information

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
