### ISSUE TITLE
Reset right Headlight Megane 4 

### ISSUE THREAD

**Issue by killuadk** [cedricp/ddt4all#683]
Hi GYUS  I'm desperate for your help.
So I have Megane 4 2016 
My issue begins when the right LED (C one) of the headlight is off.
After opening, I found some water, which damaged the control unit, so I replace it.
But the C LED does not turn on then I switched the headlights to test the new control unit and it works (the right headlight worked on the left side) so in finals, I found that one of the cables in the right connector headlight doesn't give ~12V like the left one  (give nothing) , i did check the fuse but with no luck somme one on youtube told me that i have to clear UPC 1337 with clip 
is that possible with DDT4ALL  ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
