### ISSUE TITLE
Carminat Tomtom - No radio info bar on GPS screen 

### ISSUE THREAD

**Issue by luissilva1971** [cedricp/ddt4all#686]
Hello, everyone.

I would like to ask your help i order to solve a problem on my megane 3 (ph1) sw 2010. Also a have a SD card (non oficial / prepared for new free maps). 
I have a non-bluetooth radio and GPS Carminat tomtom.  Also i have DDT4all program, and PyREN and a ELM327 with switch to change CAN1 /CAN2 reading.
Well, my GPS now does not show radio info bar and temp in the bottom as it was a few days ago. also if i change radio station or change radio volume, no info appears on screen. Radio plays as always.

"standard" GPS image
![GPS](https://user-images.githubusercontent.com/73643866/170534367-b9e5c936-a716-4e0e-ae85-bf82e7a5460f.jpg)

Atual GPS (no radio info bar...)
![IMG_20220523_083443](https://user-images.githubusercontent.com/73643866/170534699-b6052268-3cb8-44d7-8ce0-730a22c8e097.jpg)

I have scanned the navigation ECU - NFA v0.6 - and  i have compared the values with a previos dump i made on PyREN on mod_ddt. And all the parameters are the same.

Previous parameters (from PyREN NFA dump):
![NFA_origi_conf](https://user-images.githubusercontent.com/73643866/170534082-e9d44a79-51b9-4f45-94ac-9e65b7636f4b.jpg)

scanned parameters yesterday (ddt4all)
![NFA_v0 6_25052022](https://user-images.githubusercontent.com/73643866/170534194-b1aa574a-45e6-47c4-8aee-2021049e1805.png)

Also radio has the same previous parameters.
Anyone knows how can this be solved?

Thank you in advance.

**Comment by BarektE** [comment]
https://youtu.be/3HKBovSiJt8

**Comment by luissilva1971** [comment]
Problem solved. Thank you @BarektE
