### ISSUE TITLE
2021 güncelleme 

### ISSUE THREAD

**Issue by EserSe** [cedricp/ddt4all#687]
2021 taliant çıkmıyor veya farklı araçla bağlanmıyor 2021 güncelleme nezaman gelir

**Comment by EserSe** [comment]
Taliant gizli ozelligi açan oldumu hiç ?

**Comment by KarelSvo** [comment]
The first vehicles are completely sealed off from the factory. The data network can be activated for reading data by updating the dealer.
Writing data is blocked for the end user by the security gateway.
https://www.egea-association.eu/wp-content/uploads/08-RENAULT-proposal-ISO-TC22SC31WG2-1st-WebEx-of-Project-Team-on-Authe....pdf
So you have to build a new connection behind the security gateway.

**Comment by EserSe** [comment]
Teşekkürler
