### ISSUE TITLE
SCENIC II ECU VIRGINIZE / REPLACE

### ISSUE THREAD

**Issue by aporebski13** [cedricp/ddt4all#689]
Hello, I have a problem with my Scenic. 
It is 2.0 petrol automatic 
https://carinfo.kiev.ua/cars/vin/renault/vin_check?su=rlev07n2xrga

It had small fire and Injection ECU was damaged ( S3000).
Unfortunate EPROM was damaged.

I had bought cheap, a S3000 ECU wit almost the same numbers - apart S/N. , but from 1.6 manual.

Is it possible to virginize it and program actual VIN and all EPROM memory for 2.0 automatic with the use of DDT4ALL ?

I have also good clone of Renault CAN Clip with reprog - but it cannot change VIN therefore automatic configuration is not possible ( There is a function that in theory and probably will configure ECU by its VIN, and maybe update eprom )

Is there a way to obtain EPROM dump or somebody knows a place on the internet where I could find dump or virginized dump for this car - I can desolder and program the eprom, I just newer played with cars electronics ;)

**Comment by cedricp** [comment]
I did that, just virginize the eeprom by filling it with $FF. Just connect it to the car and power it up. It will automatically pair with the car and sets up parameters from hardware connections.
You'll need to finish air intake and other learning.

**Comment by cedricp** [comment]
Vin programming is not mandatory to start the car, about the engine power issue, you may need to reprogram the injection map with clip after.

**Comment by aporebski13** [comment]
Can you give a hint how to : "reprogram the injection map with clip after."   ?

**Comment by BarektE** [comment]
As I understand from what they wrote change the chassis number with RenoLink, if you have a Renault CAN Clip (reprog) and a (token) that will do automatic promotion (token), you can pull your own car software from the renault pool
![Ekran görüntüsü 2022-06-02 075038](https://user-images.githubusercontent.com/43322396/171560287-9b32dc2e-5756-4930-bcdb-b96334187e65.png)

**Comment by cedricp** [comment]
> Can you give a hint how to : "reprogram the injection map with clip after." ?
> 
> After Virginizing ECU do I need aditionaly program an old VIN number??

Unfortunately not, I had a Clip clone that worked 3 days before it passes away...
I tried the partial EEPROM clear, for me it was the opposite, the ECU was programmed for an auto gearbox and my car car has manual shift. It didn't work, only full clear worked.
You better start with a 2.0-16V engine map programmed ECU.

**Comment by aporebski13** [comment]
Unfortunately I do not have Renolink, only some USB ELM which work with DDT4ALL and good clone of Renault CLIP. I think it would be possible to reprogram it with PIN Extractor (as token).. maybe,

Firstyl need to virginize ECU - so either open it and program 95160 SPI, or is it possible wit DDT4ALL ? I means virginize , and then changing VIN in ECU for the actual of the chassis.

**Comment by BarektE** [comment]
Token has to be inserted in CLIP. It is impossible to do without Token with CLIP.

**Comment by aporebski13** [comment]
> 

Yes, reprog uses Renault.net with paid token and some operations can be done wit CD (reprog) and crack calculator for tokens called PIN EXTRACTOR as I understand. I will be fighting with it in weekend. But still don`t know if I could program new VIN with DDT4ALL ?

**Comment by BarektE** [comment]
A personal encrypted USB flash provided by Renault is used to connect to the Renault database. It is only given to authorized service personnel. It's called (Token)

**Comment by BarektE** [comment]
You can write a new Chassis number with ddt4all or ECU.

**Comment by cedricp** [comment]
S3000 command is here :

![s3000](https://user-images.githubusercontent.com/5940937/171587399-220e46dd-ae63-49f2-b583-dad16f712414.png)

**Comment by BarektE** [comment]
![image](https://user-images.githubusercontent.com/43322396/171587772-2e4ba812-1b51-4c8e-a66b-124a94433069.png)

**Comment by cedricp** [comment]
Forgot I did that too :+1:

**Comment by cedricp** [comment]
Not sure it will work, though, the data type is "hexadecimal", and shouldn't be typed as string.

**Comment by aporebski13** [comment]
So the correct CRC for VF1JM0U0A32625939

is 374D ?
many thanks :)

**Comment by aporebski13** [comment]
VF1JM0U0A32625939 to hex ? -> 5646314a4d305530413332363235393339 so the command will be 

**3B81**5646314a4d305530413332363235393339

**Comment by cedricp** [comment]
yep, CRC is correct, but it needs to be appended to the command : 

**3B81**5646314a4d305530413332363235393339**374D**

**Comment by aporebski13** [comment]
Ok, I will give it a try :) maybe it will work.

**Comment by aporebski13** [comment]
OK, virginization was easy with simple programmer CH341a ( small modification regarding Vcc to 5V).

Unfortunately I couldn`t change VIN with DDT4All, there were always an error:
0:37:16.478;7E0;3E;7F3E80;NR: Service Not Supported In Active Diagnostic Mode

tried different sessions but it didn`t change.
But I was able to program new VIN with the Renault Can Clip - unfortunately no auto adaptation / configuration and programming were available. Funny thing configuration Injection ECU S3000 was correct ( auto transmission etc) therefore probably after virginization EC|U read some config from rest of the CAN network
.

**Comment by aporebski13** [comment]
I tried also new ELM327 i bought but it don`t work with DD4ALL 
https://viaken.pl/pl/polski-elm327-v4-interfejs-vscan-stn2120-usb.html
It says it should work but there is communication error: PermissionError: [Error 13] Permission denied

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
