### ISSUE TITLE
Very lagy on WINDOWS 10

### ISSUE THREAD

**Issue by hnizil** [cedricp/ddt4all#690]
i'm trying to use the app on windows 10 , but , i cant because the GUI is very laggy and doesn't respond to mouse clicks, i can't choose ELM port so it stucks on the interface in picture bellow.

Have someone managed to solve this problem ?

Best regards.

![image](https://user-images.githubusercontent.com/7702219/172867483-a1449d1e-8e5b-478f-a8a9-dcda3f777b77.png)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
