### ISSUE TITLE
Screens do not display / unexpected type 'float' under Python 3.10.4

### ISSUE THREAD

**Issue by lhitc** [cedricp/ddt4all#692]
I installed ddt4all on a fresh Lubuntu 22.04 machine (using git clone from master).
I start ddt4all via command line ($ python3 ddt4all.py)
Whenever I try to display a screen (even in edit mode), nothing happens in the screen area, but on the command line I see a stack trace:
```
  File "/opt/ddt4all/ddt4all.py", line 940, in changeScreen
    inited = self.paramview.init(screen, self.screenlogfile)
  File "/opt/ddt4all/parameters.py", line 627, in init
    scr_init = self.initScreen(screen)
  File "/opt/ddt4all/parameters.py", line 977, in initScreen
    self.panel.initXML(screen)
  File "/opt/ddt4all/displaymod.py", line 177, in initXML
    self.resize(self.screen_width, self.screen_height)
  File "/opt/ddt4all/displaymod.py", line 193, in resize
    super(screenWidget, self).resize(x, y)
TypeError: arguments did not match any overloaded call:
  resize(self, QSize): argument 1 has unexpected type 'float'
  resize(self, int, int): argument 1 has unexpected type 'float'
```

When I try a quick fix and put round() or int() around the parameters of that specific resize, all kinds of similar errors popup, all of which seem to be related to QT calls expecting integers, but getting floats.

Lubuntu 22.04 comes with the following packages:
- python3 3.10.4-0ubuntu2 (pre-installed)
- python3-pyqt5 5.15.6+dfsg-1ubuntu3 (pre-installed)
- python3-pyqt5.qtwebengine 5.15.5-1 (installed by me to fullfill ddt4all dependencies)

I tried installing on a Lubuntu 20.04 system, which works flawlessly. Here, the package versions are:
- python3 3.8.2-0ubuntu2 (pre-installed)
- python3-pyqt5 5.14.1+dfsg-3build1 (pre-installed)
- python3-pyqt5.qtwebengine 5.14.0-2build1 (installed by me to fullfill ddt4all dependencies)

Apparently in the newer version a stronger typing has been introduced.

**Comment by moulinGavray** [comment]
quick fixes by putting round function worked well for me after modifying twelve lines in four different files (lines 193+396+403+405+580+596+597+612+614 in displaymod.py, line 982 in parameters.py, line 75 in uiutils.py and line 937 in elm.py) executing "python3 ddt4all-2.0/ddt4all.py" with macOs Big Sur (11.2.3) on a 2013 11" macBook Air (A1465), hope this helps
