### ISSUE TITLE
> da, koristite modificirani kabel i odaberite can2 box u pyrenu

### ISSUE THREAD

**Issue by vraug666** [cedricp/ddt4all#693]
> da, koristite modificirani kabel i odaberite can2 box u pyrenu
He found nothing
OK

_Originally posted by @vraug666 in https://github.com/cedricp/ddt4all/issues/237#issuecomment-1161792836_

**Comment by vraug666** [comment]
He found nothing

**Comment by vraug666** [comment]
![Uploading IMG_20220621_180728.jpg…]()

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
