### ISSUE TITLE
 32 pin r-link 2 connector pins diagram

### ISSUE THREAD

**Issue by myshuker** [cedricp/ddt4all#696]
Hej all
I need  32 pin r-link 2 connector pins diagram for renault Scenic 4 or Megane 4 
https://ibb.co/k52jqYJ

https://ibb.co/7rgVpgD

**Comment by MellotronScratch** [comment]
Here you go. This is from a Kadjar, should be the same pinout.


Pin | Signal | Signal label
-- | -- | --
1 | 107W | DIAGNOSTIC SOCKET CANH MULTIMEDIA SIGNAL
2 | 107X | DIAGNOSTIC SOCKET CANL MULTIMEDIA SIGNAL
3 | 107G | HANDS FREE TELEPHONE MICROPHONE +
4 | 107F | MULTIMEDIA MICROPHONE SIGNAL
6 | 137H | CAN H SIGNAL
7 | 137G | CAN L SIGNAL
11 | 34EC | RIGHT HAND LINE IN + SIGNAL
12 | 34EE | LEFT HAND LINE IN + SIGNAL
13 | 34EM | LINE IN SIGNAL
20 | 107J | TELEPHONE MICROPHONE SCREENING
21 | 34KL | REAR CAMERA VIDEO SIGNAL
22 | 34KJ | - REAR CAMERA
23 | 34KK | + REAR CAMERA
24 | TB34 | REAR CAMERA SHIELDED CABLE
27 | TB37 | LINE IN SHIELDED CABLE
28 | 34ET | - LINE IN

**Comment by endrjuk** [comment]
Hi, I guess that 12 pins connector (on left in the photo) is just power and speakers, but do you also have the 24 pins connector electric diagram for R-Link2? 
![screen](https://user-images.githubusercontent.com/122672268/218255578-b5cd6558-4307-4c42-b02b-fb6fbb3be149.png)

**Comment by MellotronScratch** [comment]
@endrjuk This is all information I have. Your connector has more connections. You are right about the connector on the left on the photo. It's for power and speakers.

| Pin | Signal | Signal label               |
|-----|--------|----------------------------|
| 6   | 34AS   | RADIO SATELLITE IN0 SIGNAL |
| 7   | 34AT   | RADIO SATELLITE IN1 SIGNAL |
| 8   | 34AU   | RADIO SATELLITE IN2 SIGNAL |
| 9   | 34AP   | RADIO SATELLITE SIGNAL L0  |
| 18  | 34AQ   | RADIO SATELLITE SIGNAL L1  |
| 19  | 34AR   | RADIO SATELLITE SIGNAL L2  |
| 20  | 107V   | VOICE RECOGNITION          |
| 21  | 107O   | MASS VOICE RECOGNITION     |

**Comment by endrjuk** [comment]
Thank you! I'm in the process of modifying the wiring harness to rlink-2 in Megane IV and any informations are helpful. Do you have any information about the multi-pin plug connected to the front panel? It's a Megane IV, so it must be something related to the air conditioning control and buttons for emergency lights/central locking. It's hard to get any electric diagrams in these generations of Renault cars...
![panel](https://user-images.githubusercontent.com/122672268/218259269-b8891895-f38a-41de-8692-85caa4d3c8e8.png)

**Comment by EddyG70** [comment]
Can anyone tell me what all the connections are for from left to right? Please your help would be appreciated 😎

**Comment by MellotronScratch** [comment]
From left to right:
Speakers, 12v+ and ground.
GPS Antenna (blue)
Telematic module (Brown USB)
USB Ports (Black USB)
Display (Blue USB)
[See my earlier post](https://github.com/cedricp/ddt4all/issues/696#issuecomment-1191154034) (32Pin white connector)
[Steering wheel controls](https://github.com/cedricp/ddt4all/issues/696#issuecomment-1426750362) (24Pin white connector)
FM2 antenna (Yellowish fakra connector)
FM1 antenna (White fakra connector
DAB+ (Brown fakra connector)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 not bad info rappot it to discutions!!!
