### ISSUE TITLE
Problem with r link after using developer mode

### ISSUE THREAD

**Issue by saadbm1** [cedricp/ddt4all#697]
![5F135743-E256-414A-89EC-2AB427FE929D](https://user-images.githubusercontent.com/108997662/178118840-22502d8b-8768-4ef8-a489-47f52cd7128a.jpeg)

**Comment by shrlnm** [comment]
What is your VIN?

**Comment by saadbm1** [comment]
> What is your VIN?

how would that help in any way ?

**Comment by AndyIreland** [comment]
I should imagine VIN number would match up as to what features you have in your car and the rlink can be then configured as to what and not features your particular car has got

**Comment by saadbm1** [comment]
it’s more about if it’s possible to configure it or should i just give up, and if it’s possible then how ?

**Comment by AndyIreland** [comment]
what is it an rlink2 is it?

**Comment by saadbm1** [comment]
yes and the update version is 2.2.19.300

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
