### ISSUE TITLE
Remove the remote closure on Renault Scenic III

### ISSUE THREAD

**Issue by f4gqk** [cedricp/ddt4all#699]
Hello,

I own a scénic III from 2015, I would like to remove the central locking on the remote with DDT4ALL but I don't know where to go?

Let me explain, when I have the hands-free card in my bag and I walk away from the vehicle, it closes. I would just close it by putting my hand on the handle.

Thanks

Sebastien

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 !!???
