### ISSUE TITLE
Font alignment??

### ISSUE THREAD

**Issue by hoonythink** [cedricp/ddt4all#7]
hi
first, i thanks for you.
and I have a request from you.
ddt4all does not support font alignment.
So the menu is messy.
I want to sort the font right.
Can font alignment be supported?

- ddt4all screen
![11](https://user-images.githubusercontent.com/31832805/30306296-54c53226-97b2-11e7-8ba5-faf24403ddf4.JPG)

- RenoLink screen
![22](https://user-images.githubusercontent.com/31832805/30306297-54c55b34-97b2-11e7-8bb3-2417b1ae03a4.JPG)

it's same xml file. (RadNav V2.3 ...)

and... I wish I had the ability to select xml files.

thanks.

**Comment by cedricp** [comment]
Which XML file is it ?

**Comment by hoonythink** [comment]
thanks for your answer.

i tested "RadNav_v2.3_20170726T141106.XML"


===================================
피큐브(주)

조정훈

H.P : 010 - 3153 - 2012
E-MAIL : hoonythink83@gmail.com
===================================

2017-09-13 17:23 GMT+09:00 Cedric PAILLE <notifications@github.com>:

**Comment by hoonythink** [comment]
attaching XML file.

it is some edited for see menu text.

===================================
피큐브(주)

조정훈

H.P : 010 - 3153 - 2012
E-MAIL : hoonythink83@gmail.com
===================================

2017-09-13 17:23 GMT+09:00 Cedric PAILLE <notifications@github.com>:

**Comment by cedricp** [comment]
Fixed

**Comment by gordon6** [comment]
Thanx, Hoony and Cedric...
It goes enhanced..!

**Comment by hoonythink** [comment]
thanks ^^

===================================
피큐브(주)

조정훈

H.P : 010 - 3153 - 2012
E-MAIL : hoonythink83@gmail.com
===================================

2017-09-13 18:48 GMT+09:00 Cedric PAILLE <notifications@github.com>:
