### ISSUE TITLE
Renault Grand Scenic 2017 - Main screen bricked 

### ISSUE THREAD

**Issue by frazier990** [cedricp/ddt4all#708]
Hi all,

I have a problem with my main screen , I wrongly pressed a button in system menu and now it is fully dark ive taken it back to the dealer ship and they are scratching their heads with it. 
If they can't fix it when they give me it back.

Is it possible to turn it back with ddt4all and how please.

**Comment by AndyIreland** [comment]
I predict you have a rlink 2 , if so have a read here I think you could fix using pyren:
https://gitlab.com/py_ren/pyren/-/wikis/how-to-rlink2-black-screen

**Comment by frazier990** [comment]
Thank you, and I do have the Rlink2 system.
If they can't fix it their end I'll be sure to give this a try and let you know the outcome.

Also can any ELM work ?

Thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
