### ISSUE TITLE
Lights

### ISSUE THREAD

**Issue by JAzevedo351** [cedricp/ddt4all#709]
Hello all, i need  big hhelp and informatioa too.
How can i did turn off lights imediatli whene i turn off engine on my car?? My car is a grand scenic IV.
thank You for the help

**Comment by AndyIreland** [comment]
hello, its one of the settings in the emm lighting ECU .. I think its the 'swiss CF' if that is set to '1' then the headlights stay on when the ignition turns off and only go out when the drivers door is opened.

![swiss lights](https://user-images.githubusercontent.com/49172217/182044278-70fa82bf-002c-4828-92d4-44e59bc4cc0f.jpg)

**Comment by JAzevedo351** [comment]
Hello, Thanks, first of all, the scenic 4 does not have, emm module, the light settings is in bcm, but I'll look better but thanks for your feedback

**Comment by AndyIreland** [comment]
you havent got the scenic 4 ph2 have you by any chance only there is a setting in the UCH ecu for delay after engine turned off for the lights:
![scenic 4 lights delay](https://user-images.githubusercontent.com/49172217/182047424-e69773c7-bc9d-4ed1-ad6b-f5afc3ecedf5.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by memo0616** [comment]
Hello, does your vehicle have an automatic headlight sensor?
