### ISSUE TITLE
Android App crash while reading ecu.zip

### ISSUE THREAD

**Issue by Mierscheid** [cedricp/ddt4all#711]
Hi guys, 

when I unzip the ecus.rar from the link in Issue #56 and repack it as ecu.zip, the Android app crashes reproducible.
Is there another way, or a "real" ecu.zip as download?

Redmi Note 5, MIUI 11.03, Android 9
Renault Twizy 2012
Can connect to the ELM-ODBII-BT-Dongle i.e. with "TWIZY", "Tune the T" or also "Torque".

TIA
Regards
Mierscheid

**Comment by Mierscheid** [comment]
Could someone send me an ecu.zip that works with the app so I can verify and isolate the error?

**Comment by AndyIreland** [comment]
hopefully this one will work for you it does with my ecu tweaker app:

https://filebin.net/8pco7lo5ts6uv0j8

**Comment by Mierscheid** [comment]
<3 
Thanks a lot! I'll try it!

**Comment by Mierscheid** [comment]
It works! Wow! Thank you!

**Comment by AndyIreland** [comment]
great stuff glad to have helped

**Comment by salihakin** [comment]
> hopefully this one will work for you it does with my ecu tweaker app:
> 
> https://filebin.net/8pco7lo5ts6uv0j8

I am interested in this file. Can you upload it again

**Comment by salihakin** [comment]
> It works! Wow! Thank you!

Is everything ok for twizy.
I want to try it.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
