### ISSUE TITLE
Clio 5 Gateway bypass

### ISSUE THREAD

**Issue by burakcankose** [cedricp/ddt4all#712]
hello, can you give information about the solutions to bypass the gateway in clio - captur and zoe vehicles?

**Comment by AndyIreland** [comment]
big thread on it here worth reading through:
https://github.com/cedricp/ddt4all/issues/404

**Comment by burakcankose** [comment]
hi, i read the whole topic but i saw that there is still no valid solution, if there is any other idea we can try it?

**Comment by KarelSvo** [comment]
then you haven't read the topic carefully

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
