### ISSUE TITLE
Ecu.zip for android app

### ISSUE THREAD

**Issue by fineryx** [cedricp/ddt4all#713]
Hello, where can i get the ecu.zip database for the android app? Thanks

**Comment by AndyIreland** [comment]
try this:
https://filebin.net/n9p7epmza9trispq

**Comment by xtendpayaa** [comment]
Hi!
I'm interested too. Thx!

**Comment by AndyIreland** [comment]
try here: 
https://we.tl/t-gQhbd2xuxp

**Comment by xtendpayaa** [comment]
> try here: https://we.tl/t-gQhbd2xuxp

Thank you!

**Comment by Jantjuh26** [comment]
I'm also interested! Someone got a link?

**Comment by AndyIreland** [comment]
Try here:
https://we.tl/t-zZxCrR0F3v

**Comment by Jantjuh26** [comment]
Thanks!

**Comment by AndyIreland** [comment]
> Thanks!

your welcome

**Comment by svenvogel** [comment]
Hi there, the links are not more working. Can anyone send me a link to the ECU.zip too?

**Comment by AndyIreland** [comment]
> Hi there, the links are not more working. Can anyone send me a link to the ECU.zip too? Where is normally the place where I can download them?

here is link (for 7days anyway) - I dont really know where  the normal place is for it to be honest.
https://we.tl/t-ioqrkphpq0

**Comment by svenvogel** [comment]
@AndyIreland thank you very much! Where do you found them or where are updates for them?

**Comment by AndyIreland** [comment]
> @AndyIreland thank you very much! Where do you found them or where are updates for them?

no problem - I found that ages ago - could be a year ago now. - Think I got it either off a car  forum or I might have download it from here for ddt4all with ecu zip included 
https://www.drive2.ru/b/498093336985338243/

and then just copied over the zip file

**Comment by xtendpayaa** [comment]
Here is a bigger ecu file:
https://mega.nz/folder/nEsgHDCQ#UJt650dKyzVdUe4CLzH0uw

**Comment by svenvogel** [comment]
@AndyIreland @xtendpayaa thanks!

**Comment by cybersholt** [comment]
@xtendpayaa thanks for the upload. 

It would be great if the install docs link to a file or explained how to generate.

**Comment by salihakin** [comment]
I'm also interested! Someone got a link?

**Comment by xtendpayaa** [comment]
> I'm also interested! Someone got a link?

3 reply above to you the mega.nz file working nicely

**Comment by salihakin** [comment]
> > I'm also interested! Someone got a link?
> 
> 3 reply above to you the mega.nz file working nicely
> 
> Or here the smaller one: https://mega.nz/file/NaFwGZIa#p713tInIHptfSkYwH2R3lP-wm3FFrkobeih_zM3bhTQ Need to rename the ecu.zip2 to ecu.zip to get working.

Thank you so much.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by radjool** [comment]
hi,
i am looking for the latest ecu.zip database that contains dacia duster 2023,  could those who have it share please?

**Comment by MTPro94** [comment]
> Iată un fișier ECU mai mare: https://mega.nz/folder/nEsgHDCQ#UJt650dKyzVdUe4CLzH0uw

Link 2024 please

**Comment by MTPro94** [comment]
ecu.zip 2024 valid link ? Please . Thank you

**Comment by Furtif** [comment]
> ecu.zip 2024 valid link ? Please . Thank you

https://github.com/cedricp/ddt4all/discussions/845#discussioncomment-6144566
