### ISSUE TITLE
RLink2 antitheft mode active

### ISSUE THREAD

**Issue by RPAuto** [cedricp/ddt4all#714]
Can someone help m remove antitheft mode on renault megane 4?
Unit change
Original dead 
thanks

**Comment by MellotronScratch** [comment]
You need to change a byte in the eeprom. Not possible through OBD as far as I know.

**Comment by rttr67** [comment]
I can help  
remove antitheft mode on renault

**Comment by RPAuto** [comment]
Perfect what you need?

A sábado, 8/10/2022, 21:29, rttr67 ***@***.***> escreveu:

**Comment by rttr67** [comment]
I answer you by email.

**Comment by Rob69rt** [comment]
I have the same problem right now. I bought radio LANR16 from  Kadjar to my megane IV(with LANR14)and could someone help me with deactivation antitheft mode?

**Comment by rttr67** [comment]
Rob69rt.
Leave an email and I will tell you options.

**Comment by Rob69rt** [comment]
> 

> 
My email:
xiaomih1s@gmail.com
Thanks in advance

**Comment by jurekogurek** [comment]
> Rob69rt. Leave an email and I will tell you options.

will you help me take off the antitheft? I bought a module for carplay lanr16. My email: knowak161@wp.pl

**Comment by Grazi77** [comment]
c e una soluzione per sbloccare rlink2 con antitheft erroneamente attivato?

**Comment by rttr67** [comment]
c'è sempre una soluzione

**Comment by Grazi77** [comment]
mi puoi contattare?
g.torazza@gmail.com

**Comment by Grazi77** [comment]
> Devi cambiare un byte nella eeprom. Non è possibile tramite OBD per quanto ne so.

hai maggiori informazioni su questo bit da modificare nel dump della eprom?
ho fatto il dump della eprom ma nn riesco a montare l immagine bin su l emulatore

**Comment by ionitagelu** [comment]
Hello, for my Megane 4 I bougt a v9 unit (from another car), and I need to disable antitheft. Please help me. I have Eprom programmer.
My email: gelu.ionita@gmail.com
Thank you!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by MouadSoufiani** [comment]
Hi, can you send me also email for anti theft? mouadsoufiani@hotmail.be

**Comment by ahs2184** [comment]
Could you please email regarding anti-theft Alex-simpson@blueyonder.co.uk

**Comment by Serg797979** [comment]
Hello. help me remove the LANR14 anti-theft protection please. buditch_s@mail.ru

**Comment by ricardomontenegro24** [comment]
Can you email me how to remove anti theft?

rjvmontenegro@hotmail.com

**Comment by kzoid** [comment]
Someone already found out? I want to put an v9 unit in my Megane IV.

**Comment by Kjaer123** [comment]
Rttr67

I need help to deactivate anti theft on a lanr16. 
I have changed vin and vehicle id. 
Mikael@kjhansen.dk

**Comment by saadousfar** [comment]
hi i have the solution to desable the antitheft message by can for any information plz contact mee on saadousfar59@gmail.com

**Comment by Kjaer123** [comment]
Thanks for your reply, I found the vehicle I'd in the dump from my old radio, and put it in the new radio. Then it was only a matter of adaption.
Now I works

Regards mikael

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: saadousfar ***@***.***>
Sendt: Friday, December 29, 2023 12:23:10 AM
Til: cedricp/ddt4all ***@***.***>
Cc: Mikael Hansen ***@***.***>; Comment ***@***.***>
Emne: Re: [cedricp/ddt4all] RLink2 antitheft mode active (Issue #714)


hi i have the solution to desable the antitheft message by can for any information plz contact mee on ***@***.******@***.***>

**Comment by GiuseppeGullo67** [comment]
> Posso aiutarerimuovere la modalità antifurto su renault

**Comment by GiuseppeGullo67** [comment]
Buonasera a tutti, io come ho letto anche altri sono in procinto per acquistare un Rlink usato, come faccio a non farlo bloccare , ho visto che con il programma ddt4all puoi cancellare e riscrivere il vin, ma prima di fare delle belinate vorrei essere sicuro, se qualcuno mi può dare consigli o aiuto ne sarei grato, la mia mail è ducatista67@libero.it , grazie anticipatamente

**Comment by GiuseppeGullo67** [comment]
ducatista67@libero.it

**Comment by Kjaer123** [comment]
Grazie per la risposta.
l'ho risolto da solo

Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
________________________________
Fra: GiuseppeGullo67 ***@***.***>
Sendt: Wednesday, March 6, 2024 10:16:16 PM
Til: cedricp/ddt4all ***@***.***>
Cc: Mikael Hansen ***@***.***>; Comment ***@***.***>
Emne: Re: [cedricp/ddt4all] RLink2 antitheft mode active (Issue #714)


Posso aiutarerimuovere la modalità antifurto su renault

**Comment by shrlnm** [comment]
@GiuseppeGullo67 
https://www.drive2.ru/b/669234795749858633/

**Comment by GiuseppeGullo67** [comment]
Grazie mille, un po’ complicato per me, ma ti darò aggiornamento in ogni caso

Giuseppe Gullo
Il 7 mar 2024, 07:06 +0100, shrlnm ***@***.***>, ha scritto:

**Comment by lklik** [comment]
hi rttr67 I need your help to deactivate anti theft  with my Rlink  this's my email azizouaankour@yahoo.fr

**Comment by munkun46** [comment]
> merhaba rttr67 Rlink'imle hırsızlığa karşı korumayı devre dışı bırakmak için yardımınıza ihtiyacım var bu benim e-posta adresim [azizouaankour@yahoo.fr](mailto:azizouaankour@yahoo.fr)

If you have an elm327 device, you can unlock it.

**Comment by lklik** [comment]
Merhaba, Thanks to your reply, i appreciate your help , yes I do have the OBD2 device .Envoyé de mon iPhoneLe 12 avr. 2024 à 15:31, munkun46 ***@***.***> a écrit :﻿

merhaba rttr67 Rlink'imle hırsızlığa karşı korumayı devre dışı bırakmak için yardımınıza ihtiyacım var bu benim e-posta adresim ***@***.***

If you have an elm327 device, you can unlock it.

**Comment by saadousfar** [comment]
contact mee

**Comment by Arcadius82** [comment]
Hello. I have same problem with radio LANR14 replaced on second hand as oryginal unit not responding. Changed ID and VIN but its black screen still not working  and black screen. Before when i plug in second hand unit was ani theft message,

Can someone help me with this ?Please
aer.automotive@mail.com

**Comment by andresantosmocas** [comment]
> I can help remove antitheft mode on renault

Hey, I also Bought a LANR16 and I have the anti-theft message. andresantosbraz@gmail.com

**Comment by liciniofs** [comment]
Can you send me as well darth.design@gmail.com

**Comment by johnkar87** [comment]
> Thanks for your reply, I found the vehicle I'd in the dump from my old radio, and put it in the new radio. Then it was only a matter of adaption.
> Now I works
> 
> Regards mikael
> 
> Sendt fra Outlook til iOS<https://aka.ms/o0ukef>
> […](#)

hi could you send me your email?

**Comment by saadousfar** [comment]
I sell à Software to remove anti-theft via can saadousfar59@gmail.com

**Comment by johnkar87** [comment]
my friend There is no way to pay to anybody I dint trust anybody who just
saying he have any software (not only you) if you want help people to forum
help them and not want to pay you

Στις Πέμ 27 Μαρ 2025 στις 21:11 ο χρήστης saadousfar <
***@***.***> έγραψε:

**Comment by shrlnm** [comment]
@johnkar87 You may try it for free..  https://www.drive2.ru/b/669234795749858633/
Now qpyren3 contains this macro.
- Install qpyren3 and run it
- press button UPDATA and wait DONE message
- Go to MACRO
- select ./macro/rlink2  folder
- then select unlock.cmd

**Comment by saadousfar** [comment]
i have a software to remove the anti-theft no need t odissampble the unit to read eeprom  saadousfar59@gmail.com

**Comment by saadousfar** [comment]
![Image](https://github.com/user-attachments/assets/8c8978e6-c37d-4670-843d-d61e8b310492)

**Comment by MouadSoufiani** [comment]
This guy above me does it for 120eu. Very expensive

![Image](https://github.com/user-attachments/assets/cd47ac20-69c9-4643-a204-e81b0a0d21b3)

**Comment by Renotech1** [comment]
Don't pay anyone 🙂
If they dont want to share there all scamming bullshitsss

Op za 17 mei 2025, 13:40 schreef Mouad Soufiani ***@***.***>:

**Comment by ionitagelu** [comment]
> Don't pay anyone 🙂
> If they dont want to share there all scamming bullshitsss
> 
> Op za 17 mei 2025, 13:40 schreef Mouad Soufiani ***@***.***>:
> […](#)

You can use PyRen and script from russian site. It's free !

**Comment by Renotech1** [comment]
Still not figured out how do I run the .cmd script ?

Op za 17 mei 2025, 15:28 schreef ionitagelu ***@***.***>:

**Comment by MouadSoufiani** [comment]
Offcourse not. Whole this community is free.

**Comment by saadousfar** [comment]
> Ne payez personne 🙂 S'ils ne veulent pas partager leurs conneries d'arnaque Le 17 mai 2025, 13:40, Mouad Soufiani a écrit ***@***.***>:
> […](#)

TIME = money

**Comment by MouadSoufiani** [comment]
> > Still not figured out how do I run the .cmd script ?
> 
> Run the pyren3 or qpyren3 launcher. Press UPDATE to download the latest macro including the unlock. https://gitlab.com/py_ren/pyren/-/blob/pyren3/pyren3/macro/rlink2/unlock.cmd?ref_type=heads Then click the MACRO button and select unlock.cmd.

Tried it on 2 units, but doesnt work. It reboots, but anti-theft is coming back

**Comment by shrlnm** [comment]
> > > Still not figured out how do I run the .cmd script ?
> > 
> > 
> > Run the pyren3 or qpyren3 launcher. Press UPDATE to download the latest macro including the unlock. https://gitlab.com/py_ren/pyren/-/blob/pyren3/pyren3/macro/rlink2/unlock.cmd?ref_type=heads Then click the MACRO button and select unlock.cmd.
> 
> Tried it on 2 units, but doesnt work. It reboots, but anti-theft is coming back

May you capture all frames from the bus during reboot of the RL2?

**Comment by saadousfar** [comment]
> Can someone help m remove antitheft mode on renault megane 4? Unit change Original dead thanks

i have the solution no need to read the eeprom you can unlock any Rlink2 unit by obd via my script for more information contact me on saadousfar59@gmail.com

**Comment by saadousfar** [comment]
> You need to change a byte in the eeprom. Not possible through OBD as far as I know.

hi it possible to disable the antitheft via can by my software saadousfar59@gmail.com
