### ISSUE TITLE
Cannot read data

### ISSUE THREAD

**Issue by zkmsh** [cedricp/ddt4all#715]
Hi, 

I cannot read data with DDT4ALL, everything show "NO DATA" when I go to Navigation module. Can you help me figuring this out please? I bought an OBD adapter that I modified, PIN 13 to PIN 6 and PIN 14 to PIN 12.
My car is a megane 3 and I use the OBDLINK SX (the red one).

Here is my LOG.
ECU: https://pastebin.com/zKhuWvbh
ELM:  https://pastebin.com/1bMVGsx5

Thanks for you help!

**Comment by AndyIreland** [comment]
your car got the rlink2 yes?
Did you wire it up like this:
![image](https://user-images.githubusercontent.com/49172217/185755058-fd83c374-7a8a-4926-8205-6a488201c595.png)

what are you trying to enable / disable on it and have you tried changing the CAN timeout ms to 600ms and then refresh?

**Comment by zkmsh** [comment]
Hey,

So I make it work but my pin was a little bit damaged so I have a lot of error message. I order another adapter.

I don't have medianav (R-LINK) but I have the Carminat TOMTOM.

I'm trying to restore radio and bluetooth fonctionnality why was remove by Renault when I went to see them seeking for help.

**Comment by zkmsh** [comment]
Hello, I have a weird issue, everytime I try to change ms timeout to 600 ms, ddt4all just closed itself. 

I think the issue is that my acoustic parameters have been reset. I'm still looking on how to get them back.

I have no idea why ddt4all closed itself tho...

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by zkmsh** [comment]
Hello,

I gave up on this issue but I'm back at it.

If I understand correctly I have to find accoustic parameters and write them with DDT4ALL. I found these parameters: [https://gitlab.com/py_ren/pyren/-/blob/master/pyren/macro/megane3_fluence/radiosat_classic_bluetooth_accoustic.cmd](url), do you think it could work?
