### ISSUE TITLE
Crashes X11 Server on Linux Mate while Reading DTV

### ISSUE THREAD

**Issue by Nosleep28** [cedricp/ddt4all#716]
I got my version working on Linux Mate since made a few INT() castings when move or resize window function is called. It works fine now and is also displaying screen with appropriated information. It took a while to get QT5 installed, especially with the WebKit.
I had some trouble with the USB Signatur of my ELM327 Interface because it conflicted with other USB Hardware but i managed to find the conflict Hardware and comment it out in /usr/lib/udev/rules.d/85-brltty.rules seach for Device 1A86:7523 NLS eReader Zoomax and comment it out, reboot.

Finaly I got connect and got a lot of type mismatch errors. Expected int and got float. So I casted every occurrence of move and resize and finally it worked. 

Remaining issue is that X11 session crashed and logging out when I try to read DTC. I guess this has something to do with th type mismatch as well. Can you tell my where to find the logfile when ddt4all crashes?

best regards

Boris

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
