### ISSUE TITLE
R-Link Kangoo retrofit

### ISSUE THREAD

**Issue by Xtecek** [cedricp/ddt4all#720]
Hi! I am working in a Kangoo 2 for install R-link, i have bought full Kangoo rlink system with wiring but i have some problems

I am trying to start the sistem out of the car, i give +12 and ground to system but not work, screen start with TomTom logo and radio unit lights are on

I have a 32pin connector that dont have other to Connect, in this connector i have a lot of wires that i dont know for what are so i need a diagram or scheme for this connector, scheme says R369

Thanks a lot
![Screenshot_2022-09-14-01-26-30-200_com whatsapp](https://user-images.githubusercontent.com/113481207/190027011-ecf5b826-bc99-4e2c-b07a-358c5b419ddd.jpg)
![Screenshot_2022-09-14-01-26-11-430_com google android apps docs](https://user-images.githubusercontent.com/113481207/190027013-acb7d919-ae07-4c79-bfa1-0473a1a31097.jpg)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
