### ISSUE TITLE
R-link reset 

### ISSUE THREAD

**Issue by gabrielcozma33** [cedricp/ddt4all#721]

**Comment by gabrielcozma33** [comment]
Hello , i just delete all setup on the r link . I have a talisman 2016  and for the First time using ddt4all . I presa the Button on hard reset i think ! Now screen is black , no sound from speackers and all setup are gone . I try to reconfigure the settings but once i go out and return , everything is delete . Is there any option to configure the rlink? I dont want to go to dealership 🙈 sorry for my language

**Comment by AndyIreland** [comment]
hello - its more than likely 'soft reset' button you have pressed - have you not even got a screen with triangle saying "EOL" on it?

**Comment by gabrielcozma33** [comment]
Hello , thank you for the comment , no i dont have anithing , its all black . No sound ... if i go in radio setings all is not present , if i go in navigation all is deletet , i dont know what to do .

**Comment by gabrielcozma33** [comment]
I will put some photos with what i did .

**Comment by AndyIreland** [comment]
if you have windows laptop and bluetooth OBD2 adaptor and can get Internet in your car will you let me take over and look at your settings of your rlink over the Internet and try a couple of things?

**Comment by gabrielcozma33** [comment]
Yes , tomorow i will write you and we can try it if you want

**Comment by AndyIreland** [comment]
sure - I shall be available from 2pm onwards (UK Time)

**Comment by gabrielcozma33** [comment]
Hello . ![image](https://user-images.githubusercontent.com/113786441/190890591-dd982bd0-c0e6-4c08-9069-232d1e0e69b6.jpeg)

This is what i did.. configuration reset or key on reset . I dont remember 🙈

**Comment by AndyIreland** [comment]
Hello , it looks like you have the Rlink2 in your car would i be correct? - does it look something like this: 

![image](https://user-images.githubusercontent.com/49172217/190902321-7eb0793e-568f-49d8-afbb-443419beb326.png)

I was thinking you had a Rlink1 for some reason , and I was going to look at the files on my rlink1 and try them but that will be no good if you have a rlink2 unit

**Comment by gabrielcozma33** [comment]
Hello , i have fix it today . I Found a guy with program (peyton) i think 🥴 and he set the original File . Now Everithin is ok

**Comment by AndyIreland** [comment]
ah yes  right thats good PyREN he most probably used and a dump file

**Comment by gabrielcozma33** [comment]
Thank you for your help !👍👍👍

**Comment by AndyIreland** [comment]
thats OK, glad you got it working in the end

**Comment by hugoreispt** [comment]
Hey Andy. I messed up my rlink1 on Renault zoe. Need eol settings something like that. Could you help me? Got Windows 10 computer with ethernet connect and obd single, i just dont know how to operante pyren. 
Mu e-mail: hugoreispt1@gmail.com

**Comment by hugoreispt** [comment]
> thats OK, glad you got it working in the end

Hey Andy. I messed up my rlink1 on Renault zoe. Need eol settings something like that. Could you help me? Got Windows 10 computer with ethernet connect and obd single, i just dont know how to operante pyren.
Mu e-mail: hugoreispt1@gmail.com

**Comment by Aviv5510** [comment]
> Hello , i have fix it today . I Found a guy with program (peyton) i think 🥴 and he set the original File . Now Everithin is ok

hey, can u send me this ?

**Comment by AndyIreland** [comment]
> > thats OK, glad you got it working in the end
> 
> Hey Andy. I messed up my rlink1 on Renault zoe. Need eol settings something like that. Could you help me? Got Windows 10 computer with ethernet connect and obd single, i just dont know how to operante pyren. Mu e-mail: [hugoreispt1@gmail.com](mailto:hugoreispt1@gmail.com)

did you get it sorted/working?

**Comment by hugoreispt** [comment]
No. Havent spent time on it. Do you have a solution?

A sábado, 22/04/2023, 12:49, Andy Robus ***@***.***> escreveu:

**Comment by AndyIreland** [comment]
you can try copying this TomTom.000 file onto the root of a 8gb SD Card formatted to fat32 (not your map card) and see if it gets your rlink1 working. If not, put the file onto a 8gb usb stick formatted to fat32 and see if that gets your rlink1 working again:
https://we.tl/t-a87B6HD4wJ

**Comment by Aviv5510** [comment]
> you can try copying this TomTom.000 file onto the root of a 8gb SD Card formatted to fat32 (not your map card) and see if it gets your rlink1 working. If not, put the file onto a 8gb usb stick formatted to fat32 and see if that gets your rlink1 working again:
> https://we.tl/t-a87B6HD4wJ

You have a solution like this for Rlink 2 ?

**Comment by AndyIreland** [comment]
> > 
> You have a solution like this for Rlink 2 ?

No I havent , I just done this on my Rlink1 - there is a command script I think you can use with PyREN and try get rlink2 working i think

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
