### ISSUE TITLE
Noob questions 

### ISSUE THREAD

**Issue by xtendpayaa** [cedricp/ddt4all#724]
Hello everyone!
I have a 2018 Renault Kadjar and a 2010 Renault Grand Scenic.
I don't have garage so when it's raining outside all the night my Kadjar folding mirrors don't wanna really work. When no rain it's working perfectly. So I wanna switch off the automatic mirror folding I don't need it (if I need it anyway there is a button for it). So somebody know that how to do that? Because if it's not working perfectly now because the rain then 100% it's not going to work in -25°C too 😂
If somebody know in Scenic too it's a big plus!
Second thing is just an option not so important but is that possible to disable start-stop?
And where I can find database file for Renault?
Thank you!

**Comment by AndyIreland** [comment]
Hiya - i dont know what ECU's DDT4ALL finds on your Kadjar - but on my Clio mk4 2016 its on the UPC EMM ECU

![image](https://user-images.githubusercontent.com/49172217/191826908-53c42c46-1af8-4027-ad40-f4b4e0dcd9a6.png)

here is details for disabling stop start system , should be similar instructions for your car>
https://youtu.be/7-vIlxGQkv0

**Comment by xtendpayaa** [comment]
Thank you very much! I'm gonna try

**Comment by xtendpayaa** [comment]
I tried today the Android version ddt4all but no luck.
![Screenshot_20220924-112124](https://user-images.githubusercontent.com/45143351/192088914-e195e5da-ef63-47a9-8884-99e08cbd744f.png)
I've got only initializing CAN protocol... and that's it. I have iLC bluetooth obd2 scanner what is working perfectly with Torque pro but maybe not good with that software?

What is the cheapest known working device for PC or phone?

**Comment by AndyIreland** [comment]
I much prefer using the PC version of DDT4ALL 

This is one I got about a year ago , Kingbolen Bluetooth OBD2 works with DDT4ALL with me
£6.99 UK pounds

**Comment by AndyIreland** [comment]
If you have a windows laptop and can get an internet signal in your car and want me to check your obd2 and settings remotely over the internet just let me know

**Comment by xtendpayaa** [comment]
> If you have a windows laptop and can get an internet signal in your car and want me to check your obd2 and settings remotely over the internet just let me know

Thank you! I just order it from official website but 17.99USD. I don't know when it's arrive so now I need to wait patiently.

**Comment by xtendpayaa** [comment]
Hi again!
So my Kingbolen bluetooth obd reader arrived. I'm connected to Windows then start the ddt4all program. I've got Com3 and Com4 as port. If I choose com4 i got "permission denied" message if I choose com3 then start testing com speed but nothing more happening. I'm checked in Windows the com3 is incoming port with obd name, and com4 is outgoing with obd slave name. 
So what I'm fu*ked up? Or first start need to wait lot of time? Thank you!

**Comment by AndyIreland** [comment]
hiya glad you got it delivered - i would need to see how your laptop is configured and i cannot do that blindly, all i can do is log onto your laptop remotely and see how its all configured sorry

**Comment by xtendpayaa** [comment]
Hi again!
So ddt4all still not working with computer but working the Android program.
I have switched off start/stop and the folding mirrors with this:
https://github.com/cedricp/ddt4all/issues/131#issuecomment-457033526

But.. when open the car there is a led light in the tails until I start the car because then only DLR lighting in the front (of course there is light in the rear if switch on or auto switch the car because start to be dark outside). I think this is the welcome light? But where I can enable this led tail lights always on when I start the car? Because now in Finland starts to all the they "grey" weather but when starts little bit darkening then the "normal" tail lights switching on. I hope you understand what I want 😂

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
