### ISSUE TITLE
Megane 4 OBD2 can't connect via wifi

### ISSUE THREAD

**Issue by webmaster750** [cedricp/ddt4all#726]
Hello

I can't connect ddt4all with my adapter(on youtube the same adapter works and can do coding).  Car is Megane 4 GT. 

The error is : no ELM327 or OBlink detected on com port 192.168.0.10 :35 000

Maybe it is adapter fault?! But adapter works with apps like Torque and Csr scanner.

If You guys have working adapter that works, please post the name or link.

Thank You
![Screenshot_20221001_134351_com amazon mShop android shopping_edit_138318781590873](https://user-images.githubusercontent.com/114811210/193408125-d4fd00d5-3437-4c4c-a6ce-4d022ce80ef7.jpg)

**Comment by AndyIreland** [comment]
DDT4ALL normally requires a OBD2 Adaptor with a PIC18F25K80 chip in it - maybe yours not has it in it?

Here is mine that works with DDT4ALL , but its a bluetooth one:
https://www.amazon.co.uk/Kingbolen-Bluetooth-Scanner-Diagnostic-Compatible/dp/B07LC8LKRP

**Comment by webmaster750** [comment]
> DDT4ALL normally requires a OBD2 Adaptor with a PIC18F25K80 chip in it - maybe yours not has it in it?
> 
> Here is mine that works with DDT4ALL , but its a bluetooth one: https://www.amazon.co.uk/Kingbolen-Bluetooth-Scanner-Diagnostic-Compatible/dp/B07LC8LKRP

Yea maybe they changed the chip. I was looking this video and he use the same adapter and it works. https://youtu.be/8_MwY3U1klw
I will not open it to search what chip is it as I will return it, and buy what You recommend.
Thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
