### ISSUE TITLE
Clio V deactivate seatbelt warning

### ISSUE THREAD

**Issue by HolzFichte** [cedricp/ddt4all#727]
Hi ;) 
Is it possible to disable seatbelt alarm? 

Thx for the answers

**Comment by AndyIreland** [comment]
you would have to unlock the security gateway with a token first I think , it being a Clio mk5

**Comment by HolzFichte** [comment]
So I didn't have a chance to do it?

**Comment by AndyIreland** [comment]
> So I didn't have a chance to do it?

dont think you have a chance to change any parameters until you unlock the security gateway - can read settings, but not change/apply them

**Comment by HolzFichte** [comment]
Thx :)

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
