### ISSUE TITLE
Disable Auto STOP START not working on Clio IV ph2

### ISSUE THREAD

**Issue by fatherscott** [cedricp/ddt4all#728]
Hi;

Thanks for your hardwork and appreciated.
I have Clio 4 ph2, which is manufactured 06/2018. I Disable the setting under:
UPC-EMM -> EMM_EDISON_DDT2000_SW15_2_V1.0 -> EMM_AlternatorManagment -> EMM_AlternatorManagement-Configuration -> C_STOPSTARTInhibit 1 to 0. But nothing has changed. What has he done wrong?
Any idea?
Thanks

**Comment by AndyIreland** [comment]
I would have thought C_STOPSTARTInhibit should be at 1 for yes , instead of 0 

here instructions for Megane IV to disable stop and start - but should be similar settings to be carried out on the Clio 4
https://youtu.be/7-vIlxGQkv0

**Comment by fatherscott** [comment]
The default is 1, so I set it to 0

I think the default should be zero, too

Did I find the ecu wrong?

**Comment by fatherscott** [comment]
잘못된 정보때문에 되지 않았습니다.

BCM/UCH -> T4_VS_BCM_DDT2000_SW16_5 -> GEE -> GEE - Configuration -> E_B_STOPSTARTINHIBIT_CF false -> true

으로 변경해서 성공하였습니다.


It didn't work because of the wrong information.

BCM/UCH -> T4_VS_BCM_DDT2000_SW16_5 -> GEE -> GEE - Configuration -> E_B_STOPSTARTINHIBIT_CF false -> true

It was successful by changing to .

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
