### ISSUE TITLE
no choice on the combo in expert mode

### ISSUE THREAD

**Issue by thomthom33** [cedricp/ddt4all#73]
hello, 
i've an empty combo when choosing expert mode, i can't select "after sale". What's wrong doc ?
thanks

**Comment by cedricp** [comment]
This combo is for debug purpose, you should not use it. The program knows which diagnostic session mode to use.
If the combo is empty, it perhaps means that there are none defined in the XML. Have you tried with other XML ? It's working for me, though.

**Comment by thomthom33** [comment]
thank you for your reply. i have done what i wanted to do, with your great tool !
