### ISSUE TITLE
Help me!!!! Rlink 2 Espace V black screen

### ISSUE THREAD

**Issue by Grazi77** [cedricp/ddt4all#731]
Ciao a tutti 
Ho espace v che dopo aver tentato aggiornamento da chiavetta non si avvia più. Prese USB non vanno, non caricano nemmeno Smartphone, il display drive a volte cambia colore da solo verde a viola.
Ho già tentato diverse soluzioni, tra cui vol+- e power, 
E collegandomi con ddt4all mi sembra che le ecu siano ok.
Qualcuno ha un consiglio da darmi?
G.torazza@gmail.com

**Comment by rttr67** [comment]
il tuo blocco r link2 rotto
deve essere sostituito con un altro
Se sei interessato, ti mando offerte

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
