### ISSUE TITLE
App crashes while scanning ecu.zip file

### ISSUE THREAD

**Issue by K7J** [cedricp/ddt4all#733]
Tested on version - 1.81 and 1.74c
Android - 12 and 9 (Samsung Galaxy S21 and S9)

I've tried it with few databases and zipped/unzipped zip files with different packing speed etc. No luck, both of devices report "you need write storage permission" when clicking on logs. App crashes within no more than a few seconds. Is there any solution for that?

**Comment by AndyIreland** [comment]
have you enabled permissions for the app?

**Comment by KarelSvo** [comment]
give a small ecu.zip to test

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
