### ISSUE TITLE
Reverse camera on in driving forward? - Rlink1

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#735]
I saw on a forum the other day someone driving forward with their rear camera showing on their Rlink1 screen (normally the reverse camera image is only there on the screen when reversing obviously) - I cannot find the forum I see it on now typically and should have bookmarked it , but just for the comical factor and for testing purposes I want to enable it on mine just to see what is involved .
Any ideas what to change in the navigation settings in DDT4ALL?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ???
