### ISSUE TITLE
Edition mode doesn't work

### ISSUE THREAD

**Issue by josefe17** [cedricp/ddt4all#736]
I'm trying edition mode, but as far as i cannot find any documentation about it, i'm going blind. In fact, I don't know what does it do. I see that there are a bunch of adittional tabs, but if I select a know ECU for my car (T4 UCH SW 16.5), no data appears when in normal mode it works fine. And if I launch a search, only a non-perfect match ECM appears (but not mine, which is also not available during the scan) and the program crashes.

I don't know if I'm doing something wrong or the mode just doesn't work.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ???
