### ISSUE TITLE
No picture from rear camera on RLink(( Please help the experts)

### ISSUE THREAD

**Issue by StepanenkoNadejda** [cedricp/ddt4all#740]
Hello,
Who faced the situation. I connected the rear-view camera to the RLINK (yellow and black wires) Megane 3, activated it via ddt4all, the camera is connected to the rear lights. The camera turns on, but there is no picture on the screen. I've heard what additional configurations need to be installed. It's possible?

**Comment by AndyIreland** [comment]
have you wired up the composite video in? :

![image](https://user-images.githubusercontent.com/49172217/196780007-93cbd7c4-6de0-4c49-9908-65d9efd00d83.png)

**Comment by AndyIreland** [comment]
Did you reboot the rlink after making your changes?

**Comment by AndyIreland** [comment]
I wonder if the the wires under the seat are connected up to the back of the radio - in any case i thought the wire for the reverse camera were up  in the footwell area , not under the seat? 

there is also a CVBS (video in) ground as well on pin 19

**Comment by StepanenkoNadejda** [comment]
> I wonder if the the wires under the seat are connected up to the back of the radio - in any case i thought the wire for the reverse camera were up in the footwell area , not under the seat?
> 
> there is also a CVBS (video in) ground as well on pin 19

Yes. 19 and 21, they are the same turns out (grounding).

**Comment by StepanenkoNadejda** [comment]
![YbaH-w0_wfzVVlhqQfhRxSLj-xY-1920](https://user-images.githubusercontent.com/36893353/196790130-f9043a53-6565-4ea6-9f23-f3515cf5a5b2.jpg)
![8K73txpu-hhz9BPmxEnndNH8blI-1920](https://user-images.githubusercontent.com/36893353/196790136-af7fb57b-cb0b-4d2c-a7c1-58c67a75c55d.jpg)

**Comment by StepanenkoNadejda** [comment]
![YbaH-w0_wfzVVlhqQfhRxSLj-xY-1920](https://user-images.githubusercontent.com/36893353/196790977-43f5dc45-2a5e-45ef-aec3-31c220febc50.jpg)
![8K73txpu-hhz9BPmxEnndNH8blI-1920](https://user-images.githubusercontent.com/36893353/196790984-04b7c13b-2ba0-4791-9b27-f4d11e1bd5e8.jpg)

**Comment by AndyIreland** [comment]
if that were me i would pull off the trim , take out the rlink screen and put the wires straight to the back of the multi connector and see what happens. - its a good sign the screen goes black but backlit when you put car in reverse .
Can you see any reversing guidelines on the screen?

**Comment by StepanenkoNadejda** [comment]
> if that were me i would pull off the trim , take out the rlink screen and put the wires straight to the back of the multi connector and see what happens. - its a good sign the screen goes black but backlit when you put car in reverse . Can you see any reversing guidelines on the screen?

I also connected the R Link to the screen. Nothing. When the reverse speed is turned on, a black screen with guide lines appears, but there is no picture.

**Comment by AndyIreland** [comment]
and you are absolutely sure the camera is working - if the camera is 12v , try putting the positive up to a constant positive feed and not on the reverse light bulb socket

**Comment by StepanenkoNadejda** [comment]
> and you are absolutely sure the camera is working - if the camera is 12v , try putting the positive up to a constant positive feed and not on the reverse light bulb socket

Thank you! I'll try for the sake of experiment, maybe something will change. But as the camera has LEDs, they will be constantly lit as soon as the car will turn on.

**Comment by AndyIreland** [comment]
> > and you are absolutely sure the camera is working - if the camera is 12v , try putting the positive up to a constant positive feed and not on the reverse light bulb socket
> 
> Thank you! I'll try for the sake of experiment, maybe something will change. But as the camera has LEDs, they will be constantly lit as soon as the car will turn on.

are they infra red LED's though - the ones that help the camera see in the dark? - if they are you cannot see them lit up just with eye, but if you point your phone camera at them you will see them lit up

**Comment by StepanenkoNadejda** [comment]
No, I have a camera with ICE lighting, not infrared. Does it matter if the camera is with an ССD matrix or without an ССD?

**Comment by StepanenkoNadejda** [comment]
![20221020_084523](https://user-images.githubusercontent.com/36893353/196875711-7b7a837c-58c3-4e48-836f-63ec6402b029.jpg)

**Comment by AndyIreland** [comment]
so , when you have it wired up to the reverse bulbs when you put the car into reverse the LED lights are lit? - or do they only light up when its dark outside?

**Comment by StepanenkoNadejda** [comment]
> > > and you are absolutely sure the camera is working - if the camera is 12v , try putting the positive up to a constant positive feed and not on the reverse light bulb socket
> > 
> > 
> > Thank you! I'll try for the sake of experiment, maybe something will change. But as the camera has LEDs, they will be constantly lit as soon as the car will turn on.
> 
> are they infra red LED's though - the ones that help the camera see in the dark? - if they are you cannot see them lit up just with eye, but if you point your phone camera at them you will see them lit up

No, I have a camera with LED's lighting, not infrared. Does it matter if the camera is with an ССD matrix or without an ССD?

**Comment by StepanenkoNadejda** [comment]
> so , when you have it wired up to the reverse bulbs when you put the car into reverse the LED lights are lit? - or do they only light up when its dark outside?

LED is constantly glowing when I turn on the reverse gear. It doesn't matter day or night, since there is no light sensor on the camera. I also tried to connect the other 2 cameras. Nothing(

**Comment by StepanenkoNadejda** [comment]
> > so , when you have it wired up to the reverse bulbs when you put the car into reverse the LED lights are lit? - or do they only light up when its dark outside?
> 
> LED is constantly glowing when I turn on the reverse gear. It doesn't matter day or night, since there is no light sensor on the camera. I also tried to connect the other 2 cameras. Nothing(

They also write that you need to configure: multimedia, a parking sensor unit — so that the car understands what we want from it. To do this, the record of the type of your parking sensors (standard for example RDAVAR, RDPRAR, SRDPRO) should simply be replaced with RDAR01.

**Comment by StepanenkoNadejda** [comment]
![image](https://user-images.githubusercontent.com/36893353/196994293-9d229678-0025-45cd-8b9f-6d4e52044563.png)

**Comment by StepanenkoNadejda** [comment]
> ![image](https://user-images.githubusercontent.com/36893353/196994293-9d229678-0025-45cd-8b9f-6d4e52044563.png)

But I don't know how do it?)

**Comment by AndyIreland** [comment]
> > so , when you have it wired up to the reverse bulbs when you put the car into reverse the LED lights are lit? - or do they only light up when its dark outside?
> 
> LED is constantly glowing when I turn on the reverse gear. It doesn't matter day or night, since there is no light sensor on the camera. I also tried to connect the other 2 cameras. Nothing(

Can you make a screenshot of your settings for these parameters:

![image](https://user-images.githubusercontent.com/49172217/197040283-728b810f-c508-47ee-886d-0302da6a7cb3.png)

**Comment by AndyIreland** [comment]
and a screenshot of yours for this:

![image](https://user-images.githubusercontent.com/49172217/197041450-2b1d7b83-b467-4894-9e17-d9f72a2e0340.png)

**Comment by StepanenkoNadejda** [comment]
![2022-10-21_08-43-29](https://user-images.githubusercontent.com/36893353/197132760-a5ea9215-b736-473e-882b-2aac980b6769.png)
![2022-10-21_08-44-34](https://user-images.githubusercontent.com/36893353/197132769-eb6bcd47-1504-4463-8e67-eeea6273df28.png)

**Comment by StepanenkoNadejda** [comment]
> and a screenshot of yours for this:
> 
> ![image](https://user-images.githubusercontent.com/49172217/197041450-2b1d7b83-b467-4894-9e17-d9f72a2e0340.png)

Yes, of course)

**Comment by StepanenkoNadejda** [comment]
> Yes, of course)
> 
> ![2022-10-21_08-43-29](https://user-images.githubusercontent.com/36893353/197132760-a5ea9215-b736-473e-882b-2aac980b6769.png) ![2022-10-21_08-44-34](https://user-images.githubusercontent.com/36893353/197132769-eb6bcd47-1504-4463-8e67-eeea6273df28.png)

Yes, of course)

![2022-10-21_08-43-29](https://user-images.githubusercontent.com/36893353/197135327-7515cfa0-9284-4bc8-8702-0b5fa4f84a41.png)
![2022-10-21_08-44-34](https://user-images.githubusercontent.com/36893353/197135337-1bdbdf7a-7c4d-47cc-96bf-9b13918c3936.png)

**Comment by AndyIreland** [comment]
thanks for that , looks all ok - have you got reverse parking sensors on your car? 

Also where it says trunk handler message set that to not fitted and  the trunk open handler disable rvc set that to not fitted

**Comment by StepanenkoNadejda** [comment]
> thanks for that , looks all ok - have you got reverse parking sensors on your car?
> 
> Also where it says trunk handler message set that to not fitted and the trunk open handler disable rvc set that to not fitted

Yes, I have rear parking sensor).

**Comment by StepanenkoNadejda** [comment]
> thanks for that , looks all ok - have you got reverse parking sensors on your car?
> 
> Also where it says trunk handler message set that to not fitted and the trunk open handler disable rvc set that to not fitted

can there be a decoder in the car that does not allow the image to be displayed on the screen? 3 cameras tried to connect. Nothing(

**Comment by BarektE** [comment]
> ![20221020_084523](https://user-images.githubusercontent.com/36893353/196875711-7b7a837c-58c3-4e48-836f-63ec6402b029.jpg)

This camera does not work on R-Link.

**Comment by AndyIreland** [comment]
> > ![20221020_084523](https://user-images.githubusercontent.com/36893353/196875711-7b7a837c-58c3-4e48-836f-63ec6402b029.jpg)
> 
> This camera does not work on R-Link.

why not? - are you giving it 12v and not the 6v supply from the rlink?

**Comment by Furtif** [comment]
good post need a ref .. but clean in ... please refer it at discutions 
https://github.com/cedricp/ddt4all/issues/836

**Comment by Dorinmomo** [comment]
I have the same problem with Rlink 1, no image from rear cam. Did anyone fixed it? Can you tel me how?

**Comment by Dorinmomo** [comment]
I'm back !! I did it !!! OMG !! I have image on my rear camera. R link 1 renault captur. Activated it with ddt4all , bought a chinese connection cable  that said "for renault" but it did not work.... I thought it was the camera, tested all the wires, 👎 .... The thing was that the wires where in the wrong place(pins). I did not check if it was on the 18, 19 pins. Took all out and reconect the wires and it worked. The camera was aftermarket, like in the pictures. 
![17159652722611039177459834047726](https://github.com/cedricp/ddt4all/assets/170031235/2ada513b-92e0-407a-9436-0dea787225c6)
Thank you for posting here .

**Comment by Dorinmomo** [comment]
> I wonder if the the wires under the seat are connected up to the back of the radio - in any case i thought the wire for the reverse camera were up in the footwell area , not under the seat?
> 
> there is also a CVBS (video in) ground as well on pin 19

Probably the wires are not up to the screen, mine had not. You need to go with the wires up to the back of he screen. That's why you do not have image. 
![IMG_20240517_172346](https://github.com/cedricp/ddt4all/assets/170031235/e161d97b-a414-4339-81f6-3ac8b7227687)
![IMG_20240517_174627](https://github.com/cedricp/ddt4all/assets/170031235/d12e404c-7b2b-4527-80f8-94b004ed430a)
![IMG_20240517_171538](https://github.com/cedricp/ddt4all/assets/170031235/a2c142aa-d5a6-4c80-ba03-46c451e48c24)
![IMG_20240517_171506](https://github.com/cedricp/ddt4all/assets/170031235/4b979ea7-7ca8-491d-ae78-7d630eaead95)
![IMG_20240517_175445](https://github.com/cedricp/ddt4all/assets/170031235/ef45f5ce-4856-46d0-bee7-1092bd724ef0)

**Comment by AndyIreland** [comment]
if any help to anyone here is wiring diagram to the back of the MFD (multi function touchscreen display) 
![image](https://github.com/cedricp/ddt4all/assets/49172217/fedb80f9-4214-4d6c-94b9-2f5ddccc45d3)

**Comment by R-3MY** [comment]
> I'm back !! I did it !!! OMG !! I have image on my rear camera. R link 1 renault captur. Activated it with ddt4all , bought a chinese connection cable that said "for renault" but it did not work.... I thought it was the camera, tested all the wires, 👎 .... The thing was that the wires where in the wrong place(pins). I did not check if it was on the 18, 19 pins. Took all out and reconect the wires and it worked. The camera was aftermarket, like in the pictures. ![17159652722611039177459834047726](https://private-user-images.githubusercontent.com/170031235/331677223-2ada513b-92e0-407a-9436-0dea787225c6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5Mjg2MTgsIm5iZiI6MTcxNzkyODMxOCwicGF0aCI6Ii8xNzAwMzEyMzUvMzMxNjc3MjIzLTJhZGE1MTNiLTkyZTAtNDA3YS05NDM2LTBkZWE3ODcyMjVjNi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxMDE4MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hY2I2ZjZiMzI5OWRkNDhiMDkyZjE1MGM0ZTQ2YWVjYzljNjQzMjQ1ZWQ1MTJlZjAxOWNiNjM4ZjM2ZDliMjljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R2KvuBtsqQt3yxsCRmI-2N9O5nO7ir5_C7keNNLh0Gg) Thank you for posting here .

Thank you, you literally saved me!

I tested several 12v cameras and I still have the same problem (black screen) however when I put my finger in front of the camera I do have a "display" only it seems to be very noisy. I briefly see guide lines but no display of the image that should come from the camera.

I have a Kangoo II ph 2 with rear sensors.

Regards, Rémy.
