### ISSUE TITLE
Renault Espace V seat defekt

### ISSUE THREAD

**Issue by Espace123** [cedricp/ddt4all#742]
I'm asking for help, my seat is blocked, I can't push forwards and backwards, and everything else is done by massage, etc., I moved the ecu from the passenger seat and it worked until my wife sat down and moved the seat, it blocked again and then I bought a new ecu and it worked  until yesterday and the third one blocked it, everything works except forward and backward pushing. The cables are ok under the seat, there is nothing stuck. Can I reprogram the seat or calibrate it so that it works? Can't I keep buying the ECU which costs €452 please help

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ??????
