### ISSUE TITLE
ECU tweaker source code

### ISSUE THREAD

**Issue by cedricp** [cedricp/ddt4all#743]
Hi all,
I decided to open source the Android port - **ECU tweaker**, you can find repo here :
https://gitlab.com/DrQuark/android_can
I have no time for it anymore.

**Comment by JABICHOCU** [comment]
This has been a very useful app for me...thanx for all your efforts :)

**Comment by David050893** [comment]
hello... thank you very much in advance for contributing your knowledge to the community,

on the other hand I don't know if this is an appropriate question,
I am doing a university work and I have used much of your material specifically the ddt4all repository, which I hope to share if all goes well, only I still have doubts and I would like you to help me clarify them, because after identifying the variable in the hecadeximal data string in a PID request I have had difficulty seeing the value in our decimal system, is there a specific formula or what should I do, you could guide me please ...

**Comment by cedricp** [comment]
Please describe what's not clear, I'll try to explain as much as I can

**Comment by AlMeu** [comment]
Where can be found this edition mode?

**Comment by cedricp** [comment]
Select **edition mode** from the first window (ELM selection one)

**Comment by AlMeu** [comment]
In my 5.5.0 isn't
![image](https://user-images.githubusercontent.com/55224357/215836680-42b6be43-cde5-48b3-8153-9dd637ecd211.png)
There is another version?

**Comment by cedricp** [comment]
Latest verion : 

![startup](https://user-images.githubusercontent.com/5940937/215838387-dae045fd-f827-4059-a35a-90a3d35fe104.png)

Demo should work, though

**Comment by AlMeu** [comment]
There is somehere this last version for download?

**Comment by AlMeu** [comment]
I downloaded latest version v2 and try to run in Win10 x64 with OBD EX interface.
I installed the drivers for this and run it in connected mode, but in scan didn't detect anything.
I tried also in Edition mode and I have got this fault:
![image](https://user-images.githubusercontent.com/55224357/215882331-b6c9aba5-dce6-4f05-b807-69fe3568e950.png)

**Comment by David050893** [comment]
Thank you very much for your help, I really appreciate it!!!

**Comment by AndyIreland** [comment]
why am i seeing ECU tweaker source code in the title ... but its DDT4ALL ???

**Comment by cedricp** [comment]
Check the link in the first post, I released ECU tweaker source code

**Comment by AlMeu** [comment]
I managed to make start Edition mode but when I scan I get this error and quits:
![image](https://user-images.githubusercontent.com/55224357/217088639-1ae9b2f0-32da-47aa-9b54-e091f3915325.png)
Same issue also with same version in Connected mode.
Any ideea?

**Comment by Sartascn** [comment]
Complimenti per il progetto Ecu Tweaker. Riesco a leggere tutti i parametri ma, non riesco a modificarli. C'è qualche suggerimento utile? Grazie

**Comment by Sartascn** [comment]
Scusami Cedric... Quando avvio Ecu Tweaker non mi compare l'icona del lucchetto. Di conseguenza, non posso inviarti il codice di attivazione. Potresti spiegarmi meglio? Grazie infinite!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by Larrypao1** [comment]
hola cedric me gustaria poder tener la licencia de ecu tweaker y gracias por tu gran aporte

**Comment by billigizer** [comment]
Hi guys, i just found out about ecu tweaker. Is it to late to try? Is the elm dongle wifi/Bluetooth still compatible? I bought a autel device for 1 100 dollars just to find out this, which is almost free, is more useful for me so i feel devestated and happy at the same time. I guess money can't always buy happiness 🙁😂 thank you in advance Cedric, what amazing work (the part that is understandable for me)
