### ISSUE TITLE
Can ddt4all set clock on Megane 3 RS265 after retrofitting RS Monitor ?

### ISSUE THREAD

**Issue by c0ssie1** [cedricp/ddt4all#744]
Can ddt4all set clock on Megane 3 RS 265 after retrofitting RS Monitor ?

My RS265 currently has the carminat tomtom fitted, I am told I can swap this out for the RS Monitor V1, however some coding is required to be able to set the clock afterwards (as this is currently set via the tomtom sat nav).

Is this something ddt4all can do ?

**Comment by MellotronScratch** [comment]
You will need to modify some settings in the radio. There is a setting where you can select "with or without" navigation. When selecting 'without', the clock settings will be available in the radio menu.
I don't know the exact name of the setting, but I'm sure you will find out.
