### ISSUE TITLE
Renault Zoe 40 Electronic Parking Break Service Mode

### ISSUE THREAD

**Issue by schmidtas** [cedricp/ddt4all#748]
Hi ddt4all-User and Developer,

would it be possible with ddt4allto put the electronic parking break into the service position.
I have to change my brake pads and discs on the rear axle and am looking for a way to open the electronic parking brake.
It would really be a great help if that would work with ddt4all.

BR
Alexander

**Comment by KarelSvo** [comment]
email?

**Comment by schmidtas** [comment]
Good Morning, 
is there a possibility to send you my email via private message?
BR
AS

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
