### ISSUE TITLE
Renault talisman: screen, radio not working what to do ? 

### ISSUE THREAD

**Issue by talisman0007** [cedricp/ddt4all#752]
Hi! Suddently, the emergency download message popped up on my Renault talisman screen. I figured that need to update the system through the official website, using a USB. While doing this the system just showed “downloading: 4 min left” for about 2 hours. I had to turn of the car, and since the screen is black and nothing works. I can’t seem to figure why this has happened. Some threads link the issue to a burned screen unit, but how is this possible and what the best and easiest fix for this? Any ideas ?

**Comment by rttr67** [comment]
Hello, I will advise only by e-mail

**Comment by talisman0007** [comment]
Hello,

Yes please!


tor. 17. nov. 2022 kl. 16.44 skrev rttr67 ***@***.***>:

**Comment by rttr67** [comment]
email

**Comment by talisman0007** [comment]
My mail is: ***@***.***

Thank you !

tor. 17. nov. 2022 kl. 19.44 skrev rttr67 ***@***.***>:

**Comment by rttr67** [comment]
My mail is: ***@***.***       email I don't see mail

**Comment by talisman0007** [comment]
Oh sorry ill try again: 

316349@via.dk

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
