### ISSUE TITLE
Black Screen Renault Koleos 2018 Full Full 

### ISSUE THREAD

**Issue by Youssef-711** [cedricp/ddt4all#756]
Can you help me 
Car model Renault Koleos 2018 Full Full 
I turned on Nervision mode 
The screen is black
VF1RZG007JC301840 
![16691684193407822674649682441085](https://user-images.githubusercontent.com/118640514/203455374-d60a88af-41cc-4889-b40d-8b577db
![16691685803534107730645214789739](https://user-images.githubusercontent.com/118640514/203455673-52db8784-025b-4a9e-9bf6-4421932b7570.jpg)
68e56.jpg)

**Comment by poli27** [comment]
pyren ;)

**Comment by poli27** [comment]
https://www.blogarama.com/technology-blogs/1353906-medianav-skins-maps-wince6-micon-manager-ddt4all-navitel-igo-7way-sevenway-hacks-supermod-mn1-mn2-mn3-dacia-renault-blog/43071970-link-black-screen-repair

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
