### ISSUE TITLE
Vag Com cable support ?

### ISSUE THREAD

**Issue by lemonsqueeze** [cedricp/ddt4all#758]
Hi,

I was wondering if ddt4all can / could work with a vag com kkl obd2-to-usb cable ?
I have to check but i think linux support is good, shows up as a serial device.

For info i'm trying to talk to the EPS module of a 2004 Nissan Micra (K12).
Initially thought i might succeed with Nissan Datascan II + this cable.
Setup works to talk to the car, but it doesn't know how to talk to the EPS module unfortunately.

EPS part is almost the same on Renault Modus and Clio3 apparently, so could give the [clio3 eps reset plugin](https://github.com/cedricp/ddtplugins/blob/master/clio3_eps_reset.py) a try if it can be made to work.

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all#supported-diagnostic-adapters-so-far

**Comment by fridlington** [comment]
Did you try one of the supported adaptors? I'm also wanting to talk to the EPS module in a Micra K12 to virginise a replacement unit. I'm happy hacking python but need to know if I can see the EPS first.

**Comment by lemonsqueeze** [comment]
Unfortunately no, I don't have one of the supported adaptors besides the VAG COM KKL cable I have.
I wouldn't be surprised if it could be made to work, but could use some help / hints from ddt4all devs.
@Furtif maybe ?

**Comment by fridlington** [comment]
Thank the for the reply. I've found a cheapish ELM327 adaptor with a PIC18F25K80 on Amazon so I might just give it a go.

I'll update if I get anywhere with it - you're probably aware of the cost of a replacement EPS unit for the K12 so spending a few pounds on a cable is worth it.

**Comment by lemonsqueeze** [comment]
Cool, yes definitely, would be interesting to know if it can talk to the module.
Might start hacking too then =)

In my case after some time i got tired of trying tools that didn't work and ended up taking the thing apart and flashing the EEPROM directly to virgin it (had come across a video on youtube about it). Was a bit crazy, but it worked. Once. Afterwards the error code came back, so I guess my unit really is faulty and i'll have to replace it. Going for a second hand one though, so there will be some virgining to do.

**Comment by fridlington** [comment]
Adaptor with correct chip ordered. Fingers crossed!

**Comment by fridlington** [comment]
So I can see the EPS module (Direction assistée) - but there's no ECU file for it:

```
Scanning CAN
Found ECU [INV-RL] (no relevant ECU file found) :DIAGVERSION [0] SUPPLIER [B] SOFT [6422] VERSION [001A]
Found ECU [UPC-EMM] (no relevant ECU file found) :DIAGVERSION [0] SUPPLIER [A] SOFT [0000] VERSION [0000]
Found ECU [Direction assistée] (no relevant ECU file found) :DIAGVERSION [0] SUPPLIER [B] SOFT [6422] VERSION [001A]
Found ECU [UCH] (no relevant ECU file found) :DIAGVERSION [2] SUPPLIER [21] SOFT [0005] VERSION [0300]
```

The EPS reset plugin for the Clio III kind of works - the PS light goes out on the dash - but then it returns after a few seconds. The issue I think is that the VIN number isn't being found - entering the VIN manually results in an error.

There's also an error in the console relating to this:

`Traceback (most recent call last):
  File "./ddtplugins/clio3_eps_reset.py", line 112, in check_virgin_status
    self.read_vin()
  File "./ddtplugins/clio3_eps_reset.py", line 79, in read_vin
    vin_values = vin_read_request.send_request({}, "61 81 68 69 70 65 65 65 65 65 65 65 65 65 65 65 65 65 66 00 00")
  File "/home/eilidh/ddt4all/ecu.py", line 283, in send_request
    values = self.get_values_from_stream(elmstream)
  File "/home/eilidh/ddt4all/ecu.py", line 319, in get_values_from_stream
    values[k] = data.getDisplayValue(stream, v, self.ecu_file.endianness)
  File "/home/eilidh/ddt4all/ecu.py", line 667, in getDisplayValue
    return bytes.fromhex(value).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
`

...Looks promising though?

**Comment by AndyIreland** [comment]
manually select the DAE ecu then? 
Sometimes the magnifying glass in DDT4ALL dont pick up all ecu's so then you might have to (carefully with caution) select the ECU manually from the list:
![image](https://user-images.githubusercontent.com/49172217/230119706-80c8a5ea-c3cd-4c6c-bdec-ba6eac98b46f.png)

**Comment by fridlington** [comment]
Thanks for the reply. Unfortunately I get no data. It's really annoying because I'm certain I can see the ESP module because the light turns off and the error disappears from the screen above the radio.
![Screenshot from 2023-04-05 16-07-57](https://user-images.githubusercontent.com/7612404/230123724-cfe2d099-0bb1-491c-9566-ac940928939c.png)

**Comment by AndyIreland** [comment]
try increasing the can timeout in DDT4ALL to 600ms and refreshing - if that dont work pick one of the micra DAE in the list (if its a micra car you are working on for the EPS)?

**Comment by fridlington** [comment]
Tried increasing the timeout and still no luck. I'm wondering if I need to find the correct ECU files - ddt4all picks up 4 ECUs but none have any files associated with them. Yes, it's a Micra K12, 2005

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
