### ISSUE TITLE
clio ıv gizli özellikler

### ISSUE THREAD

**Issue by serhataydinlik** [cedricp/ddt4all#761]
merhaba 2012 clio ıv 1.5dci icon donanım arabam var eller serbestken kumandadan kapıları kilitlendiğinde eller serbest olarak kapıların açılma özelliğini nasıl açabilirim kumanda dan bağaj açmayı nasıl aktif edebilirim. Şoför ve yolcu koltuğu emniyet kemer sesini nasıl kapabilirim

**Comment by burakcankose** [comment]
brkcnks@live.com mail at yardımcı olayım

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
