### ISSUE TITLE
I ELM benchmarked my cable and some things failed - Does this matter

### ISSUE THREAD

**Issue by Sennadachi** [cedricp/ddt4all#765]
v1.0 ATZ [OK]
v1.0 ATE1 [OK]
v1.0 ATL0 [OK]
v1.0 ATI [OK]
v1.0 AT@1 [OK]
v1.0 ATAL [OK]
v1.0 ATBD [OK]
v1.0 ATBI [OK]
v1.0 ATCAF0 [OK]
v1.0 ATCFC1 [OK]
v1.0 ATCP 01 [OK]
v1.0 ATCS [OK]
v1.0 ATCV 1250 [OK]
v1.0 ATD [OK]
v1.0 ATDP [OK]
v1.0 ATDPN [OK]
v1.0 ATH0 [OK]
v1.0 ATI [OK]
v1.0 ATIB 10 [OK]
v1.0 ATIB 96 [OK]
v1.0 ATL1 [OK]
v1.0 ATM0 [OK]
v1.0 ATMA [OK/TIMEOUT]
v1.0 ATMR 01 [OK/TIMEOUT]
v1.0 ATMT 01 [OK/TIMEOUT]
v1.0 ATNL [OK/TIMEOUT]
v1.0 ATPC [OK]
v1.0 ATR1 [OK]
v1.0 ATRV [OK]
v1.0 ATSH 001122 [OK]
v1.0 ATSH 012 [OK]
v1.0 ATSP A6 [OK]
v1.0 ATSP 6 [OK]
v1.0 ATCM 123 [OK]
v1.0 ATCM 12345678 [OK]
v1.0 ATCF 123 [OK]
v1.0 ATCF 12345678 [OK]
v1.0 ATST FF [OK]
v1.0 ATSW 96 [OK]
v1.0 ATSW 34 [OK]
v1.0 ATTP A6 [OK]
v1.0 ATTP 6 [OK]
v1.0 ATWM 817AF13E [OK]
v1.0 ATWS [OK]
v1.1 ATFC SD 300000 [OK]
v1.1 ATFC SH 012 [OK]
v1.1 ATFC SH 00112233 [OK]
v1.1 ATFC SM 1 [OK]
v1.1 ATPP FF OFF [OK]
v1.1 ATPP FF ON [OK]
v1.1 ATPPS [OK]
v1.2 ATAR [OK]
v1.2 ATAT1 [OK]
v1.2 ATDM1 [OK/TIMEOUT]
v1.2 ATIFR H [OK/TIMEOUT]
v1.2 ATIFR0 [OK]
v1.2 ATIIA 01 [OK]
v1.2 ATKW0 [OK]
v1.2 ATMP 0123 [OK/TIMEOUT]
v1.2 ATMP 0123 4 [OK/TIMEOUT]
v1.2 ATMP 012345 [OK/TIMEOUT]
v1.2 ATMP 012345 6 [OK/TIMEOUT]
v1.2 ATSR 01 [OK]
v1.3 ATCRA 012 [OK]
v1.3 ATCRA 01234567 [OK]
v1.3 ATD0 [OK]
v1.3 ATFE [OK]
v1.3 ATJE [OK]
v1.3 ATJS [OK]
v1.3 ATKW [OK]
v1.3 ATRA 01 [OK]
v1.3 ATS1 [OK]
v1.3 ATSP 00 [OK]
v1.3 ATV0 [OK]
v1.4 ATCEA [OK]
v1.4 ATCEA 01 [OK]
v1.4 ATCV 0000 [OK]
v1.4 ATIB 48 [OK]
v1.4 ATIGN [OK]
v1.4 ATPB 01 23 [OK]
v1.4 ATRD [OK]
v1.4 ATSD 01 [OK]
v1.4 ATSI [OK]
v1.4 ATFI [OK]
v1.4 ATSS [OK]
v1.4 ATTA 12 [OK]
v1.4 ATCSM1 [FAIL]
v1.4 ATJHF1 [FAIL]
v1.4 ATJTM1 [FAIL]
v1.4 ATJTM5 [FAIL]
v1.4b ATCRA [FAIL]
v2.0 ATAMC [FAIL]
v2.0 ATAMT 20 [FAIL]
v2.1 ATCTM1 [FAIL]
v2.1 ATCTM5 [FAIL]
Result: 86 succeeded from 95
ELM Max version:v1.4

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ??????????????????????
