### ISSUE TITLE
Megane 3 DRL customisation

### ISSUE THREAD

**Issue by johnroberts2k** [cedricp/ddt4all#771]
Is there a parameter somewhere for the megane 3 to keep the DRL's on all the time? I noticed there is a parameter about enabling or disabling PWM on the DRL lights.

**Comment by AndyIreland** [comment]
this is instructions on my Clio Mk4 2016 - 

https://myrenaultclioblog.wordpress.com/2020/06/14/have-drl-led-driving-lights-on-along-with-headlights-on-a-renault-clio-mk4/



but i think you will have a different lighting ECU on your Megane .. in fact I am almost sure it will be.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
