### ISSUE TITLE
Sound problem and black screen after trying downgrade

### ISSUE THREAD

**Issue by Ibratk** [cedricp/ddt4all#773]
Good morning everyone, I have a Renault Megane 4 from 2016. I replaced my Radio unit from HW 1. with a used Radio unit from HW 3. I did this to be able to use Carplay. Now the Carplay works but I have no sound anymore. I have tried with cable and bluetooth but there is no sound. Not even the parking sensors. Will it help if I mount the old original radio unit and make a backup (dump) and put it back with the new radio unit? Does anyone know how I can fix this?

(Translated from Dutch)

**Comment by AlMeu** [comment]
I think your unit is bricked, remains to change with other one.
I can help with some new units or old unlocked. If you need leave an email for contact.

**Comment by Ibratk** [comment]
I've heard it might be because of Bose edition. Should I encode it maybe? My email is: ibow-58@hotmail.com

**Comment by AndyIreland** [comment]
have you got a bluetooth OBD2 and specially wired cable where you can read the radio through the obd2 socket? 
Also is  it a medianav or rlink you have? 
Medianav= USB socket to right of touchscreen.
Rlink = USB socket next to map SD Card reader down by the gear shifter.

**Comment by Ibratk** [comment]
I have an R link down by the gear shifter. I have an elm327 cable that allows me to use ddt4all but I don't know where to see the values ​​and what to do with them.

**Comment by AlMeu** [comment]
@AndyIreland don't lead again to wrong ways. 
If not sound at all, in any way ... no radio, no bluetooth, no USB .... that are not parameters
But you can try whatever you want, hope always dies last, but what's dead will stay dead.

**Comment by AndyIreland** [comment]
> I have an R link down by the gear shifter. I have an elm327 cable that allows me to use ddt4all but I don't know where to see the values ​​and what to do with them.

Ah right - you mean you have the map SD card down by the gear shifter? 

Your screen looks like this?:

![image](https://user-images.githubusercontent.com/49172217/214141930-abe3dea0-8989-4068-ab00-9e493c9f5a82.png)

and a wired up cable (or ELM327 adaptor) like this ? 
![image](https://user-images.githubusercontent.com/49172217/214143373-786d9006-c2d6-4f85-b167-5a76e3d329ee.png)

**Comment by Ibratk** [comment]
Yes SD card is down by the gear shifter. I have a R link 2 big screen. And yes i have a ELM327 adaptor like the right one on the picture. You know what i have to do ?

![62A3CD57-6947-46CC-90CD-7C40CC57364D](https://user-images.githubusercontent.com/123362948/214147254-f805ea3a-3848-433e-982a-9ed4aafbb8c8.png)

**Comment by AlMeu** [comment]
So @AndyIreland what was his question and what you answer it .... :-D

**Comment by AndyIreland** [comment]
ah right sorry both - for some reason I thought it was  a rlink 1 (evolution) and I might of had an idea if it were that.  

If it similar to rlink 1 you should still be able to go into sound parameters using DDT4ALL and check them settings, see if any adrift. 

if you have a windows laptop and can get internet signal  when in the car @Ibratk  I could take a look over the internet and see if anything jumps out at me even though I havent got an rlink2

**Comment by shrlnm** [comment]
@Ibratk what is your VIN and LGU version of new box?

**Comment by Ibratk** [comment]
Vin = VF1RFB00356620149 and Lgu version on the radio unit is: hw 3.11,4.4 and sw 3.3.16.946. but since I didn't have a radio I updated it to 9.0.37 and it still doesn't work.

**Comment by AlMeu** [comment]
@shrlnm pay attention there is not sound at all in anything, bluetooth, radio, etc and moreover now free upgrade from 3.3 to 9.0, "cherry from the cake"

**Comment by Ibratk** [comment]
Now I tried to downgrade again because some functions were not working but suddenly I got black screen. I have no image anymore. It's getting worse...

**Comment by shrlnm** [comment]
@Ibratk ohh. If you did an upgrade from LGU v3 on LGU v9 then I can't help you. Sorry. Your r-link 2 is dead.

**Comment by Ibratk** [comment]
Hi @shrlnm . I bought a new Radio for my car but i need to remove/change the VIN number of the radio. I've read in other threads that you can change in Virgin mode but I'm not good at it. Can you help me with Teamviewer or something else?

**Comment by shrlnm** [comment]
Hi @Ibratk what version of LGU is on the new radio? What VIN number do you have?

**Comment by Ibratk** [comment]
@shrlnm The HW ver: 3.10.5.4 and SW ver: 7.0.24.136. My vin number: VF1RFB00356620149

**Comment by shrlnm** [comment]
@Ibratk https://cloud.mail.ru/public/wNpb/ZhskospaT

**Comment by Ibratk** [comment]
@shrlnm What should I do with this cmd file?

**Comment by AlMeu** [comment]
Run it as macro in pyren.

**Comment by Ibratk** [comment]
So i must first activate virgin mode and then this cmd file run it on Pyren?

**Comment by shrlnm** [comment]
@Ibratk if you need to change the vin then you have to virginize the box first

**Comment by Ibratk** [comment]
@shrlnm Ok thank you!
