### ISSUE TITLE
> hopefully this one will work for you it does with my ecu tweaker app:

### ISSUE THREAD

**Issue by salihakin** [cedricp/ddt4all#776]
> hopefully this one will work for you it does with my ecu tweaker app:
> 
> https://filebin.net/8pco7lo5ts6uv0j8

I am interested in this file. Can you upload it again

_Originally posted by @salihakin in https://github.com/cedricp/ddt4all/issues/711#issuecomment-1416462790_

**Comment by salihakin** [comment]
when I unzip the ecus.rar from the link in Issue https://github.com/cedricp/ddt4all/issues/56 and repack it as ecu.zip, the Android app crashes reproducible.
Is there another way, or a "real" ecu.zip as download?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
