### ISSUE TITLE
hi. help to restore R-link with the same problem. here is my vin VF1KT12C652410846 "Unconfigured device, please add EOL settings"

### ISSUE THREAD

**Issue by Zaiac5215273** [cedricp/ddt4all#784]

**Comment by shrlnm** [comment]
t.me/pyren_bot

**Comment by bruvv** [comment]
@shrlnm that bot does not work anymore.

**Comment by shrlnm** [comment]
Please check once again. Now it's working
![Screenshot 2023-04-09 at 07 21 37](https://user-images.githubusercontent.com/16278412/230754253-09bf3e4a-fd5f-426d-81c6-0f197d3426db.png)
![Screenshot 2023-04-09 at 07 22 00](https://user-images.githubusercontent.com/16278412/230754255-9b636b1e-cd66-4d24-9763-a85ecb52a976.png)

**Comment by bruvv** [comment]
It does thanks ! So for my understanding just put these in the macro folder and run them with pyren right ?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
