### ISSUE TITLE
cannot find TCU0_Gen1_V3.4. xml in my database

### ISSUE THREAD

**Issue by AndyIreland** [cedricp/ddt4all#790]
in DDT4ALL I can find TCU0_Gen1_V3.4 ... but if I go into my ecus folder I cannot find the TCU0_Gen1_V3.4. xml file in there at all , I can find a TCU_Gen1_v3-4_20120803T094851.xml but thats not the same. 

any idea please

**Comment by KarelSvo** [comment]
If you open TCU_Gen1_v3-4_20120803T094851.xml in the editor you will see the file name as it is displayed in ddt4all.

`<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="http://www-diag.intra.renault.fr/DDT2000/DDTECUPreview.xsl"?>
<xml xmlns:ddt="http://www-diag.renault.com/2002/ECU">
<Generator name="DDT2000 XML library" version="2.0.0.1" date="2012-08-03T08:31"/>
<ddt:Target Name="TCU0_Gen1_V3.4" xmlns="http://www-diag.renault.com/2002/ECU" xmlns:ds="http://www-diag.renault.com/2002/screens" email="stephane.amic@altran.com" href="TCU_Gen1_v3-4_20120803T094851.xml" upload="8/3/2012" group="TCU"><Description><![CDATA[Base DiagONCAN TCU0 Gen1 version 3.3`

**Comment by AndyIreland** [comment]
thanks @KarelSvo  -
