### ISSUE TITLE
Is there an option within DDT4all to enable Steering wheel mounted radio controls?

### ISSUE THREAD

**Issue by MichaelPHolstein** [cedricp/ddt4all#793]
Dear all,

I am the owner of a Renault Clio and I am experiencing an issue with the radio controls on my steering wheel. As shown in the attached image, the controls are as follows:

![376a3ea0-14df-4a64-9f31-535c92e6ad12](https://user-images.githubusercontent.com/45170519/226185839-eeef0ff8-7020-41d5-b7fe-2f2eae282b95.jpeg)

I previously had a MediaNav Evolition (V1) installed and the controls worked perfectly. However, since configuring a MediaNav Evolution V2, the MediaNav does not respond to the radio controls. I would like to inquire if there is an option within the ECU audio/ULC_gen4_v.1. to enable these controls.

Thank you in advance for your assistance.

**Comment by AndyIreland** [comment]
try changing these settings swc:

![image](https://user-images.githubusercontent.com/49172217/226194935-bec914dd-3464-482e-a72b-8e1ef64cb85a.png)

**Comment by KarelSvo** [comment]
DataWrite.ECU Config2
ECU Config2.SWRC2 type
No SWRC2

DataWrite.ECU Config
ECU Config.SWRC type
Type 2: Without Mute (TypreX52)

**Comment by MichaelPHolstein** [comment]
Thank you! This solved the problem. I'll close the issue now
