### ISSUE TITLE
TuningNumber clio iv option

### ISSUE THREAD

**Issue by glcvr6** [cedricp/ddt4all#795]
It’s not a issue but question.

I was searching for some options in my Clio MK4 2015 1.5dci
 and I found this option

TuningNumber

And it have 4 options: 
0. Normal
1. Default
2. CityMode
3. (Not used)
![6799E633-32AD-4A9A-8326-2E98C9333D66](https://user-images.githubusercontent.com/28484791/227070633-63cbdf57-fad5-42fe-bd51-fec72ce71287.jpeg)

Does anyone know what this represent?
Are those ecu maps? Does anyone have more info about this?

**Comment by AndyIreland** [comment]
what ECU is it on? - it might give an idea of what it changes

**Comment by KarelSvo** [comment]
Steering assistance sensitivity

**Comment by glcvr6** [comment]
Thank you.
