### ISSUE TITLE
ECU relevant file not found [CLIO IV]

### ISSUE THREAD

**Issue by vganeshh** [cedricp/ddt4all#797]
Hello,

I am trying to edit the lighting parameters on DDT4ALL. I have attached a USB ELM327 and installed the drivers for them to work. Loaded up the software and clicked on the magnifying glass to scan CAN. During the CAN, it finds 6 ECUs however the one that I would like to edit results me with this error "found ecu [upc-emm] (no relevant ecu file found) :diagversion [8] supplier [414] soft [c130] version [4001]".

I have tried to reinstall the DDT4ALL software and updated the database to 2021. The error still occurs. I have also tried another ELM327 cable, same issue. Then I tried manually choosing the ECU from the database above. I can see that some values are being read, the rest giving me "NO DATA". I have also tried increasing the timeout to allow time to read the ECU. I'll attach screenshot of my screen, hopefully if anyone has expereiced something like this or have a solution, please do let me know.

![image](https://user-images.githubusercontent.com/128825296/227559902-599c933b-22e0-465c-ab08-48c8e3fa410e.png)

**Comment by KarelSvo** [comment]
> "found ecu [upc-emm] (no relevant ecu file found) :diagversion [8] supplier [414] soft [c130] version [4001]".

EMM_EDISON_DDT2000_SW13_V1_3
EMM_EDISON_DDT2000_SW13_V1_3_20141029T084120.xml
AutoIdent DiagVersion="8" Supplier="414" Soft="0130" Version="4001"
Your file cannot be found automatically because of a typo in the autoident line.

**Comment by vganeshh** [comment]
Yeah, got it now thanks. It was SW13.

If I change the EMM-T4 on the car to a module from a newer car, is it possible for it to be SW15 to support the features from the lighting configuration?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
