### ISSUE TITLE
 Downgrade from 7.0.24.161 to 3.3.16.961 failed

### ISSUE THREAD

**Issue by BBFul** [cedricp/ddt4all#798]
Hello! I ve made a mistake. I ve downgraded my rlink2 from 7.0. to 3.3 and now my reverse camera is not working at all, parking sensors are without sound and not appear on the display, temperature is shown in F beside C, can t turn off navigation from button. I ve tried all versions of firmware but always got this message: " It is not possible to install a former software version, current software version is kept “. Can anyone give me an advice?
P.s. Emergency  download is not working.
Thanks!
![20230324_153433](https://user-images.githubusercontent.com/55613397/227637657-70f270f8-0e3a-476b-9beb-05f5e9319153.jpg)
![20230324_153215](https://user-images.githubusercontent.com/55613397/227637669-4abd8e4d-e439-4a47-8e45-2ddb114331b2.jpg)

**Comment by rttr67** [comment]
enter your email address

**Comment by BBFul** [comment]
work.acces@yahoo.com
 Thanks!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by rttr67** [comment]
I can help.
The device needs to be replaced

**Comment by rttr67** [comment]
I can help.
The device needs to be replaced
zaliavos.ud@gmail.com

**Comment by AlMeu** [comment]
> Hello, Allow me to bump this thread. I'm facing the same error when trying to downgrade from v8 to v3, after an incorrect upgrade to v8 with an incompatible bootloader. Could you please share how you managed to solve your issue? Thank you very much!

Yes, only replace unit you can do in your case.
You have to get a new unit or old one unlocked.
