### ISSUE TITLE
Radio not turning off automatically in Clio IV after MediaNav Evolution 2 replacement

### ISSUE THREAD

**Issue by JakubUrbanowski** [cedricp/ddt4all#799]
Hello everyone, I have a Clio IV with a wireless key. I have replaced my MediaNav Evolution with a MediaNav Evolution 2. Previously, the radio would turn off when I turned off the engine and opened the door. Now, the radio stays on and I have to turn it off manually.

Does anyone have an idea which configuration could be causing this? I have only configured the ECU ULC_gen4_v.1.4 for this. I do have the "digital radio antenna phantom supply" set to active instead of passive. Could this be the problem?

Thank you in advance for your help.

**Comment by AndyIreland** [comment]
have you tried MICOM MANAGER on your evolution - it my have door setting in that. In my clio mk4 it has the evolution (9.1.3 - what is your software version on yours?)  ( mine with DAB but no AA & CP)  and I can get into Micom manager with that  . I think you can use micom manager with the later evolution with AA & CP.

**Comment by JakubUrbanowski** [comment]
I’m using 

> have you tried MICOM MANAGER on your evolution - it my have door setting in that. In my clio mk4 it has the evolution (9.1.3 - what is your software version on yours?) ( mine with DAB but no AA & CP) and I can get into Micom manager with that . I think you can use micom manager with the later evolution with AA & CP.

I have an MN3 V1.0.15.3. What settings would this be within the MiCom? And would I also be able to set up parking sensors here?

**Comment by KarelSvo** [comment]
DataWrite.WAKE UP
Wake Up from SYSTEM ON

**Comment by JakubUrbanowski** [comment]
Thank you! This did the trick. And how can I enable parking sensors within MiCom? 

This is my MiCom screen 
![5EB0C016-4EF0-4288-86AC-8699C6AD08A6](https://user-images.githubusercontent.com/128751124/227739776-3c9dd8b7-6a0d-48ab-ba19-1814248605ac.png)

**Comment by AndyIreland** [comment]
here is my 9.1.3 micom manager (its earlier than your medianav) and I think parking sensors on mine is SND or HMI i cant remember .. (and our clio mk4 hasnt got UPA sensors either) 
![image](https://user-images.githubusercontent.com/49172217/227739911-5ffe48bb-1213-4004-b71a-a73e7c7ac565.png)

**Comment by AndyIreland** [comment]
your one surely would be the bottom row 

UPA SND, UPA SPK and UPA HMI for Universal parking sensors

**Comment by JakubUrbanowski** [comment]
For me it was only the button UPAHMI. 

Thank you for helping!
