### ISSUE TITLE
Testing the program and not work

### ISSUE THREAD

**Issue by tameratf** [cedricp/ddt4all#8]
I try use the master version and it is not work , i see error when I refresh one shoot and the Changes not applied .
And I try another version  the program freeze when I select the ECU .
I need make some changes on my car
I use windows 10 .

**Comment by cedricp** [comment]
Please be serious, and give us information about your configuration : 
* OBD Cable type
* Vehicle your are trying to connect
* Log files
If you see ERROR in the parameters, you are probably facing a bad (cheap) ELM dongle, try an ELM benchmark and report

**Comment by tameratf** [comment]
>  ELM 327 usb v1.5
> Renault duster 2015
>  log files 
[logs.zip](https://github.com/cedricp/ddt4all/files/1304595/logs.zip)

**Comment by cedricp** [comment]
Try with latest commit

**Comment by hoonythink** [comment]
thanks

===================================
피큐브(주)

조정훈

H.P : 010 - 3153 - 2012
E-MAIL : hoonythink83@gmail.com
===================================

2017-09-15 16:21 GMT+09:00 Cedric PAILLE <notifications@github.com>:

**Comment by hoonythink** [comment]
the same.
it still not working.

have a nice weekend.

**Comment by tameratf** [comment]
The last version of master not read elm 327 usb .
i use Windows 10 .
