### ISSUE TITLE
Ambient light return always to red after turning off the vehicle

### ISSUE THREAD

**Issue by AymanNass** [cedricp/ddt4all#804]
I have a renault Megane IV 2018 and i have this issue, every other options is being saved but when I change the color of the ambient light and I turn off the car, if I turn it on after 15 minutes it loses the saved option and I see the ambient light red.

Is there a way to try to fix this by ddt4all? I tried to disable the color 2 from ddt4all to disable the red one but when I turn on the link I still see the 5 colors, anyone has a suggestion of something that I can do to fix this or at least delete the red color?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836 ???????????????????????????
