### ISSUE TITLE
Scenic IV - UPAMode Error

### ISSUE THREAD

**Issue by guidzit** [cedricp/ddt4all#809]
Hi there,
I had a small accident with my Scenic IV, one of the rear parking sensor got crashed, since I have an error message "aide au parking à contrôler". I changed the sensor, but I still have the error message.
I downloaded ddt4all and checked. When I diagnose the ECU (USA_Bosch_Gen5_V7.9) first of all I have no DTC. In Status/General Status I got a message UPAMode : Error. Same in Status/UPA Status.
The new sensor seems to react as when I put my finger on I can here some "clicks clicks clicks".
I thinks the system is jammed as I got an issue and I should reinitialize the ECU or something like that. Maybe the Advanced RW Configuration/Reset/SW Reset could help, but... I do not know what it does, and I would like to avoid to do something wrong.

![1](https://user-images.githubusercontent.com/130385897/230939344-c9ae715a-51d2-4ae3-ba79-571d97cace2f.png)
![2](https://user-images.githubusercontent.com/130385897/230939384-9221d967-546b-4787-926f-e9c464f4af35.png)

Could someone help, please ?

Thanks a lot !

**Comment by AndyIreland** [comment]
where is the message is it on the dashboard cluster where the speedo is?

**Comment by guidzit** [comment]
Yes on the dashboard. At the bottom, just under the speedo.

**Comment by shrlnm** [comment]
Here is my article about this problem https://www.drive2.ru/b/505062866315903447/

**Comment by AndyIreland** [comment]
ah right what does ddt4all recognise as your cluster/tdb when you do a search for ecu's with the magnifying glass ?

**Comment by guidzit** [comment]
I am downloading pyran and try. I will come back as soon as I have informations.

@AndyIreland : I will check

Thanks !

**Comment by AndyIreland** [comment]
> @AndyIreland USA_BOSH is a right ECU. I have the same in my car and I also have similar problem with it. It is very slow and ELM327 in normal mode (without special trick) can't read it.

ah right I was thinking more of disabling UPA on the dash/cluster/TDB myself of clearing message 

![image](https://user-images.githubusercontent.com/49172217/230945306-28b61420-b4fe-42a5-8702-dedfe7dba293.png)

**Comment by guidzit** [comment]
Ok, tried Pyren. It works fine ! It told me that I have tons of failures on "aide au parking". Cleared all, but as soon as I put reverse gear. Rear right sensor is again in failure. So definitely, my eBay no name sensor is not compatible... Ordered a Bosch, received a no name...
If I go 1st gear first, front sensor are responding. so ECU seems to be ok.
I will switch sensors tomorrow to
![3](https://user-images.githubusercontent.com/130385897/230965285-c90ef5a3-8247-4733-9982-9fa5251185a4.png)
 confirm the diagnosis. 

Regarding cluster ECU, it seems to be Cluster_15-40_v3.20.00, I also have a CLuster_15-40_v3.30.05.

Thanks for your support ! I will keep you informed

**Comment by guidzit** [comment]
Hi,
More info. I inverted sensors. Still the same error, so it is not coming from the sensor itself, rear right side sensor failure. I have a DTCA73195 code "bad sensor mounting". I do not really know what it means...
Is there any possibility that during the crash, as the sensor was broken in 2 that it shortcut a ECU input ?

Thanks

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
