### ISSUE TITLE
No elm response

### ISSUE THREAD

**Issue by sgouman** [cedricp/ddt4all#81]
Hello.
I tested the obd tool in ddt4all and no errors came up.

But when i connect to the car(with the correct wires soldered) and i enable android auto it just says elm response and then nothing behind it.
Also when i press hard reset in ddt4all nothing happens.

The obs tool is fine because when i use obd doctor it reads out the engine rpm fine.

i got the error log here
https://pastebin.com/YpcDka0N

**Comment by cedricp** [comment]
Check connections again...

**Comment by Furtif** [comment]
not ok by wifi .... https://github.com/cedricp/ddt4all/issues/834
