### ISSUE TITLE
Renault Talisman ventilated and heated seat not working

### ISSUE THREAD

**Issue by iulianmara** [cedricp/ddt4all#811]
Hello guys! 

I have an issue with a Talisman Initiale Paris which do nothing when I press heat or ventilation button for both front seats. Did someone had this issue? 
I saw in DDT4all that the function is active, but is not working.
Can someone help me to solve this problem?

Thanks!

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
