### ISSUE TITLE
Megane IV Rlink2 downgrade failed 3.3x to 2.2x

### ISSUE THREAD

**Issue by Aviv5510** [cedricp/ddt4all#812]
Hello, i tryied to downgrade my Rlink 2 system and failed.
screen went black in the during the downgrade (unofficial file) and stuck like this ever since.
no touchscreen, no radio,  no a\c, absoulutly nothing working.
No sound
cluster flashing 2 colors
idk if usb is working
i have tryied and phyton scripts and still no luck.

any help please ?

**Comment by AlMeu** [comment]
Your unit is dead and you nned replace with another.
The problem is all these units installed in cars, are locked to run only in that car.
If you want a brand new unit or old one unlocked, leave an email for contact.

**Comment by rttr67** [comment]
I can help  email for contact.

**Comment by Aviv5510** [comment]
Avivpele@gmail.com

Thank you 🙏🏼

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
