### ISSUE TITLE
Zoe Q210 - Not the basic "Battery charging impossible" - how to fix it?

### ISSUE THREAD

**Issue by HK-Zoe** [cedricp/ddt4all#814]
Hello all! I own Zoe Q210 but I have problem with the car. I took the car to service to have the sway bar bushings replaced (everything else was OK). I don't know what the technicians are doing but...

All this is after the replacing the sway bar bushings. First I got message "STOP Electric Failure DANGER" but after lock the car it disappeared. Less than 5 minutes after I lock the car, I get message "Battery charging impossible" and I can't start the car. After I clear EVC with CanZE the Zoe works perfectly fine until I lock the car again. 5 minutes and then I get the same message "Battery charging impossible". 

The errors are:
DF058 (DTC 048373) - TRACTION BATTERY RELAY CIRCUIT
DF018 (DTC 1525F3) - CONSISTENT MULTIPLE SIGNALS FOR CC/SL

[Screenshot of the errors.](https://i.ibb.co/hddwCct/errors.webp)

Does anyone have idea what could be the problem and is there a way to fix it temporary with ddt4all?

I tried with fully charged 12V battery and a brand new one - the issue is still here.

[Video of the issue.](https://www.facebook.com/plugins/video.php?height=314&href=https%3A%2F%2Fwww.facebook.com%2Fhristiyan.d.kolev%2Fvideos%2F175844751954387%2F%3Fidorvanity%3D695124514257075&show_text=false&width=560&t=0)

P.S. I have an appointment for diagnostics at the official dealer on 04.05 (this was the soonest available). But until then I want to try anything else.

**Comment by AndyIreland** [comment]
CC is Cruise control - SL is speed limiter. 

Do you think you are comfortable enough with  locking out the zoe to see if this resets any faults? - it might or might not work.

So with drivers door open wait for car to sleep (display and lights go off) then undo the 12v negative battery terminal under the bonnet . 

then remove the cover under the drivers mat covering the lockout (RHD Zoe) and unlock the lockout (you dont have to take it straight out), it will disconnect the 380v DC system . 

so with the 12v system and the 380v system totally disconnected this could be enough to drain the power out of the ECU's - try and leave them disconnected for an hour or 2 or overnight. 

when ready re-connect the orange 380v dc lockout and then the negative terminal onto the 12v battery in that order . 

You more than likely will have to put a code into your Zoe Rlink radionav to get it working again . You can find the number written at the back of your owners book that come with the car or install the my renault phone app and get the radio code from there. 

its worth a try , it does not cost you nothing . Dont do it if you are not comfortable - renault main dealers normally have 500volt DC protective gloves on and PPC gear and safety googles on to perform a lock out of the zoe.  - I have done it loads of times with my Zoe ... and I am still here and have not electrocuted myself yet ,  haha

**Comment by AndyIreland** [comment]
ah right at least thats one other thing you have tried. 

Maybe have a go at PyREN and see what DTC errors come up on that as 'memorized' and 'PRESENT'  ?

**Comment by shrlnm** [comment]
@HK-Zoe It's better to use qpyren3 and look inside these DTCs
Also look in documentation for description of these DTCs, especially about the first one DTC 048373

**Comment by AndyIreland** [comment]
I might sound like I am grabbing at straws sorry, but I think I have heard of a few instances where the relays have 'fused' together on the (could be PEB board or EVC board) before when they have been charged on high speed chargers - it could be that , ... but its just a guess I am not a mechanic or anything .

**Comment by HK-Zoe** [comment]
![Screenshot_2023-04-30-00-57-59-791_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327124-f39799fe-aa75-49a5-b7f5-a84048032fe9.jpg)
![Screenshot_2023-04-30-00-58-06-287_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327128-f92f9751-41b6-41d5-a2e8-50e716c58b7d.jpg)
![Screenshot_2023-04-30-00-58-15-473_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327131-764a59de-773b-4d36-ad3f-b4c17e19e5eb.jpg)
![Screenshot_2023-04-30-00-58-22-378_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327133-d15a70fa-23bd-4fcf-ab90-b0abfdca8c50.jpg)
![Screenshot_2023-04-30-00-58-28-793_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327134-e553bcf6-cdbd-4d49-a184-d8971e1f76b4.jpg)
![Screenshot_2023-04-30-00-58-36-012_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327135-4c59df23-38a0-4d9e-85f1-6e4abd9c0341.jpg)
![Screenshot_2023-04-30-00-58-42-107_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327137-dee567da-b5db-47fb-b28b-b6d9d597bcc9.jpg)
![Screenshot_2023-04-30-00-58-49-490_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327138-95736816-7bba-468d-97c8-fdaedd2cf1f3.jpg)
![Screenshot_2023-04-30-00-59-00-102_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327139-ada4b63a-a138-481e-8001-e94aec4de0d4.jpg)
![Screenshot_2023-04-30-00-59-08-063_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327140-220577e1-6b7f-4768-8888-ee7bf4575232.jpg)
![Screenshot_2023-04-30-00-59-15-551_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327141-0f294596-4727-4b91-8296-ad3c20d2d9a4.jpg)
![Screenshot_2023-04-30-00-59-22-947_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327142-235737dc-9b1f-4f27-90e3-f4dc35fc6003.jpg)
![Screenshot_2023-04-30-00-59-36-445_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327143-a7c4c739-2885-4857-b8e6-5a290c8475b7.jpg)
![Screenshot_2023-04-30-00-59-42-338_lu fisch canze](https://user-images.githubusercontent.com/127788986/235327144-d4781165-582d-4a60-a3dd-8bf73f01b6e7.jpg)

**Comment by Furtif** [comment]
i think question is in https://github.com/cedricp/ddt4all/discussions/835 have fun

**Comment by KarelSvo** [comment]
> The errors are: DF058 (DTC 048373) - TRACTION BATTERY RELAY CIRCUIT DF018 (DTC 1525F3) - CONSISTENT MULTIPLE SIGNALS FOR CC/SL

> P.S. I have an appointment for diagnostics at the official dealer on 04.05 (this was the soonest available). But until then I want to try anything else.

How was your problem solved?

**Comment by RPAuto** [comment]
i have same problem
RACTION BATTERY RELAY CIRCUIT DF018 (DTC 1525F3)
if i clear error car run when i stop for 5m error can back again.
can someone help me?

**Comment by HK-Zoe** [comment]
> i have same problem RACTION BATTERY RELAY CIRCUIT DF018 (DTC 1525F3) if i clear error car run when i stop for 5m error can back again. can someone help me?

Im driving the Zoe with this problem more than a year. If you find any solution, please share it with us.
How did you get the error for first time?

**Comment by matzel82** [comment]
> > i have same problem RACTION BATTERY RELAY CIRCUIT DF018 (DTC 1525F3) if i clear error car run when i stop for 5m error can back again. can someone help me?
> 
> Im driving the Zoe with this problem more than a year. If you find any solution, please share it with us. How did you get the error for first time?

Do want give me your VIN ? I want take a look 👀

**Comment by HK-Zoe** [comment]
> > > i have same problem RACTION BATTERY RELAY CIRCUIT DF018 (DTC 1525F3) if i clear error car run when i stop for 5m error can back again. can someone help me?
> > 
> > 
> > Im driving the Zoe with this problem more than a year. If you find any solution, please share it with us. How did you get the error for first time?
> 
> Do want give me your VIN ? I want take a look 👀

Send me a email (my email address is in my bio) and I will give you my VIN.

**Comment by KarelSvo** [comment]
> i have same problem RACTION BATTERY RELAY CIRCUIT 

[Zoe_PH1.htm.zip](https://github.com/cedricp/ddt4all/files/15047481/Zoe_PH1.htm.zip)

**Comment by matzel82** [comment]
That’s not the correct code. It’s from the speedometer….

**Comment by matzel82** [comment]
I have found it…i send you a translation per email

**Comment by KarelSvo** [comment]
> That’s not the correct code. It’s from the speedometer….

Then give the correct code from @RPAuto,  whose answer I quoted.

**Comment by HK-Zoe** [comment]
> I have found it…i send you a translation per email

Okay, i will wait for the email. Thanks!

**Comment by matzel82** [comment]
The resistance of the exciter rotor and the brushes in the motor must be measured. This work should be carried out exclusively by a specialised workshop. This is the indication of the error.
![image](https://github.com/cedricp/ddt4all/assets/31157216/bf08c442-bacf-4e78-8c27-38320479e8e4)

**Comment by matzel82** [comment]
ATTENTION: ⚠️ This work is dangerous and may only be carried out by specialist personnel, an activation of the high-voltage circuit is mandatory. There is a danger to life in case of non-compliance ⚠️
