### ISSUE TITLE
Echo and volume problems Apple carplay

### ISSUE THREAD

**Issue by Lauddt94** [cedricp/ddt4all#816]
Hi everone,

I have an issue with my megane IV after changing my 7’’ display to the 8.7’’ version.

Since this swap and some struggles with the settings, the audio quality of phone-calls with apple carplay are bad. I have no problems on my side during phone calls but on the other side of the line they hear an echo after speaking and the volume is so low they can barely hear me. 

Does anyone know what settings in DDT4All I need to check for this issue?

Thanks.

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836
