### ISSUE TITLE
Macro function Pyren

### ISSUE THREAD

**Issue by Lauddt94** [cedricp/ddt4all#817]
To load a acoustic macro I need to use the macro function on the pyren launcher. In my version the physical 'macro' button is missing. Does anyone know what to do? Is this something in the settings or do I have an wrong version? 
![snip pyren](https://user-images.githubusercontent.com/129327944/235132440-f3a4e697-225d-48d4-aca4-15ee6c1530c3.png)

**Comment by AndyIreland** [comment]
download the file from here , 
https://gitlab.com/py_ren/pyren

unzip it (if you have to) then copy the files to the Pyren folder in program files x386 folder (overwrite files when asked to do so) then launch

**Comment by Lauddt94** [comment]
Thanks, it worked!
