### ISSUE TITLE
Clio V Rain Sensor Activate Problem

### ISSUE THREAD

**Issue by rappc87** [cedricp/ddt4all#819]
My Clio V Joy already has a rain/light sensor. 

But the wiper controller did not have auto mode. I bought an controller with auto mode and replaced it.

Then I made the auto wipe mode true, but there is no reaction. In false mode, it works periodically as if it is level 1 when in auto mode. where am i doing wrong?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/issues/836

**Comment by yusufcali45tr** [comment]
Hello, I couldn't find the solution.
