### ISSUE TITLE
dddt4all.py - Localization issue

### ISSUE THREAD

**Issue by bovirus** [cedricp/ddt4all#82]
@cedricp 

Hi.

Creating the master language (**_ddt4all.pot_**) with **_pot_create.bat_** you can get an error

ddt4all.py:509: warning: 'msgid' format string with unnamed arguments cannot be properly localized:
The translator cannot reorder the arguments.
Please consider using a format string with named arguments,
and a mapping instead of a tuple for the arguments.

The problem is in **_ddt4all.py_** line **_509_**

                print _("Cannot load plugin %s, %s") % (plugin, traceback.format_exc())

It seems that the problem is the character % alone.

Thanks.

**Comment by bovirus** [comment]
@cedricp 

Is there any way to fix this problem on localization?

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/discussions/833
