### ISSUE TITLE
ddt4all crashes when opens an ECU virgin

### ISSUE THREAD

**Issue by AlMeu** [cedricp/ddt4all#822]
I try run ddt4all v1 detects the ECU with VIN empty and when try open it is crashes!!!

![2023-05-08_085052](https://github.com/cedricp/ddt4all/assets/55224357/41232ab8-b87c-47d6-b768-dd9803882b4c)

**Comment by KarelSvo** [comment]
[ULC_gen4.1_v0.5_20210325T103439.xml.zip](https://github.com/cedricp/ddt4all/files/11434559/ULC_gen4.1_v0.5_20210325T103439.xml.zip)

I don't know where the problem is in ddt4all. I have removed the ReadVIN from Screen 12 in the ECU file.
You can load the file via File/Open XML.

**Comment by AlMeu** [comment]
I open your XML and doesn't crash when I click on that tab.
There it is ddt4all the problem. I have even the old version with python 2.7 and in that doesn't crash but don't open that tab when the VIN is empty.

**Comment by KarelSvo** [comment]
Perhaps there is still an ecu.zip in the program folder without this file?

**Comment by AlMeu** [comment]
I have an ecu.zip and I renamed as ecu______.zip and it reads the same.
As I know also in that ecu.zip contains these.
I will remove ecu.zip and retry once again.

**Comment by AlMeu** [comment]
@KarelSvo 
I have tested also without ecu.zip and it is showing same list, even if ecu folder have more versions.

**Comment by AlMeu** [comment]
I ddt4all with python 2.7 same errors, but not crashes, don't open that page but keep me the window opened.
![2023-05-09_220045](https://github.com/cedricp/ddt4all/assets/55224357/49f8a7ac-ac67-40cd-8173-ba6dbf1e3bda)

**Comment by KarelSvo** [comment]
Does the ULC file appear if you don't select a vehicle type?
Tried ULC VIN in Pyrene mod_ddt?

**Comment by AlMeu** [comment]
If I have ecu folder without selecting vehicle the ULC ECU still doesn't appears all.
Then I tried and removed ecu folder and left only ecu.zip and in this way it shows all versions of ECU ULC.
I am using Pyren too, but seams also this gives the same error to this ECU with empty VIN and here even block the scanning!!!!
![2023-05-09_222238](https://github.com/cedricp/ddt4all/assets/55224357/fa39e9f2-47d2-4477-970c-9e2515c78d88)

**Comment by KarelSvo** [comment]
Try this change in ddt4all file ecu.py
![image 3612](https://github.com/cedricp/ddt4all/assets/30380693/7588dcb5-3954-4998-971c-5f70597f581a)

**Comment by AlMeu** [comment]
Yes, in this way, doesn't crash anymore. :+1: 
It opens the pages anyway, and it shows empty VIN fields. I hope to let me write in future the VIN there.

**Comment by KarelSvo** [comment]
I think so.
You need to find the file and line from the end of the crash message.

**Comment by AlMeu** [comment]
I have done, and it works
![image](https://github.com/cedricp/ddt4all/assets/55224357/ed671043-a029-4921-8da1-a5d73f1782de)
Thanks

**Comment by MiqdadAli2002** [comment]
![F66DE877-70DB-41B6-B32E-0992AB2595FE](https://github.com/cedricp/ddt4all/assets/88861243/8cf05eca-463b-4646-8b71-52b024d67821)
Can you help me with this issue please
