### ISSUE TITLE
Megane 3 - Automatic re-lock duration

### ISSUE THREAD

**Issue by LemurMort** [cedricp/ddt4all#823]
Hello all!
Curious Lemur here 😃
I have a question regarding duration of automatic re-lock (if after unlocking the car no door is opened the car locks itself again).
Default value is duration in minutes (0, 1, 2...).

I'm curious if decimal values can be put here.
Ie. for 30s should the value be 0.5 or 0,5 (with **dot** or **comma**)?

Thank you!

**Comment by Furtif** [comment]
is hard to reply try Community as https://github.com/cedricp/ddt4all/discussions

**Comment by KarelSvo** [comment]
> I'm curious if decimal values can be put here. Ie. for 30s should the value be 0.5 or 0,5 (with **dot** or **comma**)?
> 


If you don't tell the name of the relevant ECU file, it's difficult to give help.

**Comment by AndyIreland** [comment]
something like this ECU  I suppose in BCM/UCH:

![image](https://github.com/cedricp/ddt4all/assets/49172217/acd42449-68d8-4e4c-bea1-65778943d09c)

This is for BCM95 SW16 V16_1 --- but you may have a different BCM ECU version in your Megane3

**Comment by LemurMort** [comment]
Hey guys. My BCM is BCM95_SW25_V1. 1

**Comment by AndyIreland** [comment]
> Hey guys. My BCM is BCM95_SW25_V1. 1

so this then- but i could not tell you if using decimal point will work sorry (as in 1.5 means 1 and a half minutes)

![image](https://github.com/cedricp/ddt4all/assets/49172217/e5bcfcb7-fa94-41e4-b845-e44077778b51)

**Comment by KarelSvo** [comment]
> I'm curious if decimal values can be put here.

The value sent uses only 1 byte.
1 byte can only represent [whole decimal values between 0 and 255](https://kb.iu.edu/d/afdl).

![6232897u56](https://github.com/cedricp/ddt4all/assets/30380693/a6425e26-cca1-4eef-9734-747d5f458bc7)

**Comment by LemurMort** [comment]
Thanks a lot for your help! 🙂
