### ISSUE TITLE
Renault Zoe Q210 - Keyless

### ISSUE THREAD

**Issue by HK-Zoe** [cedricp/ddt4all#824]
Hello,
I own Renault Zoe Q210. Is it possible to activate keyless entry and keyless start with ddt4all?

**Comment by AndyIreland** [comment]
it possible - but you would have to have all the aerials inside the car, there are loads of them all over the place

**Comment by HK-Zoe** [comment]
What are the all aerials that I have to replace and how to activate it after that with ddt4all?

**Comment by AndyIreland** [comment]
the handsfree module aerials are in the front doors and behind the handbrake lever, and behind the dash near the cigarette lighter socket and in the boot area. 
If your car did not come with handsfree entry and keyless then none of the aerials will be there in the car (possibly neither the wiring looms for the aerials as well) - be a lot of work to put them all in I would imagine. 

the DDT4all settings would be in the BCM module 

for keyless:
![image](https://github.com/cedricp/ddt4all/assets/49172217/ed9ef3b5-f6ba-4359-9c71-ccab87d2d456)


for handsfree door entry:
![image](https://github.com/cedricp/ddt4all/assets/49172217/376a3104-330c-4b1c-99f3-cac3b79b681b)

possibly more settings elsewhere

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/discussions

**Comment by Furtif** [comment]
it is not a issue
