### ISSUE TITLE
Renault Talisman Front camera issue 

### ISSUE THREAD

**Issue by MiqdadAli2002** [cedricp/ddt4all#825]
Hello
I have an issue with my Renault Talisman 
The issue is with the front camera 
when I scan the errors I find that
(DTCAD0451 COMPUTER CALIBRATION)

**Comment by KarelSvo** [comment]
DTCAD0451 front camera : Diagnosis procedure
Performing calibration of the front camera

Force the vehicle's + after ignition feed.

Wait for 5 seconds.

Calibrate the computer.

Note!!!

The targets (Ms. 1994) should be placed in front of the vehicle.

Ensure that the field of vision of the camera is free.

Verify that the protection of the lens is removed.

RENAULT-CLIP-LAUNCH-ACTUATOR Domain:(FRONT CAMERA) CF001-COMPUTER CALIBRATION

Note!!!

If the calibration is not performed correctly, please check that targets are clear and correctly positioned, as well as the camera.

**Comment by MiqdadAli2002** [comment]
Is there another way to solve it because I don’t have laser device or targets and no workshop in my region does it

**Comment by MiqdadAli2002** [comment]
@shrlnm can you help me please?

**Comment by shrlnm** [comment]
@MiqdadAli2002 unfortunately, I don't know how to help with calibaration

**Comment by MiqdadAli2002** [comment]
I need file dump please

**Comment by shrlnm** [comment]
@MiqdadAli2002 you may generate major parameters by pyren_bot, but not sure that they contains calibrations.

**Comment by MiqdadAli2002** [comment]
actually the bot doesn’t work

**Comment by MiqdadAli2002** [comment]
dump for front camera because I have many none

**Comment by shrlnm** [comment]
@MiqdadAli2002 bot is working. Do not type brackets <> in commands. Just
/vin VF1RFD005JC25xxxxx

**Comment by shrlnm** [comment]
Bingo! )

**Comment by Furtif** [comment]
for discutions and not issue please uses https://github.com/cedricp/ddt4all/discussions

**Comment by kyhnipek** [comment]
I made it with help of [this video](https://www.youtube.com/watch?v=OoJ5Vn9krfk).  Lane departure warning and traffic sign recognition are working properly now.

Procedure for front camera calibration of Talisman;
1) Print two copies of target pattern with original size (160mm) ([target pattern](https://drive.google.com/file/d/1CxTj5uIqAX2UrDic67eXdBCQTshI3-W1/view))
2) Place target patterns:
  - I recommend performing this procedure in an enclosed, well-lit area. (sunlight also can cause fail this calibration when do it at outside)
  - Distance of target pattern from front axle center = 3000mm
  - Right target pattern must be placed center of front logo horizontally and with 1450mm height vertically for left handed drive cars (probably left pattern on center of front logo on right handed cars) 
  - Place left target pattern with a center-to-center distance of 467mm from right target pattern (467mm for europe, maybe can be different by region or by car model, check it from ddt/FCAM/routine for calibration/distance between target logos) [example](https://drive.google.com/file/d/1Kd-fUlH-Jr4ZSw9OUoiD-LqHva84z-1L/view)
3) Ignition on and engine off, Run pyren with cfc and choose /Front Camera/Changing configuration/Computer Calibration, write yes and press enter.
  - If you receive all of hex responses, back to main menu of Front Camera and check Device Errors. If Computer calibration error looks "Memorized" procedure is completed, you can delete errors and it will work after this. 
  - if you receive all of hex responses but, computer calibration error still "Active" go back step 2. and check environment lighting and alignment of target patterns.
  - if you don't have all of hex responses;
    - Check environment lighting and alignment of target patterns
    - Make sure ignition on and engine off
    - Lock the door from outside the car with key and wait a minute then continue from step 3
    - Try with cfc off or another obd2 scanner (i used vgate icar pro 2s)
