### ISSUE TITLE
DTC 926755 no way to erase it

### ISSUE THREAD

**Issue by JABICHOCU** [cedricp/ddt4all#829]
As many of you already know, I´ve been trying to inhibit stop-start on my 2013 captur for a while...until lately I managed to successfully do it on my EMM unit.But now I get this error on my Pyren diagnosis, which I have no way to erase...does this mean car is not working properly or is it just informing that  S-S system is  inhibited? [
![DTC 926755   al inhibir stopstart](https://github.com/cedricp/ddt4all/assets/66420341/3b59f7e8-a86a-4220-859c-e4c31ca515e2)
](url)

**Comment by KarelSvo** [comment]
DTC xxxx55 means not configured

**Comment by JABICHOCU** [comment]
Yes...that sounds interesting but out of my knowledge. For other cars you already have "ready to go" aftermarked switches to do what you say, but not for this one (as far as I know)

**Comment by Furtif** [comment]
you screen i like is a Pyren ... if my memory is good.. but it is not a issue please ask in https://github.com/cedricp/ddt4all/discussions
