### ISSUE TITLE
bad ELM respons

### ISSUE THREAD

**Issue by tomasvs** [cedricp/ddt4all#83]
After changing something in my EMM_lightning ecu of my Clio IV, I can't write anything in these parameters. I keep getting the notice: BAD SLM Response : WRONG RESPONSE : Unknown.

What should be the issue? by now my lights aren't working and I can't get them back to factory settings.

Please help.. 
[logs.zip](https://github.com/cedricp/ddt4all/files/2160259/logs.zip)

**Comment by cedricp** [comment]
What is the command you send. I found some "wrong responses" but for the request "3B62" (TPMS WHEEL ID 2 write command)
Screenshot ?

**Comment by cedricp** [comment]
Sorry I was on the BCM file, found on EMM one. Are you sure the file you're using is the good one ? Did the scan worked ?

**Comment by cedricp** [comment]
I think you used a bad file for this ECU : 
Found ECU [UPC-EMM] (**not perfect match**) :EMM_EDISON_DDT2000_SW10_V2 DIAGVERSION [4] SUPPLIER [414] SOFT [C100] VERSION [**9500 instead 1008**]
You should not try to write with a file that doesn't match perfectly

**Comment by tomasvs** [comment]
I think thats the issue. How can I fix this? Should the dealer update the ecu?

**Comment by cedricp** [comment]
You need to either find the correct file to put the correct parameters or ask the dealer to put the parameters back.
You can try to get an ECU from a broken car too.

**Comment by tomasvs** [comment]
Every dealer can do that?

**Comment by cedricp** [comment]
Don't know...

**Comment by cedricp** [comment]
I rebuilt your original frame from parameter reading. Open a screen with the file "EMM_EDISON_DDT2000_SW10_V2" and click on the icon "Ox".
-> set diagnostic session to 10 C0
-> paste this line to input : 
3B63015E00190AFC00C8000000000000000000000AFC0AFC0AFC07310A120AFC0AFC0AFC03E800000001000000030AFC0AFC0AFC0000000000002EE00AFC0AFC003C001E00C80A0BB8003200
then type "enter" to send the command. That should bring back your original parameters.

**Comment by ClioIV** [comment]
Bonjour, avez-vous trouvé la solution ? J’ai le même problème que vous

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all/discussions/833
