### ISSUE TITLE
libnss issue: nss_util.cc: ... NSS error code: -8018

### ISSUE THREAD

**Issue by nmschulte** [cedricp/ddt4all#831]
On GNU/Linux (Debian 12 Bookworm/Sid), I receive this error in the console when opening the app:

```
[11524:11534:0530/230548.796319:ERROR:nss_util.cc(283)] After loading Root Certs, loaded==false: NSS error code: -8018
```

The Documentation (and Screen) tabs are empty; I'm unsure what "No database found -- Check documentation" means if the page is empty.

I found this issue that has the same error, which seems to suggest it's a problem with Chromium:
https://github.com/openethereum/parity-ethereum/issues/6530

**Comment by Furtif** [comment]
seem odd all that please ask as https://github.com/cedricp/ddt4all/discussions
