### ISSUE TITLE
update, and/or the attention of all users

### ISSUE THREAD

**Issue by Furtif** [cedricp/ddt4all#836]
https://github.com/cedricp/ddt4all/discussions
 * I don't like conflicts in propositions
 * If solved please close you shit!
 * I read with everything.... frankly!!!!
 * All notifications are due to your thing, complaints, or questions.
 * Avoid loads of notifications when closing your issues, which are not really the majority of your 'asks' , let's be honest with those who give you something free.

**Comment by sadfdg4g** [comment]
May I know the auto high beam minimum speed change coding path (Talisman) ddt4all
Can Talisman modify from 45km to 20km with coding
