### ISSUE TITLE
Connecting OBDII by WiFi or Bluetooth - does not work with macOS

### ISSUE THREAD

**Issue by Vape2Die** [cedricp/ddt4all#868]
Hi,

I installed everything correctly, but when I launch the program on macOS, the software doesn't recognize WiFi and Bluetooth OBDII connections. However, the exact same OBDII plugs do work with Windows 10. There must be something wrong with the code that is preventing the connection. I have made sure that all the necessary packages were installed as per the requirements.txt file.

My OBDII plugs do support ELM327 and have the PIC18F25K80 chip. Both plugs are working in the Windows 10 program, so there shouldn't be any issue with my hardware.

**Comment by KarelSvo** [comment]
https://github.com/cedricp/ddt4all/pull/659/commits/1c68148f3e1eb0102878b4fd20acdad54bd1c401

**Comment by Vape2Die** [comment]
Thanks for the quick response @KarelSvo.
I have implemented the change in the code, but now encountering the following error:

<img width="605" alt="Pasted Graphic" src="https://github.com/cedricp/ddt4all/assets/98199956/0667fc24-086e-4fe4-8e79-648db58fa59a">

**Comment by Vape2Die** [comment]
I have added ignore flag
`    def read(self):
        try:
            byte = b""
            if self.portType == 1:
                import socket
                try:
                    byte = self.hdr.recv(1)
                    print(str(byte))
                except socket.timeout:
                    self.tcp_needs_reconnect = True
                except Exception as e:
                    print(e)
            elif self.portType == 2:
                if self.droid.bluetoothReadReady():
                    byte = self.droid.bluetoothRead(1).result
            else:
                if self.hdr.inWaiting():
                    byte = self.hdr.read()
        except:
            print('*' * 40)
            print('*       ' + _('Connection to ELM was lost'))
            self.connectionStatus = False
            self.close()
            return None
        try:
            return byte.decode("utf-8", 'ignore')  # Ignore undecodable characters (Vape2Die)
        except:
            print("Cannot decode bytes " + str(byte))
            return ""`

So the response in terminal does not flag `cannot decode bytes b'\xfc'` anymore.. but still ddt4all loads with 0 ECUs
I can't understand why it happens, any idea @KarelSvo?
<img width="586" alt="Pasted Graphic 1" src="https://github.com/cedricp/ddt4all/assets/98199956/ad2ea5c0-539d-48ef-9e65-af8aae7836ea">

**Comment by Vape2Die** [comment]
@KarelSvo You're PRO!!!
thank you so much! works great now :)
