### ISSUE TITLE
RADNAV ver2.3 Configuration Reset button problem

### ISSUE THREAD

**Issue by mansour-isa** [cedricp/ddt4all#88]
Hi,
Unfortunately when I was working with DDT4ALL at menu Audio-> RadNav v2.3-> Diagnostic-> ECU Reset, I clicked the Reset configuration button (default value) and then I lost the Rlink2 screen. It is blank and black, Radio and whatever related to voice are working but there is nothing to show,
I thought maybe by manually setting all parameters on the RadNav v2.3 display, but I do not have a snap shut from "Engineering Configuration" so I do not have enough experience to set these parameters, can you tell me please help?

**Comment by shrlnm** [comment]
Unfortunately, you are not the first ane. I may try to help. Give me your email

**Comment by mansour-isa** [comment]
Thank you Shrlnm,
my email address is victor_omidi@yahoo.com, but I tried myself by reading   Audio->RadNav v2.3->Configuration->Engineering Configuration parameters from other Talisman and setting up in my car then now it is working properly,
![screenshot 14](https://user-images.githubusercontent.com/40230840/43255941-69153d52-90e0-11e8-9388-33d4d05bab61.png)
![screenshot 15](https://user-images.githubusercontent.com/40230840/43256029-b4bc216c-90e0-11e8-8cb7-44a6a53e9112.png)
