### ISSUE TITLE
Problem ddt4all-bad elm response Megane 4

### ISSUE THREAD

**Issue by simin87** [cedricp/ddt4all#89]
Hi Cedric,sorry for my English.I have an error in ddt4all:bad elm response-wrong response
I tried two different obd tools and two different ddt4all version(exe and master).
How can I do?
My car is a Renault Megane 4 with rlink2
I send you screen
![img_20180717_180201](https://user-images.githubusercontent.com/41533166/43043219-b4048390-8d8e-11e8-93df-51009dd6d41a.jpg)

**Comment by shrlnm** [comment]
"Wrong response" with a  high probability means then you sent not supported command to your ECU or you are using bad ELM. The details you may look in elm* log file. Are you sure that you are using the appropriate xml?

**Comment by simin87** [comment]
How can I find log files? I have tested elm with a program and it is compatible..what is xml appropriate?

**Comment by shrlnm** [comment]
Usually the log is written to folder logs inside the ddt4all folder. There are should be two. Most interesting one have a name started with elm prefix

**Comment by shrlnm** [comment]
6 from 8 fields a picture above have an ERROR values. Usually it means that you use wrong xml. Did you use scanning and ddt4all determined this xml?

**Comment by KarelSvo** [comment]
In the photo a very old ddt4all version.

**Comment by shrlnm** [comment]
then look into logs for details. Search the command you sent before WRONG RESPONSE but without spaces. For example from your picture we  need to find 2E209301

**Comment by KarelSvo** [comment]
![3](https://user-images.githubusercontent.com/30380693/43237996-91f0de38-908c-11e8-8ed9-2fe3ef07161f.png)
![2](https://user-images.githubusercontent.com/30380693/43238004-95f7a5c0-908c-11e8-89b8-11b5346e6533.png)
![1](https://user-images.githubusercontent.com/30380693/43238008-989475ce-908c-11e8-9139-4b578be7b149.png)

**Comment by simin87** [comment]
The folder ddt4all can not find it .. I have to try the procedure again with the exe and then look for the log.
I scanned the ecu and found them all ... I think that elm works well.. 
Where is xml?

**Comment by simin87** [comment]
Sending the wrong command?thank you

**Comment by shrlnm** [comment]
As I can see, your car is equipped with a simple "FrontCamera". It could not do more powerful features like a LKA, ACC or AEBS witch may be realised by "RaCam". You may try to enable TSR if it is not enabled by default.

**Comment by simin87** [comment]
Ok, how do I verify Tsr enable?

**Comment by shrlnm** [comment]
it depends on a set of other ECUs (RadNav and TDB) 
Usually you need:
1) enable TSR in FrontCamera
2) enable OSP in RadNav by ddt or "Developer side"
3) reboot RadNav by long press on power button
in some cases you need pp4
4) reboot TDB by command 1103 (it may reset some saved parameters in TDB)

**Comment by igno77** [comment]
Someone had tryed to activate distance warning (DW) on this simple camera?? In the ecu file is possible to set as activate, in the radnav is possible to set on camera detection instead of radar detection but....it seems that doesn't work!

**Comment by simin87** [comment]
Is it right?It's in demo mode.


![tsr](https://user-images.githubusercontent.com/41533166/43272063-5bd4d706-90f9-11e8-9495-d9363cd40d22.jpg)
![tsr2](https://user-images.githubusercontent.com/41533166/43272513-6c866e74-90fa-11e8-8410-d8e663682819.jpg)
![osp](https://user-images.githubusercontent.com/41533166/43272959-82dbc3da-90fb-11e8-8a0c-36a5eecf959f.jpg)

**Comment by KarelSvo** [comment]
Your ddt4all version is still too old, can not distinguish phase 1 and 2.
C1A not yet in production. This is Megane 4 Phase 2.
Uninstall everything completely and use this exe https://www.drive2.ru/b/498093336985338243/

**Comment by shrlnm** [comment]
![tsr1](https://user-images.githubusercontent.com/16278412/43276940-28ecb316-910f-11e8-8c90-673071881f38.png)
![tsr2](https://user-images.githubusercontent.com/16278412/43276957-36c75c8e-910f-11e8-9ed1-17b201136723.png)

**Comment by KarelSvo** [comment]
But please do not use the camera xml from HFE Kadjar.
![hfe](https://user-images.githubusercontent.com/30380693/43280024-02a2b2e0-9110-11e8-8c25-4b2ce26c42f5.png)
![cam](https://user-images.githubusercontent.com/30380693/43280226-85b79ab0-9110-11e8-9f7c-57e8a24fed6c.png)

**Comment by shrlnm** [comment]
Yes sure. The right way is to use scanning for determining right xml for your car

**Comment by KarelSvo** [comment]
Scanning does not always help if the software references in ddt_xml are not up-to-date.
With a current ddt4all version and the right vehicle selection, you can filter out the relevant ecu very well.
Or the way via pyrene with clip database identifying the ecus.

**Comment by simin87** [comment]
Hi Karel,in that page what should I activate?also in radnav 2.4 page?

**Comment by simin87** [comment]
Nothing .. I tried and it's all active by ddt4all..Probably it can not work.no bad elm response error..
How to send log files?unknown exstension.

**Comment by KarelSvo** [comment]
Maybe the log folder zip compress?
> How to send log files?unknown exstension.

**Comment by shrlnm** [comment]
it is better to use something like google disk and share the link

**Comment by simin87** [comment]
https://drive.google.com/open?id=1NhE-re5muM_lXhGIBje8gimguv3txiTq
https://drive.google.com/open?id=13z6hKnyuPWTKIbAtzxX6QAb4phxo3tIz
https://drive.google.com/open?id=1nED4a1OcdxlvMif5PB_9zB7E-wM4IxGB

**Comment by shrlnm** [comment]
Log shows that all commands to RadNav and FrontCamera2014_ECU_V3.0_20150120T125936.xml were accepted and have positive response

But command to DAE "LKA_LDW_Activation" was not accepted and returned Negative Response

742;2E01BD03;7F2E12;

12 at the end means "SubFunction Not Supported"

**Comment by simin87** [comment]
hi, possible solutions?is it a hardware problem?

**Comment by alireza6631** [comment]
Hi

**Comment by alireza6631** [comment]
Hello, I use the elm to encounter error

**Comment by Furtif** [comment]
ok seen a problem but not at program here , ask as https://github.com/cedricp/ddt4all/discussions and rapport discution of
