### ISSUE TITLE
Can't Read Data..

### ISSUE THREAD

**Issue by hoonythink** [cedricp/ddt4all#9]
hi.. again....
thanks for font align version. 
but there is some problem.
MCAN is not working.  (I know that this problem has already been fixed once.)
(Central_Panel_7_8.7_20160620_20160621T104616.xml)

![no data](https://user-images.githubusercontent.com/31832805/30470053-2d4b0850-9a2e-11e7-90d2-ea1aac41a98e.JPG)

and now... (yesterday update version.)
all XML file are not READ DATA.

![111](https://user-images.githubusercontent.com/31832805/30470084-4fa4d5de-9a2e-11e7-83c5-e93482fd0caf.JPG)
![222](https://user-images.githubusercontent.com/31832805/30470085-4fa59050-9a2e-11e7-8bf6-0221e83a654c.JPG)
![333](https://user-images.githubusercontent.com/31832805/30470086-4fa5d72c-9a2e-11e7-945a-855c045b4d0e.JPG)
![444](https://user-images.githubusercontent.com/31832805/30470087-4fae8d90-9a2e-11e7-87a6-709f8ada925b.JPG)

check and fix please.

i use...
vehicle : Koleos II
usb cable : OBDLink SX
windows 8

thanks .

**Comment by cedricp** [comment]
Dupilcate of #8

**Comment by cedricp** [comment]
Closing
