### ISSUE TITLE
CAN ERROR on a lot of commands

### ISSUE THREAD

**Issue by elpedro31** [cedricp/ddt4all#91]
Hi, great work on this project!
Yet I'm having problems when it comes to activate smartphone replication functions in my megane III 2014 (R-Link 1), I modified my obd cable in order to theoretically be able to connect M-CAN, yet I'm having errors on almost every read command, see attached log file, so I did not try write commands
[logfile](https://github.com/cedricp/ddt4all/files/2270987/elm_ddt.txt)

I tried increasing CAN timeout to 1000ms but it didn't resolve the issue.

I'm using a bluetooth 1.5 ELM327 (probably china clone); But except for timeouts, i'm getting OK on every 95 tests on the benchmark.

Regarding version of the project i'm actually using the full master code.

Thank you in advance.

Pierre.

**Comment by SerovMOEX** [comment]
First check that you correctly soldered a switch. CAN-H should be switched between pins 6 and 13, CAN-L between 14 and 12. If it is OK then try to change CAN speed  from 500K to 250K but it is less probable reason

**Comment by cedricp** [comment]
Re-launch ELM benchmark and check that it's not an **ARM CORE**. If it is, the ELM is a fake one and won't work at all.

**Comment by elpedro31** [comment]
Thank you for your replies, I'll check this later today and let you know what I found.

**Comment by elpedro31** [comment]
No ARM CORE issue display on benchmark, plus, I tried without the custom cable and I could access to normal CAN (ON/OFF state of the car,...). I'm putting the fault on the custom cable I did. I bought a new one and I'll be able to see a bit clearer after that. Anyway thank for the tool and for the hint, where can I let you a small donation? :)

**Comment by cedricp** [comment]
Great,
For the donation, just follow the Paypal link on the bottom of the project page or you have a link at the application startup

**Comment by elpedro31** [comment]
![wiring](https://user-images.githubusercontent.com/6115614/43944666-05319320-9c80-11e8-85ac-3d777c7ba0ea.png)
Here was my wiring (which appeared to be non working), I feel like I did a mistake between my representations of the numerotation of the pins regarding male / female, do you confirm?
In my representation I'm looking at the "front" of the cable (spikes for the male, holes for the female). As an other way to tell the question : the pin numerotation (left/right) is based on the female port of the car or on the male port of the obd? I guess I know the answer but I need to be sure! Thank you a lot again for your time.

**Comment by elpedro31** [comment]
Just so anyone could not do the same error as me, my previous drawing is false, I effectively made a mistake on pin numerotation (it's the opposite on both sides), I re-made my wiring and everything worked perfectly. I'm closing the issue.
