### ISSUE TITLE
Cannot start with default language.

### ISSUE THREAD

**Issue by TA1AUB** [cedricp/ddt4all#920]
I am using Windows in Turkish. But ddt4all opens in English.
When you edit the code in the options.py file as follows, it opens in Turkish:

Original:
`lang, enc = locale.getlocale()`

Changed:
`lang, enc = locale.getdefaultlocale()`

**Comment by Furtif** [comment]
that not ok for py 3.11 https://github.com/cedricp/ddt4all/blob/master/options.py#L45 is ok set conditional set

**Comment by Furtif** [comment]
https://github.com/cedricp/ddt4all#dependencies-
