### ISSUE TITLE
Hardcoded CAN  timeout for sending long commands.

### ISSUE THREAD

**Issue by shrlnm** [cedricp/ddt4all#926]
Hi. 
The CAN timeout is hardcoded in elm.py line 965. It do not alow to send long commands

I suggested to make a fix  https://github.com/cedricp/ddt4all/commit/629b672f5caff8c0e8df319ee050f3271e8132d6 
in my branch https://github.com/shrlnm/ddt4all

The idea is to use the timeout defined on the main screen.
But I have no chance now to test this fix carefully. Can some one test it and if it's ok I'll make a pull request.

**Comment by Furtif** [comment]
merged thanks

**Comment by Becraftshannon143** [comment]
@shrlnm need your help can u email me becraftshannon@yahoo.com about MEGANE 3 ac I saw a post u helped someone please my hubby is going crazy!!!

**Comment by shrlnm** [comment]
@Becraftshannon143 let's discuss your question right here. It may help to improve this software.

**Comment by Becraftshannon143** [comment]
Ok…went from manual to automatic air conditioner the heat and everything is
working but for the a/c the compressor is not kicking on.  I believe it is
the programming that needs tweaking.  If I give someone the vin can they
tell me exactly what to do….well tell my husband lol he’s been a zombie
over this for 2 weeks now!!!

**Comment by shrlnm** [comment]
@Becraftshannon143
As I realise, your husband changed configuration of air conditioner and now a/c is working in unexpected ways and you are looking for a way to revert configuration in previous state. Am I right?  
The VIN and current dump may help in such cases.
If the configuration was not changed manually, then VIN will not help and you need to find the other cause of the malfunction

**Comment by Becraftshannon143** [comment]
My husband is sleeping right now so I’m trying to get the info for you but
what is and how do I find the dump?  lol sorry if it’s something I can’t do
I will get back to you a little later it’s early am here

**Comment by Becraftshannon143** [comment]
Sorry just woke up again and reread the message…not sure what change the
configuration means but if you mean changed the programming he did not do
anything with that nor did anyone that helped him.  So the A-C wasn’t
working fully afterwards and someone told him that after changing from
manual to auto u have to change the codes.  Is this correct?

**Comment by Becraftshannon143** [comment]
VIN:  VF1BZAB0648137165
Still need to find out the current dump sorry so many messages….also just
wanted to point out that my husband is from Morocco and me New York….so
even though he learned English when we met things like this still get lost
in translation a bit too but pretty sure I have it right lol

**Comment by Becraftshannon143** [comment]
> @Becraftshannon143 As I realise, your husband changed configuration of air conditioner and now a/c is working in unexpected ways and you are looking for a way to revert configuration in previous state. Am I right? The VIN and current dump may help in such cases. If the configuration was not changed manually, then VIN will not help and you need to find the other cause of the malfunction

Just wanted to make sure I was replying to you bc for some reason it didn’t show your name when I was replying via email….

**Comment by MehdiShanny** [comment]
> @Becraftshannon143 As I realise, your husband changed configuration of air conditioner and now a/c is working in unexpected ways and you are looking for a way to revert configuration in previous state. Am I right? The VIN and current dump may help in such cases. If the configuration was not changed manually, then VIN will not help and you need to find the other cause of the malfunction

he is not sure what you mean by dump either...just waiting for that info and will find out.  once again lost in translation so sorry!!!

**Comment by Becraftshannon143** [comment]
Do you know a tech who will do this online if I give them access somehow?
Of course will pay.  If not I know my husband can do it.  I think he is
just getting worried now

**Comment by MehdiShanny** [comment]
Ok thanks a bunch we are working on getting the software ourselves and everything thanks again!  Will be in touch soon!


Sent from Yahoo Mail for iPhone


On Wednesday, January 17, 2024, 3:43 PM, shrlnm ***@***.***> wrote:




For getting the dump file you need to run a pyren software under windows/linux/macos with option --dump. Scan the car, go to the appropriate ECU and select the "DDT : DDT screens". After running the new ddt window the dump file will be created in folder pyren3/dumps
