### ISSUE TITLE
can't "save ECU list"

### ISSUE THREAD

**Issue by hoonythink** [cedricp/ddt4all#93]
hi. long time no see. 
how are you?
i'm very appreciate to ddt4all and you.

it have one problem.
file - "Save ECU list" not working.
only created "E" file in main folder not vehicles folder.
thank you.

![1111](https://user-images.githubusercontent.com/31832805/44009355-36903364-9ee6-11e8-8963-f2d3a99b74f2.JPG)

**Comment by cedricp** [comment]
Thankt you for the report, this fixed now.

**Comment by hoonythink** [comment]
thank you.
