### ISSUE TITLE
ddt4all crash when try open a xml

### ISSUE THREAD

**Issue by AlMeu** [cedricp/ddt4all#997]
When I try open a xml I get this this error and ddt4all crashes.

![image](https://github.com/cedricp/ddt4all/assets/55224357/c5bf8d0e-146d-4515-af18-b93a32525ea3)

**Comment by Furtif** [comment]
update you app https://github.com/cedricp/ddt4all/releases/tag/v3.0.0

**Comment by Furtif** [comment]
and uses good DB https://github.com/cedricp/ddt4all/discussions/845

**Comment by AlMeu** [comment]
It works better. Thanks.
